### ISSUE TITLE
Eve API eve_error_lists Dupliate key - Error 23000 while running full updates

### ISSUE THREAD

**Issue by Bingmano** [eveseat/seat#100]
* **Problem**: Error 23000
* **Expected**: Not to get an error :smile:
* **Logs / Screenshots / Proof**
> Last Updater: Processing: ErrorList
> 
> Exception: Illuminate\Database\QueryException
> Error Code: 23000
> Error Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '106' for key 'PRIMARY' (SQL: insert into `eve_error_lists` (`errorCode`, `errorText`, `updated_at`, `created_at`) values (106, Must provide userID, keyID, or accessToken parameter for authentication., 2016-05-01 16:33:27, 2016-05-01 16:33:27))
> File: /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php - Line: 655

* **Version Info**: latest version 1.0.25

[http://pastebin.com/M5AMYGmm](url)

**Comment by leonjza** [comment]
Also seeing it on my install. It _shouldn't_ break anything serious though but will get fixed. :ccp: and their API changes ^_^

**Comment by Bingmano** [comment]
:+1:

**Comment by leonjza** [comment]
Dammit. The XML seems fine. Only one instance of errorCode 106. More investigating needed...

![xml](http://i.imgur.com/ZQDn5Uj.png)

**Comment by leonjza** [comment]
Ah, found the problem. Fix incoming.
