### ISSUE TITLE
One line installer not working

### ISSUE THREAD

**Issue by DavidirwinNI** [eveseat/seat#101]
I 'm moving my installation to a more powerful vps, so I though I would try the one line installer for centos 7, it fails because firewalld is not installed and running.

You might want to install it and start it in the your installer file.

I used the CentOS-7-x86_64-Minimal-1511.iso image and then ran the following commands
yum install firewalld
systemctl start firewalld

And then used your
curl -O https://raw.githubusercontent.com/eveseat/scripts/master/install/centos-7-x.sh && bash centos-7-x.sh

And it worked fine.

**Comment by leonjza** [comment]
Thanks for the report! Was *any* firewall installed in the base CentOS install?
