### ISSUE TITLE
DB problem

### ISSUE THREAD

**Issue by jagyro** [eveseat/seat#102]
* **Problem**: Install was haulted due to this error below
* **Expected**: to install DB
* **Logs / Screenshots / Proof**: _![problem](https://cloud.githubusercontent.com/assets/19201677/15037976/7fe97170-1265-11e6-9272-bb0047f0f5af.jpg)
The more information you give the better!_
* **Version Info**: PHP7.0 Unb16.04

Please help.  Thanks

**Comment by leonjza** [comment]
SeAT 1x does not have a `seat:install` command. The old [unsupported version of SeAT 0x](https://github.com/eve-seat/seat) had this but is no longer maintained. Please install the supported version following the documentation [here](seat-docs.rtfd.org). See _Setup Guides_ on the left.

**Comment by jagyro** [comment]
*facepalm* well crap now a new error. 

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by leonjza** [comment]
I am guessing you are running the Ubuntu 14.04 installer on Ubuntu 16.04. This will not work as the `mysql_secure_installation` questions and answers format is different (amongst a few other things that need tweaking).

I was working on the 16.04 installer this morning and hope to get it finished by the end of the week.

**Comment by jagyro** [comment]
ah ok, well i can wait.  your awesome btw, thank you so much for your hard work!  And shouldn't you be in bed:)

**Comment by leonjza** [comment]
You can see the progress [here](https://gist.github.com/leonjza/7f056ad53a0c560cba23e86f8d09b33e) if you want to try it out. I have only tested up until line 94 so far.

**Comment by leonjza** [comment]
Ubuntu 16.04 installer now available. Run it with:
`curl -O https://raw.githubusercontent.com/eveseat/scripts/master/install/ubuntu-16-04-x.sh && bash ubuntu-16-04-x.sh`
