### ISSUE TITLE
Requesting teamspeak auth/forum

### ISSUE THREAD

**Issue by jagyro** [eveseat/seat#103]
Hey,

It's me again!  I was wondering what were the chances of getting a teamspeak authentication module, and a simple forum module.  I feel if you did this it would basically​ make seat the site to use.

**Comment by leonjza** [comment]
This is planned. See the TODO [here](http://seat-docs.readthedocs.io/en/latest/todo/).

For non issue related discussions, please join Slack [here](http://seat-docs.readthedocs.io/en/latest/contact/).
