### ISSUE TITLE
Unable to update to Web v1.0.25

### ISSUE THREAD

**Issue by vivace-io** [eveseat/seat#105]
# Problem: 
Upgrade process not pulling web version 1.0.25. I successfully updated other modules just fine, but for whatever reason the web module does not.

I'm attempting to update web module v1.0.2 to v1.0.25. Checking for updates says there's nothing to update...? Checked `composer.json` and it looks like it should work just fine with the wildcard.

# Version Info: 
Latest Debian distro

`php artisan seat:version`:
<img width="325" alt="capture" src="https://cloud.githubusercontent.com/assets/13205294/15101371/59529984-155c-11e6-98c7-1a511d7c41c4.PNG">

**Comment by leonjza** [comment]
What is the output of `grep \'version /var/www/seat/vendor/eveseat/web/src/Config/web.config.php` (assuming SeAT is installed at `/var/www/seat/`?

If it is `'version'                  => '1.0.25',`, then I would suggest you run `php artisan config:clear` and rerun the `seat:version` command.

**Comment by vivace-io** [comment]
That did the trick - sorry for the late reply... finals and what not.
