### ISSUE TITLE
deleted link file in html dir:(

### ISSUE THREAD

**Issue by jagyro** [eveseat/seat#107]
As the subject says.  Would someone mind sending me a ln command.  I feel...well you know re tod did

**Comment by leonjza** [comment]
This one?
https://github.com/eveseat/scripts/blob/master/install/ubuntu-14-04-x.sh#L184

Please hop onto Slack for further support questions. Details here: http://seat-docs.readthedocs.io/en/latest/contact/#slack

**Comment by jagyro** [comment]
awsome!  Thats it!!! <3
