### ISSUE TITLE
Enhancement: Database cleanup

### ISSUE THREAD

**Issue by Betriebsrat** [eveseat/seat#109]
As mentioned in chat:
Seat DB can grow quite big depending on api key numbers.
Would be nice to have someway to clean old entrys and reduced the DB size from time to time.

**Comment by vivace-io** [comment]
What kind of parameters are you looking for? All I can think of is removing expired keys after a certain time frame, or purge them immediately.

**Comment by leonjza** [comment]
I have understood this as the type of stuff that may relate to a key. Such as character assets/mail/skills/clones etc.

**Comment by Betriebsrat** [comment]
something like only save the last x weeks/months

**Comment by shibdib** [comment]
I wouldn't mind the ability to delete bad keys automatically. Maybe just a log tracking what keys are bad and dump the actual key.

I have 805 keys right now and there's no easy way to purge the dead ones.

**Comment by trustmeimlumi** [comment]
It would awesome to limit the downloaded infos/mails/etc for the last x weeks/months
We have thousand of keys.
