### ISSUE TITLE
Corp member tracking shows member twice

### ISSUE THREAD

**Issue by Xaroth** [eveseat/seat#11]
I am seeing a character twice in the corp member tracking page; this member is the one for which the corp API key is used, so might be related to that.

**Comment by shibdib** [comment]
Also getting duplicate members on the main character list

http://i.imgur.com/ouwWOgT.png

**Comment by Xaroth** [comment]
@shibdib can you confirm that for those character you have separate 'extra' api keys defined (i.e. for me the double entry is the character that I have a corp API key for), that might make it easier to track down.

**Comment by leonjza** [comment]
@Xaroth that is the problem yeah. Atm the query does not distinct the characters or check the key types. Ill have a fix for it later today ;)

**Comment by Xaroth** [comment]
Adding to that, the "All Characters" page shows the same issue.

**Comment by leonjza** [comment]
Related: https://github.com/eveseat/services/commit/1b93322059addb8668d1cd9a525bb73cf3d3e42b

**Comment by leonjza** [comment]
Once packagist syncs, this should be fixed in eveseat/services v1.0.6

**Comment by Xaroth** [comment]
Confirmed to be fixed.
