### ISSUE TITLE
Mail Timeline: Pages not working

### ISSUE THREAD

**Issue by Betriebsrat** [eveseat/seat#110]
* **Problem**: _The pagination on the mail timeline does not work. When you click any other page it still shows the mail from page 1?_
* **Expected**: _When you click page any other page it should show said page?_
* **Logs / Screenshots / Proof**: _sadly nothing in seat or php logs!_
* **Version Info**: _PHP 56, SeAT Version current, Operating System centos7. firefox_

**Comment by leonjza** [comment]
Weird. Cant reproduce this locally or on my prod environment. Silly question. How many pages of mail is there?

**Comment by Betriebsrat** [comment]
326

**Comment by apfelqoo** [comment]
Got the same issue:
Server: Ubuntu 14.04.4, PHP 5.6, current SeAT, NginX
Client: Win 10 on different PC´s tested with FF, Chrome, IE, EDGE

Pages: ~140

**Comment by Betriebsrat** [comment]
nginx here aswell, does anybody else got said problem on apache?

**Comment by leonjza** [comment]
Seems like this may be isolated to nginx. Going to post sample nginx configs in the documentation soon which may help.

**Comment by luminarium** [comment]
same here under nginx :/

**Comment by apfelqoo** [comment]
> change this line under your sites nginx conf:
try_files $uri $uri/ /index.php?a=$args; 
to this:
try_files $uri $uri/ /index.php$is_args$args;
thanx to: @maticslaszlo

That worked. Thank you very much!

**Comment by Betriebsrat** [comment]
worked thanks!
