### ISSUE TITLE
Error on EVE SSO

### ISSUE THREAD

**Issue by sapyx** [eveseat/seat#114]
* **Problem**:Error message _Whoops, looks like something went wrong._ in http://seat-dex.eveonline-italia.it/auth/eve.  _local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Seat\Web\Extentions\EveOnlineProvider' not found' in /var/www/seat/vendor/laravel/socialite/src/SocialiteManager.php:90_ in storage/logs/laravel.log

* **Version Info**: _PHP 5.6.22, SeAT  Web Version 1.0.27, CentOS Linux release 7.2.1511 (Core)_

**Comment by leonjza** [comment]
This file definitely exists in the [1.0.27](https://github.com/eveseat/web/blob/1.0.27/src/Extentions/EveonlineProvider.php) tag.
Can you please run `composer dump-autoload` and retry. ?

**Comment by sapyx** [comment]
Sorry. Nothing changed, same errors.

Maybe PHP version?

**Comment by leonjza** [comment]
Nope PHP version is fine.

**Comment by sapyx** [comment]
waiting for infos...

**Comment by leonjza** [comment]
I am not sure what the deal is here. May be worth it for you to jump onto Slack and come give more information about your environment in detail.

**Comment by sapyx** [comment]
_after a sleepless night..._
```
php artisan clear-compiled
php artisan optimize

php artisan cache:clear
php artisan seat:cache:clear

apachectl restart
```

**Success!!!!**
I believe that the first two commands are the key
