### ISSUE TITLE
Feature: new api endpoints

### ISSUE THREAD

**Issue by Betriebsrat** [eveseat/seat#115]
It would be nice to have silo content and amount at at /api/v1/corporation/starbases/ .
As well a new endpoint to manage the group of a user to get a eve alliance with to seat bridge ready.

**Comment by leonjza** [comment]
> It would be nice to have silo content and amount at at /api/v1/corporation/starbases/  

- A new modules key will be returned based on the service modification that was done [here](https://github.com/eveseat/services/commit/2edf0fd4dc896014b2e976f3d8e13843b30cfbeb) when calling information for a specific starbase.  
- A new endpoint for getting assets contents was added [here](https://github.com/eveseat/api/commit/60475a4e08eaae421cd139db6dde1fee2255b67c). Documentation will be added soon.



> As well a new endpoint to manage the group of a user to get a eve alliance with to seat bridge ready.

Can you elaborate a little on this? Do you mean manage in the sense of adding/removing a user from a role?

**Comment by leonjza** [comment]
Docs for the new endpoint is available [here](http://seat-docs.readthedocs.io/en/latest/seat_api/corporations/#corporation-assets-contents).

**Comment by Betriebsrat** [comment]
thanks alot forthe new enpoints.
regarding the management of user roles:
* create/delete/modify new roles/groups
*  assign/unassign roles/groups of users

**Comment by leonjza** [comment]
Endpoints added in the documentation [here](http://seat-docs.readthedocs.io/en/latest/seat_api/roles_permissions/) should be available in a release later today.

**Comment by Betriebsrat** [comment]
Thanks a lot!
