### ISSUE TITLE
Mail search results for other characters

### ISSUE THREAD

**Issue by hderp886** [eveseat/seat#122]
When searching a random string i get results for mail from other characters. The character searching has zero roles, but the mail showing up in the results is to and from other user's characters. I can't open the mail, but i see the subject lines and senders.

Running  PHP 7 on Ubuntu 14.04 and seat 1.0.29

**Comment by leonjza** [comment]
Thanks for the report. I'll look into this asap.

**Comment by leonjza** [comment]
Fixed in https://github.com/eveseat/services/commit/26c16737720a4d836094325cbe320433bfbfa804. (Typo in the commit message referenced #112 instead of #122). Next `eveseat/services` package will have the fix in.

**Comment by leonjza** [comment]
Fix is now available. Upgrade to the latest versions using the upgrade script.
