### ISSUE TITLE
Cannot view all characters for a corporation

### ISSUE THREAD

**Issue by hderp886** [eveseat/seat#123]
As an example, the superuser permission allows you to visit Characters > All characters and see a list of every character registered.

When using for an alliance, if i want to give a CEO access to all his corp members, i would create a role, assign the character.list role and corporation association, and assign the CEO to the role. Obviously the other character perms would be needed to view all of the detail pages for each character.

Currently character.list doesn't appear to be functioning as expected:
- A user with no roles can see her 3 characters on the All Characters view.
- A user with the superuser role can see ALL characters in the system on the All Characters view.
- A user with the character.list perm and a corp association can still only see her own 3 characters on the All Characters view.
- A user with the ALL character related perms can still only see her own 3 characters on the All Characters view.

My expectation was that character.list was the permission required. If one does not exist, how do others manage a situation like this where access should be limited on a corp level? The superuser obviously has a different setting for generating the All Characters list.

**Comment by leonjza** [comment]
Thanks for the clear explanation. As things stand now, this is definitely a shortcoming in the current design of the permissions system. This is definitely something that should be added though so I will mark this as a wishlist item.

**Comment by RichterSR** [comment]
This works only when you affiliate the chars to the role not with the corp.

Would be nice to see this comming soon. :smile:

**Comment by warlof** [comment]
Near done, just having an issue on wallet and market permission for an unknown reason.
Should be PR today ;)

**Comment by Bingmano** [comment]
Yeah, in my case i want to create a recruiter role so i can have them see all characters associated with my corp but not have them see corp assets and other stuff like that.  I have to associate all characters individually to this user for them to see character details.  if i don't associate characters to the role specifically, they get an error saying they need Character.Sheet, but they already have that permission

**Comment by warlof** [comment]
has been fixed with parent PR, just need to wait for merge, mean not before friday since qu1ckkk is in travel.

**Comment by Bingmano** [comment]
cool so new functionality should be if i give a role the character permissions and associate with a corp, they should see all characters who are in that corp?

**Comment by warlof** [comment]
Yup

**Comment by Bingmano** [comment]
awesome thank you.

**Comment by SauerRam** [comment]
Are there some news when this feature will be done? Making everyone su is a bad fix for this functionality.

**Comment by warlof** [comment]
@SauerRam what will be a good fix ?

What is expected ? Give us a use case.

**Comment by leonjza** [comment]
@SauerRam SeAT 2x allows you to specify "All Characters" or "All Corporations" (or both) as an affiliation for a role. So, remove the Superuser roles, create a new role with all the character and or corp roles you want to grant, and affiliate with the "All <type" affiliations. You can exclude certain sensitive characters using this too by adding an inverted affiliation.

In a future patch, there will be buttons to quick setup a lot of these types of scenarios.

**Comment by SauerRam** [comment]
Since I'm on 2.0 since yesterday the ALL Affilation is new and fixes my su Problem. Would it be a big deal to add some kind of "All Affilated Corp's Characters" to the Affilation?

**Comment by shadowcodex** [comment]
@leonjza I'd like to limit all available characters to the corp selected for affiliation.

**Comment by SauerRam** [comment]
https://github.com/eveseat/web/pull/71

**Comment by shadowcodex** [comment]
@leonjza can we look at testing and merging that fix in?

**Comment by warlof** [comment]
think it has been addressed. Otherwise, require a 3.1 tag.
