### ISSUE TITLE
artisan eve:update-sde -n fails during install routine

### ISSUE THREAD

**Issue by ppfeufer** [eveseat/seat#124]
Hey there,

during the install routine (first installation) I encountered a little bug with the SDE update step.

```sh
$ php artisan eve:update-sde -n
Warning! This Laravel command uses exec() to execute a 
mysql shell command to import an extracted dump. Due
to the way the command is constructed, should someone 
view the current running processes of your server, they 
will be able to see your SeAT database users password.

Ensure that you understand this before continuing.   
The local SDE data will be updated to sde-20160704-TRANQUILITY
20 tables will be updated: dgmTypeAttributes, invCategories, invContrabandTypes, invControlTowerResourcePurposes, invControlTowerResourc
es, invFlags, invGroups, invItems, invMarketGroups, invMetaGroups, invMetaTypes, invNames, invPositions, invTypeMaterials, invTypeReacti
ons, invTypes, invUniqueNames, mapDenormalize, ramActivities, staStations
Download format will be: .sql.bz2

The SDE will be imported to mysql://user@localhost/DB_Name
Storage path is: /var/www/seat/storage/sde/sde-20160704-TRANQUILITY/
Downloading...
 20/20 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%  1 sec 17.8 MiB
Importing...
sh: 1: Syntax error: "(" unexpected
Warning: Import failed with exit code 2 and command outut: 
  1/20 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   5% < 1 sec 17.8 MiBsh: 1: Syntax error: "(" unexpected
Warning: Import failed with exit code 2 and command outut: 
  2/20 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10% < 1 sec 17.8 MiBsh: 1: Syntax error: "(" unexpected
Warning: Import failed with exit code 2 and command outut: 
  3/20 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  15% < 1 sec 17.8 MiBsh: 1: Syntax error: "(" unexpected
Warning: Import failed with exit code 2 and command outut: 
  4/20 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20% < 1 sec 17.8 MiBsh: 1: Syntax error: "(" unexpected
Warning: Import failed with exit code 2 and command outut: 
```
And so on.

The issue here is the DB password I am using. It contains a "(". Once I figured that out I had to import all the DB related stuff manually via console. I can imagine once an update on the SDE is due, there will be a similar issue. So it would be nise to escape passwords in shell scripts. If escaping is not an option, I guess it could be an idea to combine the DB files into one file and have the user enter the DB password during installation.

* **Version Info**: _PHP Version: 5.6.23, SeAT Version: 1.0.29, Operating System: Debian 8._

**Comment by leonjza** [comment]
This might be a tricky one. The way the [command is constructed](https://github.com/eveseat/console/blob/master/src/Commands/Eve/UpdateSde.php#L335) in the updater to import the SQL, it uses the `-p` argument. I think if I were to add say `""` around it, then that may be seen as part of the password.

Will have to investigate options here.

**Comment by ppfeufer** [comment]
I think that one goes in the right direction » http://stackoverflow.com/questions/5220325/how-to-escape-strings-in-bash-script

**Comment by leonjza** [comment]
The next console package release should address this.
