### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by vivace-io** [eveseat/seat#125]
* **Problem**:  Error Viewing certain character sheets. Some work, some don't.
* ****: 
I get the following error: 
`Next ErrorException: Trying to get property of non-object (View: /path/to/seat/vendor/eveseat/web/src/resources/views/character/sheet.blade.php) in /path/to/seat/storage/framework/views/13a3df02e64dafe4831b08cfc94d0ca3:75`

I have tried: 
 - `seat:cache:clear`
 - `cache:clear`
 - `view:clear`
 - Run upgrade process.

But the problem persists, the usual "Whoops, look like something went wrong!" Again, isn't an issue for ALL sheets, just some. I can post the stack trace if needed.  However

* **Version Info**:

 - PHP Version: PHP 7.0.8
 - Seat Versions:
    - Api 1.0.12
    - Console 1.0.12
    - Eveapi 1.0.15
    - Notifications 1.0.4
    - Web       1.0.2
    - Services  1.0.19 
 - OS:  Ubuntu 16.04.1 LTS

Also, side note: web refuses to upgrade to 1.0.29, not sure why. Even a fresh install of SeAT does not pull this package. All relevant tools are up to date.

**Comment by leonjza** [comment]
Please double check that you have `php-gd` and `php-curl` installed. If not, do so and rerun the upgrade script. If this allows you to upgrade to the latest version of the web package, check if the original problem you reported still exists.

**Comment by vivace-io** [comment]
Alright, progress. Still having some sheets working, others are not. Once again, fresh install, clean database. Initially seeded database with keys from the old database and let the API get pulled.

Now I get an error through the GUI stating `Unknown Character. Is the API Key on record and updated?`

I checked the database... the associated data is there.

**Comment by leonjza** [comment]
Are you experiencing the same error `Trying to get property of non-object` as you initially reported after the upgrade?

**Comment by vivace-io** [comment]
Negative, no output on the laravel.log

**Comment by leonjza** [comment]
Great.

Give the back end some time to pull everything and try viewing the character again. if it still doesn't work, then I will suggest you get on [Slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack) so that we can discuss the details.

**Comment by vivace-io** [comment]
Alright, the original issue is now re-occuring. I'll hit you up in Slack.

**Comment by vivace-io** [comment]
Closed as a freak accident solved by rebooting (don't ask, I don't know).
