### ISSUE TITLE
JobQueue issue

### ISSUE THREAD

**Issue by warlof** [eveseat/seat#126]
* **Problem**: Since today's update (eveseat/eveapi 1.0.16), people are no longer able to add new key. (error occured after key addition confirmation)
* **Expected**: People able to add API keys
* **Logs / Screenshots / Proof**: `Symfony\Component\Debug\Exception\FatalErrorException: Trait method dispatch has not been applied, because there are collisions with other trait methods on Seat\Eveapi\Jobs\CheckAndQueueKey in /var/www/fec.eveseat.net/vendor/eveseat/eveapi/src/Jobs/CheckAndQueueKey.php:42`
* **Version Info**:

```
> PHP Version: 7.0.6-1+donate.sury.org~wily+1
> Host OS: Linux quenser.eveseat.net 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64
> 
> Checking Local and Github Versions. Please wait...
> +---------------+---------------+---------------+
> | Package Name  | Local Version | Latest Github |
> +---------------+---------------+---------------+
> | Api           | 1.0.13        | 1.0.13        |
> | Console       | 1.0.13        | 1.0.13        |
> | Eveapi        | 1.0.16        | 1.0.16        |
> | Notifications | 1.0.4         | 1.0.4         |
> | Web           | 1.0.30        | 1.0.30        |
> | Services      | 1.0.20        | 1.0.20        |
> +---------------+---------------+---------------+
```

**Comment by leonjza** [comment]
Should be fixed now with the latest versions.
