### ISSUE TITLE
Proposal: design change corp pages | Unicode problems

### ISSUE THREAD

**Issue by Xaroth** [eveseat/seat#13]
While showing the corporation information is useful, it might be worth mentioning that the space it takes on the other tabs (Assets, Contacts, etc) could be used more efficiently.

For example, the Industry tab used to have a progress indicator in the 0.X release that no longer exists, also, the due date is nowhere to be found, albeit being very useful information.

I would propose removing the Summary panels from all tabs except the Summary tab, and reuse that space for more detailed information.

Also, something worth mentioning, not sure if it's an API issue or just a display issue, but certain ascii characters are not properly displayed:
![image](https://cloud.githubusercontent.com/assets/180744/11868315/20670a8a-a4b7-11e5-9153-7c0db2f1f394.png)

all those â- entries are unicode 2588 (full block) ingame, but are displayed as &acirc;&#150;&#136; , so it looks like an unicode issue.

**Comment by leonjza** [comment]
Thanks.
As for the encoding weirdness, its partly due to the fairly aggressive escaping that it goes through in [this](https://github.com/eveseat/services/blob/master/src/Helpers/helpers.php#L149-L172) function.

As for the industry progress bars etc, this is something that can easily be added again. I just don't have API keys that can give me detailed info to actually test with.

**Comment by Xaroth** [comment]
I would have no issue with sharing some keys that are actively used if you need that to test.

I'll have a look at that function and see if I can suggest some changes to make this work better.

**Comment by Cynabal** [comment]
I can provide you also some keys on corp or pilot base.

**Comment by leonjza** [comment]
Cool. I'll poke this thread again when I am ready.

**Comment by Xaroth** [comment]
As for the unicode parts, some quick looking shows that DOMDocument will not treat the html content as unicode unless explicitely specified.

One option would be to wrap it in wrapper html and set a meta tag to specify the content to be unicode, or use mb_convert_encoding to convert all non-ascii stuff from UTF-8 with html entities.

On that note, I also see that color and size props are stripped out, while I understand that part (plus, ccp's font color spec is not rgb, it's argb). While I agree with the implications of having that, an argument could be made that font colour is not really a security issue, and could be a configurable option whether or not to strip out.

**Comment by leonjza** [comment]
Could something like [this](https://github.com/anchorcms/anchor-cms/blob/4d46856a09a05d32f9c6df5254b0f4d478fbe84a/system/helpers.php#L67-L73) work to normalize those chars?

**Comment by Xaroth** [comment]
Not really, the data itself is actually unicode data (2 bytes per character), but it is forced downwards to ascii (1 byte per character), so the data you see is not the data the API returns.

the parser that is being used needs to be made aware that the data it is extracting should be unicode data, or convert the unicode data to ascii with html entities using mb_convert_encoding... after that it -should- work just fine.

For reference, the API output: https://api.eveonline.com/corp/CorporationSheet.xml.aspx?corporationID=98387826

**Comment by leonjza** [comment]
Ah, excellent, thanks for the example.

**Comment by leonjza** [comment]
Unicode problems should be gone with `eveseat/services` [1.0.14](https://github.com/eveseat/seat/wiki/Services-Changelogs#1014).

Going to hold off with the corp page designs for now.
