### ISSUE TITLE
Mail "To" is only showing ID's not names

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#138]
http://i.imgur.com/jwMsBfs.png

Think this was an old issue if I remember correctly but seems to be back.

Characters you can click and get the name on the character page, but corps/alliances it takes a little effort to get.

**Comment by shibdib** [comment]
http://sec.mambaonline.org/support/names/resolve Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by leonjza** [comment]
The check the logfile at `storage/logs/laravel.log` when a call to `names/resolve` is made. It should be possible to determine what is wrong from there.

**Comment by shibdib** [comment]
http://pastebin.com/k9Mgr3s5

log

no idea what to look for

**Comment by leonjza** [comment]
Tail the log. Take note of the time. Request a page that calls the name/resolve endpoint (like mail timeline) and see the new entry in the log. Post the error message you get for that specific request.

**Comment by leonjza** [comment]
This is not a code problem. I see a lot of MySQL related problems in that log file. For example:

```
[2016-09-25 00:38:13] local.ERROR: Character/Eve for 4657926 failed with Illuminate\Database\QueryException: SQLSTATE[08S01]: Communication link failure: 1053 Server shutdown in progress
```

And:

```
[2016-09-25 00:38:13] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
```

Please double check that your database server is OK.
For further help, lets not make noise here as this is not development related and continue on Slack.

Thanks.

**Comment by shibdib** [comment]
db is fine, kb/forums working fine. Seat is the only issue atm

**Comment by warlof** [comment]
You definetely have an issue between mysql and seat. Are they running on the same server ? Have a look on your mysql settings aswell as `.env` seat config file
