### ISSUE TITLE
POLL: SeAT 2.0 System Changes

### ISSUE THREAD

**Issue by leonjza** [eveseat/seat#139]
Development on what hopes to be SeAT _1.1_ will finally be starting with a number of (hopefully great) things planned. More information, upgrade guides and all of that will be available as soon as a lot of the current uncertainties have been finalized.

As planning is currently underway for this release, I feel that a few architecture changes should be made too. Those are:
- Change the default web server from Apache to php-fpm and nginx. I know I threatened this change a while ago, but will finally be making it.
- Make PHP 7 the minimum required PHP version.

For most, this will probably not matter much. However, to make sure I understand the use cases out there, this poll aims to gather some information.
- If you are in **favour** of this, please react to this ticket with a 👍 
- If you are **not in favour** of this, please react to this ticket with a 👎 

For anything else, please raise your concern. I am also open to any other suggestions. Now is the time to make them.

**Comment by CokkocZateki** [comment]
👎

**Comment by CokkocZateki** [comment]
👎. My server uses apache for all my other goodies.

**Comment by leonjza** [comment]
> 👎. My server uses apache for all my other goodies.

Apache will still work fine. It will just not be the default.

**Comment by warlof** [comment]
👎

Yes for php7.0
No for default nginx.

I maintain that we should provide both script fot nginx and apache 😝

**Comment by Synnite** [comment]
I agree with warlof.

**Comment by DavidirwinNI** [comment]
Yes for php7.0
No for nginx, as I know this will break other parts of my server.

**Comment by freedenizen** [comment]
php7 + nginx w/ php-fpm gets a +1 from me as it's what I use already.

**Comment by rohimma** [comment]
👍

**Comment by HunHawk** [comment]
I agree with warlof too.
PHP7 is a vey good idea, but I use Apache for too much goodies to replace it to nginx.

**Comment by Lenlevee** [comment]
I agree with warlof as well

**Comment by G0wd** [comment]
PHP 7 + Nginx as default seems perfect.

+1

**Comment by op6sie** [comment]
I Have No problematiek with it i Have a dedicated vm for it i do however like a good upgrade script

**Comment by monasucks** [comment]
👎

**Comment by trustmeimlumi** [comment]
php7*nginx 👍

**Comment by trustmeimlumi** [comment]
seat2  alpha already has php7 dependencies, so go for it :)

**Comment by leonjza** [comment]
2.0.0 has been tagged with PHP7 now being a minimum requirement.

As for the webserver, the installer repository I started [here](https://github.com/eveseat/installer) is going to ask which webserver (apache/nginx) you want configured. The installer will be easily extendable to add more webserver as we feel.

Thanks to everyone that chimed in and voted!
