### ISSUE TITLE
POST via API causing a redirect

### ISSUE THREAD

**Issue by spawnstah** [eveseat/seat#14]
I'm not sure this is a Bug, or due to my own incompetence. All Get requests I've tried works, but I can't get it to post information via the API. 

I'm using FQDN/seat instead of a vhost for my site and it seems to work fine. (This is for version 1.x released today). 

curl -X POST -H "X-Token:ghzwSKa5124nDWu7KAwJLPMy9iNN2LG1" -d "key_ID=4881318 v_Code=mfZDvD8vRUNbYiaoqQJPhOpktK1rtowT35jlX3k5pNrhGTMXTKPFhpFBpwXfVAcy" http://127.0.0.1/seat/api/v1/key

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://127.0.0.1/seat" />

        <title>Redirecting to http://127.0.0.1/seat</title>
    </head>
    <body>
        Redirecting to <a href="http://127.0.0.1/seat">http://127.0.0.1/seat</a>.
    </body>

**Comment by leonjza** [comment]
Looks like you have to set the Accept Header for `application/json`:

```bash
curl -X POST https://seat.testsite.local/api/v1/key -H "Accept: application/json" -H "X-Token: L3SxgdX4XUw6pVWVSCftgsh16eAbBF3D" -d "key_id=123&v_code=123"
{"v_code":["The v code must be 64 characters."]}
```

I'll update the documentation to reflect this.

**Comment by leonjza** [comment]
For reference: https://github.com/eveseat/seat/wiki/SeAT-API-Reference#content-type

**Comment by spawnstah** [comment]
Thanks for the ultraquick answer, it's working now.  :+1:
