### ISSUE TITLE
How is your corporation managing its wallet?

### ISSUE THREAD

**Issue by warlof** [eveseat/seat#141]
Hey there,

Today I would like to ask People how they are managing their corporation wallet.

I especially curious about wallet division usage.

The goal is to see if my ideas for an industrial plugin for SeAT could fit to everyone or if I should think differently.

Let's go Guys, have a chat !

**Comment by SystemPhreak** [comment]
Not exactly sure but would love to see a way to see where x money went and came from aside from the transactions. More like we sold X ammount of items and it costed this % to build/make/import and we made X % from selling at whatever rate its being sold at. Maybe with some graph action in there.

Kinda geared more towards Financial Statics.

**Comment by warlof** [comment]
Actually in order to manage that I think to monitor transactions on specified Wallet division (which will be of course editable).

In addition, it could enable transaction tracking using specific code while allowing unmonitored transaction (like internal ship transaction or whatever)

**Comment by SauerRam** [comment]
evaluation of transaction types would be great, so for example the production Officer can easily investigate the amount of production fees used in timeframe x-y from division Production to fill up the wallet with the needed sum for the next month or help with profit calculation (in many cases there are mixed transaction types on a specific wallet, for example: Production: production Fees, Research Costs, Buy and Sell orders for Materials or Contract Fees mixed in 1 division according to a specific type of activity, in this case the term Production as a whole) 

We (our Corp) allways have to keep in mind scenarios like paying ally tax based on the net production earnings, or paying provisions to members based on their procentual production activitys compared to other corp members.
Also separating for example Bounty Income, Transactions from other corporations/out of corp players and ISK movement to other devisions on the master wallet is a regular task for accounters.

If striking out a bit more for corporation trading: net profit in a given timeframe with unforfilled market orders associated with that devision kept in mind is also a situation where it's not sufficient to compare the balance of now, and from a month ago. (But I'm not sure at this point if there is a information according to the wallet division in market orders API information, in that case ignore my last thaughts :) )

I hope you can follow my thaughts :P

**Comment by leonjza** [comment]
Closing this for now.
