### ISSUE TITLE
Redis password

### ISSUE THREAD

**Issue by G0wd** [eveseat/seat#142]
Hello,

Is it possible to specify the Redis password somewhere in case Redis is password protected on a server?

Thanks in advance for the help.

**Comment by warlof** [comment]
Hey, go into you're seat path, then édit .env  file with REDIS_PASSWORD=redispass

**Comment by G0wd** [comment]
Hello,

I tried:

CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=redis
REDIS_PASSWORD=Hp_<bMP5j"r7dUHF

(the password is fake but have the same kind of characters)

But it's not working apparently,

"Whoops, looks like something went wrong."

Redis is well configured and working with the password, I have another software that uses it on the same host.

Any ideas?

**Comment by warlof** [comment]
What's your redis server configuration ?

**Comment by G0wd** [comment]
http://pastebin.com/mb9Baqeb

Seat is working well if I don't set a password to redis.

**Comment by warlof** [comment]
My bad, it's a new setting introduced for 2.x
Go into `seatpath/config/database.php`
And change the redis array like this https://github.com/eveseat/seat/blob/master/config/database.php#L122-L133

It will add following .env parameters :
- REDIS_PASSWORD
- REDIS_HOST
- REDIS_PORT

Default value are respectively empty, localhost and 6379.

**Comment by G0wd** [comment]
Perfect, it's working.

Ty for the help.
