### ISSUE TITLE
Only allow EVE SSO

### ISSUE THREAD

**Issue by G0wd** [eveseat/seat#143]
Hello,

I would like to hide the classical login/register a new membership/I forgot my password links and only keep Login with EVE.

Is it possible? Under what file are those links?

Also, if someone login with EVE, does it act like a registration?

Ty for the help

**Comment by warlof** [comment]
Actually no, there are no settings to remove register/forgot password.
But, you can edit the view which is in `seatpath/vendor/eveseat/web/src/ressources/views/auth/login.blade.php`

https://github.com/eveseat/web/blob/master/src/resources/views/auth/login.blade.php#L45-L51

And yes, using SSO act as registration.

**Comment by G0wd** [comment]
Very helpful.

Fixed :)
