### ISSUE TITLE
Error using 1 line installer

### ISSUE THREAD

**Issue by JacobOkanta** [eveseat/seat#144]
Trying to use the 1 line installer on Ubuntu 16.10 hosted on a laptop in my home and getting error 
user@ubuntu-server:/$ sudo bash <(curl -fsSL https://raw.githubusercontent.com/eveseat/scripts/master/install/installer.sh)
bash: /dev/fd/63: No such file or directory
user@ubuntu-server:/$ (23) Failed writing body
I have tried multiple times and continue to have this problem.

**Comment by leonjza** [comment]
Can confirm this is happening for me too. Will investigate.

**Comment by leonjza** [comment]
Looks like its related to me running `zsh` as the parent shell. Can you drop into a `bash` shell and run it again?

**Comment by JacobOkanta** [comment]
I am new to server how can I do that?

**Comment by leonjza** [comment]
Ill suggest you join us on [Slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack) to try and debug your problem.

In the mean time, I have started a new repository to have a proper installer/upgrader for SeAT 2.0. You can see the progress here: https://github.com/eveseat/installer

**Comment by warlof** [comment]
any feedback about this issue ?

**Comment by leonjza** [comment]
@JacobOkanta the new SeAT installer has been built and the [installation docs](http://seat-docs.readthedocs.io/en/latest/installation_guides/getting_started/) have been updated. If you are still having issues feel free to jump on Slack for some help.

**Comment by Fundaris** [comment]
For people who runs into this problem
sudo into root and then run the bash commands
sudo doesn't like to run curled scripts
