### ISSUE TITLE
Create Permissions

### ISSUE THREAD

**Issue by Kacer88** [eveseat/seat#146]
Hi, i have Problems to set Permissions to New Groups.

for Exampel, i wish to Create a Permissiongroup Producer.
So this Group should show Corparate Industrie Jobs.

I created new group, Producer, give them 
Corporation.industry 	
Corporation.listAll 	
Corporation.summary
and the Corparation.

But it doesnt Show anything more than Corp Summary.

Pls Help

**Comment by leonjza** [comment]
Add an affiliation for the corporation in question. As this is not a code related issue / bug, please join the Slack group in the #support channel.

http://seat-docs.readthedocs.io/en/latest/contact/#slack
