### ISSUE TITLE
Cronjob Problem

### ISSUE THREAD

**Issue by BigMikeOWL** [eveseat/seat#147]
Hello Dear, me cronjob doesn´t work. The logfile is empty.

but i have ubuntu 16.04 with automatic script installer from this script here.

**Comment by nizzan** [comment]
Hi!
What seems to be the issue?
Are the jobs not queing up or working through?
Have this worked before or is this a new install that doesn't work?

Your report is lacking a good explanation of what is happening (or not happening).

**Comment by BigMikeOWL** [comment]
Hi,

it´s a new installed ubunto 16.06. Cronjob doesn´t work.

The log say:

`#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/seat/bootstrap/cache/compiled.php(9639): call_user_func_array(Array, Array)
#32 /var/www/seat/bootstrap/cache/compiled.php(11590): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/seat/bootstrap/cache/compiled.php(9639): call_user_func_array(Array, Array)
#35 /var/www/seat/bootstrap/cache/compiled.php(12735): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/seat/bootstrap/cache/compiled.php(9639): call_user_func_array(Array, Array)
#38 /var/www/seat/bootstrap/cache/compiled.php(12672): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/seat/bootstrap/cache/compiled.php(9639): call_user_func_array(Array, Array)
#41 /var/www/seat/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/seat/bootstrap/cache/compiled.php(9639): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/seat/bootstrap/cache/compiled.php(9629): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /var/www/seat/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/seat/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 /var/www/seat/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 {main}  
[2016-11-27 16:55:02] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:00:02] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:05:02] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:10:02] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:15:01] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:20:01] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:25:01] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:30:01] local.WARNING: A job for Api Server and owner 0 already exists.  
[2016-11-27 17:35:01] local.WARNING: A job for Api Server and owner 0 already exists.  `

**Comment by warlof** [comment]
> Cronjob doesn´t work.

Which mean ? How do you know it's not working ?
Did you set the admin password ?
Did you check `php artisan seat:admin:diagnose` output ?
Is supervisor running ?
What are your config...

Well, such information

**Comment by leonjza** [comment]
@BigMikeOWL I'll suggest you join us on Slack where it will be much easier for us to help you. You can find the details here: [http://seat-docs.readthedocs.io/en/latest/contact/#slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack)

**Comment by BigMikeOWL** [comment]
supervisorctl reload
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228

**Comment by warlof** [comment]
better should try `sudo service supervisor restart` in order to restart supervisor.

**Comment by BigMikeOWL** [comment]
Okay, now hav a failure:

Exception: UnexpectedValueException
Error Code: 0
Error Message: The stream or file "/var/www/seat/storage/logs/pheal-2016-11-27.log" could not be opened: failed to open stream: Permission denied
File: /var/www/seat/bootstrap/cache/compiled.php - Line: 13430

**Comment by leonjza** [comment]
@BigMikeOWL Please join slack for further installation support. This is not a code issue.
Thanks!

**Comment by MisteryMan** [comment]
this is/was a file permission problem, for anyone else running into this particular error the following solution can be used to fix on both ubuntu 14.04 and 16.04

http://seat-docs.readthedocs.io/en/latest/setup_guides/ubuntu1404/#seat-permissions
