### ISSUE TITLE
CCP is changing characterIDs

### ISSUE THREAD

**Issue by freedenizen** [eveseat/seat#149]
In 5 days (13 Dec 2016) CCP is changing characterIDs to start from 2112000000. This will break the current int(11) characterID column definitions throughout seat. 

https://developers.eveonline.com/blog/article/character-id-range-change

**Comment by leonjza** [comment]
Changed integer sizes with https://github.com/eveseat/eveapi/commit/0227052f7c36ad3c22affc1dfb27ce3c557aadc6.

**Comment by leonjza** [comment]
Fixed as part of the 2.0.0 release.
