### ISSUE TITLE
Can't access API key from character windows

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#15]
Is was helpful to be able to access to key linked to the carrier straight from the character window in the old version.

Perhaps adding this option in the "account information" box would be easy to do.

(No clue how to tag things as wishlist)

**Comment by leonjza** [comment]
Are you referring to the vCode?

**Comment by shibdib** [comment]
Old version you had a link to the actual key that the character info is coming from.

**Comment by leonjza** [comment]
Ah ok. Yes this can be added easily.
