### ISSUE TITLE
Queue times incorrect.

### ISSUE THREAD

**Issue by BasiliskB** [eveseat/seat#152]
Seem to be affected +/- your timezone.

"Created at" / "Updated at" times are UTC.
xxxx hours ago is based on the clients local time

Example: I'm UTC+2, all new jobs will say "2 hours ago"
Example: In UTC+5, all new jobs will say "in 5 hours"

**Comment by leonjza** [comment]
Got a feeling this has to do with the client side date calculations that use be server side in SeAT 1.x

**Comment by warlof** [comment]
TZ can bet set into config path, in app.php file.
You have to set the TZ according to your server tz. But could have an impact on ui side since TZ cannot be changé according to user.

**Comment by BasiliskB** [comment]
Changing the timezone in the app.php file does not fix the problem.
Setting timezone from UTC to EST, made newly created jobs for me go to "7 hours ago" from "2 hours ago"

Seems to be that whatever is handling the displaying of the jobs compared the time submitted to client time instead of server/application time.
