### ISSUE TITLE
Failure by Upgrade SEAT

### ISSUE THREAD

**Issue by BigMikeOWL** [eveseat/seat#154]
But i startet a update with 

bash <(curl -fsSL https://raw.githubusercontent.com/eveseat/scripts/master/upgrade/upgrade-seat.sh)

and i become a failure:

bash <(curl -fsSL https://raw.githubusercontent.com/eveseat/scripts/master/upgrade/upgrade-seat.sh)
 * SeAT Auto Upgrader

Be sure to read the source before continuing if you are unsure.

Are you sure you want to continue? (y/n) y

 * Changing directories to /var/www/seat
 * Putting SeAT into maintenance mode
Application is now in maintenance mode.
 * Updating composer itself
You are already using composer version 1.2.4 (stable channel).
 * Updating SeAT packages
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Generating autoload files
Warning: Ambiguous class resolution, "CreateJobsTable" was found in both "/var/www/seat/database/migrations/2016_11_28_000545_create_jobs_table.php" and "/var/www/seat/database/migrations/2015_08_28_203349_create_jobs_table.php", the first will be used.
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
Compiling common classes
 * Publishing vendor directories
Copied Directory [/vendor/eveseat/api/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/eveapi/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/notifications/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/services/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/web/src/resources/assets] To [/public/web]
Copied Directory [/vendor/eveseat/web/src/database/migrations] To [/database/migrations]
Publishing complete for tag []!
 * Running any database migrations

  [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'jobs' already exists (SQL: create table `jobs` (`id` bigint unsigned not null auto_incre
  ment primary key, `queue` varchar(255) not null, `payload` longtext not null, `attempts` tinyint unsigned not null, `reserved` tinyint unsigned not null
  , `reserved_at` int unsigned null, `available_at` int unsigned not null, `created_at` int unsigned not null) default character set utf8 collate utf8_uni
  code_ci)

  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'jobs' already exists

**Comment by warlof** [comment]
from which version are you coming and to which version do you want to go ?

if you're coming from 1.x and want to go to 2.x, please follow this : http://seat-docs.readthedocs.io/en/latest/upgrade_guides/seat1_to_2/

**Comment by leonjza** [comment]
@BigMikeOWL for this one, please jump on Slack so that we help you better.

**Comment by MisteryMan** [comment]
And please also tell us your OS version (i.e. which ubuntu) and which php version you have running. (can be found by typing "php -v" in your terminal)

**Comment by leonjza** [comment]
Closing due to lack of response. @BigMikeOWL if you still need help with this later, please join us on [Slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack).
