### ISSUE TITLE
[BUG] Starbases API endpoint (No starbase_id use)

### ISSUE THREAD

**Issue by karbowiak** [eveseat/seat#156]
Hello there!

```Route::get('/starbases/{corporation_id}', 'CorporationController@getStarbases');```
should be
```Route::get('/starbases/{corporation_id}/{starbase_id}', 'CorporationController@getStarbases');```
on line 138 in `api/src/Http/routes.php`

;)

**Comment by leonjza** [comment]
Thanks for the report! Its actually `Route::get('/starbases/{corporation_id}/{starbase_id?}', 'CorporationController@getStarbases');`

Will fix asap.

;)

**Comment by karbowiak** [comment]
Potato potato :P

Probably more in there that's missing something tho - didn't really check however, will report if more come up :)
