### ISSUE TITLE
[Idea / Request] Notification for Siphon detection

### ISSUE THREAD

**Issue by karbowiak** [eveseat/seat#157]
Hi there.

Simple idea / request - a notification type that detects possible siphons from silos.
Loop over all starbases, find all silos, look at contents, if it's divisible by 100, it's fine, if not, might contain a siphon.

```if($contentInSilo % 100) { oh noes, siphon }```

**Comment by leonjza** [comment]
Siphon detection added in https://github.com/eveseat/notifications/commit/72f7d1342cb08c4cb239e364c12da3dff314984a. Will be available in the next tagged release of the notifications package.
