### ISSUE TITLE
Email Address for SSO

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#158]
When verifying email with SSO, the user gets Whoops! Something went wrong.  If they go back to the original hosting address SeAT lets them in without verifying the email address.

**Comment by leonjza** [comment]
Check your logs for the error that was thrown. There is something wrong with your email setup. Hop on slack for more support on this please.

Can you double check if you have the email verification requirement enabled or disabled?

**Comment by drkthunder02** [comment]
I have require email activation disabled.  I don't see a setting in SeAT 2.x for email verification.  I did not setup email settings in the .env just yet, but I will do that and let you know when I have it setup.

**Comment by leonjza** [comment]
Ok great. Going to mark this as a bug because the expected behavior was not to ask for an email address if its disabled in the SeAT 2x settings.

**Comment by drkthunder02** [comment]
I have updated the mail settings in the .env file as well.

**Comment by drkthunder02** [comment]
After updating the mail settings in the .env file, I tried again, and got the same results.

**Comment by leonjza** [comment]
You will have to debug that. As I have mentioned before, if you need help with that, please make use of the support channel on slack. Ill fix the odd behaviour with SSO in the meantime.
