### ISSUE TITLE
Api Key Update

### ISSUE THREAD

**Issue by JackONeill12** [eveseat/seat#16]
http://i.imgur.com/WB3dskI.png

The Api Keys are stuck in there for a day now and theres no way to clear the working queues. Not even a complete serrver restart fixes it.

**Comment by leonjza** [comment]
There was a bug in an older version of the api updater package when it comes to handling HTTP 403 responses from the EVE API. Make sure you are up to date, and clear all the job history via the Web UI.

If the problem still persists, I may need a sample API key to see whats happening.

**Comment by shibdib** [comment]
Issue still exists when updated to newest version

http://i.imgur.com/DKIOlyJ.png

**Comment by leonjza** [comment]
Have you cleared all the jobs history yet? I see some of those are form "4 days ago".  
Access the queue info from the top right -> history in the total jobs widget -> Clear All History.

**Comment by JackONeill12** [comment]
Thx. That fixes it for me.

**Comment by leonjza** [comment]
Thanks for the update.
