### ISSUE TITLE
[REQ] Corporation API Keys "knowing" of each other, and getting scheduled accordingly

### ISSUE THREAD

**Issue by karbowiak** [eveseat/seat#160]
Hello there.

Idea is simple enough
1 corp key: update once an hour
2 corp keys:
                     key 1 00:00 01:00 etc.
                     key 2 00:30 01:30 etc.
3 corp keys:
                     key 1 00:00 01:00 etc.
                     key 2 00:20 01:20 etc.
                     key 3 00:40 01:40 etc.
4 corrp keys: you get the picture :)

The more keys, the faster corporation information updates. (Thus starbases, wallet info etc. is more up to date)

**Comment by warlof** [comment]
not sure CCP will be happy about this tweak

**Comment by karbowiak** [comment]
As long as it obeys the timer pr. Api key, they don't care. :)

**Comment by leonjza** [comment]
3x implementation is drastically different. Lets see how it goes.
