### ISSUE TITLE
Feature Request:  More categories in "Wallet Ledger" in Corporations

### ISSUE THREAD

**Issue by warriorsoul15** [eveseat/seat#162]
Across the top you get 'Bounty Prizes Per Month" and "PI"  I would love to have "Reprocessing Tax" and "Mfg / Research / Market Tax"  options on that list as well.    With Citadels being far more common than outposts tracking how much taxes are collected where would be nice.  I know many citadel specific things are not in the API yet but just pure Tax volume by type just like is done for bounty prizes would be nice.

Ideally a "Summary" Panel that showed totals of each type (or top 10 types) Bounty Prizes, Prices for Contracts, Reprocessing, etc   would be nice as a quick summary list of what kind of tax revenue is collected monthly by type.

**Comment by warlof** [comment]
pending
https://github.com/eveseat/web/pull/88
https://github.com/eveseat/services/pull/31

**Comment by soratidus999** [comment]
i have attempted this myself under
https://github.com/eveseat/services/pull/79
https://github.com/eveseat/web/pull/252

since this was a functionality i was after
