### ISSUE TITLE
Quick Install script fails to configure supervisor

### ISSUE THREAD

**Issue by johnsondnz** [eveseat/seat#163]
script : bash <(curl -fsSL https://git.io/v15KU)
Ubuntu 16.04
Apache Server

**supervisor.conf**
```
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf
```

**/var/www/seat/.env**
```
APP_ENV=local
APP_KEY=*********************************
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=********
DB_USERNAME=*******
DB_PASSWORD=*********************************
DB_DEBUG=false

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=redis

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=noreply@localhost.local

EVE_CLIENT_ID=null
EVE_CLIENT_SECRET=null
EVE_CALLBACK_URL=http://seat.local/auth/eve/callback
```

I manually had the add this to the config files using Documents pages
http://seat-docs.readthedocs.io/en/latest/admin_guides/seat_supervisor/

Once this was done seat connected to supervisor without issue

**Comment by leonjza** [comment]
Thanks for the report!

**Comment by johnsondnz** [comment]
No worries.  I have found that even after correcting the connection to supervisor none of the scheduled tasks run.  I have to manually trigger each task.

https://puu.sh/sV3MO/c75a6388b7.png
https://puu.sh/sV3Nj/13303d276a.png
https://puu.sh/sV3NX/b827ae734c.png

Cheers

**Comment by ripzeus** [comment]
Currently having same issue.

Installed with the quick install, also went over the guide to make sure everything was correct. I also get this error in the mail.

/bin/sh: -c: line 0: syntax error near unexpected token newline'
/bin/sh: -c: line 0:/usr/bin/php /var/www/seat/artisan schedule:run 1>> /dev/null
2>&'

**Comment by leonjza** [comment]
Want to keep this ticket specifically for the supervisor integration that the new installer does not configure. @johnsondnz & @ripzeus could you please join [slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack) for support on those two separate problems?

Thanks!

**Comment by ripzeus** [comment]
We both have the same problem, I've just added the email error I get with the supervisor tries to run.

Also I am on Slack.

**Comment by johnsondnz** [comment]
have done a fresh install with nginx as server, still no supervisord connection
https://puu.sh/sX1uI/9292cff7c0.png

**Comment by johnsondnz** [comment]
still the same with apache
https://puu.sh/sX3F1/1bc3f1b1da.png

**Comment by warlof** [comment]
Don't care about nginx, apache or whatever is serving your files here.
I don't see inet_http bloc in the config files you have send.
Plus, can you try to set à password and update env file please ?

**Comment by leonjza** [comment]
@warlof this is something for the installer to configure. I'll double check the recent commit. Thanks for the feedback @johnsondnz 👍

**Comment by warlof** [comment]
o7

**Comment by leonjza** [comment]
@johnsondnz ok tested this and I can see the config seems ok, but supervisor has to be restarted in order for the `inet_http_server` to start. Could you confirm that restarting supervisor after an install fixes the problem?

**Comment by leonjza** [comment]
Pushed an updated installer that will restart supervisor after the integration setup.

**Comment by johnsondnz** [comment]
will give this a try now

**Comment by leonjza** [comment]
Fresh install on a 16.04.1 box seems to work with the installer now (after the recent [supervisor restart](https://github.com/eveseat/installer/commit/94017d9a80fa4378a8cef42c6793d46f490b6044) commit):

<img width="1193" alt="screen shot 2016-12-22 at 2 10 17 pm" src="https://cloud.githubusercontent.com/assets/1148127/21425203/6f1568d0-c850-11e6-91b6-584afaf1cf43.png">

**Comment by leonjza** [comment]
@johnsondnz as far as scheduled tasks go, a crontab issue was fixed [here](https://github.com/eveseat/installer/commit/67d84eed3da12e606ec0d781e08700ebe0392dd6). If you still have problems with it, please join us on Slack so we can interactively try and debug it.

Thanks!
