### ISSUE TITLE
seat fails to work 

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#164]
PHP Fatal error:  Default value for parameters with a class type hint can on                                                            ly be NULL in /var/www/seat/vendor/eveseat/services/src/Helpers/helpers.php on l                                                            ine 264

**Comment by leonjza** [comment]
Ensure you have PHP7 available to your webserver. For further support please join [slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack).

**Comment by shibdib** [comment]
https://goo.gl/H3SZq0
