### ISSUE TITLE
Assets in citadels not showing up(Eve issue&potential workaround)

### ISSUE THREAD

**Issue by Gammro** [eveseat/seat#165]
As seen in this thread: https://forums.eveonline.com/default.aspx?g=posts&t=484276
The API doesnt return all of the assets in citadels, causing not all of my assets to show up on the page

However, [this post](https://forums.eveonline.com/default.aspx?g=posts&m=6602968#post6602968) does get all of the results by adding &flat=1 to his api call

So his call looks like this:
https://api.eveonline.com/char/AssetList.xml.aspx?keyID=#{account.keyID}&vCode=#{account.vCode}&characterid=#{account.characterID}&flat=1
and if I'm correct, it should return all assets

**Comment by leonjza** [comment]
Nice! If `flat=1` is the trigger to get more info, the this should be an easy fix.

**Comment by leonjza** [comment]
Ok so the `flat=1` case loses relations for everything else and it seems there is no easy way to 'resolve' a citadel atm? This is definitely a harder problem to solve than I originally thought.

**Comment by leonjza** [comment]
Closing this in favor of the discussion over at #174
