### ISSUE TITLE
language Chinese

### ISSUE THREAD

**Issue by zylx0532** [eveseat/seat#166]
Maybe me updata chinese lang.
not finish.

`<?php
/*
This file is part of SeAT

Copyright (C) 2015, 2016  Leon Jacobs

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

return [

    // General
    'home'                  => '首页',
    'character'             => 'Character|Characters',
    'corporation'           => 'Corporation|Corporations',
    'user'                  => 'User|Users',
    'last_update'           => '刷新时间',
    'unknown'               => 'Unknown',
    'note'                  => 'Note',
    'name'                  => 'Name|Names',
    'granted'               => 'Granted',
    'denied'                => 'Denied',
    'enabled'               => '启用',
    'disabled'              => '禁用',
    'username'              => '用户名',
    'email'                 => 'Email',
    'close'                 => 'Close',
    'date'                  => 'Date',
    'status'                => '状态',
    'id'                    => 'ID|IDs',
    'type'                  => 'Type|Types',
    'expiry'                => '过期',
    'never'                 => 'Never',
    'detail'                => 'Detail|Details',
    'delete'                => '删除',
    'kill'                  => 'Kill',
    'verify'                => 'Verify',
    'reset'                 => 'Reset',
    'back'                  => 'Back',
    'summary'               => '摘要',
    'quantity'              => 'Quantity',
    'volume'                => 'Volume',
    'group'                 => 'Group',
    'owner'                 => 'Owner',
    'description'           => '描述',
    'labels'                => 'Labels',
    'created'               => '创建',
    'issuer'                => 'Issuer',
    'title'                 => '标题|Titles',
    'price'                 => '收款',
    'reward'                => '付款',
    'collateral'            => '押金',
    'location'              => '位置',
    'filter'                => 'Filter|Filters',
    'clear'                 => 'Clear',
    'none'                  => 'None',
    'permission'            => 'Permission|Permissions',
    'affiliation'           => 'Affiliation|Affiliations',
    'role'                  => '角色|Roles',
    'edit'                  => 'Edit',
    'remove'                => 'Remove',
    'yes'                   => 'Yes',
    'no'                    => 'No',
    'update'                => 'Update',
    'action'                => 'Action',
    'key'                   => 'Key',
    'log'                   => 'Log|Logs',
    'view'                  => 'View',
    'item'                  => 'Item|Items',
    'usage'                 => 'Usage',
    'unit'                  => 'Unit|Units',
    'add'                   => 'Add',
    'all'                   => 'All',
    'inverse'               => 'Inverse',
    'read'                  => 'Read',
    'level'                 => 'Level',

    // Requirements
    'requirements'          => 'Requirements',
    'requirements_message'  => 'The following list shows missing PHP extentions. Please install' .
        ' them first before you can continue.',
    'php_version'           => 'PHP Version',
    'php_version_message'   => 'The installed version of PHP does not meet the minimum version' .
        ' requirement for SeAT. Please upgrade your PHP installation.',
    'installed_version'     => 'Installed Version',
    'min_version'           => 'Minimum Version',
    'admin_contact_warning' => 'An administrative contact for this install has not been set.' .
        ' No jobs will be queued because of this. Please configure it in the SeAT settings.',
    'sso_email_warning'     => 'This profile is using an auto generated email addres due to it ' .
        ' being an EVE SSO login. Please set a valid email address in your profile settings.',
    'sso_activation'        => 'SSO Activation',
    'sso_confirmation'      => 'It appears you already own an account. Please confirm your credentials in order to enable SSO.',

    // Auth
    'failed'                => 'These credentials do not match our records.',
    'throttle'              => 'Too many login attempts. Please try again in :seconds seconds.',
    'login_welcome'         => 'Welcome, please enter your credentials.',
    'remember_me'           => 'Remember me',
    'password'              => 'Password',
    'password_again'        => 'Password Again',
    'forgot'                => 'I forgot my password',
    'register'              => 'Register a new membership',
    'sign_in'               => 'Sign In',
    'mfa_welcome'           => 'Please enter an Authentication Code to proceed.',
    'mfa'                   => 'Multifactor Auth',
    'email_verify'          => 'Email Verification',
    'email_verify_welcome'  => 'Please enter a valid email address for your account.',

    // Registration
    'new_account'           => 'New Account',
    'register_welcome'      => 'Please choose a username and a strong password.',
    'register_eve_warn'     => 'Do not use the same password that you use to log onto Eve Online',
    'existing_account'      => 'I already have an account',
    'register_account'      => 'Register Account',

    // Passwords
    'password_reset'        => 'Password Reset',
    'reset_welcome'         => 'Please enter the email address for the account whos password should be reset.',
    'remember'              => 'I remember my credentials',
    'reset_topic'           => 'Reset Password',
    'reset_token_welcome'   => 'Please enter the email and new password.',

    // Header
    'toggle_navigation'     => 'Toggle Navigation',
    'queued'                => 'Queued',
    'working'               => 'Working',
    'joined'                => 'Joined',
    'profile'               => 'Profile',
    'sign_out'              => 'Sign Out',
    'stop_impersonation'    => 'Stop Impersonation',

    // Notifications
    'error'                 => 'Error',
    'success'               => 'Success',
    'warning'               => 'Warning',
    'notice'                => 'Notice',
    'info'                  => 'Info',

    // Menu
    'api_key_management'    => 'API Key 管理',
    'add_api_key'           => '新增API',
    'list_keys'             => 'API列表',
    'all_char'              => '所有角色',
    'mail_timeline'         => 'Mail Timeline',
    'all_corp'              => '所有军团',
    'configuration'         => '配置',
    'access'                => '权限管理',
    'other'                 => '其他',
    'tools'                 => '工具',
    'security_logs'         => '安全日志',
    'import'                => '导入API',
    'settings'              => 'SeAT设置',
    'schedule'              => '计划任务',
    'no_main_char'          => 'No Main Character',
    'hello'                 => 'Hello',
    'online'                => '在线',
    'search'                => 'Search',
    'main_menu'             => '主菜单',
    'security'              => 'Security',
    'tracking'              => '跟踪',
    'worker_constraints'    => 'Worker Constraints',

    'assets'                      => '资产',
    'calendar'                    => 'Calendar',
    'channels'                    => 'Channels',
    'contacts'                    => '联系人',
    'contracts'                   => '合同',
    'industry'                    => '工业',
    'intel'                       => 'Intel',
    'killmails'                   => 'Killmails',
    'mail'                        => '邮件',
    'market'                      => '市场',
    'notifications'               => '通知',
    'pi'                          => '行星开发',
    'research'                    => '研究',
    'sheet'                       => 'Sheet',
    'skills'                      => '技能',
    'standings'                   => '声望',
    'wallet_journal'              => '钱包日志',
    'wallet_transactions'         => '钱包交易',

    // 仪表盘
    'home_page'                   => 'The Home Page',
    'dashboard'                   => '仪表盘',
    'online_layers'               => '在线玩家数',
    'owned_api_keys'              => 'API总数',
    'total_character_isk'         => 'Total Character ISK',
    'total_character_skillpoints' => 'Total Character Skillpoints',
    'total_killmails'             => 'Total Killmails',
    'main_char_skills'            => ':character_name\'s Skills',
    'main_char_skills_per_level'  => 'Skills Per Level',
    'main_char_skills_coverage'   => 'Skills Coverage (in percent)',

    // Api Keys
    'api_key_add'                 => 'Add a New API Key',
    'key_id'                      => 'Key ID',
    'v_code'                      => 'Verification Code',
    'check_key'                   => 'Check Key',
    'api_new_key'                 => 'Create a New API Key',
    'api_use_link'                => 'Use the following link to create a new API Key',
    'api_full_link'               => 'Full API Key for All Characters',
    'api_full_min_mask'           => 'API Key with minimum Mask needed',
    'insufficient_access_mask'    => 'This API Key does not meet the minimum Access Mask required',
    'api_key_info'                => 'API Key Info',
    'api_key_type'                => 'API Key Type',
    'api_access_mask'             => 'API Access Mask',
    'api_add_type_key'            => 'Add :type Api Key',
    'api_add_job'                 => 'Adding an Api Key will automatically queue a new update job for it',
    'api_min_mask'                => 'Min. Mask',
    'api_access'                  => 'Access',
    'api_detail'                  => 'API Key Detail',
    'api_key_status'              => 'API Key Status',
    'api_job_update'              => 'Queue an Update Job',
    'owner_info'                  => 'Owner Information',
    'no_owner'                    => 'This API Key has no Owner',
    'last_login'                  => 'Last Login',
    'account_status'              => 'Account Status',
    'transfer_ownership'          => 'Transfer Ownership',
    'seat_user'                   => 'SeAT User',
    'transfer'                    => 'Transfer',
    'mask_map_fail'               => 'Unable to load the Access Mask map',
    'recent_jobs'                 => 'Recent Jobs',
    'scope'                       => 'Scope',
    'api_all'                     => 'All API Keys',
    'reveal'                      => 'Reveal',
    'add_success'                 => 'Api Key Successfully Added. Update Job :jobid Dispatched',
    're_enable'                   => 'Re-enable Key',
    'disable'                     => 'Disable key',
    'reenable_all_disabled'       => 'Re-enable all disabled keys',
    'disable_all_enabled'         => 'Disable all enabled keys',
    'joblog'                      => 'Job Log',

    // People
    'people_groups'               => 'People Groups',
    'unaffiliated_keys'           => 'Unaffiliated Keys',
    'add_to_existing'             => 'Add to Existing',
    'add_to_existing_group'       => 'Add to Existing Group',
    'group_main'                  => 'Group Main',
    'new_group_with_main'         => 'New Group with :name as Main',

    // Access
    'access_mangement'            => 'Access Management',
    'quick_add_role'              => 'Quick Add Role',
    'role_name'                   => 'Role Name',
    'add_new_role'                => 'Add New Role',
    'available_roles'             => 'Available Roles',
    'quick_add_user'              => 'Quick Add User',
    'add_new_user'                => 'Add New User',
    'edit_role'                   => 'Edit Role',
    'available_permissions'       => 'Available Permissions',
    'grant_permissions'           => 'Grant Permissions',
    'inverse_permission'          => 'Inverse Permission',
    'inverse_affiliation'         => 'Inverse Affiliation',
    'current_permissions'         => 'Current Permissions',
    'has_superuser'               => 'Has Superuser',
    'permission_inherit'          => 'Inherits All Permissions',
    'available_corporations'      => 'Available Corporations',
    'available_characters'        => 'Available Characters',
    'add_affiliations'            => 'Add Affiliations',
    'current_affiliations'        => 'Current Affiliations',
    'available_users'             => 'Available Users',
    'add_user'                    => 'Add User|Add Users',
    'current_users'               => 'Current Users',
    'select_item_add'             => 'Select a Item to Add',
    'impersonate'                 => 'Impersonate',
    'edit_user'                   => 'Edit User',
    'activate_user'               => 'Activate User',
    'deactivate_user'             => 'Deactivate User',
    'account_status_change'       => 'The account status has been changed',
    'user_agent'                  => 'User Agent String',
    'login_history'               => 'Login History',
    'role_summary'                => 'Role Summary',
    'user_updated'                => 'The user has been updated',
    'user_deleted'                => 'The user has been deleted',
    'self_delete_warning'         => 'You can not delete yourself!',
    'impersonating'               => 'Impersonating :user',
    'revert_impersonation'        => 'Impersonation Stopped',
    'user_created'                => 'User Created',
    'unauthorized_request'        => 'Unauthorized Request',
    'unauthorized_request_logged' => 'This attempt has been logged.',

    'role_added'                   => 'Role has been added',
    'role_removed'                 => 'Role has been removed',
    'permissions_granted'          => 'Permissions have been granted',
    'permission_revoked'           => 'Permission has been revoked',
    'user_added'                   => 'Users were added to this role',
    'user_removed'                 => 'User has been removed from this role',
    'affiliations_added'           => 'Affiliations were added to this role',
    'affiliation_removed'          => 'Affiliation has been removed from this role',

    // Import
    'api_import_title'             => 'Import Eve Online API Keys',
    'csv_data_source'              => 'CSV Data Source File',
    'help'                         => 'Help',
    'importing_csv_data'           => 'Import CSV Data',
    'csv_format_explained'         => 'The file format for the CSV is keyID,vCode and sampled below',
    'important_notes'              => 'Important Notes',
    'curr_user_becomes_owner'      => 'The current user (:user) will become the owner of the API keys.',
    'only_format_is_checked'       => 'Only API key format is checked here. No checking is done to ensure that ' .
        'minimum api masks are configured.',
    'update_with_next_job'         => 'Key data will only populate once the next updater job comes by, or is manually started.',

    // Schedule
    'new_schedule'                 => 'New Schedule',
    'available_commands'           => 'Available Commands',
    'cron_expression'              => 'Cron Expression',
    'current_schedule'             => 'Current Schedule',
    'command'                      => 'Command',
    'cron'                         => 'Cron',
    'allow_overlap'                => 'Allow Overlap',
    'allow_maintenance'            => 'Allow in Maintenance Mode',
    'scheduled_commands'           => 'Scheduled Commands',
    'choose_prepop'                => 'Choose a pre-populated cron expression, or write your own.',
    'add_scheduled'                => 'Add Scheduled Command',

    // Security
    'category'                     => 'Category',
    'message'                      => 'Message',
    'source'                       => 'Source',

    // Ledger
    'ledger'                       => 'Wallet Ledger',
    'bountyprizesbymonth'          => 'Bounty Prizes By Month',
    'bountyprizetotal'             => 'Prize Total',
    'pitotals'                     => 'PI Total Taxes',
    'wallet_division_name'         => 'Wallet Division Name',
    'wallet_summary'               => 'Wallet Summary|Wallet Summaries',

    // Users
    'user_management'              => 'User Management',

    // Settings
    'admin_email'                  => 'Administrator Email',
    'admin_email_help'             => 'Please enter the email address of the administrator of this SeAT installation.',
    'min_access_mask'              => 'Minimum Required Access Mask',
    'min_character_access_mask'    => 'Minimum Required Character Access Mask',
    'min_corporation_access_mask'  => 'Minimum Required Corporation Access Mask',
    'force_min_mask'               => 'Force Min. Access Mask',
    'registration'                 => 'Registration',
    'single_signon'                => 'Eve Online Single Signon',
    'admin_warn_sso'               => 'Double check you EVE_CLIENT_ID, EVE_CLIENT_SECRET and EVE_CALLBACK_URL' .
        ' values in the .env file as they may be empty or invalid. SSO can fail because of this!',
    'allow_sso'                    => 'Allow Single Signon',
    'allow_registration'           => 'Allow Registration',
    'email_activation'             => 'Email Activation',
    'require_activation'           => 'Require Email Activation',
    'module_versions'              => 'SeAT Module Versions',
    'tp_versions'                  => 'Third Party Versions',
    'installed'                    => 'Installed',
    'current'                      => 'Current',
    'url'                          => 'Url',
    'google_analytics'             => 'Google Analytics',
    'allow_tracking'               => 'Allow Tracking',
    'tracking_id'                  => 'Unique Tracking ID',
    'tracking_help'                => 'Before disabling the usage tracking, please refer to the below' .
        ' document first.',
    'worker'                       => 'Worker|Workers',

    // Character
    'joined_curr_corp'             => '加入当前公司',
    'skillpoint'                   => '技能点|Skillpoints',
    'account_balance'              => '钱包余额',
    'current_ship'                 => '当前舰船',
    'last_location'                => '最后位置',
    'security_status'              => '安全等级',
    'items_taking'                 => 'items taking',
    'calendar_events'              => 'Calendar Events',
    'positive_standings'           => 'Positive Standings',
    'neutral_standings'            => 'Neutral Standings',
    'negative_standings'           => 'Negative Standings',
    'start'                        => 'Start',
    'installer'                    => 'Installer',
    'system'                       => 'System',
    'activity'                     => 'Activity',
    'run'                          => 'Run|Runs',
    'blueprint'                    => 'Blueprint',
    'product'                      => 'Product',
    'victim'                       => 'Victim',
    'ship_type'                    => 'Ship Type',
    'transaction_type'             => 'Transaction Type',
    'owner_1'                      => 'From',
    'owner_2'                      => 'To',
    'amount'                       => 'Amount',
    'balance'                      => 'Balance',
    'corporation_name'             => 'Corporation Name',
    'from'                         => 'From',
    'subject'                      => 'Subject',
    'to'                           => 'To',
    'to_corp_alliance'             => 'To Corporation / Alliance',
    'to_char'                      => 'To Characters',
    'total'                        => 'Total',
    'updated'                      => 'Updated At',
    'planet'                       => 'Planet',
    'upgrade_level'                => 'Upgrade Level',
    'no_pins'                      => '# Pins',
    'agent'                        => 'Agent',
    'skill'                        => 'Skill|Skills',
    'points_p_day'                 => 'Points per Day',
    'remainder'                    => 'Remainder',
    'skills_summary'               => '技能概要',
    'curr_training'                => '当前训练',
    'skill_training_end'           => '当前技能剩余时间',
    'skill_queue'                  => '技能队列',
    'no_skill_training'            => '没有技能正在训练',
    'empty_skill_queue'            => '技能队列为空',
    'account_info'                 => '账户信息',
    'paid_until'                   => 'Ω到期时间',
    'logon_count'                  => '登录次数',
    'online_time'                  => '在线时间',
    'jump_fatigue'                 => '跳跃疲劳',
    'jump_clones'                  => '克隆疲劳',
    'jump_act_timer'               => 'Jump Activiation Timer',
    'no_jump_clones'               => 'No Jump Clones',
    'implants'                     => '脑插',
    'no_implants'                  => '没有脑插',
    'employment_history'           => '雇佣记录',
    'corporation_titles'           => '公司头衔',
    'item_type'                    => 'Item Type',
    'client_name'                  => 'Client Name',
    'client'                       => 'Client',
    'qty'                          => '#',
    'unknown_character'            => 'Unknown Character. Is the API Key on record and updated?',
    'no_account_info'              => 'No Account Information Available',
    'channel_members'              => 'Channel Members',
    'motd'                         => 'MoTD',
    'bookmark'                     => '位标|Bookmarks',
    'coordinates'                  => 'Coordinates',
    'folder'                       => 'Folder',
    'skills_graph'                 => 'Skills Graph',

    // Character Intel
    'loading_journal'              => 'Loading Journal Entries ...',
    'loading_transactions'         => 'Loading Transaction Entries ...',
    'loading_mail'                 => 'Loading Mail Entries...',

    // Corporation
    'alliance'                     => 'Alliance',
    'ticker'                       => 'Ticker',
    'ceo'                          => 'CEO',
    'home_station'                 => 'Home Station',
    'tax_rate'                     => 'Tax Rate',
    'member_count'                 => 'Member Count',
    'roles_change_log'             => 'Roles Change Log',
    'affected'                     => 'Affected',
    'member_limit'                 => 'Member Limit',
    'shares'                       => 'Shares',
    'member_capacity'              => 'Member Capacity',
    'divisional_information'       => 'Divisional Information',
    'corporation_divisions'        => 'Corporation Divisions',
    'wallet_divisions'             => 'Wallet Divisions',
    'unknown_corporation'          => 'Unknown Corporation. Is the API Key on record and updated?',
    'created_by'                   => 'Created By',
    'starbase'                     => '基地|Starbases',
    'state'                        => 'State',
    'fuel_level'                   => 'Fuel Level',
    'offline'                      => 'Offline Est.',
    'cargo_usage'                  => 'Cargo Usage',
    'onlined_at'                   => 'Onlined At',
    'moon'                         => 'Moon',
    'use_standings_from'           => 'Use Standings From',
    'attack_on_agression'          => 'Attack On Agression',
    'attack_on_war'                => 'Attack On War',
    'corp_member_access'           => 'Corp Member Access',
    'alliance_member_access'       => 'Alliance Member Access',
    'fuel_levels'                  => 'Fuel Levels',
    'fuel_blocks'                  => 'Fuel Blocks',
    'fuel_usage'                   => 'Fuel Usage',
    'low_fuel'                     => 'Low Fuel',
    'stront_usage'                 => 'Strontium Usage',
    'blocks_p_h'                   => 'Blocks p/h',
    'units_p_h'                    => 'Units p/h',
    'sov_bonus'                    => 'Sovereignty Bonus',
    'reinforce_estimate'           => 'Reinforcement Estimate',
    'module'                       => 'Module|Modules',
    'content'                      => 'Content',
    'no_known_assets'              => 'No Known Assets',
    'volume_usage'                 => 'Volume Usage',
    'loading_modules'              => 'Loading Module Information...',
    'pocos'                        => 'Pocos',
    'reinforcement'                => 'Reinforcement',
    'standing_level'               => 'Standing Level',
    'tax_alliance_corp'            => 'Tax: Alliance/Corp',
    'tax_standings'                => 'Tax: Standings',

    // Profile
    'user_profile'                 => '用户资料',
    'user_preferences'             => '用户首选项',
    'user_account'                 => '用户账户',
    'account_settings'             => '账户设置',
    'upgrade_sso'                  => 'Upgrade to EVE Online SSO Account',
    'change_password'              => 'Change Password',
    'change_email'                 => 'Change Email',
    'superuser'                    => 'Superuser',
    'user_interface'               => 'User Interface',
    'main_character'               => 'Main Character',
    'seat_skin'                    => 'SeAT Skin',
    'language'                     => 'Language',
    'sidebar_size'                 => 'Sidebar Size',
    'mail_as_threads'              => 'View Mail as Threads',
    'number_format'                => 'Number Format',
    'current_format'               => 'Current Format',
    'thousands_seperator'          => 'Thousands Seperator',
    'decimal_seperator'            => 'Decimal Seperator',
    'email_notifications'          => 'Email Notifications',
    'require_mfa'                  => 'Require MFA',
    'setup_token_now'              => 'Setup Token Now',
    'owned_keys'                   => 'Owned Keys',
    'account_help'                 => 'For any account related enquiries, including permissions amendments, ' .
        'please contact the SeAT administrator.',
    'current_password'             => 'Current Password',
    'new_password'                 => 'New Password',
    'confirm_new_password'         => 'Confirm New Password',
    'current_email'                => 'Current Email',
    'new_email'                    => 'New Email',
    'confirm_new_email'            => 'Confirm New Email',
    'mfa_setup'                    => 'Multifactor Authentication Setup',
    'scan_qr'                      => 'Scan QR Code',
    'scan_qr_help1'                => 'Please scan the below QR code with your authenticator application.',
    'scan_qr_help2'                => 'Each time this page loads, a new token and qr code is generated.',
    'supported_apps'               => 'Supported Google Authenticator Apps',
    'preferred_apps'               => 'Preferred Apps',
    'other_apps'                   => 'Other Apps',
    'confirm_code'                 => 'Confirm an Authentication Code',
    'confirm_help'                 => 'Next, confirm your setup by entering a confirmation code generated ' .
        'by your authentication application.',
    'code'                         => 'Code',
    'confirm_setup'                => 'Confirm Setup',

    // Queue
    'queue_manage'                 => 'Queue Management',
    'total_jobs'                   => 'Total Jobs',
    'queued_jobs'                  => 'Queued Jobs',
    'working_jobs'                 => 'Working Jobs',
    'error_jobs'                   => 'Errored Jobs',
    'complete'                     => ' complete.',
    'history'                      => 'History',
    'submit_jobs'                  => 'Submit Jobs',
    'job_submit_desc'              => 'These buttons allow you to manually queue jobs into the scheduler. It ' .
        'runs exactly the same commands as you would on the commandline or via the scheduler.',
    'no_working'                   => 'There are currently no working jobs',
    'no_queue'                     => 'There are currently no queued jobs',
    'job_error_detail'             => 'Job Error Details',
    'error_details_desc'           => 'This is a full stack trace for this job error. If this is not something ' .
        'that you understand, or a developer has asked for this, please copy the entire section below ' .
        'and paste it on a site such as pastebin and send the link along.',
    'full_job_error'               => 'Full Job Error Detail',
    'job_id'                       => 'Job ID',
    'api'                          => 'Api',
    'actions'                      => 'Actions',
    'owner_id'                     => 'Owner ID',
    'clear_all_errors'             => 'Clear All Errors',
    'output'                       => 'Output',
    'last_output'                  => 'Last Output',
    'view_full'                    => 'View Full',
    'no_errors'                    => 'There are no known errors',
    'clear_all_history'            => '清空所有历史记录',
    'job_history'                  => 'Job History',
    'no_history'                   => 'There are no historical jobs',
    'eve_api_status'               => 'EVE API状态',
    'eve_api_error_threshold'      => 'API Errors',
    'eve_api_connection_threshold' => 'Connection Errors',
    'supervisor_offline'           => 'Offline',
    'supervisor_online'            => 'Online',

    // Tools
    'standings_builder'            => 'Standings Builder',

    // Footer
    'web_version'                  => 'Web Version',
    'sde_version'                  => 'SDE Version',
    'render_in'                    => 'Rendered In',
    'copyright'                    => 'Copyright',
];

`

**Comment by leonjza** [comment]
Thank you! This will be most welcome.

I would recommend you fork the [web](https://github.com/eveseat/web) repository and a language file [here](https://github.com/eveseat/web/tree/master/src/lang). You can use the English one as reference from [here](https://github.com/eveseat/web/blob/master/src/lang/en/seat.php). Once done, submit the pull request back.

Thanks again.

**Comment by leonjza** [comment]
Closing this for now. Please feel free to submit a PR for the Chinese language when you are ready.
