### ISSUE TITLE
Create hook for Character and Corporation view

### ISSUE THREAD

**Issue by freedenizen** [eveseat/seat#17]
Create hooks so that external packages can appear on the top menus for character and corporation pages

**Comment by leonjza** [comment]
This has been added to `eveseat/web` [1.0.18](https://github.com/eveseat/seat/wiki/Web-Changelogs#1018). For details on how to use this, see [this](https://github.com/eveseat/seat/wiki/Package-Development#views---character-submenus) and [this](https://github.com/eveseat/seat/wiki/Package-Development#views---corporation-submenus). Information on bootstrapping the required config can be found [here](https://github.com/eveseat/seat/wiki/Package-Development#views---bootstrapping-menu-items)
