### ISSUE TITLE
Starbase State notification firing unessesary

### ISSUE THREAD

**Issue by leonjza** [eveseat/seat#176]
* **Problem**: The starbase state change notification alerts even when the state actually hasn't changed.
* **Expected**: The alert should fire only when the starbase state has changed.

The `statetimestamp` field is included in the fields that makes an alert _unqiue_: https://github.com/eveseat/notifications/blob/master/src/Alerts/Corp/StarbaseStateChange.php#L122

To 'fix' this, a new concept should be introduced where a uniqueness check should only occur on the last value in the history cache, and not all values. The `statetimestamp` value should also be removed then.

**Comment by Raikia** [comment]
In addition to this, the "New Evemail" notification fires for each evemail received even if the evemail is a duplicate.

Example: if you have 2 characters in an alliance and an alliance mail gets sent, the evemail is reported twice

**Comment by warlof** [comment]
Flag it as a wontfix since starbase is on the dying line.
