### ISSUE TITLE
Feature request: Force assign all new API keys to a user

### ISSUE THREAD

**Issue by Raikia** [eveseat/seat#177]
Hi,

A nice feature would be the ability to force-assign all new API keys added to a designated user.  My use-case is using SEAT as a "blackhole" of API keys.  If someone submits a new API key, the owner is assigned to the admin user and then they only have permissions to view the information that is granted via access control.

**Comment by Raikia** [comment]
Or a button up here:

![img](https://vgy.me/ehE7xH.png)

that says "Assign all API keys to self" if the user is a superuser.

**Comment by leonjza** [comment]
Not 100% sure I understand your use case here, but its not really a hard thing to implement.

**Comment by leonjza** [comment]
Just to double check. Are you asking that keys currently assigned to the admin user have a way to be bulk reassigned to someone else, or all keys in SeAT?

**Comment by Raikia** [comment]
I am asking for a superuser-level button that assigns all API keys in the system to the current user.

Use:  Have recruiters submit API keys to the system and use SEAT for recruitment purposes, then periodically click this button so the superuser gains ownership over it and the recruiter loses access.

**Comment by leonjza** [comment]
Perfect thanks for the explanation!

**Comment by leonjza** [comment]
No more a thing in 3x.
