### ISSUE TITLE
Add new endpoints for "People Groups" feature

### ISSUE THREAD

**Issue by BenHUET** [eveseat/seat#178]
Would be nice to be able to query these data from the SeAT API.

Something like : 

- GET `/api/v1/group/` to list all existing groups.
- GET `/api/v1/group/{group_id}` to get details from one group. (main character, alts, keys...)

**Comment by leonjza** [comment]
Definitely possible! Thanks for the suggestion.

On this topic, I anticipate people groups becoming more a thing once ESI is in full swing.

**Comment by leonjza** [comment]
Added the endpoints and docs in the above mentioned commits. Will be available in the latest api package later today.
