### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by Raikia** [eveseat/seat#179]
![img](https://vgy.me/bIDVUK.png)

This happens every time SEAT tries to pull one specific API key... if there is a way to see what API its failing on, I can send the API to you.

**Comment by leonjza** [comment]
Just above this block there should be a small summary that includes thins like owner id, job hash etc. The owner id related to the api key in question for this job.

Having a look at the code [here](https://github.com/eveseat/eveapi/blob/master/src/Api/Base.php#L201), for some reason there is difficulty getting either the characters for the key in question, or the corporation the character is in to process the Corporation Assets update.

**Comment by Raikia** [comment]
![img](https://vgy.me/PYQtM0.png)

That doesn't tell me the API keyid or anything though, unfortunately.  All the API keys are owned by one user, so the owner ID doesn't help :-/

**Comment by leonjza** [comment]
Alright. PM me the key on Slack then I can have a look.

**Comment by leonjza** [comment]
Any update on that key?

**Comment by Raikia** [comment]
The problem is I have over 2500 API keys in the system and that error message doesn't tell me which API key it is that is failing :-/.

**Comment by leonjza** [comment]
Ill check if I can patch in some relation to a key for the error reporting.

**Comment by leonjza** [comment]
Just realized, in the `queue/errors` view, the `ownerID` field is visible in the error list. This reflects the keyID that error was caused on.

**Comment by Raikia** [comment]
Honestly I'm extremely confused at what I'm seeing on this API key.  It.....has no associated accounts....wtf?
3366895
QqJnfL8OeluVmxSNPD6sGWDylOmY8wOaa26tnduMjCy7kcgaC43QXATu2FaZOtcd

Maybe its just an old-ass key that doesn't work anymore.

![image](https://cloud.githubusercontent.com/assets/18066499/22283176/659c029e-e2a6-11e6-8d38-f8f795bc8f3a.png)

**Comment by leonjza** [comment]
Maybe the account sold off all of the characters via the character bazaar. Thanks for the key, I will definitely patch this asap.

**Comment by Raikia** [comment]
Well, its a corporation key, so no idea, lol

**Comment by leonjza** [comment]
> Well, its a corporation key, so no idea, lol

Oh dear. Good point! Nonetheless, I am going to add a check for this.

**Comment by leonjza** [comment]
The entire job system has changed in 3x.
