### ISSUE TITLE
Problem when updating Seat version

### ISSUE THREAD

**Issue by kishar3762** [eveseat/seat#18]
Hey !
I have a problem when I want to update from Seat 0.14 to 1.0.
If I use the line: "php artisan vendor:publish --force" then, I have this "error:  [InvalidArgumentException]
  There are no commands defined in the "vendor" namespace."

I'm using Laravel 4.1.31 (source of the file: the install of Seat 0.14).

Do you have any idea how I can do to update Seat ?

**Comment by freedenizen** [comment]
There is no upgrade path, you need to do a clean install

**Comment by leonjza** [comment]
There is no 0x -> 1x upgrade path.
