### ISSUE TITLE
Extend Slackbot Access Management to in-game titles

### ISSUE THREAD

**Issue by BenHUET** [eveseat/seat#182]
![image](https://cloud.githubusercontent.com/assets/5278648/22150440/53334e7c-df19-11e6-9186-629d43447131.png)

Add a new tab in this view to allow the Slackbot to manage channel access based on people's in-game titles. 

For example if an user has a character with the title "Director", the bot will give him access to #director (combined with all other filters). 

It would allow a more fluent management since for now an user has to be manually removed/added from/to a group in SeAT to give him access to specific slack's channels.

**Comment by warlof** [comment]
Hey, slackbot is a third party extension.

https://github.com/warlof/slackbot/issues

**Comment by leonjza** [comment]
@BenHUET looks like this might have been added in https://github.com/warlof/slackbot/commit/e4bafc04f061450d303a1d8e56aa531495664905.
