### ISSUE TITLE
Totals on Dashboard include stats of all characters in the system.

### ISSUE THREAD

**Issue by Raikia** [eveseat/seat#183]
This is an access-control failure.  On the dashboard, "Total Character Isk" and "Total Character Skillpoints" lists the number of all the characters in the system together.  So someone with minimal access to seat can see those stats and have an idea of the amount of data in the system.

These statistics should only be of the characters the user has access to.

**Comment by leonjza** [comment]
I do not agree that this is an _access control failure_ **at all**. Please can you elaborate what I know by knowing that there is x amount of skillpoints and x amount of isk in the system apart from maybe the size of the installation?

**Comment by mmolitor87** [comment]
I don't really see a security risk behind it, but rather I would prefer that it limits it to the characters under each user's name so the information is more useful.

Why would a user care about seeing system totals? Maybe move that information to the corporation summary so it can be restricted if needed and then we have the best of both worlds?

**Comment by Bamfro** [comment]
Is there a way to turn this feature off? as stated when people join Eveseat(no roles added yet) they see a total of Isk and SP

**Comment by warlof** [comment]
Answer still negative

**Comment by Bamfro** [comment]
TY Warlof

**Comment by warlof** [comment]
solved with last release of `web` and `services`
