### ISSUE TITLE
Feature request: change industry overview

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#184]
In the corp industry overview (corporation/view/industry/) currently a list is showing of current and past industry jobs.

It would be nice to have by default only the jobs that are currently running or are completed but not yet delivered, and seperate any other past jobs to a seperate history overview.

Secondly, currently the installation date is being shown, which for most purposes is not interesting and it would be nice to replace this with the (expected) completion date instead.

Thanks!

**Comment by leonjza** [comment]
> Secondly, currently the installation date is being shown, which for most purposes is not interesting and it would be nice to replace this with the (expected) completion date instead.

Thanks. This feedback is valuable (considering I am not much of an indy guy to really understand it :P)

**Comment by kwazulueve** [comment]
Np

I would also recommend showing only active jobs (industry/science) by default. Could seperate the active and historic jobs into seperate tabs, or a selection option

**Comment by Jeckerson** [comment]
+1 for that feature. It really missing part not being able to see when job will be finished.

Separate jobs in different panels would be amazing. 
Also, summary page of all characters/corps industry jobs.

**Comment by kwazulueve** [comment]
I am giving a 250 mil bounty to whoever solves this issue before the 1st of September 2017

**Comment by warlof** [comment]
@kwazulueve I'll prefer a reward than a bounty :p

Thank to support SeAT :)

**Comment by kwazulueve** [comment]
Nice, sending iskies as soon as I can update my installation :D

**Comment by kwazulueve** [comment]
Thanks
