### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by fackir** [eveseat/seat#187]
```
[Tue Feb 28 05:39:38.023993 2017] [:error] [pid 1148] [client 192.168.0.1:49997] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/seat/vendor/eveseat/services/src/Helpers/helpers.php on line 265
[Tue Feb 28 05:39:46.280330 2017] [:error] [pid 2626] [client 192.168.0.1:50003] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/seat/vendor/eveseat/services/src/Helpers/helpers.php on line 265, referer: *******/configuration/settings/view
[Tue Feb 28 05:39:48.946848 2017] [:error] [pid 1210] [client *******:51784] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/seat/vendor/eveseat/services/src/Helpers/helpers.php on line 265, referer: *******/corporation/view/ledger/bountyprizes/98363768

    sudo -u apache php artisan seat:admin:diagnose
This helps to check whether the permissions are correct.

 * Getting environment information
Current User: www-data
PHP Version: 7.0.16-3+deb.sury.org~trusty+1
Host OS: Linux webserver 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/app/pheal/ is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is writable

 * Checking Database
+------------+------------------+
| Setting    | Value            |
+------------+------------------+
| Connection | mysql            |
| Host       | 127.0.0.1        |
| Database   | seat1            |
| Username   | seat             |
| Password   | **************** |
+------------+------------------+
Connection OK to database: seat1

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: uMa84DQtENpUjYsOblq9qGaSoilNvRyuixJkh70fHWzm3kjHVgLVf9NC1r9TkLN7
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 24602

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 2.0.7         | 2.0.7         |
| Console       | 2.0.4         | 2.0.4         |
| Eveapi        | 2.0.10        | 2.0.10        |
| Notifications | 2.0.8         | 2.0.8         |
| Web           | 2.0.13        | 2.0.13        |
| Services      | 2.0.8         | 2.0.8         |
+---------------+---------------+---------------+
SeAT Diagnostics complete
```

**Comment by warlof** [comment]
Hello fackir,

can you provide the full stack exception ?
It should be available into `seatpath/storage/logs/laravel-date.log`

**Comment by fackir** [comment]
Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(116): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'seat', '*************...', Array)
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(56): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'seat', '************...', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#3 /var/www/seat/bootstrap/cache/compiled.php(12036): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(965): call_user_func(Object(Closure))
#6 /var/www/seat/bootstrap/cache/compiled.php(11897): Illuminate\Database\Connection->getPdo()
#7 /var/www/seat/bootstrap/cache/compiled.php(11892): Illuminate\Database\DatabaseManager->refreshPdoConnections('mysql')
#8 /var/www/seat/bootstrap/cache/compiled.php(11918): Illuminate\Database\DatabaseManager->reconnect('mysql')
#9 [internal function]: Illuminate\Database\DatabaseManager->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(820): call_user_func(Object(Closure), Object(Illuminate\Database\MySqlConnection))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(792): Illuminate\Database\Connection->reconnect()
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(732): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\Database\QueryException), 'insert into `fa...', Array, Object(Closure))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `fa...', Array, Object(Closure))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `fa...', Array)
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `fa...', Array)
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `fa...', Array, NULL)
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php(62): Illuminate\Database\Query\Builder->insertGetId(Array)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(162): Illuminate\Queue\Failed\DatabaseFailedJobProvider->log('redis', 'medium', '{"id":"pADig4tO...', 'Illuminate\\Queu...')
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(132): Illuminate\Queue\Console\WorkCommand->logFailedJob(Object(Illuminate\Queue\Events\JobFailed))
#20 [internal function]: Illuminate\Queue\Console\WorkCommand->Illuminate\Queue\Console\{closure}(Object(Illuminate\Queue\Events\JobFailed))
#21 /var/www/seat/bootstrap/cache/compiled.php(10266): call_user_func_array(Object(Closure), Array)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(371): Illuminate\Events\Dispatcher->fire('Illuminate\\Queu...')
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->raiseFailedJobEvent('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\MaxAttemptsExceededException))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(268): Illuminate\Queue\Worker->failJob('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\MaxAttemptsExceededException))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(197): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\Queue\Jobs\RedisJob), 1)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#30 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#31 /var/www/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#33 /var/www/seat/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/seat/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/seat/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/seat/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 {main}

**Comment by fackir** [comment]
seat2.0 and seat-development error 500
seat 1.7work

**Comment by NathMorgan** [comment]
Getting the same issue here:

root@REMOVED:/var/www/seat.eve-apoc.org/public_html# sudo -u REMOVED php artisan seat:admin:diagnose
SeAT Diagnostics
If you are not already doing so, it is recommended that you run this as the user the workers are running as.
Eg:
    sudo -u apache php artisan seat:admin:diagnose
This helps to check whether the permissions are correct.

 * Getting environment information
Current User: REMOVED
PHP Version: 7.1.2-3+deb.sury.org~xenial+1
Host OS: Linux eve-apoc.org 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64
SeAT Basepath: /var/www/REMOVED/public_html

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/REMOVED/public_html/storage is writable
/var/www/REMOVED/public_html/storage/app/pheal/ is writable
/var/www/REMOVED/public_html/storage/sde/ is writable
/var/www/REMOVED/public_html/storage/logs/laravel.log is not writable

 * Checking Database
+------------+----------------------------------+
| Setting    | Value                            |
+------------+----------------------------------+
| Connection | mysql                            |
| Host       | 127.0.0.1                        |
| Database   | REMOVED                    |
| Username   | REMOVED                         |
| Password   | REMOVED |
+------------+----------------------------------+
Connection OK to database: alliance_seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | REMOVED |
| Port     | REMOVED      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: iC1F03qlJH38pJkd1peghuPrZQ9OswzIA8WJ1U5bxIQShMiTyeO9lxKJRx2s0TtY
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 20352

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 2.0.7         | 2.0.7         |
| Console       | 2.0.4         | 2.0.4         |
| Eveapi        | 2.0.10        | 2.0.10        |
| Notifications | 2.0.8         | 2.0.8         |
| Web           | 2.0.13        | 2.0.13        |
| Services      | 2.0.8         | 2.0.8         |
+---------------+---------------+---------------+
SeAT Diagnostics complete

**Comment by leonjza** [comment]
Guys, please join the slack channel for  support on this. If it is determined to be a code bug there, then we can log a ticket with the details needed.

Thanks.

**Comment by NathMorgan** [comment]
Fixed it, was an error on my part it was running PHP 5.6 instead of 7.1.... Ooops!

**Comment by fackir** [comment]
Fixed it, was an error on my part it was running PHP 5.6 instead of 7.1.
