### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by McGirton** [eveseat/seat#188]
Would it be possible to get this as Docker Container? Does anybody maybe have it already? 
Thanks!

**Comment by leonjza** [comment]
You may find lots of interesting and useful things here: https://github.com/eveseat/scripts

;)

**Comment by warlof** [comment]
https://github.com/eveseat/scripts/tree/master/docker

scripts repository have a lot of usefull stuff for sysadmin ;)

**Comment by wasgehthierab** [comment]
and how do you make data persistent?
which folders do you have to expose?
