### ISSUE TITLE
Feature requests: access mask's alert if changed

### ISSUE THREAD

**Issue by shir4hime** [eveseat/seat#189]
Hello,

It could be really cool to get away to be alerted if an API already saved in the database has been modify and do not meet anymore the minimum requirement asked when entered.
It could be cool too, to get away to directly see the access mask of the API on the List all APIs page.

And then, something else, have a direct button on the List all APIs page to update it. Indeed I would like to give a permission to user to be able to check if the API meets the minimum requirement and be able to refresh it without giving the APIkeydetails permission because it's showing the ID and vCode.

**Comment by leonjza** [comment]
While I agree that this is definitely something that would have been nice, one needs to keep in mind that the move to ESI is going to dramatically change the way API access works. No longer will there be such a thing as access masks and other funny things. A one time scope acceptance is all that is going to be needed. Then, there is either a refresh token for a character or not.

What I am saying is I am not sure if its worth the efforts atm when it could probably be better spent getting ESI integration ready ; ))
