### ISSUE TITLE
Installing Seat on Debian / composer error

### ISSUE THREAD

**Issue by shir4hime** [eveseat/seat#19]
On the step of this command line: 
"composer create-project eveseat/seat seat --keep-vcs --prefer-source --no-dev"
I have this error: 
" [InvalidArgumentException]
  Could not find package eveseat/seat with stability stable."

Do you have any idea how I can resolve this issu ?

**Comment by warlof** [comment]
Looks a network issue.
What about your firewall ?

**Comment by shir4hime** [comment]
I've just flushed iptables but I still have the same issue

**Comment by warlof** [comment]
what are your network architecture ? something like a proxy or another firewall ?
Is iptable got a default flag equal to ACCEPT on all kind of route ?

**Comment by shir4hime** [comment]
All trafic seems allowed after flushing rules :

Chain INPUT (policy ACCEPT)
target     prot opt source               destination
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

No further rules after those

**Comment by leonjza** [comment]
Could you give some more details about your environment? Is this a fresh debian install? What versions etc. At best id like to try and replicate this.

In the mean time, try the following. If you cant get `composer create-project` to work. Run the following:

- `git clone https://github.com/eveseat/seat.git`
- `cd seat`
- `composer install`
- Continue with the rest of the install guide.

**Comment by shir4hime** [comment]
Thanks for your quick replies.

OS is Debian 7 x64.
As it was not a fresh install, I've created a new fresh one in VirtualBox (Debian 7.9 iso minimal with latest package)., I get the exact same issue : "Could not find package eveseat/seat with stability stable.".

Cloning the repository and running manually composer as you wrote seems to work but I'm in front of a new problem, my Php version is too old, I got 5.4.45, and > 5.5.9 is asked.

I think my OS is too old for the requirements of the latest Seat version, so I wil try another fresh Debian install in VirtualBox, but with version 8.2 this time.

**Comment by leonjza** [comment]
Can you post the output of `composer create-package eveseat/seat -vvv` ?

**Comment by shir4hime** [comment]
@debian7:/var/www# composer create-package eveseat/seat -vvv

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "create-package" is not defined.

Exception trace:
 () at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:514
 Symfony\Component\Console\Application->find() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25

**Comment by shir4hime** [comment]
Here the output of composer list, create-package seems not exist :

root@debian7:/var/www# composer list
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0-dev (d6ae9a0529e1f39c4c7f9b2f29fff019d79cd1fb) 2015-12-22 20:44:41

Usage:
  command [options] [arguments]

Options:
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --profile                  Display timing and memory usage information
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  about           Short information about Composer
  archive         Create an archive of this composer package
  browse          Opens the package's repository URL or homepage in your browser.
  clear-cache     Clears composer's internal package cache.
  clearcache      Clears composer's internal package cache.
  config          Set config options
  create-project  Create new project from a package into given directory.
  depends         Shows which packages depend on the given package
  diagnose        Diagnoses the system to identify common errors.
  dump-autoload   Dumps the autoloader
  dumpautoload    Dumps the autoloader
  global          Allows running commands in the global composer dir ($COMPOSER_HOME).
  help            Displays help for a command
  home            Opens the package's repository URL or homepage in your browser.
  info            Show information about packages
  init            Creates a basic composer.json file in current directory.
  install         Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.
  licenses        Show information about licenses of dependencies
  list            Lists commands
  remove          Removes a package from the require or require-dev
  require         Adds required packages to your composer.json and installs them
  run-script      Run the scripts defined in composer.json.
  search          Search for packages
  self-update     Updates composer.phar to the latest version.
  selfupdate      Updates composer.phar to the latest version.
  show            Show information about packages
  status          Show a list of locally modified packages
  suggests        Show package suggestions
  update          Updates your dependencies to the latest version according to composer.json, and updates the composer.lock file.
  validate        Validates a composer.json and composer.lock

**Comment by leonjza** [comment]
Apologies. I meant `create-project`.

**Comment by shir4hime** [comment]
haha no problem, here it is :

@debian7:/var/www# composer create-project eveseat/seat -vvv
Downloading https://packagist.org/packages.json
Writing /root/.composer/cache/repo/https---packagist.org/packages.json into cache
Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json from cache
Downloading http://packagist.org/p/provider-2015-04%24afedd3b8f9b1aaaa9dcb7d61f36cb4a76f9486a2e784a5bf03b6d592edba9477.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json into cache
Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json from cache
Downloading http://packagist.org/p/provider-2015-10%2410f5900b65ece440506cfa20bb0f17233b365a93041bd737b587cc0beb6511de.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json into cache
Reading /root/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%247da3a441b0f61531e83aceee06562a0f9a88d7493fa91e9f3ebc9c0c0f655e89.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Reading /root/.composer/cache/repo/https---packagist.org/provider-eveseat$seat.json from cache



  [InvalidArgumentException]
  Could not find package eveseat/seat with stability stable.



Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:287
 Composer\Command\CreateProjectCommand->installRootPackage() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:141
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:130
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by shir4hime** [comment]
The command "composer create-project eveseat/seat seat --keep-vcs --prefer-source --no-dev" works like a charm on Debian 8.2, I continue installing.

**Comment by leonjza** [comment]
Will investigate the Debian 7 issue.
For now, its a start from scratch, although there is a todo to create some scripts that will migrate data from SeAT 0x to 1x.

**Comment by shir4hime** [comment]
Thanks for your support, I will check the todo.

You should forget the Debian 7 issue as the Php version of this OS is obsolete.
It would be easier to dist-upgrade to Debian 8 instead of manually compiling an up to date Php version..

**Comment by leonjza** [comment]
For the record: https://github.com/eveseat/seat/wiki/FAQ#q-when-i-try-and-install-seat-i-get-an-error-like-invalidargumentexception-could-not-find-package-eveseatseat-with-stability-stable
