### ISSUE TITLE
persistent docker image

### ISSUE THREAD

**Issue by wasgehthierab** [eveseat/seat#190]
Hey there,

how do I make the data in the container persistent? Do you have any further instructions how to run it in docker?

thx

**Comment by McGirton** [comment]
Would like to know this as well. As of now you can set it up but without proper saving it's worthless unfortunately.

**Comment by wasgehthierab** [comment]
anyone?

**Comment by leonjza** [comment]
Assuming I have time, I'll try get a proper `docker-compose` slapped together for production use next week.

**Comment by wasgehthierab** [comment]
Hey :) 

any news on this? 

thx in advance

**Comment by leonjza** [comment]
There is a PR for this atm [here](https://github.com/eveseat/scripts/pull/9) for those whom want to give it a spin.

**Comment by thiesschneider** [comment]
i will try this. hope the PR will soon be closed :)

**Comment by wasgehthierab** [comment]
is anybody going to close this?

**Comment by leonjza** [comment]
Definitely, its just a matter of time. ;)

**Comment by leonjza** [comment]
Check out https://github.com/eveseat/scripts/tree/master/docker-compose thanks to @BenHUET.
