### ISSUE TITLE
Potential API key cleanup issue

### ISSUE THREAD

**Issue by pandarus-jaded** [eveseat/seat#192]
* **Problem**:  Users (non admins), when they have recreated their API keys and re-added them to SEAT are unable to see people groups they have created.
The people group does actually get created (can be seen by admin), but the individual user does not see it.

It appears that the people group is created based on the previous API key that has not been deleted, BUT it is also not associated with that user any more. 

When the admin adds the new key to the existing people group (the one the user cannot see), the peoplegroup becomes visible to the user, and the user can then unlink the "old key", and it appears to be removed from the system.

* **Expected**:  User should be able to create a new people group and see it without admin intervention

* **Logs / Screenshots / Proof**: I've manually "fixed" all of our people groups so there aren't any screenshots to add, but if it happens again I will take a screenshot

* **Version Info**: PHP 7.0.14, Centos 7,  SEAT version 2.0.8

**Comment by warlof** [comment]
https://github.com/eveseat/web/pull/81

**Comment by leonjza** [comment]
Fix should land in a new version of the web package later today.

**Comment by leonjza** [comment]
PR merged. Should be fixed now. Thanks @warlof !
