### ISSUE TITLE
changing domains

### ISSUE THREAD

**Issue by shadowcodex** [eveseat/seat#197]
I am changing my domain to be used with SEAT. However I'm not 100% sure on the correct way to do this.

Here is what I believe needs to happen, but how do I do it?
1. DNS Changed (Done)
2. Add new Let's Encrypt SSL for new domain (How?)
3. Update NGINX configs for new domain (best way?)

Thanks!

**Comment by leonjza** [comment]
SeAT it self will probably just run fine and not even know the domain changed. ;) As for web server configs and Lets Encrypt stuff, it will be best to just join Slack and ask in the #support channel.
