### ISSUE TITLE
Recruiters for 1 corp within Alliance

### ISSUE THREAD

**Issue by sergiorochalopes** [eveseat/seat#199]
I am having issues creating a recruiter role in Seat.
My setup has an Alliance view, ie, added 10 corporation APIs to it.

I now need to setup a recruitment role for each corp, ie, recruiter from Corp X can only see Corp X and character sheets for Corp X member (without having to add each member individually into affiliations).

Example:
- Recruiter from Corp X (and only Corp X) can list and view/open the Corp Sheet & Corp Tracking (works)
- Recruiter from Corp X (and only Corp X) clicks on Tracking and views Corp member list (works)
- Recruiter from Corp X (and only Corp X) clicks on the Name of a member (API added previously) and sees the Character Sheet & Character Contacts (does not work -- Unauthorized Request).

Any help?

Thank you!

**Comment by warlof** [comment]
about the last point, not doable with current ACL.

corp permission refer to corp object and char permission refer to char object.
There are no cross type inheritance at the moment (planned for 3.x or maybe if this PR is merged https://github.com/eveseat/web/pull/76)

**Comment by leonjza** [comment]
With the XML API and "many characters per account key" concept falling away, the permissions overhaul might also make a lot of things easier to do in SeAT. Closing this for now as something that we can definitely revisit with 3.x
