### ISSUE TITLE
Error while php artisan key:generate

### ISSUE THREAD

**Issue by Cynabal** [eveseat/seat#2]
I used the CentOS Setup guide from the wiki.

I ran into an error while `php artisan key:generate`

PDO Error cannot find Table `schedules`.

i cretated the table manually and ran after that in an error while `php artisan migrate`

PDO Error Table schedules already exist.

I added following line to the `database/migrations/2015_12_01_201414_create_schedules_table.php` infront of `Schema::create...`

`Schema::drop('schedules');`

I got 1.0.3 running with this workaround.

Maybe i missed something in the instructions :P

**Comment by leonjza** [comment]
Thanks! This is something I am aware of at the moment and will be fixed before the official release.
