### ISSUE TITLE
SSO Auth Failure

### ISSUE THREAD

**Issue by Amely87** [eveseat/seat#200]
I have a Problem with SSO Auth

{"error":"invalid_request","error_description":"Some parameters are either missing or invalid"}

What is the Problem here ?

**Comment by warlof** [comment]
hello,

should be the SSO settings, did you setup the values into `.env` file which is located at seat root directory ?

**Comment by Amely87** [comment]
In the log: 
EVE_CLIENT_ID=null
EVE_CLIENT_SECRET=null
EVE_CALLBACK_URL=https://url.bbio-eve.de/auth/eve/callback

the path is /var/www/seat.

**Comment by warlof** [comment]
those parameters should be set according to the app you've created early on ccp portal.

see http://seat-docs.readthedocs.io/en/latest/admin_guides/sso/

**Comment by Amely87** [comment]
Okay, tghanks.

Now have problem:

ERR_CONNECTION_REFUSED when he get to https

**Comment by warlof** [comment]
are you using https ?

**Comment by Amely87** [comment]
when he go t https he has error

**Comment by leonjza** [comment]
Closing this for now as it seems like a setup issue. If you need more help @Amely87, please join the SeAT Slack group.
