### ISSUE TITLE
Trying to get property of non-object 

### ISSUE THREAD

**Issue by garry198** [eveseat/seat#201]
we see some errors in log

```
[2017-05-26 17:50:04] local.ERROR: ErrorException: Trying to get property of non-object in /var/www/admin/data/www/prothean.org/seat/vendor/eveseat/services/src/Repositories/Corporation/Starbases.php:191
Stack trace:
#0 /var/www/admin/data/www/prothean.org/seat/vendor/eveseat/services/src/Repositories/Corporation/Starbases.php(191): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/admin/...', 191, Array)
```

new api key added, but see http://joxi.ru/dp27KQ7ilVvJ27
seat version 2.0.82

can you help?

**Comment by garry198** [comment]
our hosters administrators say this can only be fixed from your side. 
so far our seat version is unusable
yesterday it was working - today it permanently crashed. please help

**Comment by warlof** [comment]
what are the mask from the missing keys ?!
as well, is the issue start when those keys has been added ?

**Comment by warlof** [comment]
pong @garry198 
what's up with this issue ?
