### ISSUE TITLE
404 due /seat/public/home

### ISSUE THREAD

**Issue by Traace** [eveseat/seat#203]
* **Problem**: _Whats wrong?_

Seat got installed well. But it seems like it isn't compatible with the Nginx Webserver. The root folder is the seat public folder exactly like in the tutorial.

When i connect to. Seat reroutes me to a /var/www/seat/public/home and this folder is not there anyway..

I'm sure that my configuration is correct.
Therefore it must be a bug within seat code.

Nginx Config:
`server {
	listen 80;
	listen [::]:80;

	root /var/www/seat/html;

	# Add index.php to the list if you are using PHP
	index index.php index.html index.htm index.nginx-debian.html;

	server_name hide.hide.me www.hide.hide.me;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass PHP scripts to FastCGI server
	#
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
	#
	#	# With php-fpm (or other unix sockets):
		fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	}
}`

Seat Config:

`APP_ENV=local
APP_KEY=base64:*hidememachide*
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://*hidden domain here ;)*

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=seat
DB_USERNAME=seat
DB_PASSWORD=*hideme mc hide*
DB_DEBUG=false

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=redis

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=noreply@localhost.local

EVE_CLIENT_ID=null
EVE_CLIENT_SECRET=null
EVE_CALLBACK_URL=http://seat.local/auth/eve/callback
`
* **Expected**: _What did you expect to happen?_

The correct folder has to be /var/www/seat/public/ so nginx can actually find some files to work with

PHP 7.0.18 (+ OPCache) | Newest Seat version | Ubuntu 17.04

Using Apache is no option for my environment at all.

**Comment by warlof** [comment]
https://github.com/eveseat/scripts/blob/master/docker/nginx/default

**Comment by Traace** [comment]
Perfect. works great

Thanks for that fast help.
