### ISSUE TITLE
How to add another language to this project

### ISSUE THREAD

**Issue by fujiwara-takumi** [eveseat/seat#204]
How to add another language to this project. I am a player of EVE China server, I hope this project can support EVE China and Simplified Chinese.

**Comment by warlof** [comment]
Hi,

In each package you have a lang directory which is containing a sub
directory per language :
en -> English
fr -> French
ch -> Chiness

Fork every project
Append the language directory including the file
Translate the content
Commit and push your change
Open a pull request

:)

Le 6 juin 2017 3:20 AM, "fujiwara-takumi" <notifications@github.com> a
écrit :

**Comment by leonjza** [comment]
This was added in eveseat/web/pull/79. Thanks @violarulan!
