### ISSUE TITLE
i can't set the admin password~

### ISSUE THREAD

**Issue by fujiwara-takumi** [eveseat/seat#206]
[root@localhost ~]# php artisan seat:admin:reset
Could not open input file: artisan

**Comment by leonjza** [comment]
Make sure that you are in the SeAT directory. If you followed the documentation, this will be in `/var/www/seat`. Issuing the command from that directory will work as the `artisan` script lives there.

**Comment by leonjza** [comment]
Please join the SeAT slack group for more help. Thanks!
