### ISSUE TITLE
php-dom isn't found using installer

### ISSUE THREAD

**Issue by vaindil** [eveseat/seat#207]
* **Problem**: Installer is trying to install `php-dom`, but that package is part of `php-xml`. It therefore fails.

* **Expected**: `php-xml` is already installed, so the installer should've accepted that and continued.

* **Logs / Screenshots / Proof**:

Relevant part of the installer log:
```
Running command: apt-get install php-dom -y
Package Installation (php-dom)> Reading package lists...
Package Installation (php-dom)> Building dependency tree...
Package Installation (php-dom)> Reading state information...
Package Installation (php-dom)> Package php-dom is a virtual package provided by:
  php7.1-xml 7.1.6-1~ubuntu16.04.1+deb.sury.org+1Package Installation (php-dom)> php7.0-xml 7.0.20-2~ubuntu16.04.1+deb.sury.org+1Package Installation (php-dom)> php5.6-xml 5.6.30-12~ubuntu16.04.1+deb.sury.org+1
Package Installation (php-dom)> EPackage Installation (php-dom)> : Package Installation (php-dom)> Package 'php-dom' has no installation candidatePackage Installation (php-dom)>

[Seat\Installer\Exceptions\PackageInstallationFailedException]
php-dom installation failed.
```
`php-dom` is already installed as part of `php-xml`:
```
$ sudo apt-get install php-dom
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php-dom is a virtual package provided by:
  php7.1-xml 7.1.6-1~ubuntu16.04.1+deb.sury.org+1
  php7.0-xml 7.0.20-2~ubuntu16.04.1+deb.sury.org+1
  php5.6-xml 5.6.30-12~ubuntu16.04.1+deb.sury.org+1
You should explicitly select one to install.

E: Package 'php-dom' has no installation candidate

$ sudo apt-get install php7.1-xml
Reading package lists... Done
Building dependency tree
Reading state information... Done
php7.1-xml is already the newest version (7.1.6-1~ubuntu16.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt-get install php7.1-dom
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.1-xml' instead of 'php7.1-dom'
php7.1-xml is already the newest version (7.1.6-1~ubuntu16.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

* **Version Info**: PHP 7.1, Ubuntu 16.04, SeAT Installer 2f555de

**Comment by huideaki** [comment]
I just got the same problem with a fresh 16.04 install

**Comment by warlof** [comment]
using only base repository or custom ones ?

**Comment by idlenexusgaming** [comment]
I did not run into this when I installed it on a fresh 16.04 host

**Comment by Nadarob-Skillane** [comment]
This seems to be a bug with the latest php release. 
I had all going fine on my ubuntu server, but SEAT failed for this exact reason as soon as I did an apt-get update.
Luckily I am using digitalocean and had created a snapshot prior to updating.

**Comment by warlof** [comment]
I more think it's related to your php default version which should most probably not be the 7.1 for which you installed dom extension.

**Comment by warlof** [comment]
pong @vaindil
what's the status of this issue ?

Did you solved it ?

**Comment by raykai** [comment]
running on digitalocean VPS fresh Ubuntu 16.04.3 X64

i get this error to when using the Quick Install method:

![1bug](https://user-images.githubusercontent.com/8138894/31575453-6beb806a-b0b5-11e7-9712-c01ce751a5ca.JPG)

**Comment by leonjza** [comment]
Added ppa now. Should be ok.

**Comment by gknasln** [comment]
how did you do it @leonjza  ? please send command

**Comment by warlof** [comment]
https://eveseat.github.io/docs/installation/manual_installation/#php
