### ISSUE TITLE
[Feature request] Some ideas/suggestion

### ISSUE THREAD

**Issue by SNIPER722** [eveseat/seat#208]
During the use of SeAT, Here is the problem we encountered

We have PVP, ratting, mining split into 3 different corp in null-sec. (around 600 keys)

I tweak the keys update schedule to every 4 hours. Each run takes about 40 minutes to run.
( for PVP corp to update kill-mail and ratting TAX, but for mining corp 4 hours interval is a bit too short)

**schedule**
I hope there could be a update schedule table for key(s) like groups 
eg. (group A run every hour, group B run every 4 hours and group C run every day)

- this will save resources on update "useless" keys
- If possible constraint keys detail  ( such as update kill-mail every hour and update clone status every week etc.)

**permission**
now all the admins can check/view every key in the system.
may be add constraint to permissions for admin only available to view/change/delete the key belong to their own company and only view the character belong to their own corp.

**update info**
when update each keys add a list of corps/alliance. If character(s) left the company flag the key to be review by admin/mod to determine disable or delete

**Comment by kwazulueve** [comment]
Checking 600 keys for the info you mention seems a waste of resources when the same can be done by checking only a few corporation keys more often (km's, tax entries)

So I can imagine different groups as well but use corp keys for corp info, not the member ones imho

**Comment by SNIPER722** [comment]
Yes, That is what I current wish to happen.  check corp keys every hour and update character keys every day. It could be even detail, like update character km every day but book mark and assert every week.

**Comment by kwazulueve** [comment]
What I've done is run specific keys via a crontab to get them updated more often, while either disabling or slowing the default key check

Ideally yes you could make a distinction between character and corp keys in the Scheduler

**Comment by warlof** [comment]
Closing since it's a little bit too much generic issue.
I've kept the scheduler part in a separated issue which is still relevant whereas others has been sorted.
