### ISSUE TITLE
Corp View for Fuel Techician

### ISSUE THREAD

**Issue by Bamfro** [eveseat/seat#209]
* **Problem**: trying to give a role perms to view star base fuel levels without adding them to the Dangerous Corp listing perm to view a list of all corps in SEAT.
* **Expected**: would like Member to be able to view corp fuel listing for corp in Affiliation without viewing all corps added to seat
* **Logs / Screenshots / Proof**: sorry i can answer questiosnt ot he best of my knowledge
* **Version Info**: latest PHP, Latest SEAT to my knowledge

**Comment by Bamfro** [comment]
Another example of it not working is the sample Corp accountant role described in the read me does not give access to the Corp wallet unless you give it the fifth permission of Corp list (which is listed as dangerous in the manual)

**Comment by warlof** [comment]
Permissions
Corporation.listAll
Corporation.summary
Corporation.starbases

Affiliations
Corp A

Available Users
Whoever you want

**Comment by Bamfro** [comment]
ty, i was hoping i could accomplish this without listing all, but i see i must not have understood the "Affiliation" scope
