### ISSUE TITLE
Undefined variable in Shareholders.php

### ISSUE THREAD

**Issue by l0ser140** [eveseat/seat#21]
Looks like Shareholders.php was broken in this commit: https://github.com/eveseat/eveapi/commit/411e46cb8b70c04b5b6dcbe553ba37be58a939c0#diff-823b6e543bbdbc6b28fdc53492d39ca8
```
Exception: ErrorException
Error Code: 0
Error Message: Undefined variable: character
File: /var/www/seat/vendor/eveseat/eveapi/src/Api/Corporation/Shareholders.php - Line: 84
```

**Comment by leonjza** [comment]
Thanks for the report. I think I never tested a scenario where a corporation is a shareholder.

**Comment by Xaroth** [comment]
I have the same issue, a lot more would have that, seeing the 'default' shareholder when creating a corp, is the corp you are creating.

**Comment by warlof** [comment]
Fix with https://github.com/eveseat/eveapi/pull/4
