### ISSUE TITLE
*/ require __DIR__.'/../bootstrap/autoload.php'

### ISSUE THREAD

**Issue by gbrann** [eveseat/seat#210]
* **Problem**: Missing something during install on Ubuntu Server
* **Expected**: The site to load.
* **Logs / Screenshots / Proof**: 
I get the following when I go to the IP address of the server. 

*/ /* |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provides a convenient, automatically generated class loader for | our application. We just need to utilize it! We'll simply require it | into the script here so that we don't have to worry about manual | loading any of our classes later on. It feels nice to relax. | */ require __DIR__.'/../bootstrap/autoload.php'; /* |-------------------------------------------------------------------------- | Turn On The Lights |-------------------------------------------------------------------------- | | We need to illuminate PHP development, so let us turn on the lights. | This bootstraps the framework and gets it ready for use, then it | will load up this application so that we can run it and send | the responses back to the browser and delight our users. | */ $app = require_once __DIR__.'/../bootstrap/app.php'; /* |-------------------------------------------------------------------------- | Run The Application |-------------------------------------------------------------------------- | | Once we have the application, we can handle the incoming request | through the kernel, and send the associated response back to | the client's browser allowing them to enjoy the creative | and wonderful application we have prepared for them. | */ $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response); 

I followed the documentation perfectly - copy and paste pretty much. The Quick Install gives me errors that the file can't be found on the address provided. So I did the manual Ubuntu installation for 16.04 Server. Loaded on a AWS instance and made public. (52.14.170.96) As you can see I got a Composer error. How can I fix this? (I'd get on your slack if the I could the info)

* **Version Info**:  PHP7, Ubuntu 16.04 Server, Amazon EC2 Instance

**Comment by gbrann** [comment]
the bootstrap is installed - I verified the /var/www/seat/bootstrap had all files and is how it should be. Problem seems to be with the index.php maybe?

**Comment by warlof** [comment]
did you use the installer or install it by your own ?

**Comment by gbrann** [comment]
installed manually as stated. all dependencies are installed and PHP7 is installed, but I need to check if it the default loader. It actually appears that the index.php file is being parsed out like regular text.

**Comment by gbrann** [comment]
found it. there are several important steps missing from the documents. you need in to install zip and unzip  and for this issue, you need to make sure apache has the php7 modules installed, as such

apt-get install libapache2-mod-php7.0

after I did this and restarted apache - it worked great.

**Comment by warlof** [comment]
zip and unzip are recommanded by composer but not mandatory and libapache should be installed as dependency as soon as you've apache installed. I figure something has change since 5.x :(

**Comment by gbrann** [comment]
Yeah. I had to make sure to go back and run the apt-get for zip and unzip prior to composer creating the project or I'd get a bunch of exceptions. And at the end I had to make sure that the php 7 mod was installed for apache as I stated. Otherwise, no issues with the Ubuntu installer as of 7/25/2017.
