### ISSUE TITLE
Character shows wrong corp on Character Sheet page.

### ISSUE THREAD

**Issue by zero-extent** [eveseat/seat#212]
For some Characters on the Character sheet page it is showing the characters previous corporation even though on the Character List screen it shows the character in the correct corporation.
[character corp diff.xlsx](https://github.com/eveseat/seat/files/1198073/character.corp.diff.xlsx)

**Comment by warlof** [comment]
you should first try to clear pheal cache in order to ensure the update are properly updated (corrupted xml lead to crash parsing, therefore no update applied)

to do so : `php artisan seat:cache:clear --include-pheal`
then requeue a job for the key

**Comment by groniu** [comment]
I have similar problem, after investigation I've found that if you remove and change api key for character it does not get updated in https://seat/character/view/sheet/[:id] , "Summary" and "account information" still using the old key but all other info like sklill summary employment history gets updated with new api key

And for me it still showing last pull from old api key like old corp summary  and old api key id and rest int Account Information

SeAT Api Installed: v2.0.8
SeAT Console Installed: v2.0.4
SeAT Eveapi Installed: v2.0.12
SeAT Notifications Installed: v2.0.9
SeAT Web Installed: v2.0.15
SeAT Services Installed: v2.0.10

**Comment by warlof** [comment]
Since Web#2.0.15, key should be properly drop. With which version did you notice that ?

**Comment by groniu** [comment]
I'm not sure ive discovered  it in 2.0.14 but i've changed keys for this character i think 2.0.12 but again not sure

**Comment by groniu** [comment]
account_api_key_infos
account_api_key_info_characters

old api keys are still in this 2 tables but not in eve_api_keys
Is it safe to delete old keys from these 2 tables ?

**Comment by warlof** [comment]
yes it is, they should non longer be there with the 2.0.15 patch, but if the key has been droped previously, they will stay here.

**Comment by groniu** [comment]
removing old api keys from account_api_key_infos and account_api_key_info_characters fixed my issue
