### ISSUE TITLE
Ability to assign role automatically based of corp affiliation 

### ISSUE THREAD

**Issue by Busterguy** [eveseat/seat#213]
I'm looking for a way to give a person a role automatically once they register an API and are confirmed to be in a certain corp.
This is so I don't have to manually go in and give the person the role myself. This is mainly because if people have big corps or alliances and the SeAt is being used by a lot of people joining and leaving, it would be nice to have this automated.
I was told in slack this may be something that can be done with the API. But all I know how to do is edit bits of code that already exist I'm not that good at coming up with new stuff. So if anyone can point me in the right direction or make something for me that will be amazing.

**Comment by warlof** [comment]
You need to read that https://seat-docs.readthedocs.io/en/latest/seat_api/overview/
And that https://seat-docs.readthedocs.io/en/latest/seat_api/eve_api_keys/

About the workflow, create a key from seat ui
Then create a script in whatever language you want
- List all keys
- Foreach keys, get detail
- Foreach detail, get characters and check if the key is meeting your requirements (ie:having a toon in a special corp)
- if the key is meeting your requirements, get the related userid and grant him whatever role you want 

Alternative: alliance Auth should do that (I think)

**Comment by Busterguy** [comment]
A guy in my corp managed to create a script that lets you do this. Works as intended.
Feel free to use it if you also want this. Just step up a cron to auto run it.
https://github.com/AWRyder/seat-autoupdater

**Comment by warlof** [comment]
covered by https://github.com/herpaderpaldent/seat-groups and can be close.
