### ISSUE TITLE
ACL not honor set character.sheet permission

### ISSUE THREAD

**Issue by huberfe** [eveseat/seat#214]
Please don't log issues for general discussions or non code problems. Instead, join us on Slack for a chat.

http://seat-docs.readthedocs.io/en/latest/contact/

For some help on where to find logs, put SeAT into DEBUG mode etc, please refer to the following link:

Current User: root
PHP Version: 7.0.22-0ubuntu0.16.04.1
Host OS: Linux dlp 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/app/pheal/ is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is not writable

 * Checking Database
+------------+------------------------------------------+
| Setting    | Value                                    |
+------------+------------------------------------------+
| Connection | mysql                                    |
| Host       | 127.0.0.1                                |
| Database   | seat                                     |
| Username   | seat                                     |
| Password   | **************************************** |
+------------+------------------------------------------+
Connection OK to database: seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: 56bVGIhRe4vrgQn1eDbsMq3BTv6VXjdSWAQerSnUwxUvkVBTADEQPXZhpUTfkvez
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 29384

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 2.0.9         | 2.0.9         |
| Console       | 2.0.4         | 2.0.4         |
| Eveapi        | 2.0.13        | 2.0.13        |
| Notifications | 2.0.11        | 2.0.11        |
| Web           | 2.0.17        | 2.0.17        |
| Services      | 2.0.11        | 2.0.11        |
+---------------+---------------+---------------+
SeAT Diagnostics complete

Thanks for wanting to report an issue you've found in SeAT. Please delete
this text and fill in the template below. If you are unsure about something,
just do as best as you're able.

* **Problem**:  User with character.sheet permission can not access character sheet. It gets logged as 
![image](https://user-images.githubusercontent.com/6583519/29583647-6d302aaa-8781-11e7-89e4-776f6e09e793.png)

* **Expected**: User has access to character sheet
* **Logs / Screenshots / Proof**:  
![image](https://user-images.githubusercontent.com/6583519/29583740-b521b590-8781-11e7-8a05-8697d50220a9.png)
1. User got character.sheet access
2. user got corp affiliation
3. user is set
receiving this error:
![image](https://user-images.githubusercontent.com/6583519/29583779-d8694f0e-8781-11e7-904a-7ab3eb6d718a.png)

Log shows:
![image](https://user-images.githubusercontent.com/6583519/29583819-fa9153ce-8781-11e7-8995-7a507cece068.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by warlof** [comment]
You're issue is in affiliation.

With current ACL, SeAT can only bind character permission to character affiliation.

With your current role, SeAT will search for `character.*` or `character.characterSheet` permission for `96606430` character but in you're role, you didn't add this character as affiliated one.

**Comment by huberfe** [comment]
solved, TY!

**Comment by warlof** [comment]
You're welcome :)
