### ISSUE TITLE
Corp Affiliation Not Working?

### ISSUE THREAD

**Issue by paintballlaws** [eveseat/seat#218]
So I am trying to add permissions for a corp CEO to be able to view just his corporation and just his characters associated with his corporation but even thou I add all the permissions for that like character.sheet so he can see all the characters and click on them to view all the character info it comes up and says that unauthorized access and when I look in the security log it just says there missing the permission character.sheet so I am highly confused if I am messing something up or if the program is not working as intended? I have the role setup with corp affiliations for just his corp and the inverse perms for all the other corps so idk what I am doing wrong.

**Comment by warlof** [comment]
https://github.com/eveseat/seat/issues/214
https://github.com/eveseat/seat/issues/146
http://seat-docs.readthedocs.io/en/latest/admin_guides/rbac/

**Comment by paintballlaws** [comment]
So im confused does this mean I have to have each member of that corporation in a role that is affiliated with that specific corporation? Can you provide pictures for on exactly how todo this because the references you used I tried to understand what they are trying todo but dont really know how to apply it.

**Comment by warlof** [comment]
Short answer is yes, up to 3.x

You've a screen exemple for a corp role in the documentation I've linked.
The same pattern is applied for character permissions.

**Comment by paintballlaws** [comment]
So basically every time someone new joins they will have to be manually added to that group for the CEO to be able to view his api? Am I understanding this correct?

**Comment by leonjza** [comment]
Give this a shot with 3.x
