### ISSUE TITLE
Massive pheal log file

### ISSUE THREAD

**Issue by Kryion** [eveseat/seat#219]
I constantly have a massive Pheal.log file (upwards of 700 MB).  Running seat for 3 hours have given 50MB of a log file in Pheal.log (I'm storing 2000+ APIs).  Is there a way to turn off this logging?  It looks like its just logging GET requests which isn't useful for me.

**Comment by warlof** [comment]
Non standard solution, disable the Pheal log : https://github.com/eveseat/eveapi/blob/master/src/Helpers/PhealSetup.php#L68 replace the ```new PsrLogger(
            $this->getPhealLogger());```

by `null;`

**Comment by leonjza** [comment]
You can configure a logrotate setup for the pheal log as well.

**Comment by leonjza** [comment]
Pheal is no longer used since 3.x
