### ISSUE TITLE
Integrity constraint violations character_character_sheet_jump_clones

### ISSUE THREAD

**Issue by IvandaNothabeer** [eveseat/seat#220]
This is a duplicate of issue #194 which was closed without any resolution

Code is apparently trying to 'insert' a new record when it should be updating an existing record to the character_sheet_jump_clones table.

Exception       : Illuminate\Database\QueryException
Error Code      : 23000
Error Message   : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '24453375' for key 'PRIMARY' (SQL: insert into `character_character_sheet_jump_clones` (`characterID`, `jumpCloneID`, `typeID`, `locationID`, `cloneName`, `updated_at`, `created_at`) values (xxxxxxxxxx, 24453375, 164, 60000988, , 2017-10-02 12:46:10, 2017-10-02 12:46:10))
File            : /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 770

I'm seeing this error 8 to 10 times per day with around 3000 keys in the database.

SeAT versions are all up to date at time of posting this bug report

**Comment by sn0opy** [comment]
I may have found a solution. It think this bug occurs on characters with multiple keys being processed at the same time by mutliple workers.

**Comment by IvandaNothabeer** [comment]
Update \\vendor\\eveseat\\eveapi\\src\\Api\\Character\\clones.php as follows ...

`<?php

/*
 * This file is part of SeAT
 *
 * Copyright (C) 2015, 2016, 2017  Leon Jacobs
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

namespace Seat\Eveapi\Api\Character;

use Seat\Eveapi\Api\Base;
use Seat\Eveapi\Models\Character\CharacterSheet as CharacterSheetModel;
use Seat\Eveapi\Models\Character\CharacterSheetImplants;
use Seat\Eveapi\Models\Character\CharacterSheetJumpClone;
use Seat\Eveapi\Models\Character\CharacterSheetJumpCloneImplants;

/**
 * Class Clones.
 * @package Seat\Eveapi\Api\Character
 */
class Clones extends Base
{
    /**
     * Run the Update.
     *
     * @return mixed|void
     */
    public function call()
    {

        // TODO: Check if we have access to char/characterSheet
        // and ship this updater as we already have everything
        $pheal = $this->setScope('char')->getPheal();

        foreach ($this->api_info->characters as $character) {

            $this->writeJobLog('clones',
                'Processing characterID: ' . $character->characterID);

            $result = $pheal->Clones([
                'characterID' => $character->characterID, ]);

            // Get the CharacterSheet Data
            $character_data = CharacterSheetModel::firstOrNew([
                'characterID' => $character->characterID, ]);

            // .. and update it
            $character_data->fill([
                'DoB'               => $result->DoB,
                'race'              => $result->race,
                'bloodLineID'       => $result->bloodLineID,
                'bloodLine'         => $result->bloodLine,
                'ancestryID'        => $result->ancestryID,
                'ancestry'          => $result->ancestry,
                'gender'            => $result->gender,
                'freeRespecs'       => $result->freeRespecs,
                'cloneJumpDate'     => $result->cloneJumpDate,
                'lastRespecDate'    => $result->lastRespecDate,
                'lastTimedRespec'   => $result->lastTimedRespec,
                'remoteStationDate' => $result->remoteStationDate,
                'jumpActivation'    => $result->jumpActivation,
                'jumpFatigue'       => $result->jumpFatigue,
                'jumpLastUpdate'    => $result->jumpLastUpdate,
                'intelligence'      => $result->attributes->intelligence,
                'memory'            => $result->attributes->memory,
                'charisma'          => $result->attributes->charisma,
                'perception'        => $result->attributes->perception,
                'willpower'         => $result->attributes->willpower,
            ]);

            $character_data->save();

            // Next up, Implants. We need to clear up the ones
            // that we already know of as implants can change
            // at any given time.
            CharacterSheetImplants::where(
                'characterID', $character->characterID)->delete();

            // Lets loop over the implants and create them
            foreach ($result->implants as $implant) {

                CharacterSheetImplants::create([
                    'characterID' => $character->characterID,
                    'typeID'      => $implant->typeID,
                    'typeName'    => $implant->typeName,
                ]);

            } // Foreach Implants

            // Next up, Jump Clones. Because we know that Clones can
            // change at any moment, we will have to take the ones
            // we know of and remove them, and then re-add what
            // we got from the API
            CharacterSheetJumpClone::where(
                'characterID', $character->characterID)->delete();
            CharacterSheetJumpCloneImplants::where(
                'characterID', $character->characterID)->delete();
            
            // Lets loop over the clones for the character.
            // Issue 220 - Sometimes we get duplicates from somewhere - so create or update
            foreach ($result->jumpClones as $jump_clone) {

                $jc_data = CharacterSheetJumpClone::firstOrNew([
                    'characterID' => $character->characterID,
                    'jumpCloneID' => $jump_clone->jumpCloneID,
                    ]);
                
                $jc_data->fill([
                    'typeID'      => $jump_clone->typeID,
                    'locationID'  => $jump_clone->locationID,
                    'cloneName'   => $jump_clone->cloneName,
                ]);
                
                $jc_data->save();

            } // Foreach JumpClone

            // Lets loop over the Jump Clone Implants for the character
            // Issue 220 - Sometimes we get duplicates from somewhere - so create or update
            foreach ($result->jumpCloneImplants as $jump_clone_implant) {

                $jci_data = CharacterSheetJumpCloneImplants::firstOrNew([
                    'characterID' => $character->characterID,
                    'jumpCloneID' => $jump_clone_implant->jumpCloneID,
                ]);
                
                $jci_data->fill([
                    'typeID'      => $jump_clone_implant->typeID,
                    'typeName'    => $jump_clone_implant->typeName,
                ]);
                
                $jci_data->save();
                
            } // Foreach JumpCloneImplant

        } // Foreach Character

    }
}
`

**Comment by leonjza** [comment]
Jobs got quite a big kick in the face in 3.x.
