### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by raykai** [eveseat/seat#222]
Running on digitalocean VPS fresh Ubuntu 16.04.3 X64

I get this error to when using the Quick Install method:

![1bug](https://user-images.githubusercontent.com/8138894/31575469-dbd01864-b0b5-11e7-875b-00d8759a88a7.JPG)

how can i fix this?

**Comment by sn0opy** [comment]
Your VPS has not enough memory which is why the system kills the composer update. Either create a Droplet with more RAM or add some swap.

```
# fallocate -l 1G /swapfile
# chmod 600 /swapfile
# mkswap /swapfile
# swapon /swapfile
```

You may have to cleanup a few things (remove /var/www/seat for example), since SeAT aborted mid-installation.
