### ISSUE TITLE
Feature Req:  Personal and Corporate Mining Ledger Support

### ISSUE THREAD

**Issue by warriorsoul15** [eveseat/seat#223]
Please add this as soon as endpoint access is available!

**Comment by warlof** [comment]
hi

endpoint is in staging on ESI, but we had first to release 3.x :)
this feature should not be able in current 2.x since it has been froze for hotfix only since almost 1 month now.

Wait a bit :p

**Comment by warriorsoul15** [comment]
Is 3  released?

**Comment by rohimma** [comment]
no, but they are working on it (also no estimate release date)

**Comment by Flugschreipbaer** [comment]
Is there any news on when 3 is coming?

**Comment by rohimma** [comment]
no

**Comment by leonjza** [comment]
V3 will take a while. A beta might become available at some stage (noone knows when ;p). An important part of the v3 process is feature parity with the XML API. So even from a CCP perspective, this will take time.

**Comment by Flugschreipbaer** [comment]
Tell me if you need some Beta testing. With the massive DB from us, I could do that.

**Comment by leonjza** [comment]
3.x beta is out with this in.
