### ISSUE TITLE
compiled docker image?

### ISSUE THREAD

**Issue by raykai** [eveseat/seat#224]
Would be nice to have this in a compiled docker image ready to go for less tech-savvy users. It would be a lot simpler for people to use. Even more, seeing as Plesk web panel now supports dockers images out of the box and i think to cpanel too.

Plus digital ocean now supports docker image out of the box. Wich many corp already use digital ocean to host their eve corp websites.

i for one would use it.

Anyhow keep up the good work!

**Comment by sn0opy** [comment]
I know it's an alternative, but have you seen the quick install guide? You basically have to do only a few clicks to get everything up and running.

http://seat-docs.readthedocs.io/en/latest/installation_guides/quick_install/

**Comment by warlof** [comment]
I also add that there will never have support for plesk, cpanel and such click and magical do platform.

Such system are largely altered and don't meet any conventional things. Even them at their support are lost when something need to be altered into their config files.

Providing a docker image is a possibility though. There is already a docker script in repos.

**Comment by raykai** [comment]
@warlof thats what im saying compiled docker image, with that even ppl with plesk or cpanel even ppl on windows can use it without a prob.

i did see that there is a docker script in repos. But i have new clue how to use it. That's why having it already compiled as an image and ready to download and use would be nice.

**Comment by raykai** [comment]
@sn0opy 
> I know it's an alternative, but have you seen the quick install guide? You basically have to do only a few 
> clicksto get everything up and running.
> http://seat-docs.readthedocs.io/en/latest/installation_guides/quick_install/

ya i did try this on a fresh ubuntu 16.4 docker image but it gave an error about mysql not having a script for rebooting if i remember well. this script works well on a full ubuntu server 16.4 normal install tho (not docker )

**Comment by raykai** [comment]
i did try running the scripts/docker-compose/ code from here [https://github.com/eveseat/scripts/tree/master/docker-compose](https://github.com/eveseat/scripts/tree/master/docker-compose) but getting an error:

```
 git clone git@github.com:eveseat/scripts.git
Cloning into 'scripts'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Please make sure you have the correct access rights
and the repository exists.

**Comment by warlof** [comment]
Be sure you're allowed to write into the target directory. 

I think it's causing by a missing ssh key into your config.

You can do this instead `https://github.com/eveseat/scripts.git`

**Comment by raykai** [comment]
Anyhow, il hope there will be a compiled docker image. It would be much easier for ppl to use that are not to teck savy.

**Comment by leonjza** [comment]
Since 3x-beta we have native docker support: https://eveseat.github.io/docs/guides/installation/basic_installation/installation/
