### ISSUE TITLE
SSO LOGIN BUG

### ISSUE THREAD

**Issue by frank1210** [eveseat/seat#225]
* **Problem**: Trying to login by SSO after authorizing on CCP's site i get a Whoops, looks like something went wrong.
* **Expected**: Log into seat with the SSO information
* **Logs / Screenshots / Proof**: https://pastebin.com/w1KQAUwE LOGS
* **Version Info**: php 7.0, seat 2.0, Ubuntu 16. Recently installed with the seat Tool

**Comment by warlof** [comment]
Can you also provide the callback uri you've setup in eve development portal?

**Comment by frank1210** [comment]
before: www.fwscuad.com
Callback URL: http://fwscuad.com/auth/eve/callback

**Comment by warlof** [comment]
Both domain must be equal 
In your case, your public URL is www.fwscuad.com

Whereas you setup fwscuad.com in the callback 

Cross-origin is not allowed, just choose one of them.
