### ISSUE TITLE
Duplicated items in character_asset_list_contents

### ISSUE THREAD

**Issue by IvandaNothabeer** [eveseat/seat#226]
It is possible to get duplicated records for the same item in character_asset_list_contents.

No error is detected because the character_asset_list_contents table has no unique primary key. However, itemID is supposed to be unique.

Root cause is probably the same as issue #220  ( Duplicated jump clones)

This isn't just theoretical ....  it does and has happened.

**Comment by warlof** [comment]
`character_asset_lists`, `character_asset_list_contents`, `corporation_asset_list_contents`, `corporation_asset_lists` must have primary keys.

**Comment by IvandaNothabeer** [comment]
I agree they ** should **. But they dont ....

![image](https://user-images.githubusercontent.com/1829066/32413465-b74e4f2e-c276-11e7-9a4e-54d582b47e87.png)

**Comment by warlof** [comment]
I know, that's why I tell it.

After this change in table, duplicate insert will throw exception which could be fix using insert/update method.

Sn0opy is working on it today.

**Comment by IvandaNothabeer** [comment]
ty :)

**Comment by IvandaNothabeer** [comment]
@snoopy ... How does this fix resolve the exception thrown when inserting a duplicate record ?

**Comment by sn0opy** [comment]
@IvandaNothabeer I was thinking about adding it to the migration script. Unfortunately, I haven't added it yet. There might be better ways, but I just deleted them by using something like 

```sql
SELECT itemID, COUNT(*) as cnt
FROM character_asset_lists
GROUP BY itemID
ORDER BY cnt DESC
LIMIT 50
```
and basically removed the 2-3 entries having more than one result. There are definetely better and more automated options I guess.

**Comment by IvandaNothabeer** [comment]
But new duplicates happen every time you run an update. This is a very common issue, not an edge case.

There's something fundamentally not right here. Duplicated itemID's shouldn't ever happen unless (a) CCP have completely screwed the API or (b) the same asset is being processed simultaneously by more than one job. That's wasteful and inefficient and leads to conflicts like this 

I'm assuming from feedback into the jump clones issue that (b) is the root cause. And the solution should really be to stop the root cause - not patch up code that allows it to happen.

In any case, IMO there's no simple solution here because the assets are updated in batches of 1000 with an "insert" statement. The workaround would be to revert to a series of 1000 createOrUpdate

**Comment by sn0opy** [comment]
@IvandaNothabeer there's a simple answer: stop inserting multiple keys for the same character. This only happens if you have more than one key for a character. Since both keys MAY be processed by two different workers simultaneously, they MAY cause this error to happen.

**Comment by MilosRasic** [comment]
@sn0opy Managing a corp or an alliance isn't the only thing seat is useful for, so people may want multiple keys for same account in it.

**Comment by sn0opy** [comment]
@MilosRasic I was just answering @IvandaNothabeer's question. There's no bug or anything similar. If you have multiple keys for the same character, you're going to process data more than once everytime. My fix just makes sure there's no unnecessary duplicate data in the database.

**Comment by MilosRasic** [comment]
@sn0opy I'm just explaining why someone may want multiple keys for the same character :)

**Comment by IvandaNothabeer** [comment]
Sorry @snoopy, bu no, the fix doesn't do this. Your fix prevents duplicate data, but it doesnt prevent the processing ques from throwing an error and hanging.

**Comment by sn0opy** [comment]
@IvandaNothabeer restart the workers to make sure they use the updated code.

**Comment by IvandaNothabeer** [comment]
Then somebody needs to pay attention to #227 because right now your updates aren't getting distributed ;)

You cant stop users adding multiple keys for the same account. This isn't under the administrators control.

**Comment by IvandaNothabeer** [comment]
I haven't tried it but it looks like it might work ....

https://packagist.org/packages/yadakhov/insert-on-duplicate-key

**Comment by warlof** [comment]
Insertorupdate method will did the tricks. 

First was lacks of Pk which avoid to use such things. Second fix is related to method change.

Normally that should be good as soon as all files will be released.

**Comment by IvandaNothabeer** [comment]
laravel's "insertOrUpdate" method only works on single models. The insert method works on bulk updates of 1000 assets with a single transaction.

There's a substantial performance difference between the two methods. If you simply replace the insert with 1000 insertOrUpdate you'll have 1000 transactions instead of one.

The linked package makes use of mySQL's inbuilt bulk insertion to handle duplicate key issues properly with a single transaction, and hence, without the performance hit.

**Comment by sn0opy** [comment]
@IvandaNothabeer feel free to create a PR then. For me, my fix works kinda well even without any _substantial_ performance issues.

**Comment by leonjza** [comment]
V3 jobs system got a major upgrade, lets see how it goes.
