### ISSUE TITLE
Updates not being merged to 2.x release

### ISSUE THREAD

**Issue by IvandaNothabeer** [eveseat/seat#227]
See #221 

Updates are being merged in the Master release. However, as per #221, your current "Master" is a development branch and is not for production release. Updates are NOT being merged into the 2.x branch - which is your current Production install.

For example, the Jump Clone bug fix ( #220 ) is missing from your 2.14 production release and consequently does not get installed by the seat:update tool

**Comment by leonjza** [comment]
The 2x branching was a confusing time as panic was sown to start work on 3x. Well, we are now here with a beta released.
