### ISSUE TITLE
Api PI Error

### ISSUE THREAD

**Issue by JackONeill12** [eveseat/seat#23]
While updating the Api Keys Seat stuck at a some of them with the following exeption:

```
Last Updater: Processing: PlanetaryColonies

Exception: Illuminate\Database\QueryException
Error Code: 42S22
Error Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `character_planetary_colonies` set `lastUpdate` = 2015-12-19 19:11:22, `updated_at` = 2015-12-24 14:10:54 where `id` is null)
File: /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php - Line: 651

Traceback: #0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('update `charact...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->run('update `charact...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(359): Illuminate\Database\Connection->affectingStatement('update `charact...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1816): Illuminate\Database\Connection->update('update `charact...', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(316): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1588): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1507): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 /var/www/seat/vendor/eveseat/eveapi/src/Api/Character/PlanetaryColonies.php(72): Illuminate\Database\Eloquent\Model->save()
#8 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(99): Seat\Eveapi\Api\Character\PlanetaryColonies->call()
#9 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(193): Illuminate\Container\Container->call(Array)
#12 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(205): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\RedisJob->fire()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '10', '0')
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop('', 'high,medium,low...', '0', '3', '10')
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker('', 'high,medium,low...', '0', '128', false)
#24 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#27 /var/www/seat/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/seat/vendor/symfony/console/Application.php(838): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/seat/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/seat/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 {main}
```

**Comment by leonjza** [comment]
Please run the following SQL query and paste the output:

```
describe `character_planetary_colonies`;
```

**Comment by JackONeill12** [comment]
How do i run this query?

**Comment by warlof** [comment]
just by running it in phpmyadmin or something else.

You can use ssh console aswell :
`mysql -u user -p`
`use seatdb`
`describe character_planetary_colonies`

**Comment by JackONeill12** [comment]
mysql> describe character_planetary_colonies;
+-----------------+--------------+------+-----+---------------------+-------+
| Field           | Type         | Null | Key | Default             | Extra |
+-----------------+--------------+------+-----+---------------------+-------+
| solarSystemID   | int(11)      | NO   | MUL | NULL                |       |
| solarSystemName | varchar(255) | NO   |     | NULL                |       |
| planetID        | int(11)      | NO   | MUL | NULL                |       |
| planetName      | varchar(255) | NO   |     | NULL                |       |
| planetTypeID    | int(11)      | NO   |     | NULL                |       |
| planetTypeName  | varchar(255) | NO   |     | NULL                |       |
| ownerID         | int(11)      | NO   | MUL | NULL                |       |
| ownerName       | varchar(255) | NO   |     | NULL                |       |
| lastUpdate      | datetime     | NO   |     | NULL                |       |
| upgradeLevel    | int(11)      | NO   |     | NULL                |       |
| numberOfPins    | int(11)      | NO   |     | NULL                |       |
| created_at      | timestamp    | NO   |     | 0000-00-00 00:00:00 |       |
| updated_at      | timestamp    | NO   |     | 0000-00-00 00:00:00 |       |
+-----------------+--------------+------+-----+---------------------+-------+
13 rows in set (0.00 sec)

**Comment by warlof** [comment]
It seems you're running recent package on an outdated database. Did you run the `php artisan migrate` after updating package ?

**Comment by JackONeill12** [comment]
I used the Upgrade script. So yes and it shows "nothing to migrate"

**Comment by warlof** [comment]
can you run it again and tell us if `describe character_planetary_colonies` result contain an id fiel ?
aswell, can you run `select * from migrations` too ?

**Comment by JackONeill12** [comment]
Rerun upgrade script. Still shows Nothing to migrate.

describe character_planetary_colonies

+-----------------+--------------+------+-----+---------------------+-------+
| Field           | Type         | Null | Key | Default             | Extra |
+-----------------+--------------+------+-----+---------------------+-------+
| solarSystemID   | int(11)      | NO   | MUL | NULL                |       |
| solarSystemName | varchar(255) | NO   |     | NULL                |       |
| planetID        | int(11)      | NO   | MUL | NULL                |       |
| planetName      | varchar(255) | NO   |     | NULL                |       |
| planetTypeID    | int(11)      | NO   |     | NULL                |       |
| planetTypeName  | varchar(255) | NO   |     | NULL                |       |
| ownerID         | int(11)      | NO   | MUL | NULL                |       |
| ownerName       | varchar(255) | NO   |     | NULL                |       |
| lastUpdate      | datetime     | NO   |     | NULL                |       |
| upgradeLevel    | int(11)      | NO   |     | NULL                |       |
| numberOfPins    | int(11)      | NO   |     | NULL                |       |
| created_at      | timestamp    | NO   |     | 0000-00-00 00:00:00 |       |
| updated_at      | timestamp    | NO   |     | 0000-00-00 00:00:00 |       |
+-----------------+--------------+------+-----+---------------------+-------+
13 rows in set (0.00 sec)


select * from migrations

| migration                                                                    | batch |
+------------------------------------------------------------------------------+-------+
| 2014_10_12_000000_create_users_table                                         |     1 |
| 2014_10_12_100000_create_password_resets_table                               |     1 |
| 2015_08_28_203349_create_jobs_table                                          |     1 |
| 2015_08_29_070847_create_failed_jobs_table                                   |     1 |
| 2015_08_29_080855_create_server_server_statuses_table                        |     1 |
| 2015_08_29_093035_create_job_trackings_table                                 |     1 |
| 2015_08_29_170127_create_eve_ref_types_table                                 |     1 |
| 2015_08_29_190007_create_eve_error_lists_table                               |     1 |
| 2015_08_29_203744_create_eve_conquerable_station_lists_table                 |     1 |
| 2015_08_30_091747_create_eve_alliance_lists_table                            |     1 |
| 2015_08_30_091757_create_eve_alliance_list_member_corporations_table         |     1 |
| 2015_08_30_131400_create_map_sovereignties_table                             |     1 |
| 2015_08_30_151002_create_map_kills_table                                     |     1 |
| 2015_08_30_152811_create_map_jumps_table                                     |     1 |
| 2015_09_03_061804_create_eve_api_call_lists_table                            |     1 |
| 2015_09_04_120853_create_eve_api_keys_table                                  |     1 |
| 2015_09_04_191707_create_account_api_key_infos_table                         |     1 |
| 2015_09_04_193632_create_account_api_key_info_characters_table               |     1 |
| 2015_09_05_064929_create_account_account_statuses_table                      |     1 |
| 2015_09_05_074832_create_character_account_balances_table                    |     1 |
| 2015_09_05_111043_create_character_asset_lists_table                         |     1 |
| 2015_09_05_111048_create_character_asset_list_contents_table                 |     1 |
| 2015_09_06_153552_create_character_character_sheets_table                    |     1 |
| 2015_09_06_193835_create_character_character_sheet_jump_clones_table         |     1 |
| 2015_09_06_193840_create_character_character_sheet_jump_clone_implants_table |     1 |
| 2015_09_06_201549_create_character_character_sheet_implants_table            |     1 |
| 2015_09_06_202557_create_character_character_sheet_skills_table              |     1 |
| 2015_09_06_203850_create_character_character_sheet_corporation_titles_table  |     1 |
| 2015_09_07_072617_create_character_contact_lists_table                       |     1 |
| 2015_09_07_072635_create_character_contact_list_labels_table                 |     1 |
| 2015_09_07_072648_create_character_contact_list_corporates_table             |     1 |
| 2015_09_07_072657_create_character_contact_list_corporate_labels_table       |     1 |
| 2015_09_07_072704_create_character_contact_list_alliances_table              |     1 |
| 2015_09_07_072708_create_character_contact_list_alliance_labels_table        |     1 |
| 2015_09_07_102154_create_character_contact_notifications_table               |     1 |
| 2015_09_07_115102_create_character_contracts_table                           |     1 |
| 2015_09_07_122844_create_character_contract_items_table                      |     1 |
| 2015_09_09_134822_create_character_industry_jobs_table                       |     1 |
| 2015_09_11_094433_create_eve_character_infos_table                           |     1 |
| 2015_09_11_114448_create_eve_character_info_employment_histories_table       |     1 |
| 2015_09_11_145629_create_character_kill_mails_table                          |     1 |
| 2015_09_12_054148_create_character_mail_messages_table                       |     1 |
| 2015_09_12_060908_create_character_mail_message_bodies_table                 |     1 |
| 2015_09_12_065749_create_character_mailing_lists_table                       |     1 |
| 2015_09_12_071856_create_character_mailing_list_infos_table                  |     1 |
| 2015_09_12_093642_create_character_notifications_table                       |     1 |
| 2015_09_12_094545_create_character_notifications_texts_table                 |     1 |
| 2015_09_13_132001_create_character_planetary_colonies_table                  |     1 |
| 2015_09_13_191626_create_character_planetary_pins_table                      |     1 |
| 2015_09_13_194723_create_character_planetary_routes_table                    |     1 |
| 2015_09_13_201227_create_character_planetary_links_table                     |     1 |
| 2015_09_14_044841_create_character_market_orders_table                       |     1 |
| 2015_09_14_053206_create_character_researches_table                          |     1 |
| 2015_09_14_055236_create_character_skill_in_trainings_table                  |     1 |
| 2015_09_14_064332_create_character_skill_queues_table                        |     1 |
| 2015_09_14_084042_create_character_standings_table                           |     1 |
| 2015_09_14_091742_create_character_upcoming_calendar_events_table            |     1 |
| 2015_09_14_101601_create_character_wallet_journals_table                     |     1 |
| 2015_09_14_121453_create_character_wallet_transactions_table                 |     1 |
| 2015_09_14_165825_create_character_chat_channels_table                       |     1 |
| 2015_09_14_180357_create_character_chat_channel_infos_table                  |     1 |
| 2015_09_14_181449_create_character_chat_channel_members_table                |     1 |
| 2015_09_15_053517_create_character_bookmarks_table                           |     1 |
| 2015_09_18_160323_create_corporation_account_balances_table                  |     1 |
| 2015_09_19_065332_create_corporation_asset_lists_table                       |     1 |
| 2015_09_19_065341_create_corporation_asset_list_contents_table               |     1 |
| 2015_09_19_090641_create_corporation_locations_table                         |     1 |
| 2015_09_20_085119_create_corporation_contact_lists_table                     |     1 |
| 2015_09_20_090028_create_corporation_contact_list_labels_table               |     1 |
| 2015_09_20_131759_create_corporation_contact_list_alliances_table            |     1 |
| 2015_09_20_131807_create_corporation_contact_list_alliance_labels_table      |     1 |
| 2015_09_20_140139_create_corporation_contracts_table                         |     1 |
| 2015_09_20_142419_create_corporation_contract_items_table                    |     1 |
| 2015_09_20_182953_create_corporation_sheets_table                            |     1 |
| 2015_09_20_183110_create_corporation_sheet_divisions_table                   |     1 |
| 2015_09_20_183114_create_corporation_sheet_wallet_divisions_table            |     1 |
| 2015_09_21_043404_create_corporation_customs_offices_table                   |     1 |
| 2015_09_21_044511_create_corporation_customs_office_locations_table          |     1 |
| 2015_09_21_052037_create_corporation_industry_jobs_table                     |     1 |
| 2015_09_21_083629_create_corporation_kill_mails_table                        |     1 |
| 2015_09_21_091720_create_corporation_market_orders_table                     |     1 |
| 2015_09_21_093841_create_corporation_medals_table                            |     1 |
| 2015_09_21_100128_create_corporation_member_medals_table                     |     1 |
| 2015_09_21_121251_create_corporation_member_securities_table                 |     1 |
| 2015_09_21_150811_create_corporation_member_security_titles_table            |     1 |
| 2015_09_21_155901_create_corporation_member_trackings_table                  |     1 |
| 2015_09_21_164649_create_corporation_member_security_logs_table              |     1 |
| 2015_09_21_180635_create_corporation_shareholders_table                      |     1 |
| 2015_09_22_044313_create_corporation_standings_table                         |     1 |
| 2015_09_22_051121_create_corporation_starbases_table                         |     1 |
| 2015_09_22_052842_create_corporation_starbase_details_table                  |     1 |
| 2015_09_22_062834_create_corporation_titles_table                            |     1 |
| 2015_09_22_145146_create_corporation_wallet_journals_table                   |     1 |
| 2015_09_22_160837_create_corporation_wallet_transactions_table               |     1 |
| 2015_09_23_183112_create_kill_mail_attackers_table                           |     1 |
| 2015_09_23_183122_create_kill_mail_details_table                             |     1 |
| 2015_09_23_183133_create_kill_mail_items_table                               |     1 |
| 2015_09_28_171451_create_roles_table                                         |     1 |
| 2015_09_28_171456_create_permissions_table                                   |     1 |
| 2015_09_28_180546_create_affiliations_table                                  |     1 |
| 2015_09_28_182002_create_permission_roles_table                              |     1 |
| 2015_09_28_182015_create_role_users_table                                    |     1 |
| 2015_09_28_182023_create_affiliation_users_table                             |     1 |
| 2015_09_28_182123_create_affiliation_roles_table                             |     1 |
| 2015_09_29_110435_create_user_login_histories_table                          |     1 |
| 2015_09_29_110524_create_security_logs_table                                 |     1 |
| 2015_10_30_140512_create_eve_notification_types_table                        |     1 |
| 2015_11_28_053529_create_user_settings_table                                 |     1 |
| 2015_11_28_071315_create_global_settings_table                               |     1 |
| 2015_11_30_153611_create_api_tokens_table                                    |     1 |
| 2015_11_30_153848_create_api_token_logs_table                                |     1 |
| 2015_12_01_201414_create_schedules_table                                     |     1 |
| 2015_12_02_153458_create_notifications_table                                 |     1 |
| 2015_12_18_204239_add_character_bookmark_map_info                            |     2 |
| 2015_12_20_130542_create_corporation_bookmarks_table                         |     2 |
+------------------------------------------------------------------------------+-------+
115 rows in set (0.00 sec)

**Comment by warlof** [comment]
I've reached my limit with my current known of the new seat. It strange that you don't have an id fiel in this table since it is present in 2015_09_13_132001_create_character_planetary_colonies_table migration and it's flag as passed.

The quick fix is to add an `id` field to this table with a type `int(10) unsigned` and `primary key`.
But it doesn't explain why you don't have it or why it's not created even with migrate command.

**Comment by leonjza** [comment]
Did you install this before the official release? There was a primary key added after the migration was created, so if you installed this before official release you may have missed it. Its ok, you can add it with the following query:

```sql
ALTER TABLE `character_planetary_colonies` ADD `id` INT  UNSIGNED  NOT NULL  AUTO_INCREMENT  PRIMARY KEY  AFTER `solarSystemID`;
```

**Comment by JackONeill12** [comment]
Yes i installed Seat before the official release.

And thanks its now working.
