### ISSUE TITLE
BadMethodCallException when running seat install:development

### ISSUE THREAD

**Issue by ddavaham** [eveseat/seat#231]
* **Problem**: _Whats wrong?_

seat development install fails.

* **Expected**: _What did you expect to happen?_

Successful installation of seat:development

* **Logs / Screenshots / Proof**: _The more information you give the better!_

```
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize


  [BadMethodCallException]
  Method aliasMiddleware does not exist.


Script php artisan optimize handling the post-update-cmd event returned with error code 1


  [Seat\Installer\Exceptions\ComposerInstallException]
  Composer installation failed.
```

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
root@local:/var/www# php -v
```
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

```

```
root@local:/var/www# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

```

**Comment by leonjza** [comment]
Sorry, I am currently in a major migration to use ESI and have not yet had a chance to test the dev installer for this yet. If you want to try out the latest code you could do a manual installation from the `master` branch now. [This gist](https://gist.github.com/leonjza/35b6319afab32523e56b51ef2b45d70b) should get you going. If you have trouble with it, join us on Slack!
