### ISSUE TITLE
Rework ACL to group management

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#234]
# Rework ACL to group management

SeAT lacks currently one very important functionality: groups. Groups to which Users are automatically assigned, groups they can opt-in and groups that can be managed by managers. 
With these groups it is actually possible to be independent of Alliance Auth and manage services from Integrations such as fitting or slackbot from @warlof

## Business Requirements

	1. As an user with no special rights (no superuser, no manager) i should be able to join, apply for and leave groups so that i receive whatever permission this group contains.
	2. As an alliance/corporation, i must assign users automatically to groups as long as they are in a set corp/alliance so that my members receives services/permissions as long as they are members.
	3. As a group manager, i want to be able to invite/remove manually users from managed groups so that i can controll who receives permission of this managed group
	4. As a group manager i must to be able to accept/reject applications to managed groups so that i control who receives permissions of this managed group
	5. As a group manager i must to be able to set the requirements for users to be able to join/apply a group based upon their membership, so that no not-qualified user can see, join, apply, leave etc. any group

---

## Open Questions

[] should group manager be able to assign User or character?

---

## ToDo

[] AC for GroupAdminDetail
[] AC for Available Groups

---

### Group Admin Overview
![image](https://user-images.githubusercontent.com/6583519/35236646-4f8dd840-ffa8-11e7-9d1b-279d65c66f01.png)

*GIVEN* a user which is Group Manager in a group, opens Group Management Overview
*WHEN* he looks at the available groups table
*THEN* he only sees the groups he is manager for

*GIVEN* a user which is admin/superuser opens the Group Manager Overview
*WHEN* he looks at the available groups table
*THEN* he see all groups.

*GIVEN* a user which is Group Manager in a group *OR* is admin/superuser, opens Group Management Overview
*WHEN* he looks at the available groups table
*THEN* he sees the type of group {auto-group,open,hidden,managed}

*GIVEN* a user which is Group Manager in a group *OR* is admin/superuser, opens Group Management Overview
*WHEN* whe selects "Details"
*THEN* Group Admin Details open

### Group Admin Overview
![image](https://user-images.githubusercontent.com/6583519/35236653-5638ad64-ffa8-11e7-90b8-d1f0460347be.png)

### Group Overview
![image](https://user-images.githubusercontent.com/6583519/35236658-5a3b0d08-ffa8-11e7-91a2-0678af973523.png)

**Comment by leonjza** [comment]
Yes, there is definitely a need to "un-crap "the way it is now. I really hope to have this better in v3. If not in 3.0, at least 3.1.

**Comment by herpaderpaldent** [comment]
Having https://github.com/herpaderpaldent/seat-groups developed, i close this issue since all the acceptance criterias has been met.
