### ISSUE TITLE
Queue job error for API processing

### ISSUE THREAD

**Issue by radumalica** [eveseat/seat#236]
When some of the corp users are adding the API keys, (not full APIs) , i get this error in the queue job:

Last Updater: Processing: Clones

Exception       : Illuminate\Database\QueryException
Error Code      : HY000
Error Message   : SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `character_character_sheets` (`characterID`, `DoB`, `race`, `bloodLineID`, `bloodLine`, `ancestryID`, `ancestry`, `gender`, `freeRespecs`, `cloneJumpDate`, `lastRespecDate`, `lastTimedRespec`, `remoteStationDate`, `jumpActivation`, `jumpFatigue`, `jumpLastUpdate`, `intelligence`, `memory`, `charisma`, `perception`, `willpower`, `updated_at`, `created_at`) values (2112842509, 2017-05-27 12:10:04, Gallente, 7, Gallente, 14, Miners, Male, 2, 2018-02-19 17:35:11, 2017-06-27 13:36:30, 2017-06-27 13:36:30, 0001-01-01 00:00:00, 2018-02-17 19:04:05, 2018-02-17 19:45:40, 2018-02-17 18:59:28, 21, 21, 18, 20, 19, 2018-02-21 12:47:40, 2018-02-21 12:47:40))
File            : /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line            : 770

Traceback: 
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `ch...', Array, Object(Closure))
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `ch...', Array, Object(Closure))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `ch...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ch...', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ch...', Array, 'characterID')
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->insertGetId(Array, 'characterID')
#6 /var/www/seat/bootstrap/cache/compiled.php(11001): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /var/www/seat/bootstrap/cache/compiled.php(10987): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /var/www/seat/bootstrap/cache/compiled.php(10941): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /var/www/seat/vendor/eveseat/eveapi/src/Api/Character/Clones.php(85): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/UpdateAuthenticated.php(78): Seat\Eveapi\Api\Character\Clones->call()
#11 [internal function]: Seat\Eveapi\Jobs\UpdateAuthenticated->handle()
#12 /var/www/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#13 /var/www/seat/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#14 /var/www/seat/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#15 /var/www/seat/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Seat\Eveapi\Jobs\UpdateAuthenticated))
#16 /var/www/seat/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(Seat\Eveapi\Jobs\UpdateAuthenticated), false)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(153): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
#24 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#25 /var/www/seat/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#27 /var/www/seat/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/seat/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/seat/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/seat/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 {main}

**Comment by warlof** [comment]
Hey,

Can you provide the key related mask?
Attached character must be 2112842509

**Comment by radumalica** [comment]
Fixed, the users submitting API key with lower mask than minimum required.
