### ISSUE TITLE
POS Tracker, No Modules

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#24]
None of our pos modules show up, says "No known assets". Everything else seems to work fine

**Comment by leonjza** [comment]
How long after the upgrade did you log this ticket?
There was a bug in the way the eveapi package was determining asset locations. This will solve itself wit the next update of the corp assets once the cache timer expires (around 6-8 hours).

**Comment by shibdib** [comment]
Probably the issue than, this was right after the update.

**Comment by leonjza** [comment]
Let us know if its still broken after the next asset update.
