### ISSUE TITLE
Testing seat 3.0 - Corporation/contact

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#240]
* **Problem**: 

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'Seat\Eveapi\Models\Corporation\ContactList' not found"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in /var/www/seat/packages/eveseat/services/src/Repositories/Corporation/Contacts.php:45
```

* **Expected**: 
* **Logs / Screenshots / Proof**:  /corporation/view/contacts/
![image](https://user-images.githubusercontent.com/6583519/38111797-541c7304-33a0-11e8-8e3b-b376af6dbaa0.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by warlof** [comment]
unfortunately, we're relying to that issue https://github.com/ccpgames/esi-issues/issues/779 which is still pending :(

contacts has not been updated on corporation yet due to it.

**Comment by warlof** [comment]
have to be close ♥
