### ISSUE TITLE
Testing Seat 3.0 - Assets Locations in WH Space are overwritten

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#241]
* **Problem**:  First time you have ESI:Character pull the locations of your assets the location is been named correctly. J-Sig + Citadel name. As soon as another Update ESI:Character or ESI:Corporation runs the Location gets overwritten with _UNKNON_
* **Expected**:  Have J-SIG + Citadel Name as it is after inital update:
* **Logs / Screenshots / Proof**: 

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by herpaderpaldent** [comment]
Just confirmed this is still a thing, for corporation asset locations as well as for character asset

![image](https://user-images.githubusercontent.com/6583519/38472144-9e2a8854-3b7b-11e8-844b-8d317f1ca3d8.png)

**Comment by herpaderpaldent** [comment]
Maybe this has something to do with it: https://github.com/eveseat/eveapi/blob/master/src/Jobs/Universe/Structures.php#L95 

Could this be the issue: overwriting the property for a character that has no docking access (and  therefore does not know the name)?

**Comment by warlof** [comment]
Normally; that should only create structure with unknown flag; never update.
I'll send a fix.

In order to be sure it is related; can you tell me if you loose access to the renamed structure ?

**Comment by herpaderpaldent** [comment]
Char A may have no access to strucutre -> no name
Char B has access to structure -> see name
Char C had previously access to structure ->

- Case 1 (K-Space): assets move in asset safty
- Case 2 (WH-Space): assets still in hangar of that citadel (no asset safty), in Game Assets show name of strucutre.

----------------
I hope i answered your question, cause the screenshots taken are from citadels i have ledgit access. I believe error occurs when Char A Data is imported after Char B

**Comment by herpaderpaldent** [comment]
I got some answers of my tester: He provided me with screenshots showing SeAT Value vs. Ingame.
![image](https://user-images.githubusercontent.com/6583519/38620982-262e5822-3da0-11e8-84ef-a4bc5c5ddb52.png)

some locations he can not pinpoint but the ones he was able to were all outposts. Maybe this helps. I will submit the other pictures later.
