### ISSUE TITLE
Testing SeAT 3.0 - No PI Data present

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#246]
* **Problem**: No PI Data present in DB or 
* **Expected**: See Extractors etc.
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/38167066-7a05ba18-352f-11e8-8d1b-a4f85012efb3.png)

![image](https://user-images.githubusercontent.com/6583519/38167073-8bc13638-352f-11e8-8377-e65d16e9b3b9.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by warlof** [comment]
you need to turn on `esi-planets.manage_planets.v1` scope into settings > single sign on; which is disabled by default.

@leonjza wonder why ?

**Comment by herpaderpaldent** [comment]
it's not in the choosable scopes?

**Comment by leonjza** [comment]
> @leonjza wonder why ?

Probably finger trouble when I disabled the writable scopes.

**Comment by warlof** [comment]
https://github.com/eveseat/eveapi/blob/master/src/Config/eveapi.scopes.php#L85?
