### ISSUE TITLE
Testin SeAT 3.0 - Create Admin Login URL broken

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#248]
* **Problem**:  Can not create Admin URL Login 
* **Expected**: Return Admin URL to login
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/38170384-a8c5427e-3584-11e8-9ca9-828be2775399.png)

* **Version Info**: docker-composer-dev: git commit 90bb6d505e4e13b2c88be3b0b7fd7a98e2b4c246

**Comment by leonjza** [comment]
I can not reproduce this. Sure you have the latest code and have run `dump-autoload`?

**Comment by leonjza** [comment]
Reproducible in a fresh install.
