### ISSUE TITLE
Testin SeAT 3.0 - No CorpName Resolution without Corp-Scopes

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#249]
* **Problem**: This Test Setting is a simple LineMember and Corp-Enpoints should return nothing since it has no corp-scopes. The issue is that the CorpIDs are not getting resolved
* **Expected**: i'd expect corp Names instead of the Corp IDs
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/38170810-47a0c3e2-358e-11e8-8b2d-44a59f1f4a27.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by herpaderpaldent** [comment]
![image](https://user-images.githubusercontent.com/6583519/38170850-e223b780-358e-11e8-91f3-53921a26160c.png)

same goes to CharacterIDs

**Comment by leonjza** [comment]
Please pop open your browsers inspector -> network tab -> check the response for the "resolve" endpoint.

**Comment by herpaderpaldent** [comment]
```
Request URL: http://test.irs-eve.online:8080/support/names/resolve
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 167.99.34.173:8080
Referrer Policy: no-referrer-when-downgrade
```

**Comment by herpaderpaldent** [comment]
Looks like a method is missing or typo? (Log is empty btw)

![image](https://user-images.githubusercontent.com/6583519/38171236-ef1db3e4-3595-11e8-9250-df8ec211d7a5.png)


Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException thrown with message ""

Stacktrace:
#26 Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:255
#25 Illuminate\Routing\RouteCollection:methodNotAllowed in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:242
#24 Illuminate\Routing\RouteCollection:getRouteForMethods in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:176
#23 Illuminate\Routing\RouteCollection:match in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
#22 Illuminate\Routing\Router:findRoute in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
#21 Illuminate\Routing\Router:dispatchToRoute in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
#20 Illuminate\Routing\Router:dispatch in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php:56
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/seat/public/index.php:54

**Comment by leonjza** [comment]
I can not reproduce this this. Name resolution is not affected by any form of permission either.

**Comment by herpaderpaldent** [comment]
this is done on the Dev-Docker runnin latest

**Comment by herpaderpaldent** [comment]
updated all packages and restarted docker. Error persists.

Docker running on Ubuntu 16.04

**Comment by herpaderpaldent** [comment]
Error still persist
![image](https://user-images.githubusercontent.com/6583519/38195324-499acba8-367d-11e8-8df9-fa11a28d8b0f.png)

Running latest docker-dev setup.

**Comment by leonjza** [comment]
I need help to debug this case. I have two docker instances running now that do not have this problem.

**Comment by warlof** [comment]
could be related to a non live ID
that's why I've surrounded the thing by try/catch by past

**Comment by herpaderpaldent** [comment]
Anything you need. Running it on ubuntu 16.04

This is all i got in Laravel: 
```
[2018-04-02 12:01:13] local.ERROR: The stream or file "/var/www/seat/storage/logs/eseye.log" could not be opened: failed to open stream: Permission denied {"userId":2112572972,"exception":"[object] (UnexpectedValueException(code: 0): The stream or file \"/var/www/seat/storage/logs/eseye.log\" could not be opened: failed to open stream: Permission denied at /var/www/seat/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107)
```

@warlof : Dunno but Corp is ShekelSquad and Alliance IRS. so both live?

**Comment by leonjza** [comment]
Fix the permissions and it should work then?

**Comment by herpaderpaldent** [comment]
i haven't touched the docker-compose yet (except .env for EVE_Client & EVE_CLIENT_SECRET) so this indicates me to smth missing in the docker-compose?

Who would need permission?

**Comment by leonjza** [comment]
Solved as permissions issue where Eseye couldn't write to the logfile.
