### ISSUE TITLE
Testing SeAT 3.0 - User Management 

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#260]
* **Problem**: 

1. Not sure if QuickAddUser still needed
2. inactive as user-status certainly wrong
3. the count refers to Key's should be Token and that is always = 1 atm
4. Upon Deletion of User the Token is not deleted (not 100% sure)

* **Expected**: inactive as user-flag should only be set if token is invalid (no idea how to check this)
* **Logs / Screenshots / Proof**: 
![image](https://user-images.githubusercontent.com/6583519/38765220-d1380276-3fbd-11e8-847b-0fcb46795833.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by herpaderpaldent** [comment]
@leonjza maybe not delete the 'inactive status' since it might be useful to see if someone invalidates his refresh token? Maybe that is done somewhere else but from a logic model thinking

**Comment by leonjza** [comment]
Restored the ability today to disable accounts in https://github.com/eveseat/web/commit/9062385866d513438a3a4f682f18b362997b81f4, need to test a case where SeAT got revoked via the EVE Account Status page still. This is probably best done in the updater logic somewhere, but needs testing.

**Comment by leonjza** [comment]
Tokens are now removed when invalid  as per https://github.com/eveseat/eveapi/commit/144d9c57e4f486fb9f5baa3ebe617d181df539d4. Think everything for this ticker is now done.
