### ISSUE TITLE
Testing SeAT 3.0 Cron 

### ISSUE THREAD

**Issue by ysm1mh** [eveseat/seat#264]
Corperation Cron job not running even if it shows added on seat schedule.

![cron](https://user-images.githubusercontent.com/4145723/38926593-8a9d030e-4303-11e8-83ba-c953abed555a.png)

used docker logs -f <app_name> and only shows

> Running scheduled command: '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' esi:update:serverstatus > '/dev/null' 2>&1
crond: USER root pid 150 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 158 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 166 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 174 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 182 cmd php /var/www/seat/artisan schedule:run
Running scheduled command: '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' esi:update:serverstatus > '/dev/null' 2>&1
crond: USER root pid 206 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
Running scheduled command: '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' esi:update:s

crond: USER root pid 214 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 222 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 230 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 238 cmd php /var/www/seat/artisan schedule:run
Running scheduled command: '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' esi:update:serverstatus > '/dev/null' 2>&1
crond: USER root pid 262 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 270 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 278 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
crond: USER root pid 286 cmd php /var/www/seat/artisan schedule:run
No scheduled commands are ready to run.
Running scheduled command: '/usr/local/bin/php' 'artisan' horizon:snapshot > '/dev/null' 2>&1
Running scheduled command: '/usr/local/bin/php' 'artisan' esi:update:serverstatus > '/dev/null' 2>&1
crond: USER root pid 206 cmd php /var/www/seat/artisan schedule:run

**Comment by warlof** [comment]
Are you sure you wait enough and get enough roles? 

According to the screen, corp job will only be run at the following

00:00
02:00
04:00
06:00
08:00
10:00
12:00
14:00
16:00
18:00
20:00
22:00

**Comment by ysm1mh** [comment]
i checked again.  and it still doesnt update. corp updated more then 1 day ago.

**Comment by ysm1mh** [comment]
works. closing
