### ISSUE TITLE
Feature request: change market overview

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#266]
In the corp market overview (corporation/view/market/) currently a list is showing of current and past industry sell/buy orders.

Like in the Industry tab, it would be handy to have a suboverview of types of orders:
Active
Expired/Fullfilled
Cancelled

This enables me to sort Expired sell/buy orders by date, which is currently not possible

Secondly, currently the start date is being shown, which for most purposes is not interesting and it would be nice to replace this with the (expected) expiration date instead.

**Comment by leonjza** [comment]
Please refrain from doing "bounties" for feature requests. The preferred ways to contribute to this project are via bug reports for bugs and wishlist items (like this one), code contributions or [donations](https://github.com/eveseat/seat#donate).

**Comment by kwazulueve** [comment]
Ok seemed to work last time, but donated ;)
