### ISSUE TITLE
Laravel log error "failed to open stream"  Seat V3

### ISSUE THREAD

**Issue by ysm1mh** [eveseat/seat#269]
i am still getting laravel log errors.  failed to open stream. 

does the storage/logs needs to have a specific ownerhip and access mask?

**Comment by herpaderpaldent** [comment]
Since this is a dev-enviroment: just delete the log and let it recreate. On Docker for Windows i can observe this behaviour as well.
Won't be an issue with the productive Docker-Version of SeAT 3.0

**Comment by ysm1mh** [comment]
i tried that as well. deleted the log files.  but still shows error accessing log file.

so somewhere the access mask isnt setup properly? 
not sure if this is a big issue?  if not then i will ignore it.

**Comment by ysm1mh** [comment]
well.  deleted the logs again.  and now it seems to be working. all good then :)
