### ISSUE TITLE
POS Page - 504 Gateway Time-out

### ISSUE THREAD

**Issue by apfelqoo** [eveseat/seat#27]
This may be the same like #26 

Weve got ~30 Towers in Corp and i allways get an timeout.

Sysinfo:
- VPS
- Ubuntu
- 4 Cores ("owned" on a 4x Xeon E5-2620 v2 @ 2.10GHz host)
- 2GB RAM (50% in use atm)

The page loads, when i set the "fastcgi_read_timeout to 180" - but it takes it over a minute.

**Comment by leonjza** [comment]
Can you share a key with me with corp assets for load testing via slack / irc pm please?

**Comment by leonjza** [comment]
Also, does your assets view timeout?

**Comment by apfelqoo** [comment]
Assets Page loads within 1-2 seconds.
I need some time to get a key from my CEO. I will contact you then.

**Comment by leonjza** [comment]
Closing this as a duplicate of #26
