### ISSUE TITLE
Mining Ledger  missing ore prices V3.0.0-Beta

### ISSUE THREAD

**Issue by ysm1mh** [eveseat/seat#271]
i found a issue in the mining ledger.
some prices are missing. 

prices that are missing are:

Iridescent Gneiss   type_id 17865 Missing from database
Triclinic Bistot        type_id 17428 in database but prices not showing
Bright Spodumain  type_id 17466 in database but prices not showing
Crimson Arkonor   type_id 17425 missing from database
Thick Blue Ice        type_id 17975 missing from database
Dark Glitter           type_id 16267 missing from database
Krystallos              type_id 16269 missing from database
Gelidus                 type_id 16268 missing from database
Glare Crust           type_id 16266 missing from database
Sharp Crokite       type_id 17432 missing from database
Onyx Ochre         type_id 17436 in database

here a screenshot so you can see.
http://prntscr.com/jbw7rj

**Comment by ysm1mh** [comment]
weird thing is. i cheched the database type_id's . the ones that are missing are now getting updated on prices. i ran the cron job php artisan esi:update:public manually. and prices are starting to show.

i do however get this issue.
Illuminate\Queue\MaxAttemptsExceededException: Seat\Eveapi\Jobs\Market\Prices has been attempted too many times or run too long. The job may have previously timed out. in /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:394

**Comment by warlof** [comment]
the job need arround 21 minutes to complete.
I think we should add an extra long queue for such job.
I assume alliance, name and structure jobs will be quite long as well.

**Comment by ysm1mh** [comment]
Seat\Eseye\Exceptions\RequestFailedException: failed to coerce value 'None' into type integer (format: int32), 'ids' is required in /var/www/seat/packages/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:235

might this also be a issue that assets show in Unknown Structure ??

**Comment by warlof** [comment]
We need full stack exception, only that line is not usefull enough. We just know that something fail.

**Comment by leonjza** [comment]
Yeah some work will be needed for the jobs that take a little longer. For now, just assume that they will eventually update. Just give it time.

**Comment by ysm1mh** [comment]
it takes alot of time indeed.  all prices have being retracted. so all good.

thx alot guys.
