### ISSUE TITLE
3.X Corp summary incorrect display TAX rate and Member Capacity

### ISSUE THREAD

**Issue by SNIPER722** [eveseat/seat#272]
* **Problem1**: TAX rate is incorrect displayed (*100?)
* **Problem2**: Member Capacity is incorrect displayed/calculated as 100%
* **Expected**: in the corp summary tab
* **Version Info**:   3.0.0-beta3

![corpsummary](https://user-images.githubusercontent.com/1414540/39431979-59f3376c-4c60-11e8-9de9-53afa11f07a2.png)

**Comment by herpaderpaldent** [comment]
![image](https://user-images.githubusercontent.com/6583519/39693070-0ea16de6-51e3-11e8-97d8-2b54d2a313ef.png)

seems not to be fixed?

**Comment by leonjza** [comment]
This fix was tagged in web 3x beta4.
