### ISSUE TITLE
Error: Class 'Seat\Eveapi\Models\Eve\ApiKey' not found

### ISSUE THREAD

**Issue by Swizeve** [eveseat/seat#276]
* **Problem**: Receive error: local.ERROR: Class 'Seat\Eveapi\Models\Eve\ApiKey' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Seat\\Eveapi\\Models\\Eve\\ApiKey' not found at /var/www/seat/vendor/eveseat/notifications/src/Alerts/Seat/NewApiKey.php:43)
* **Expected**: _Not receive error
* **Logs / Screenshots / Proof**: Below
* **Version Info**: PHP 7.1, Seat  3.0.0-beta3, Ubuntu 17.10

> [2018-05-01 09:10:02] local.ERROR: Class 'Seat\Eveapi\Models\Eve\ApiKey' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Seat\\Eveapi\\Models\\Eve\\ApiKey' not found at /var/www/seat/vendor/eveseat/notifications/src/Alerts/Seat/NewApiKey.php:43)
> [stacktrace]
> #0 /var/www/seat/vendor/eveseat/notifications/src/Alerts/Base.php(73): Seat\\Notifications\\Alerts\\Seat\\NewApiKey->getData()
> #1 /var/www/seat/vendor/eveseat/notifications/src/Commands/AlertsRun.php(72): Seat\\Notifications\\Alerts\\Base->__construct()
> #2 [internal function]: Seat\\Notifications\\Commands\\AlertsRun->handle()
> #3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
> #6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
> #7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
> #8 /var/www/seat/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #10 /var/www/seat/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #11 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Seat\\Notifications\\Commands\\AlertsRun), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #12 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #15 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #16 {main}
> "}

**Comment by leonjza** [comment]
Alerts have not been migrated to v3 yet.

**Comment by warlof** [comment]
have to be close as it's been replaced and notification package has been ported.
