### ISSUE TITLE
Character Notifications Not Displaying Correctly

### ISSUE THREAD

**Issue by Swizeve** [eveseat/seat#277]
* **Problem**: Character notifications is not displaying correctly.
* **Expected**: Character notifications display correctly. 
* **Logs / Screenshots / Proof**: https://i.imgur.com/PRxXOOn.png
* **Version Info**: PHP 7.1, Seat 3.0.0-beta3, Ubuntu 17.10

You can hover over the talk icons and get some vague header details of each one however they are not displaying in a useful format. The standings screen does a similar thing too.

**Comment by leonjza** [comment]
Fixed in https://github.com/eveseat/web/commit/7b44abf0fe69b1ab6094ffd5457430a5dc7e662d
