### ISSUE TITLE
Testing SeAT 3.X - API on Homescreen

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#279]
* **Problem**: API Key Mentioned 
* **Expected**: either panel removed or adapted to show group tokens? 
* **Logs / Screenshots / Proof**: 
![image](https://user-images.githubusercontent.com/6583519/39517895-92a7fcda-4e01-11e8-9038-ac1917be4e93.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by warlof** [comment]
https://github.com/eveseat/web/pull/143

**Comment by warlof** [comment]
have to be close
