### ISSUE TITLE
[beta2] Call to undefined function Seat\Console\Commands\Eve\bzopen()

### ISSUE THREAD

**Issue by ppfeufer** [eveseat/seat#280]
* **Problem**:  During initial installation using the install script got an error "Call to undefined function Seat\Console\Commands\Eve\bzopen()"
* **Expected**: Not getting this error, I guess
* **Logs / Screenshots / Proof**: ![grafik](https://user-images.githubusercontent.com/2989985/39526121-21bf24ae-4e1e-11e8-8af3-20524cad6d68.png)

* **Version Info**: _PHP Version:_ 7.2, _SeAT Version:_ 3.0.0-beta2, Debian 9

**Comment by evileyecc1** [comment]
PHP Bz2 extension?
Try use php -m and paste here

**Comment by herpaderpaldent** [comment]
the seat installer does not support dev installation other then Ubuntu 16.04:
Please look into this for manual installation: https://github.com/eveseat/scripts/tree/master/docker-compose-dev
