### ISSUE TITLE
[v3b2] Requires format array

### ISSUE THREAD

**Issue by revenantal** [eveseat/seat#281]
* **Problem**:  [2018-05-04 00:03:40] local.ERROR: SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS requires format array(classname, array(ctor_args)); the classname must be a string specifying an existing class (SQL: select * from `users` where `name` = admin limit 1)
* **Expected**:  No kaboom on first use
* **Logs / Screenshots / Proof**: 
[laravel-2018-05-04.log](https://github.com/eveseat/seat/files/1973006/laravel-2018-05-04.log)

* **Version Info**:  PHP Version 7.0.30-1+ubuntu16.04.1, SEAT 3 B2

* **Additional**:  Fresh install, used installer from https://github.com/eveseat/seat/issues/262. Finished install, finished installing php extensions, then ran php artisan seat:admin:login. /home and using the admin login link both generate error pages with the attached error.

**Comment by warlof** [comment]
Hello,

SeAT is requiring php 7.1 as a minimum version and either mariadb 10.2.7 or mysql 5.7

**Comment by revenantal** [comment]
Whoops missed those docs, will review tonight and update required software.

Thanks

**Comment by revenantal** [comment]
Confirming the issue existed between the keyboard and chair.

Is it possible to have this added to seat diagnose:seat down the line?

**Comment by leonjza** [comment]
The installer is not yet complete as part of the beta. You will not be able to even install without PHP 7.1 once stable is tagged.
