### ISSUE TITLE
SeAT 3.0 Installer

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#289]
[Symfony\Component\Console\Exception\RuntimeException]
  The "--all" option does not exist.

The following error is generated when using the seat.io installer for Ubuntu 16.04.  Any help to get past would be appreciated.

**Comment by IvandaNothabeer** [comment]
For Ubuntu 16.01 LTS use this guide ....

https://github.com/eveseat/docs/blob/master/docs/guides/installation/ubuntu.md

There's a couple of minor spelling errors on the install commands, but if you begin with a clean Ubuntu 16.04 install you can pretty much copy/paste the install commands and it should mostly "just work".

If you need immediate help join the seat Slack team. In slack type "!beta" to get the latest beta install information.

**Comment by herpaderpaldent** [comment]
Check your installation if  `--all` not exists you are probably still on Laravel 5.3 (which was used for SeAT 2.x) 

@IvandaNothabeer if you find spelling errors, go ahead correct it via github:
![image](https://user-images.githubusercontent.com/6583519/39797617-438e0340-535d-11e8-933c-bd1e24947b1b.png)
Help is much appreciated

**Comment by warlof** [comment]
even better from new documentation :p
![image](https://user-images.githubusercontent.com/648753/39798475-06b69460-5361-11e8-8532-a5232145df0b.png)

**Comment by herpaderpaldent** [comment]
Link: https://eveseat.github.io/docs/

**Comment by IvandaNothabeer** [comment]
Done

**Comment by drkthunder02** [comment]
I ran your installer script which updated to php7.1.

**Comment by drkthunder02** [comment]
How do I change over to a different laravel version on my end?  I thought that was part of the install package and the end user didn't have any control over it.

**Comment by drkthunder02** [comment]
I deleted everything but resetting the OS as other applications also run on
the same server and ran the installation script.

**Comment by herpaderpaldent** [comment]
https://eveseat.github.io/docs/guides/installation/installation/#docker-recommended 
have a look here, this should get you a recommended docker instance of SeAT 3.0.beta

**Comment by drkthunder02** [comment]
Docker? Isn't that used for testing environments?

**Comment by herpaderpaldent** [comment]
No

**Comment by warlof** [comment]
btw, since SeAT is in beta stage; well... you're testing it, isn't it ?

-> SeAT 3.0 installation documentation for Ubuntu https://eveseat.github.io/docs/guides/installation/ubuntu/

Related to docker, @herpaderpaldent already linked you the existing quick talk.
You'll get the documentation related to him here :
-> https://eveseat.github.io/docs/guides/installation/docker/

/!\ It will not work on OpenVZ virtualised server most of the time since you can't handle your kernel in such environment and host kernel are outdated most of the time.

**Comment by warlof** [comment]
state ? close ?

**Comment by warlof** [comment]
Close due to inactivity
