### ISSUE TITLE
(Seat 3.0) Seat\Eveapi\Jobs\Corporation\Structures - Field 'Name' Doesnt Have a Default Value

### ISSUE THREAD

**Issue by IvandaNothabeer** [eveseat/seat#293]
* **Problem**:  Error inserting into Structures. Possibly "Structure Name" returned by ESI is blank ?
* **Expected**: 
* **Logs / Screenshots / Proof**:   Laravel Stack Trace attached
* **Version Info**: SEAT 3.0 

`Seat\Eveapi\Jobs\Corporation\Structures
ID
19353
Queue
default
Tags
corporation, structures, character_id:470623492
Failed At
18-05-10 09:19:42
Error
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value in /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141`

Full Trace ....  https://pastebin.com/hZSuLw2n

**Comment by warlof** [comment]
Do you have any idea about what this structure is related to?
Like using a default name?

**Comment by IvandaNothabeer** [comment]
sorry, no clue :(

**Comment by warlof** [comment]
just figure you didn't provide your package list, can you show them ?
especially the eveapi package according to the issue.

**Comment by MrBMT** [comment]
^ fyi the easy way to get that is to run php `/var/www/seat/artisan seat:admin:diagnose`
The last thing you'll see listed is your installed packages.

**Comment by leonjza** [comment]
I thought I fixed this in https://github.com/eveseat/eveapi/commit/447c9c8297d3909c7d8a8b407e423c1864e42a6f :| @IvandaNothabeer could you confirm you are running at least v3.0.0-beta7 of the `eveapi` package?

**Comment by IvandaNothabeer** [comment]
Nope. Beta 6. 

Sorry for the trouble

**Comment by warlof** [comment]
So, is it fixed ?!

**Comment by IvandaNothabeer** [comment]
Yes. seems to be.
