### ISSUE TITLE
Tracking link on SeAT Settings page points to old docks

### ISSUE THREAD

**Issue by justindh** [eveseat/seat#294]
The link pictued points to http://seat-docs.readthedocs.io/en/latest/admin_guides/tracking/  instead of https://eveseat.github.io/docs/guides/admin/tracking/
![wronglink](https://user-images.githubusercontent.com/5378764/39845877-418f8c44-53ad-11e8-9ebd-cc0da58a183d.PNG)

**Comment by warlof** [comment]
can be close as it has been addressed
