### ISSUE TITLE
Api Import Error

### ISSUE THREAD

**Issue by JackONeill12** [eveseat/seat#3]
I've tried to import an EvE Character API but all I've get is: Bang! Client error: `GET https://api.eveonline.com/account/APIKeyInfo.xml.aspx` resulted in a `400 Bad Request`

**Comment by leonjza** [comment]
This is currently a known issue. Its actually a bug in the way PhealNG uses Guzzle, which I am working on fixing and submitting a patch for upstream.

**Comment by JackONeill12** [comment]
OK. Thx for the quick answer. ;)

**Comment by leonjza** [comment]
Np. For reference: https://github.com/3rdpartyeve/phealng/pull/34

**Comment by ppetermann** [comment]
should be fixed with 2.3.3 of pheal (composer update in your project)

**Comment by leonjza** [comment]
Thanks.
