### ISSUE TITLE
Provide internal view for killmails

### ISSUE THREAD

**Issue by cryocaustik** [eveseat/seat#300]
currently when reviewing kills in the kill mail list, we only have links to zkb; this is great and works in most cases, but there are a lot of times when kills are not posted to zkb intentionally. 

proposing a feature to allow users to have a basic (or advanced if we want) view of the kill locally.

this would also be very easy to implement as we already capture and store all this data in seat 

 ![kill_mail_tables_in_seat](https://i.imgur.com/OmwvZ9G.png)

**Comment by warlof** [comment]
This is probably a good start for those who would contribute to the project. You need to work on some routing, a controller and blades to render killmails.

All pulling logic and models have already been handled.
