### ISSUE TITLE
3.x wallet transaction show sender and receiver as Corporation

### ISSUE THREAD

**Issue by SNIPER722** [eveseat/seat#302]
* **Problem**: on wallet tab, when click on character show transaction record as `Corporation`
* **Expected**: character name/corp name display 

* **Version Info**: PHP7.1  seat3.0.0-beta 7
* **Logs / Screenshots / Proof**: 
![eh](https://user-images.githubusercontent.com/1414540/39968634-472f9a74-569e-11e8-9d49-e2a7d468f035.png)

**Comment by leonjza** [comment]
I can't replicate this. What is your web package version?

**Comment by SNIPER722** [comment]
update to the newest version. this problem still present
it seems like on the web everything hasn't been updated ( or haven't updated yet) will be replace by `corportaion` 

and this screenshot is a interesting one
![lol](https://user-images.githubusercontent.com/1414540/40512027-8dd2c9ea-5f6f-11e8-8d7d-85725c682218.png)

**Comment by leonjza** [comment]
I still can't replicate this. Can you clear caches and all that?

`php artisan cache:clear` and `php artisan seat:cache:clear`

**Comment by warlof** [comment]
same here

**Comment by SNIPER722** [comment]
tried. still the same. after run both command. I suspect there might be error somewhere in the code that replace the numeric id to string id

**Comment by gavello** [comment]
Noticing a similar issue in my installation as well. A few extra things:

1. Security Status shows fine on other pages and only changes to Corporation on the wallet page.

2. Not all characters are effected by this issue, characters added yesterday display fine but someone who added themselves a few hours ago now is showing this issue (Something to do with when the eve servers were down perhaps?)

**Comment by warlof** [comment]
Which browser are you using?

**Comment by SNIPER722** [comment]
Google Chrome
Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by herpaderpaldent** [comment]
I have it reproduced on two servers:
1. my staging
2. Corp SeAT (where i am a pure consumer)

**Comment by leonjza** [comment]
Thanks @Lee-Klein that was most useful in tracking this down. Based on your comment I managed to reproduce this locally and fix it. Should be available in the next web package later today.
