### ISSUE TITLE
Character Intel window show blank "Top Wallet Transaction Interactions" and "Top Mail Interactions" sections.

### ISSUE THREAD

**Issue by WildStrawberryEVE** [eveseat/seat#303]
Character Intel window show blank "Top Wallet Transaction Interactions" and "Top Mail Interactions" sections. No error on opening page. Errors logged when attempting to sort by some column.
Only "total" shows number of interactions.
(Top Wallet Journal Interactions works fine)

[![Screenshot from Gyazo](https://gyazo.com/578241367c201f3826ba7e35a46057fa/raw)](https://gyazo.com/578241367c201f3826ba7e35a46057fa)

[![Screenshot from Gyazo](https://gyazo.com/988ba4447fe6afd3e7624e3a908b5045/raw)](https://gyazo.com/988ba4447fe6afd3e7624e3a908b5045)

https://pastebin.com/15caQns5
https://pastebin.com/5fELZ1HE

[![Screenshot from Gyazo](https://gyazo.com/8e8390ddd5535ef6797de4a6f72b7c36/raw)](https://gyazo.com/8e8390ddd5535ef6797de4a6f72b7c36)

**Comment by leonjza** [comment]
I see a newly registered character has a similar case in my test environment, but one that has been registered for a while does not. This might mean the affiliations job has not yet run for the character in question. Will look into it.

**Comment by WildStrawberryEVE** [comment]
![untitled](https://user-images.githubusercontent.com/20519150/39970444-cd8912ec-56eb-11e8-8906-5952936fea48.png)
Simillar errors like for the char with all empty panels. Errors only log when trying to sort by columns

**Comment by WildStrawberryEVE** [comment]
I run manualy: docker-compose exec seat-app php artisan esi:update:public
Got failed job:
https://pastebin.com/rxhjj1bk

**Comment by 73udz** [comment]
Im getting the same issue, only with mine no names are populating for any character registered to seat. Under Mail and both wallet sections just show the numbers and the row's where names should be but are blank with no photo.

**Comment by SergeyAB** [comment]
Same for me too for all chars (have a new clear installation).
![clip2net_180603133117](https://user-images.githubusercontent.com/8689208/40885622-8ab5dc8c-6732-11e8-8430-60047d9912e5.png)
![clip2net_180603133144](https://user-images.githubusercontent.com/8689208/40885623-8ad6f35e-6732-11e8-8172-062dab4f0fe7.png)

**Comment by warlof** [comment]
@SergeyAB it has normally been fixed in eveseat/eveapi v3.0.0-b18

Can you tell us if you have this job running `\Seat\Eveapi\Jobs\Character\Affiliation` (tag `affiliations`) ?

**Comment by SergeyAB** [comment]
I've SeAT Eveapi Installed: v3.0.0-beta22
I restarted job manually and have some data. Will wait for a day and monitor the job.

**Comment by KimSpecht** [comment]
I have this problem as well, on all characters. 
If I look in Horizon->Metrics->Jobs I see no jobs containing affiliation, should I look somewhere else?

**Comment by warlof** [comment]
@Kim not really good. Are you running latest packages?

**Comment by KimSpecht** [comment]
Yes, everything is latest versions, and on another note with the scheduler, if I look in Seat (not Horizon), the current schedule is empty, I saw other users having a bunch of commands here, so wondering if it's related.

**Comment by warlof** [comment]
SeAT is only showing job state from last hour.

If you want info about your job. Go on horizon dashboard. 

And if you have to monitor specific jobs for short, use monitoring with provided tag upper. Not metrics.

**Comment by KimSpecht** [comment]
Okay, I manually ran the esi:update:public command as nothing seemed to happen, now I see the job failing as seen below. I've seen this exact same error in other jobs (undefined method preflighted)
<img width="926" alt="screen shot 2018-06-06 at 23 24 43" src="https://user-images.githubusercontent.com/870107/41066149-3290774a-69e1-11e8-8d6d-4cab7da3a906.png">

**Comment by warlof** [comment]
Hum,

Did you restart supervisor after applying updates?

**Comment by KimSpecht** [comment]
Nopes, just did and now that job seems to run fine, my "intel" section is still empty though, but I'll wait and see if it doesn't show up by tomorrow before investigating further, thanks for help so far.

**Comment by warlof** [comment]
what's the state of this since release ?
supposed to be fix.

**Comment by KimSpecht** [comment]
Works for me now, but can't speak for @WildStrawberryEVE

**Comment by WildStrawberryEVE** [comment]
I still have some empty fields with only "total" number (like on this censored screenshot from 13 may). Sorting by columns works fine. Affiliation jobs are monitored and work fine.

I think I'll wipe the installation soon and install 3.0 from scratch to see how it works

**Comment by WildStrawberryEVE** [comment]
wiped, installed 3.0 - state like on 13may screenshot. Sorting works. No errors logged.
Some chars have all fields filled but most have some blank lines.

**Comment by herpaderpaldent** [comment]
I think we can close this issue.

**Comment by warlof** [comment]
Closed due to inactivity. Fill free to reopen it if you still have the issue.
