### ISSUE TITLE
Character Contacts is missing character ID/name in links to 3rd party sites

### ISSUE THREAD

**Issue by cryocaustik** [eveseat/seat#304]
three of the sites have character info added to the hyperlinks, but the others are missing the information.

example: 
![missing  info screenshot](https://i.imgur.com/HVUsSos.png)

**Comment by leonjza** [comment]
I thought this was a n easy fix, but I realised its a little trickier than I initially thought as we are resolving names client side. Fixing this is going to need some more work to implement.

**Comment by cryocaustik** [comment]
this is why I have not submitted my PR yet... 😄 

from my review, I was thinking of adding a one to one relation on Contacts to pull character names, but I was not sure if we store that data anywhere...

**Comment by MrBMT** [comment]
@cryocaustik Contact names are not currently stored anywhere, no

**Comment by leonjza** [comment]
Yep. Currently we warm up the cache with name resolutions [here](https://github.com/eveseat/web/blob/master/src/Http/Controllers/Support/ResolveController.php#L113) but should definitely consider more permanent storage and an optimal way to perform the resolutions too.

**Comment by cryocaustik** [comment]
would we consider a job to pull and store public info on all characters existing as a contact?

**Comment by warlof** [comment]
- eve-prism is actually updating
- eve gate should be replaced by eve forums which is lower cased character name replacing ` ` with `_`
- eveboard could be replaced as I understood

**Comment by warlof** [comment]
addressed in https://github.com/eveseat/web/pull/185 pending better implementation.

**Comment by leonjza** [comment]
Should be fixed with the hack in the latest releases.
