### ISSUE TITLE
Problem with config in docker release

### ISSUE THREAD

**Issue by nsdonner** [eveseat/seat#305]
It seems to that ssl doesn't configured correct in nginx docker container. When i tried to access seat via https (8443) there are errors in docker logs about missed certificate. It would not be a big problem with revers proxy in frontend, but app generates internal links with http instead https, so it useless.

I'm not very in with docker, and i didn't find it in seat docs, so if there is the way how to fix it fast - it will be greate.

**Comment by leonjza** [comment]
I think I should probably remove that as configuring the web server is something you would need to do manually after the docker installation. Nonetheless, installing nginx with a configuration similar to [this](https://eveseat.github.io/docs/guides/installation/basic_installation/nginx/#docker-ssl-support) one should get you going.

**Comment by nsdonner** [comment]
May be, the right way will be mounting a volume somewhere with nging config, so users can do config manualy without digging docker container.

**Comment by herpaderpaldent** [comment]
@leonjza that would make sense since i had to comment out stuff to get Traefik running 👍 
https://github.com/eveseat/docs/pull/43

**Comment by warlof** [comment]
Traefik will be natively shipped with SeAT for Gen 4 on Docker installation. This will hide all your SeAT containers and ensure ssl support 😉
