### ISSUE TITLE
Failed job: Seat\Eveapi\Jobs\Industry\Corporation\Mining\ObserverDetails

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#306]
Debian 9, automatic install SeAT beta

Error: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.corporation_industry_mining_observer_data' doesn't exist in /var/www/seat.tgrad.space/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80

Solution: seat.corporation_mining_observer_data seems to need to be renamed to seat.corporation_industry_mining_observer_data

**Comment by leonjza** [comment]
This was fixed in https://github.com/eveseat/eveapi/commit/0564cbc0bb477524b9190a2fe8f6a9a1b67e45f8. What is the version of your `eveapi` package?

**Comment by kwazulueve** [comment]
Ah ok, I have 3.0.0-beta5 installed (~ 3 days ago), explains I missed the fix from yesterday I guess :)
