### ISSUE TITLE
SEAT 3.0 Corporation character list sort by name bugged

### ISSUE THREAD

**Issue by dae-eliador** [eveseat/seat#308]
* **Problem**: _Whats wrong?_
Sorting character list by name in the CORPORATION sheet, "TRACKING" view is bugged. It does not sort by character name at all.

* **Expected**: _What did you expect to happen?_
I expect an alphabetically ordered list of character names

* **Logs / Screenshots / Proof**: _The more information you give the better!_
![image](https://user-images.githubusercontent.com/22895830/40065374-f090c236-5861-11e8-91b2-4187765d2e8d.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
SDE Version sde-20180323-TRANQUILITY | Web Version 3.0.0-beta9

NOTE : screenshot is empty because I don't want to give all details of my full corporation haracter list out in the open, but you can clearly see that : 
- name filter is active
- list is not alphabetically sorted at all (you can see the first few letters of each name)

I am in the corporation sheet, "Tracking" menu

**Comment by leonjza** [comment]
The screenshot is basically empty. Could you fill out the template you got presented when you filed this issue with more information please?

**Comment by dae-eliador** [comment]
Done. I don't believe you need a fuller screenshot to see the issue.

**Comment by leonjza** [comment]
I only wanted the issue template filled in. Thank you.

**Comment by Metzgermeister81** [comment]
http://<myseatdomain>/corporation/view/tracking/<corpID>
it seems to sort for the character ID when I point over the link and move down the number is either in- or decreasing depening on current sorting

hope this helps

**Comment by herpaderpaldent** [comment]
The issue with that sorting is, that it sorts by character_id not by the resolved name. Since we are resolving the name after Datatables loads the results (and sorts) i am unsure how we could solve this. 

We might need to disable sorting on this column

**Comment by warlof** [comment]
Disabling the sort is a bypass and not a fix. We should find a way to update cache after name resolving or perhaps making the resolve earlier.

**Comment by herpaderpaldent** [comment]
I am working on something like this ... But the include main char pr is blocking me needs merging

**Comment by herpaderpaldent** [comment]
this could be closed

**Comment by warlof** [comment]
nope, it's specifically targeting corporation tracking which still need to be refactored ;)
