### ISSUE TITLE
"Current Ship" in character Sheet view, does not show the name of the ship

### ISSUE THREAD

**Issue by H4Z4RD-H42** [eveseat/seat#309]
* **Problem**: _Whats wrong?_
In the Character Sheet view, the label "Current Ship" show always this text: **called**
* **Expected**: _What did you expect to happen?_
Show me the name of the ship the pilot is currently driving
* **Logs / Screenshots / Proof**: _The more information you give the better!_
![image](https://user-images.githubusercontent.com/6650832/40107787-7a3f5a78-58f9-11e8-8eb8-4d59411caa3f.png)
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
SeAT 3.0, SeAT Web v3.0.0-beta11, PHP 7.2.5-0ubuntu0.18.04.1,

**Comment by MrBMT** [comment]
This has been fixed with the release of eveapi v3.0.0-beta13. Note that initially it may show something like `#system called Charactername's Capsule` (for example) however when the ship update job is next run for that character it will correct this so that it shows the ship type instead.

**Comment by leonjza** [comment]
Fixed in latest betas. Give the workers some time to populate the data as a field was missing.
