### ISSUE TITLE
admin authentification url not correctly work

### ISSUE THREAD

**Issue by leg0las-devel** [eveseat/seat#310]
Authentification link, wich generated by

`sudo -H -u seat bash -c 'php /var/www/seat/artisan seat:admin:login'`

and open it in new tab show error:

`Type error: Argument 1 passed to Seat\Console\Bus\CharacterTokenShouldUpdate::__construct() must be an instance of Seat\Eveapi\Models\RefreshToken, null given, called in /var/www/seat/vendor/eveseat/web/src/Events/Login.php on line 62`

But if refresh page with seat, i get admin access.

**Comment by leonjza** [comment]
Thanks for reporting this. Definitely because of some refactoring I did last night. Will fix.

**Comment by leonjza** [comment]
Fixed in a recent web update.
