### ISSUE TITLE
Feature request: Security log showing title entries

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#313]
Currently the corporation/view/security/log/773499566 is showing changes in assigned roles to members.
Our corporation works with titles exclusively, and current behaviour is that when a title (with multiple roles) gets assigned multiple entries in the security log appear.

It would be very handy if with a title change just a single line with the assigned/removed title would appear in the log

**Comment by warlof** [comment]
@kwazulueve unfortunately we don't have this information available from ESI.
The only available corporation security log endpoint is the roles one.

I urge you to make a request to esi team [here](https://github.com/esi/esi-issues) :)

**Comment by kwazulueve** [comment]
This should be possible with https://esi.evetech.net/ui#/Character/get_characters_character_id_titles
When updating the seat DB from the endpoint you could notice any changes and subsequent log that
You can even filter out the title based role assignments that way and make a distinction between the two in the log

**Comment by warlof** [comment]
indead, but it will not show you who did it.
