### ISSUE TITLE
Standings page browser loading issues

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#315]
* **Problem**: The standings overview page at corporation/view/standings/773499566 takes a long time to load and causes several Chrome popups to potentially kill the page loading
* **Expected**: 
* **Logs / Screenshots / Proof**: 
* **Version Info**: Debian 9, PHP 7.1, Apache, latest SeAT beta, Chrome 66.0.3359.170

The page is undoubtly causing errors because our corporation simply has a huge number of entries on this page, around 8000 standings. Pagination would perhaps be the best solution here (with a search box?)

**Comment by MrBMT** [comment]
Yeah I was discussing this with qu1ckkkk the other day, pagination is already on the to-do list for this.

**Comment by leonjza** [comment]
Standings paginate now in the latest versions.
