### ISSUE TITLE
Proposal: NodeBB integration

### ISSUE THREAD

**Issue by nizzan** [eveseat/seat#32]
I saw the list with the other planned integrations, I'm a big fan of NodeBB, which already has an eve-api module for registering and such.
https://community.nodebb.org/topic/2140/nodebb-plugin-eve-eve-online-registration-whitelists

**Comment by warlof** [comment]
what do you want ? node registration to seat or seat registration to nodebb ?!

**Comment by leonjza** [comment]
At the moment, I'd imagine most integrations meaning that the external software should be able to auth from SeAT (and be able to grab group info).

**Comment by warlof** [comment]
Using seat api ?

**Comment by johnnysplunk** [comment]
I recently integrated NodeBB with the old version of eve-seat. It used SSO and a custom oauth2 implementation in eve-seat.

I'm going to be migrating to the new version of eveseat and will release an oauth2 package and corresponding NodeBB package. The oauth2 package could be used with other services/apps that support it.

**Comment by leonjza** [comment]
Added to the [wishlist](https://github.com/eveseat/seat/wiki/Todo-List#wishlist)
