### ISSUE TITLE
Feature Request: Ability to Create users from an External Auth system

### ISSUE THREAD

**Issue by IvandaNothabeer** [eveseat/seat#322]
As discussed in Slack's dev channel ....

The request is to be able to create Seat Users from an external Authorisation system, have the External Auth pass the required ESI Auth token when the User is created and allow Seat to use a common client_id & secret_key to refresh tokens. 

Users would then log in to seat using the "Authentication Only" SSO.
  
- Ability to Create a User using a POST request to the Seat API
- Ability to post an ESI Auth or RefreshToken as part of the create user action
- Ability for Seat to use a shared client_id / Secret_key to refresh the ESI tokens. i.e. External Auth system and Seat both have the same client_id & secret_key set in their respective .env file.
- Ability to log into Seat using Authentication Only SSO

**Comment by kanelarrete** [comment]
Auth 1.x of Alliance Auth had a great integration with SeAT and I have been hoping something would be created to link these together. Could it be something where whatever the Authorization system keeps the access tokens refreshed and then SeAT will just ask for the tokens when needed? This would allow the user to only have one login to worry about and you could ask for "Full API" upfront.

**Comment by leonjza** [comment]
Just landed https://github.com/eveseat/api/commit/81bf6d396079df11ca16007aa19c34e78d948ecb which adds the endpoints to create / delete users from a SeAT instance. It is a re-implementation of [this pr](https://github.com/eveseat/api/pull/18) and should pave the way to better integration post 3.x stable.
