### ISSUE TITLE
seat DEV - Starbases show wrong est online time

### ISSUE THREAD

**Issue by ysm1mh** [eveseat/seat#323]
found a issue with the corp starbases showing the wrong est time online.  see screenshot.

http://prntscr.com/jjvbi3

- SeAT Api
- Installed: v3.0.0-beta5
- SeAT Console
- Installed: v3.0.0-beta6
- SeAT Eveapi
- Installed: v3.0.0-beta15
- SeAT Notifications
- Installed: v3.0.0-beta2
- SeAT Web
- Installed: v3.0.0-beta13
- SeAT Services
- Installed: v3.0.0-beta8

**Comment by kwazulueve** [comment]
I have the same, latest SeAT beta:

![image](https://user-images.githubusercontent.com/25641678/41372554-f1413596-6f4d-11e8-8c3f-89f346953b3e.png)

![image](https://user-images.githubusercontent.com/25641678/41372595-117aa338-6f4e-11e8-9c47-4f527349e434.png)

Its a bit annoying to have to fix this with Starbases being removed next year but if shown correctly this would be very useful for our pos fueling team :)

**Comment by leonjza** [comment]
Should be fixed in latest versions.
