### ISSUE TITLE
CorporationListAll permission not working

### ISSUE THREAD

**Issue by cedgewick** [eveseat/seat#327]
Default users have access to the corporation list from the left side menu. 

Creating roles with CorporationListAll permission (inverted and not) did not change anything. 

Users without CorporationSummary permission couldn't see the corp's summary pages.

**Comment by Nairmiod** [comment]
I set up an install yesterday and get the same bug.

**Comment by warlof** [comment]
@joeeigel that will be fixed with release for sure.

Related to the dangerous thing... Leave it to @qu1ckkkk as I've never get the purpose 😋

**Comment by leonjza** [comment]
Yeah so the permissions code is really... crap, and probably the code I hate the most to be honest. I wanted to literally rip it out and start fresh for 3.0 but the ESI migration took priority over that. However, the _primary_ goal for 3.1 will be a complete permissions rewrite to something hopefully more logical and sane. Stay tuned!

**Comment by warlof** [comment]
Addressed into eveseat/console#25
