### ISSUE TITLE
Seat Failed to Generate Database Structure

### ISSUE THREAD

**Issue by 73udz** [eveseat/seat#328]
* **Problem**: Receiving errors when attempting to Generate Seat Database Structure. This may be caused by my little experience with Ubuntu, but I followed each step along the way and do have some basic Linux knowledge.  I have tried wiping the cloud image and starting from scratch to ensure I didnt miss a step along the way and I still get the same errors. 

Command ran:      sudo -H -u seat bash -c 'php /var/www/seat/artisan migrate'

* **Expected**: Seat to generate the database structure.
* **Logs / Screenshots / Proof**: http://prntscr.com/jk4ask<- Errors received. 
* **Version Info**:  OS: Ubuntu 16.04.4 LTS, PHP Version: 7.1.17 Seat Version: New Install so Newest availabe.

**Comment by IvandaNothabeer** [comment]
There's a lot of confusing advice on the internet about how to fix this error. Its a known issue with laravel.

https://wildlyinaccurate.com/mysql-specified-key-was-too-long-max-key-length-is-767-bytes/

You'll need to adjust your my.ini settings for mysql.

**Comment by leonjza** [comment]
This is a typical problem you do not have the the min version database required for SeAT. Please have a look at the [requirements documentation](https://eveseat.github.io/docs/general/requirements/#software-requirements) and update accordingly.

**Comment by warlof** [comment]
In addition, it's covered by doc https://eveseat.github.io/docs/guides/installation/manual_installation/ubuntu/#database

**Comment by MrBMT** [comment]
The version of MySQL or MariaDB you're using is simply too old. The key length workaround mentioned above will not work, because SeAT also makes use of data types that the older versions do not support, so the only option you have here is to install a newer version.

**Comment by 73udz** [comment]
I appreciate the quick feedback. It appears that the database was slightly below the requirements. It was 10.2.5 not 10.2.7.
