### ISSUE TITLE
Possible : Bug when i restart server + "Whoops, looks like something went wrong"

### ISSUE THREAD

**Issue by baussant** [eveseat/seat#329]
[Debian]() 9
Seat 3.0  with Docker. 
the server worked perfectly, i just restart the server and now impossible to use the application.

2018-05-20 09:46:37] production.ERROR: SQLSTATE[HY000] [2002] Connection refused {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /usr/src/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:50, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /usr/src/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:46)
[stacktrace]
#0 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', 'forge', '', Array)
#1 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'forge', '', Array)
#2 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)
#3 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))
#6 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(940): Illuminate\\Database\\Connection->getPdo()
#7 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(399): Illuminate\\Database\\Connection->getReadPdo()
#8 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(325): Illuminate\\Database\\Connection->getPdoForSelect(true)
#9 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select `value` ...', Array)
#10 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `value` ...', Array, Object(Closure))
#11 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `value` ...', Array, Object(Closure))
#12 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\\Database\\Connection->select('select `value` ...', Array, true)
#13 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\\Database\\Query\\Builder->runSelect()
#14 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(483): Illuminate\\Database\\Query\\Builder->get(Array)
#15 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(467): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#16 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#17 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(449): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#18 /usr/src/seat/vendor/eveseat/services/src/Settings/Settings.php(89): Illuminate\\Database\\Eloquent\\Builder->value('value')
#19 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(362): Seat\\Services\\Settings\\Settings::Seat\\Services\\Settings\\{closure}()
#20 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->rememberForever('seat.queue_work...', Object(Closure))
#21 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Cache\\CacheManager->__call('rememberForever', Array)
#22 /usr/src/seat/vendor/eveseat/services/src/Settings/Settings.php(100): Illuminate\\Support\\Facades\\Facade::__callStatic('rememberForever', Array)
#23 /usr/src/seat/vendor/eveseat/services/src/Helpers/helpers.php(289): Seat\\Services\\Settings\\Settings::get('queue_workers')
#24 /usr/src/seat/vendor/eveseat/web/src/WebServiceProvider.php(269): setting('queue_workers', true)
#25 /usr/src/seat/vendor/eveseat/web/src/WebServiceProvider.php(95): Seat\\Web\\WebServiceProvider->configure_horizon()
#26 [internal function]: Seat\\Web\\WebServiceProvider->boot(Object(Illuminate\\Routing\\Router))
#27 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#28 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#30 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#31 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call(Array)
#32 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider(Object(Seat\\Web\\WebServiceProvider))
#33 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Seat\\Web\\WebServiceProvider), 23)
#34 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#35 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#36 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#37 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#38 /usr/src/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#39 /usr/src/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 {main}
"} 
[

**Comment by leonjza** [comment]
Best to come and join us on slack for this one please. https://eveseat.github.io/docs/about/contact/

**Comment by leonjza** [comment]
There is an issue with the permissions in the containers atm. This will resurface every time you restart the container until I fix it. Once the restart is done, run `sh` in the `seat-app` container and fix up the storage directories ownership.

```
cd /opt/seat-docker
docker-compose exec seat-app sh
chown -R www-data:www-data storage/
exit
```

**Comment by leonjza** [comment]
I think I fixed this. Update your docker env as per: https://eveseat.github.io/docs/guides/admin/docker/#performing-updates

**Comment by leonjza** [comment]
Right - convinced fresh Docker installs will be more awesome now and not have these troubles!
