### ISSUE TITLE
Proposal: Integrate Let's Encrypt

### ISSUE THREAD

**Issue by nizzan** [eveseat/seat#33]
It'd be nice to have a fancy https connection.
Would it be possible to add automatic letsencrypt install/configuration to the one-line installers?
https://letsencrypt.org/
https://community.letsencrypt.org/t/quick-start-guide/1631

**Comment by leonjza** [comment]
Letsencrypt is actually not related to SeAT itself. Determining the domain owned by the user means we have to add user interaction which I will prefer not to do. I will however add it to the wiki.
