### ISSUE TITLE
Cannot View Character Sheets

### ISSUE THREAD

**Issue by paintballlaws** [eveseat/seat#330]
* **Problem**: Cannot View Character Sheets
* **Expected**:  To see characters sheet
* **Logs / Screenshots / Proof**: https://pastebin.com/EV803LL1
* **Version Info**: 3.0.0-beta15, Ubuntu 18.04 x64

**Comment by leonjza** [comment]
What is on `/var/www/seat/storage/framework/views/d75db327921c748b6fa3610768f9dadad521ece9.php` line 76?

**Comment by paintballlaws** [comment]
how would I view that?

**Comment by paintballlaws** [comment]
https://pastebin.com/pZ8UBZ0C

**Comment by warlof** [comment]
@paintballaws got Sde?

**Comment by paintballlaws** [comment]
@warlof whats sde? I just used the docker install

**Comment by paintballlaws** [comment]
but I updated from beta 3 which worked fine and then went to beat 15 and it didn't work ant then went to beta 16 and still didn't work?

**Comment by IvandaNothabeer** [comment]
I have seen this error when character data has not been pulled yet from the ESI.

Check /seat/storage/logs/laravel*.log and eseye*.log for any errors.

**Comment by paintballlaws** [comment]
https://pastebin.com/HBKi4tSL   ---Laravel Log
https://pastebin.com/SK1MPf3N    ----eseye log

Here are both the logs I only see one error and its a nginx error so dont know how much that effects it?

**Comment by paintballlaws** [comment]
@warlof should I just wipe and restart? If I do that cant I backup my database to save all the character tokens and stuff so people don't have to resubmit all of it?

**Comment by paintballlaws** [comment]
Just an update on this I completely wiped my server and reinstalled and it works fine but then I restored from backup the database and the same problem occurs so don't really know where to go from here but just thought I would update you on this

**Comment by herpaderpaldent** [comment]
@paintballlaws is your horizon working? i noticed on my Dev-Machine similiar behaviour then i had to restart the whole docker-compose

To actually look what the containers are doing and their output use:
`docker-compose logs --tail 10 -f`

If you notice some notification from seat-cron and seat-horizon that they are ideling because seat-app has not started yet you might want to restart the whole docker-compose

**Comment by paintballlaws** [comment]
https://i.imgur.com/WIrJgdA.png 
This is after a full restart of docker

**Comment by paintballlaws** [comment]
So I think for this issue even thou you guys have been helping im just going to say that some how on an update the database corrupted it's self and thats why this wont work. So im just going to wipe everything and start over but thanks for the help, you guys really are awesome and thank you for the work you do!!
