### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by marazmatik** [eveseat/seat#331]
Making update by seat update:seat
 Running command: /usr/local/bin/composer update --no-interaction --no-ansi --no-dev --no-progress -d /var/www/seat/
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: darkaonline/l5-swagger
Discovered Package: eveseat/api
Discovered Package: eveseat/console
Discovered Package: eveseat/eveapi
Discovered Package: eveseat/notifications
Discovered Package: eveseat/services
Discovered Package: eveseat/web
Discovered Package: fideloper/proxy
Discovered Package: laravel/horizon
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Package manifest generated successfully.
 Running command: /usr/bin/php /var/www/seat/artisan vendor:publish --force --all
SeAT Setup Command> Copied File [/vendor/laravel/horizon/config/horizon.php] To [/config/horizon.php]SeAT Setup Command> Copied Directory [/vendor/laravel/horizon/public] To [/public/vendor/horizon]SeAT Setup Command> Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]SeAT Setup Command> Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]SeAT Setup Command> Copied File [/vendor/darkaonline/l5-swagger/config/l5-swagger.php] To [/config/l5-swagger.php]SeAT Setup Command> Copied Directory [/vendor/darkaonline/l5-swagger/resources/views] To [/resources/views/vendor/l5-swagger]SeAT Setup Command> Copied Directory [/vendor/eveseat/api/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied Directory [/vendor/eveseat/eveapi/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied Directory [/vendor/eveseat/notifications/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied Directory [/vendor/eveseat/services/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied File [/vendor/maatwebsite/excel/src/config/excel.php] To [/config/excel.php]SeAT Setup Command> Copied File [/vendor/yajra/laravel-datatables-oracle/src/config/config.php] To [/config/datatables.php]SeAT Setup Command> Copied File [/vendor/yajra/laravel-datatables-oracle/src/resources/assets/buttons.server-side.js] To [/public/vendor/datatables/buttons.server-side.js]SeAT Setup Command> Copied Directory [/vendor/yajra/laravel-datatables-oracle/src/resources/views] To [/resources/views/vendor/datatables]SeAT Setup Command> Copied Directory [/vendor/eveseat/web/src/resources/assets] To [/public/web]SeAT Setup Command> Copied Directory [/vendor/eveseat/web/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied File [/vendor/components/font-awesome/css/font-awesome.min.css] To [/public/web/css/font-awesome.min.css]SeAT Setup Command> Copied Directory [/vendor/components/font-awesome/fonts] To [/public/web/fonts]SeAT Setup Command> Copied File [/vendor/fideloper/proxy/config/trustedproxy.php] To [/config/trustedproxy.php]SeAT Setup Command> Copied Directory [/vendor/laravel/framework/src/Illuminate/Mail/resources/views] To [/resources/views/vendor/mail]SeAT Setup Command> Copied File [/vendor/laravel/tinker/config/tinker.php] To [/config/tinker.php]SeAT Setup Command> Publishing complete.
 Running command: /usr/bin/php /var/www/seat/artisan migrate
SeAT Setup Command> Nothing to migrate.
 Running command: /usr/bin/php /var/www/seat/artisan db:seed --class=Seat\\Notifications\\database\\seeds\\ScheduleSeeder
 Running command: /usr/bin/php /var/www/seat/artisan db:seed --class=Seat\\Services\\database\\seeds\\NotificationTypesSeeder

SeAT Setup Command> In Container.php line 752:SeAT Setup Command> SeAT Setup Command> Class Seat\Services\database\seeds\NotificationTypesSeeder does not existSeAT Setup Command> 
                                                    
  [Seat\Installer\Exceptions\ArtisanCommandFailed]  
  Setup failed.

**Comment by MrBMT** [comment]
I've also been able to replicate this, I'm guessing it's a bug that was introduced with the notifications re-work that was committed today.

**Comment by leonjza** [comment]
Oops. Yes, [this line](https://github.com/eveseat/installer/blob/master/src/Utils/Seat.php#L135) is causing the headache. Ill remove it and push a new installer build tonight.

**Comment by leonjza** [comment]
Fixed in https://github.com/eveseat/installer/commit/b58dfdf1e7ced785ec1ff0cad4e58988c4239f9e. New SeAT tool has been built. `seat update:self` to get it.
