### ISSUE TITLE
Dev: Can't get main_character_id from group

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#334]
* **Problem**: i can't receive the `main_character_id` from a group: https://github.com/eveseat/web/blob/master/src/Models/Group.php#L48-L50 
* **Expected**: If i use `auth()->user()->group->main_character_id` i receive the ID of the groups main. Other then that:
@leonjza [suggested](https://eve-seat.slack.com/archives/CAPC5V8QK/p1526673009000259) to use `setting('main_character_id`) but this results for every user globally the same `main_character_id`
* **Logs / Screenshots / Proof**: 
I did test this on two machines: 1 Windows Docker with vagrant and 1 Mac Docker Dev ...
![seat____github_scripts_docker-compose-dev_seat__-_____vendor_herpaderpaldent_seat-groups_src_resources_views_seatgroups_index_blade_php__seat__und_seat___seat_groups](https://user-images.githubusercontent.com/6583519/40361026-3f5aeff2-5dc8-11e8-97fe-a05700db4608.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by warlof** [comment]
Just mean that the main as not been set?

**Comment by herpaderpaldent** [comment]
unfortunately not. I was tinkering around and found that groups created prior to the admin-link are working but for new groups:
![image](https://user-images.githubusercontent.com/6583519/40385377-af6d3870-5e06-11e8-96d0-feefc8c1a53e.png)
You See in 1 my main: herp which is found in `Group::find(1)`
But for Group_id=4 i don't get an correct response ...

**Comment by herpaderpaldent** [comment]
Seems to be a caching issue ... need @leonjza input why this is happening. After clearing the cache via console group 4 appears. 
* All groups are created via SeAT-UI
* Group Nr.1 differs from others, probably because it is set like this initially. I never changed to the userprofile and 'updated' the main_character_id

**Comment by leonjza** [comment]
Thanks for reporting. I changed the [prefix used](https://github.com/eveseat/services/blob/master/src/Settings/Settings.php#L112) for settings caches to match a group_id instead of the session_id and wonder if I didn't stuff something up there. Will debug.
