### ISSUE TITLE
"Unknown structures (ID)" in Assets tab

### ISSUE THREAD

**Issue by leg0las-devel** [eveseat/seat#337]
Some structures not resolved names and view as "Unknown structures (ID)". Example: https://image.ibb.co/nfEut8/Screenshot_20180523_160438.png

In logs/eseye.log i see:
`[2018-05-23 13:01:09] eseye.ERROR: [http 403, forbidden] get -> https://esi.evetech.net/v1/universe/structures/1027329364798/?datasource=tranquility [t/e: 0.60s/86]`

**Comment by leonjza** [comment]
A known issue as a result of how ESI works atm.
