### ISSUE TITLE
Entity names not being resolved due to a permissions bug on default docker-compose install

### ISSUE THREAD

**Issue by dancodes** [eveseat/seat#338]
* **Problem**: Character, corporation and alliance names are not being updated on the browser from their IDs
* **Expected**: The names being updated
* **Logs / Screenshots / Proof**: Unfortunately I couldn't take a screenshot but `/support/names/resolve` was returning a 500 error due to the lavarel log not being writable.
* **Version Info**: PHP 7.1.17 running the latest images from the scripts/docker-compose-dev folder.

Setting proper recursive permissions to the seat/storage/logs folder fixed this issue.

**Comment by herpaderpaldent** [comment]
This is probably a dublication of #249

Root of this may be the missing writing permission on the logfile for eseye

if you are using apache you need to realize www-data is not able to access the seat if he does not own it or have permission to RL from it
2 solution : 1. set permission to 777 (unsecure) 2. let virtual host run as the user own director (deafult seat)

**Comment by leonjza** [comment]
Hey,

Thanks for reporting this. At first glance this does not look like a code related issue (which are the only ticket types we would like to track here.) Please join us on Slack so that we can help you there in the #support channel.

For Slack invites, please see: https://eveseat.github.io/docs/about/contact/

Please remember to come back and close this issue when you are done :)

**Comment by dancodes** [comment]
I understand that this would normally not be a code issue, but it is a bug of [scripts/docker-compose-dev](https://github.com/eveseat/scripts/tree/master/docker-compose-dev) which should be running chmod on that folder to prevent the issue from happening.

This is only because I believe the docker solution should be an easy "one-click" install of SeaT and I definitely considered this to be a bug in the docker script (not in the seat website itself).

Please let me know what you think and maybe I can make a pull request of my own :)

**Comment by leonjza** [comment]
Think I fixed this in the production docker setups that you can update with https://eveseat.github.io/docs/guides/admin/docker/#performing-updates.

If you are using the dev compose setup, the code volume is mounted outside of the container so you would need to just fix those permissions up.

**Comment by leonjza** [comment]
Should be solved now with the latest docker configurations.
