### ISSUE TITLE
Lock Monthy Values for Mining

### ISSUE THREAD

**Issue by ErickAsmock** [eveseat/seat#341]
Monthly values for previous months mining fluctuate with current 28 New Eden average. Once the month is over they should be locked into something like the monthly average or final day of the month or something near.

Looking at previous months and have the values change relative to current prices isn't something we would expect.

**Comment by leonjza** [comment]
This is an interesting one. We have some market prices that update as time goes by, which obviously reflects as you mention. Will have to consider the options here as technically its possible to say add a column to lock the avg price for that month.

**Comment by kwazulueve** [comment]
This would be useful

**Comment by herpaderpaldent** [comment]
regarding our discussion yesterday. I +1 this request

**Comment by herpaderpaldent** [comment]
this could probably be closed
