### ISSUE TITLE
Character Industry tab does not update correctly

### ISSUE THREAD

**Issue by H4Z4RD-H42** [eveseat/seat#344]
* **Problem**: _Whats wrong?_
One of my industry corp mate told me that the character page "Industry" is not working properly and I wanted to try it myself. Two days ago I started a job to make 10 drones. The next morning the work had been completed, but the page still showed it in "Running" status (blue column), also after a logout/login in SeAT for update the character. Before pressing the "delivery" button on the game, I wanted to wait another 24 hours, until tonight where I could see that the work is always shown in "Running". Nothing is reported in the other tabs. After I pressed "Delivery" on the game and logout/login on SeAT, the work disappeared from the "Running" column and is shown in the "History" column.

* **Expected**: _What did you expect to happen?_
When a job ends, before I press the "Delivery" button inside the game, the job should be shown in the "completed" column (green).

* **Logs / Screenshots / Proof**: _The more information you give the better!_
-- no useful screenshots --

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
SeAT 3.0 beta, PHP 7.2.5-0ubuntu0.18.04.1
![image](https://user-images.githubusercontent.com/6650832/40519084-0e60ece2-5fbe-11e8-8d04-c01e63c59705.png)

I have read that you are not industry player, me neither. You must know, however, that when a job ends, the player must press a button (Delivery) to make sure that the items are delivered in the item hangar. Only at that time the work is considered completed for the game.
I have not tested the "Paused" and "Cancelled" jobs.

**Comment by warlof** [comment]
We're using esi to display information. 

There are high chance that this will turn into an esi issue.

I'll double check that we've no issue on the filters though.

**Comment by warlof** [comment]
@H4Z4RD-H42 do you still have the issue ?

**Comment by warlof** [comment]
request a close due to inactivity

**Comment by H4Z4RD-H42** [comment]
my corp mate that send me this issue is on holiday.
