### ISSUE TITLE
Slack invite request broken?

### ISSUE THREAD

**Issue by KongGal** [eveseat/seat#350]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

https://eveseat-slack.herokuapp.com/

**Comment by leonjza** [comment]
The free dyno hours have been reached it seems. DM me your email address on [twitter](https://twitter.com/leonjza) for now and I'll shoot you an invite manually. This will be "fixed" when the new month starts.

I should probably also remove the slack badge from the projects home page to help reduce usage ;)
