### ISSUE TITLE
Corp asset list timing out

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#352]
* **Problem**:  Asset page partially loading, layout messed up, showing errors
* **Expected**: 
* **Logs / Screenshots / Proof**: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in ...
* **Version Info**: Debian 9, Apache, latest beta

I could extend the execution time, but it would be a bit abritary fix. The main problem I think is trying to list all items at once, which can be a huge page.

In our previous corp management tool ECM the asset listing was grouped per station/location:

![image](https://user-images.githubusercontent.com/25641678/40687884-64aa5cd2-639c-11e8-9749-104cdeed73b0.png)

This would perhaps make the Asset overview page more managable page, especially combined with the search option and filters

**Comment by herpaderpaldent** [comment]
I would need some more details on how `Asset page partially` is loaded. 
Did you alter ther blade? create a screenshot and maybe draw on it or explain via prosa what you would expect.
Include in your report the laravel.log if an error occours. 

From what i understood you alterd something from core and need assistance, for Dev related input you might want to join Slack and ask in #developers channel.

**Comment by kwazulueve** [comment]
Hi
Nothing in the installation codebase was altered. No core code and no blade templates.
The page works for corporations that have few assets, but the corp I am trying to open the page for has roughly 27000 rows in seat.corporation_assets.
The only error showing up in Laravel logs is:

[2018-05-30 08:21:35] local.ERROR: Maximum execution time of 30 seconds exceeded {"userId":395763831,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:311)
[stacktrace]
#0 {main}
"}

![image](https://user-images.githubusercontent.com/25641678/40708379-9db869f4-63f3-11e8-9ab4-4777433a780b.png)
![image](https://user-images.githubusercontent.com/25641678/40708471-d1e271de-63f3-11e8-8aec-d175f5032641.png)

**Comment by leonjza** [comment]
Enough assets can totally destroy the view in way like you have seen. If you can for now, up the limits a tad. I am going to keep this one open so we can remember it needs improvements.

**Comment by kwazulueve** [comment]
This view is not timing out anymore, thanks!
(Have another issue with it now but will file a new ticket for that)
