### ISSUE TITLE
SSO Login with NPC Corp Chars

### ISSUE THREAD

**Issue by kaho88** [eveseat/seat#353]
If a Char with a NPC Corp register to the Auth, the Auth try to get the Informatiom from 11k chars and cause lags and timeout.

A Option to Filter NPC Corps or a "Blacklist" would be awesome.

Seat3

**Comment by leonjza** [comment]
Two quick thoughts. Yes, we are blacklisting NPC corps for data pulls but there is a small logic flaw in it atm making the block fail for public endpoints. Ill fix this soon. The other is that I am surprised than an NPC corp char can pull a memberlist. Are you sure about this?

**Comment by kaho88** [comment]
hmm you are right sorry. A NPC Char caused some server lags. after i deleted the char it was smoother.
But they dont track the Corp things, my failure sorry.
