### ISSUE TITLE
Horizon not returning anything?

### ISSUE THREAD

**Issue by alexedwardh** [eveseat/seat#355]
Trying to look at notifications/errors just returns a HTML page with no content (or rather, a blank SVG embedded). The CSS and JS files resolve fine so no issue there.

Not sure what is causing this as no errors in web console and no errors being logged..

Info:

3.0.0-beta19, Apache, CentOS 7, PHP 7.1.18

**Comment by leonjza** [comment]
Are you serving SeAT from a subdirectory? It would seem like Horizon doesn't like that much, unfortunately. Hopefully we can find a way to solve this soon. For now, serving SeAT from a subdomain should work ok.

**Comment by alexedwardh** [comment]
Thanks for replying. I have a subdomain set up but when redirecting it couldn't find /home. I think this is because I have a site in www/html/ and SeAT is located in www/seat/.

How many configs would I need to change to move SeAT to below www/html/ ?

**Comment by leonjza** [comment]
You should be setting the document root for your domain to the `public/` folder only. Serving the entire SeAT directory will expose your `.env` file which includes your database password, app key and SSO secrets. Examples for [Ubuntu](https://eveseat.github.io/docs/guides/installation/manual_installation/ubuntu/#web-server) and many other distros ca be found in the documentation.
