### ISSUE TITLE
Error /api/documentation

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#356]
* **Problem**: /api/documentation yields an error, see sreenshot below. Couldn't find any other useful information in the logs
* **Expected**: 
* **Logs / Screenshots / Proof**: See below
* **Version Info**: PHP 7.1, Apache, latest SeAT beta installation

![image](https://user-images.githubusercontent.com/25641678/40754799-5dc6643a-647b-11e8-9fa6-7f21703b5fa4.png)
![image](https://user-images.githubusercontent.com/25641678/40754810-70620b3a-647b-11e8-8300-e08201311761.png)

**Comment by leonjza** [comment]
Run `php artisan l5-swagger:generate` to generate the json file. This should be run after every upgrade as API documentation now lives inside the source code as annotations.

Dockerfile [example](https://github.com/eveseat/docker-eveseat-app/blob/a1785049643b154c223651120a8485f4743b7a07/Dockerfile#L20) line.
