### ISSUE TITLE
Backlog Item: Improve `/corporation/view/tracking` view

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#357]
* current: list shows characters and if they are registerd with SeAT
* future: user-groups are grouped by main-character. Everything else should stay as is.

**Comment by leonjza** [comment]
For now I think it should stay as is, but will keep this open for a bit.

**Comment by herpaderpaldent** [comment]
solved by: https://github.com/eveseat/web/commit/3166690a175fa2951931ea5030bb414665efcd46
