### ISSUE TITLE
predefined scheduled job to update sde seems wrong?

### ISSUE THREAD

**Issue by ZarosTenjin** [eveseat/seat#358]
* **Problem**:  The SDE wasnt being updated.so i looked in sheduled tasks inside eveseat and noticed the update sde command doesnt follow the same naming characteristic as the other update commands. Shouldnt it be eve:update:sde instead of eve:update-sde? No manual changes were done on the shedules tasks since install.
* **Expected**: The predfined cron job updates to the newest SDE version automatically
* **Logs / Screenshots / Proof**: 
![image](https://user-images.githubusercontent.com/17838944/40974786-f77c2348-68c8-11e8-9985-c10f77be862f.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
![image](https://user-images.githubusercontent.com/17838944/40974813-11dbfdc6-68c9-11e8-9214-5c089521e3bd.png)

**Comment by leonjza** [comment]
Thanks for reporting this! Indeed you are correct! [This seeder](https://github.com/eveseat/services/blob/fb4f0e1a03107f7a117a30afdc98dd960c09375c/src/database/seeds/ScheduleSeeder.php#L80) has the wrong command configured and can be fixed easily.

**Comment by leonjza** [comment]
Fixed in https://github.com/eveseat/services/commit/2633f6d940caf13d20786bda48e4fffa16189ff7#diff-9b46e3f2cace02ee7b6862de6ab91dcf.
