### ISSUE TITLE
[FR]: Superuser overview of 'own' characters

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#359]
Currently a normal user can see all his registered characters under All Characters
As a superuser however I see all registered characters of everybody

![image](https://user-images.githubusercontent.com/25641678/41008154-c7a80806-6929-11e8-8c70-648891293b3d.png)

It would be nice to have the option as a superuser to simply have a list of his own characters. Adding another menu option with 'My Characters' appears to be the most elegant, and have the additional All Characters only visible for the superuser types

**Comment by warlof** [comment]
Hey,

you can use the switch character top right on your profile.

**Comment by kwazulueve** [comment]
Technically yes you are right there is a group of all my charactes in the top right :D

Knowing which characters I have is not really the issue, though, but a stepping stone for a functional idea (like issue #268), to see some specific overview of your own characters that are very useful for users, like current locations, or present shiptypes, or available slots, or current skill training, etc. Options are really numerous here.

**Comment by mmolitor87** [comment]
I was searching issues because I wanted to suggest just this. Leaving 'All Characters' and 'All Corporations' for superusers and adding a universal 'My Characters' and 'My Corporations' would make the tool more easily usable for superuser accounts.

**Comment by herpaderpaldent** [comment]
@leonjza could be an idea also for combined representation that would overload the Homescreen.
F.e. Mining details of all ownd characters etc .... (could be an idea for  #391 )

**Comment by mmolitor87** [comment]
@herpaderpaldent could also be an idea for #399

**Comment by warlof** [comment]
Closed since it has been implemented.
