### ISSUE TITLE
Bulk API Import Issue

### ISSUE THREAD

**Issue by tripeve** [eveseat/seat#36]
The API import appears to have issue with windows line endings (CR LF) in the .csv file, in order to get it to accept and add the API's i had to convert the .csv file to use Linux line endings (LF). Additionally it fails if there is a blank line at the end of the file.

**Comment by drkthunder02** [comment]
Also when doing a bulk api, the users can no longer assume control of the api unless the person who imported gives them control of the api.  Is there a way to make it to where when someone adds the api to their account, they assume control of the api as what was occurring previously in SeAT beta versions?

**Comment by leonjza** [comment]
@drkthunder02 that does not relate to the CR LF issue. Please file a new ticket for this.

**Comment by leonjza** [comment]
This should be fixed in `eveseat/web` [1.0.19](https://github.com/eveseat/seat/wiki/Web-Changelogs#1019)
