### ISSUE TITLE
[FR]: Single asset overview/search of all characters

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#360]
A great feature suggested by one of my corpmembers would be to have an option to search for an asset in all assets of a group of registered characters (and see subsequently on which character the asset can be found)
And/or have the option for an overview of all assets on all registered characters

**Comment by warlof** [comment]
not doable with the top left searchbar ?

**Comment by kwazulueve** [comment]
Yes you can search with the top left search box, which is real great (Thanks for that!)

There are some issues though that would be nice to consider:
- As a superuser searching is not useful for my own characters (as it searches in all characters). Like the #359 ticket seperating those functionalities seems more useful
- When you search on something like a Rhea you also get all Hammerheads returned, being able to search on a specific item type would be awesome

**Comment by warlof** [comment]
This has been addressed by https://github.com/eveseat/web/commit/86b8dd9aac293009ff9db2ad9460755ab2a47130

You can now search over all characters assets from a groups.
