### ISSUE TITLE
Character Assets Throwing 'Trying to get property of non-object' error.

### ISSUE THREAD

**Issue by space-bits** [eveseat/seat#361]
*  **Problem**: Viewing assets for a character who had assets in a null station as of 5th June 2018 - prior to the migration of null stations to faction citadels - can throw a *Trying to get property of non-object* exception
* **Expected**: Assets of character should be displayed as such:
![Character's assets](https://user-images.githubusercontent.com/11449623/41023202-0ec33fdc-69af-11e8-987a-961082bf3b12.png)

* **Logs & Screenshots**: 
The lines that cause the error from the character assets view blade file:
```
<?php echo e(number_metric($assets->where('location_id', $location->first()->location_id)->map(
    function($value){
        return $value->quantity * $value->type->volume;
    })->sum()
)); ?>
```
Screen shots of the 2 errors:
![Error 2/2](https://user-images.githubusercontent.com/11449623/41022961-65b2aa2c-69ae-11e8-9780-1c9513f10a40.png)

![Error 1/2](https://user-images.githubusercontent.com/11449623/41022963-65f5035e-69ae-11e8-8d87-89eb5ebf6f26.png)

* edited to remove unknown structure issue as described in issue #337 *

* **Version Info**: PHP Version 7.1.17-1, Ubuntu server version: 4.4.0-109-generic, Nginx version: nginx/1.10.3 (Ubuntu)

**Comment by leonjza** [comment]
Hey, could you report the SDE version you have? If its not [sde-20180529-TRANQUILITY](https://github.com/eveseat/resources/blob/master/tools/generate_sde_json.php#L22), update and test again?

**Comment by space-bits** [comment]
Should the file 'generate_sde_json.php' be in `seat/resources/tools/`?

**Comment by leonjza** [comment]
Nah, you just need to run the SDE update command (which is scheduled to run monthly anyways I think) manually if your instance does not have the latest with: `php artisan eve:update:sde`

**Comment by space-bits** [comment]
Ah, cheers. Alright so that updated to the latest SDE by the looks of things, updated 22 tables, and it fixed the issue I was having.
Sorry about opening an issue for that, but thanks - I'm not the one who installed seat on our server so was just trying to trouble shoot.
I'll have to have a better look into the docs.

**Comment by ZarosTenjin** [comment]
also check your scheduled jobs if this bug is present and add the proper update job in this manually to check for the most recent sde https://github.com/eveseat/seat/issues/358
