### ISSUE TITLE
Updating From Installer

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#366]
When running the updater or by doing a manual update, when typing sudo php artisan migrate, I get the following errors:
In Connection.php line 664:
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists (SQL: alter table `mail_
  labels` drop index `mail_labels_label_id_index`)

In PDOStatement.php line 143:
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists

In PDOStatement.php line 141:
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists

Any idea how I can get this fixed?

I also noticed a day or two ago the Mail Timeline button just stopped working.

**Comment by drkthunder02** [comment]
mysql> SELECT * FROM mail_labels;
+--------------+----------+---------------------------+---------+---------------------+---------------------+
| character_id | label_id | name                      | color   | created_at          | updated_at          |
+--------------+----------+---------------------------+---------+---------------------+---------------------+
|     92626011 |        1 | Inbox                     | #00ff33 | 2018-05-12 23:52:21 | 2018-06-11 01:37:43 |
|     92626011 |        2 | Sent                      | #fe0000 | 2018-05-12 23:52:21 | 2018-06-11 01:37:43

Sample from the database table called mail_labels when I do a SELECT * FROM mail_labels;

**Comment by leonjza** [comment]
Something broke with the upgrades in the beta, sorry about that. You can manually create the `mail_labels_label_id_index` index on the `mail_ labels` table and run the migration.

**Comment by drkthunder02** [comment]
What properties should the column have?

**Comment by drkthunder02** [comment]
Added mail_labels_label_id_index as int(11) and indexed the row.  Ran php artisan migrate and the following errors were produced.

In Connection.php line 664:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1246
  493499-1' for key 'PRIMARY' (SQL: alter table `mail_labels` add primary key
   `mail_labels_character_id_label_id_primary`(`character_id`, `label_id`))


In PDOStatement.php line 143:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1246
  493499-1' for key 'PRIMARY'


In PDOStatement.php line 141:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1246
  493499-1' for key 'PRIMARY'

**Comment by warlof** [comment]
what's the state of this issue on a fresh install ?!

**Comment by drkthunder02** [comment]
Do I need to do a fresh install from the beta to get over this issue?

**Comment by leonjza** [comment]
If you can do a fresh install absolutely do that. 👍

**Comment by drkthunder02** [comment]
Well if you do php artisan migrate:fresh then it drops all the table data and does the migration correctly.  It's almost as bad as a fresh install.  The problem is then I lose all the tokens and all the information already stored.  Is there some way to mark a migration as done and just skip it?

**Comment by warlof** [comment]
No no

**Comment by leonjza** [comment]
Please join us on slack for further support on this.
