### ISSUE TITLE
database migration errors

### ISSUE THREAD

**Issue by BrownStar** [eveseat/seat#369]
sudo -H -u www-data bash -c 'php /var/www/seat/artisan migrate'
Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_name_unique`(`name`))

In PDOStatement.php line 143:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

In PDOStatement.php line 141:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by leonjza** [comment]
This almost always means you do not have the minimum database version requirement met. Have look at the documentation: https://eveseat.github.io/docs/general/requirements/#software-requirements
