### ISSUE TITLE
Corporate tax rate not being updated via a full API Key

### ISSUE THREAD

**Issue by molten360** [eveseat/seat#37]
Corp tax rate says 0% even though it is set to 15%. Verified its a full key, and updated the api.

**Comment by leonjza** [comment]
Oops. Looks like I forgot to add `taxRate` to the CorpSheet updater. :P Will add it shortly.

**Comment by leonjza** [comment]
Upgrading the `eveseat/eveapi` package to [v1.0.8](https://github.com/eveseat/seat/wiki/Eveapi-Changelogs#108) should fix the problem.
