### ISSUE TITLE
User Management: Columnsize of subtable bugged

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#371]
* **Problem**: all column sizes in subcolumn containing group-characters have various sizes. 
* **Expected**: have same width in columns
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/41395970-d7b86d6c-6faf-11e8-8751-015036a93abc.png)

* **Version Info**:   SDE Version sde-20180529-TRANQUILITY | Web Version 3.0.0-beta21 Copyright © 2018 | SeAT

**Comment by leg0las-devel** [comment]
Confirm it problem - after yesterday update
https://image.ibb.co/kB5haJ/Screenshot_20180614_155616.png

**Comment by leonjza** [comment]
Fixed in web/3.0.0-beta22
