### ISSUE TITLE
seat 3.0 stable tag Corp Starbases not working

### ISSUE THREAD

**Issue by ysm1mh** [eveseat/seat#373]
so after i update seat to the latest 3.0 stable tag the corp starbases arent working. before the update it did.

i recieve the following error retrieving the Corp starbases.
see the screenshot for more info on the error.

http://prntscr.com/jvrrdb

please let me know what info you need more from me.

 Api           | 3.0.0         | 3.0.0         |
| Console       | 3.0.0         | 3.0.0         |
| Eveapi        | 3.0.0         | 3.0.0         |
| Notifications | 3.0.0         | 3.0.0         |
| Web           | 3.0.0         | 3.0.0         |
| Services      | 3.0.0         | 3.0.0

**Comment by leonjza** [comment]
Fixed in https://github.com/eveseat/web/commit/ec4f25716759c744c6e794fc4348ca2c6062fe16.
