### ISSUE TITLE
Corp-Tracking location

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#374]
* **Problem**: Corp-Tracking location is not resolving
* **Expected**: instead of having an ID, show location name
* **Logs / Screenshots / Proof**: 
![image](https://user-images.githubusercontent.com/6583519/41506533-04527512-7220-11e8-9157-fbb5385d24dc.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by herpaderpaldent** [comment]
I tried to get my hands dirty with the id to name resolver but i failed with the locations in Member tracking. 
Seems it is connected to our issue not being able to resolve locations in universe structure endpoint for which we dont have access rights anymore. 
Would it be an idea to drop the location then? I see we have done this with the profile partial?

Or could we use a location table?

**Comment by herpaderpaldent** [comment]
How about we try to resolve any location ID with only Director-Role Refreshtoken first? As part of the /universe/structure solution?

**Comment by warlof** [comment]
does it have to be close ?
I don't have location column on corporation tracking tab

**Comment by herpaderpaldent** [comment]
You could close this, but create a new story for reenabling the corp-location tracking. This is currently disabled due to the structure issues.

**Comment by herpaderpaldent** [comment]
as discussed with @warlof i close this story
