### ISSUE TITLE
Ability to create Account with Simple Scopes

### ISSUE THREAD

**Issue by KingVoodoo** [eveseat/seat#376]
Need SeAT to allow members to login to use modules based solely on corporate affiliation and not ask for all scopes wide open. Add character on one one developer application and login thru another using public/limited scopes. Have a direct need for this. Pre 3.0 this was possible. Scopes too much for people wanting to see operations board or register for discord/teamspeak thru the great community packages availble but needed for managing corp members. I am sure this is wishlist but if this can be worked in this would be great. Having this will allow people to drill down their SeAT instance to become an active services website from a straight compliance audit.

**Comment by leonjza** [comment]
I find it hard to grok entirely what you are asking here, but nonetheless going to back burner this for 3.1.

**Comment by Fundaris** [comment]
Since its corp affli based 
Try this plugin
https://github.com/herpaderpaldent/seat-groups

you can setup there auto groups based on affilation like corp/alliance

**Comment by warlof** [comment]
Merging into eveseat/seat#382 which is a little bit larger in the user request but lead to the same changes.
