### ISSUE TITLE
Don't show que notifications without QueueManager Permission

### ISSUE THREAD

**Issue by aaronmallen** [eveseat/seat#377]
* **Problem**: Users without the `QueueManager` permission can see queue icons in the top nav
* **Expected**: Users without the `QueueManager` permission should not be able to see queue icons in top nav
* **Version Info**: PHP 7.1.18-1+ubuntu18.04.1+deb.sury.org+1, SeAT Version: v3.0.0, Digitalocean droplet Ubuntu 18.04

**Comment by leonjza** [comment]
Current having the queue icons with counts is shown for everyone by design. This is to indicate current system load and I do not believe it gives away any information.

**Comment by aaronmallen** [comment]
I'm not super concerned with security here as I am with the user experience... I don't believe the typical user will understand or find the notification useful, and the fact that it can't be clicked through makes it all the more confusing IMO.

**Comment by leonjza** [comment]
Thanks for the feedback! Going to keep it as is for now.
