### ISSUE TITLE
Potential Bug: Structures and Pocos Table empty

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#378]
* **Problem**: Poco and Strucutre views are empty eventhough they should contain data:

![image](https://user-images.githubusercontent.com/6583519/41809495-db003324-76ee-11e8-93da-8f4424a9d3a9.png)

* **Expected**: See name, location, remaining fuel etc
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: SeAT 3.0.1

Not sure if really a bug but i am parking this here.

**Comment by leonjza** [comment]
Please debug this further? (Access, tokens, etc.) I have correct data for both so I do not think there is a bug.

**Comment by herpaderpaldent** [comment]
will do. i own ceo of a corp with a fortizar and don't see data ... and got no errors in the horizon log. so that is why i submit this

**Comment by herpaderpaldent** [comment]
Today i did `docker-compose pull && docker-compose up -d` and all data are shown again. Weird but not reproducable
