### ISSUE TITLE
[Feature Request] Corporation Moon Mining Ledger

### ISSUE THREAD

**Issue by paintballlaws** [eveseat/seat#379]
Feature Request:

A way to pull the corp mining ledger?

**Comment by leonjza** [comment]
Browse to a corporation and select the mining menu item?

**Comment by paintballlaws** [comment]
Lol that is not the corporation mining ledger that is a list of everyone in your corporation’s and there mining ledger.

**Comment by herpaderpaldent** [comment]
Are you @paintballlaws asking for Corporation **moon** mining ledger?

**Comment by paintballlaws** [comment]
Yes sorry for not being specific.
