### ISSUE TITLE
Queue Jobs

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#38]
When a user who does not have the permission queue manager, they can see the buttons for queued jobs, working jobs, and error jobs.  If the user then pushes the buttons they get an unathorized error message.  I think it would be more useful to hide these buttons if the user does not have the correct permission set to view what is contained in the page the buttons link to.

**Comment by drkthunder02** [comment]
How is this a wishlist item, when thats how it worked in the 0.x version of SeAT?

**Comment by Cynabal** [comment]
Because this is a completely new SeAT from scratch .

**Comment by drkthunder02** [comment]
Yes, but it seems something that should be so simple could be easily fixed.  If you send me how do I find the html from the Controllers for these buttons, then I will write the programming myself.  But since, I am not good with Laravel, I don't know where these buttons are handled in the vendor packages, therefore, I can't find the buttons to hide them from users who don't have the correct permissions.

**Comment by warlof** [comment]
I'll take it

**Comment by leonjza** [comment]
Leave the queue numbers. Just remove the `<a>` tags if the `queue` permission is missing.

**Comment by leonjza** [comment]
Should be fixed in `eveseat/web` [1.0.19](https://github.com/eveseat/seat/wiki/Web-Changelogs#1019)
