### ISSUE TITLE
Mining Ledger - DataTable 2 does not respect unit definition

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#381]
* **Problem**: Mining Ledger does not respect settings for unit representation:
* **Expected**: respect settings
* **Logs / Screenshots / Proof**: 
<img width="1077" alt="grafik" src="https://user-images.githubusercontent.com/6583519/41850057-89ab5224-7883-11e8-9fff-07670d840f53.png">
<img width="546" alt="grafik" src="https://user-images.githubusercontent.com/6583519/41850073-93aebc20-7883-11e8-8353-c9dc612a6f3e.png">

* **Version Info**: SeAT 3.0.2

**Comment by warlof** [comment]
unsure it's even use in most of layouts. Should take a break and dig into all of them :/
