### ISSUE TITLE
Allow user to select granted scopes

### ISSUE THREAD

**Issue by aaronmallen** [eveseat/seat#382]
I would like to see the auth flow tweaked a bit.  I would like a user to be able to login in with JUST publicData scope and then have a settings window with checkboxes for the permissions they are willing to allow, of course when they update their scopes they'll have to go back through the EVE SSO flow but this is ok.  For this to work tho there would need to be a window letting people with the appropriate roles (i.e. Leadership) see which scopes the character has enabled.  This way we could have people who we assign a "Friend" role have access to some of our public-ish services without having to feed us all of their intel.

**Comment by herpaderpaldent** [comment]
I'd argue against this feature. I see already how it can be misused: f.e. Some members dont want to share their mails, directors dont want to share their super and titans etc...
My solution: ask your friends to use an alpha.

**Comment by aaronmallen** [comment]
@herpaderpaldent thats a bit of a shitty user experience IMO.  I can't find it right this second but theres an Eve Mail web client out there that has a similar flow... As long as leadership is able to see what scopes the user has enabled this should work just fine.

**Comment by aaronmallen** [comment]
what about scoped links... like you could have a "buddy" link for friends that links to the seat Auth page but will only auth with publicData scopes, and you could have a link for Alliance members that will ask for full API access. Then its just a matter of sharing the right SeAT link with the right people, just like the old XML Api accessMasks feature.

**Comment by leonjza** [comment]
Tagging this for 3.1 with the ACL rework.

**Comment by warlof** [comment]
It will be a doable thing with v4.
The option will be left to the instance owner though - who will be able to define list of scope and provide authentication routes to use them.

**Comment by FloydianSound** [comment]
+1

my ally is really invasive with scopes, id like to select which ones i would rather not share.
i'll deal with the PR later :D
