### ISSUE TITLE
Seat 3.0 setup fails using SeAT Tools

### ISSUE THREAD

**Issue by op6sie** [eveseat/seat#386]
While running :

```bash
bash <(curl -fsSL https://git.io/seat-installer)
seat install:production
```

i get this error : 

```
> @php artisan key:generate
Application key [base64:9mZ7XkmQtplq2g2zMhKxQFwBPZPNbQeHTFvIS7S6ZbQ=] set successfully.


 [OK] SeAT Downloaded OK


 Running command: /usr/bin/php /var/www/seat/artisan vendor:publish --force --all
SeAT Setup Command> Copied File [/vendor/laravel/horizon/config/horizon.php] To [/config/horizon.php]SeAT Setup Command> Copied Directory [/vendor/laravel/horizon/public] To [/public/vendor/horizon]SeAT Setup Command> Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]SeAT Setup Command> Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]SeAT Setup Command> Copied File [/vendor/darkaonline/l5-swagger/config/l5-swagger.php] To [/config/l5-swagger.php]SeAT Setup Command> Copied Directory [/vendor/darkaonline/l5-swagger/resources/views] To [/resources/views/vendor/l5-swagger]SeAT Setup Command> Copied Directory [/vendor/eveseat/api/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied Directory [/vendor/eveseat/eveapi/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied Directory [/vendor/eveseat/notifications/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied Directory [/vendor/eveseat/services/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied File [/vendor/maatwebsite/excel/src/config/excel.php] To [/config/excel.php]SeAT Setup Command> Copied File [/vendor/yajra/laravel-datatables-oracle/src/config/config.php] To [/config/datatables.php]SeAT Setup Command> Copied File [/vendor/yajra/laravel-datatables-oracle/src/resources/assets/buttons.server-side.js] To [/public/vendor/datatables/buttons.server-side.js]SeAT Setup Command> Copied Directory [/vendor/yajra/laravel-datatables-oracle/src/resources/views] To [/resources/views/vendor/datatables]SeAT Setup Command> Copied Directory [/vendor/eveseat/web/src/resources/assets] To [/public/web]SeAT Setup Command> Copied Directory [/vendor/eveseat/web/src/database/migrations] To [/database/migrations]SeAT Setup Command> Copied File [/vendor/components/font-awesome/css/font-awesome.min.css] To [/public/web/css/font-awesome.min.css]SeAT Setup Command> Copied Directory [/vendor/components/font-awesome/fonts] To [/public/web/fonts]SeAT Setup Command> Copied File [/vendor/fideloper/proxy/config/trustedproxy.php] To [/config/trustedproxy.php]SeAT Setup Command> Copied Directory [/vendor/laravel/framework/src/Illuminate/Mail/resources/views] To [/resources/views/vendor/mail]SeAT Setup Command> Copied File [/vendor/laravel/tinker/config/tinker.php] To [/config/tinker.php]SeAT Setup Command> Publishing complete.
 Running command: /usr/bin/php /var/www/seat/artisan migrate
SeAT Setup Command> Migration table created successfully.
SeAT Setup Command> In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_name_unique`(`name`))SeAT Setup Command> SeAT Setup Command> In PDOStatement.php line 143:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytesSeAT Setup Command> SeAT Setup Command> In PDOStatement.php line 141:SeAT Setup Command> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

  [Seat\Installer\Exceptions\ArtisanCommandFailed]
  Setup failed.


install:production [-s|--seat-destination [SEAT-DESTINATION]] [--minimum-stability [MINIMUM-STABILITY]]

root@owncloud:~#
```

* **Problem**:  while running seat install:production as root!!
                         i get above error.
* **Expected**: a setup completing without error
* **Logs / Screenshots / Proof**: i can repeat this for a screen shot but above text is all there is.
* **Version Info**: 
Linux owncloud 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Server version: 10.0.34-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

PHP 7.1.18-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 11 2018 14:22:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

database schema created in an existing schema as instructed with the installer.

**Comment by leonjza** [comment]
SeAT needs MariaDB 10.2.7 or newer. I am not sure why the installer didn't help you get the latest MariaDB on Ubuntu 16.04 to be honest.

**Comment by leonjza** [comment]
Now that I think about it, we may have to add the mariadb repositories in the bootstrap script like we do for the [debian install](https://github.com/eveseat/scripts/blob/master/install/debian-9-x.sh#L24-L26).

**Comment by op6sie** [comment]
when running apt install it will not find mariadb 10.2.7 or newer for ubuntu 16.04.4
how do i proceed?

**Comment by warlof** [comment]
Add mariadb repository `curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash`

**Comment by op6sie** [comment]
root@owncloud:~# curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
[info] Repository file successfully written to /etc/apt/sources.list.d/mariadb.list
[info] Adding trusted package signing keys...
Executing: /tmp/tmp.9au8NHNN0h/gpg.1.sh --keyserver
....
....
....

root@owncloud:/var/www# mysql --version
mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
root@owncloud:/var/www#

is the result of the repository. the error remains the same.

my mysql is a bit rusty but this is the shown statement : 
alter table `users` add unique `users_name_unique`(`name`))
and the error on that is  1071 Specified key was too long; max key length is 767 bytes
when i look at the table users then varchar(255) (field name)  can not hold 767 bytes.

Kind regards Tonny

**Comment by warlof** [comment]
You still have to upgrade your mariaDB installation...

Check for `mariadb-server-10.2 package`
Or perhaps even `apt-get full-upgrade` will bump it for you.

**Comment by op6sie** [comment]
after executing : 
ALTER TABLE `seat`.`users` CHANGE COLUMN `name` `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL ;
it works.
does the name field need to be 255 chars long?

taken from : 
767 bytes is the stated prefix limitation for InnoDB tables in MySQL version 5.6 (and prior versions). It's 1,000 bytes long for MyISAM tables. In MySQL version 5.7 and upwards this limit has been increased to 3072 bytes.

You also have to be aware that if you set an index on a big char or varchar field which is utf8mb4 encoded, you have to divide the max index prefix length of 767 bytes (or 3072 bytes) by 4 resulting in 191. This is because the maximum length of a utf8mb4 character is four bytes. For a utf8 character it would be three bytes resulting in max index prefix length of 254.

source : https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by warlof** [comment]
Short answer : do as you which as longer as you don't want to meet requirements.
They are clearly listed here : https://eveseat.github.io/docs/installation/requirements/

**Comment by leonjza** [comment]
While that may solve your immediate problem, not upgrading to the recommended version will leave you with other issues when we make use of them in SeAT. The only accepted answer here is to upgrade to the recommended version. Please can we take this discussion to Slack if you require any further assistance.

Leaving this open for me to check the installer for ubuntu 16.04 though.

**Comment by op6sie** [comment]
it appears i need an invite to join https://eve-seat.slack.com/

**Comment by warlof** [comment]
SeAT Tools is discontinued.

We now ship SeAT using Docker for "user friendly" and "automatized" deployment.
Alternatively, bare metal deployment is still valid and can be used as an alternative of SeAT tools.
