### ISSUE TITLE
Having contact affiliation on character/corporation contacts

### ISSUE THREAD

**Issue by Philekunf** [eveseat/seat#387]
Currently the contacts page lists contact with Name, Type, Standing, Label & a few links.

It would be crucial for recruitement purposes to be able to easily see the corp & alliance affiliation of contacts directly in that list rather than clicking each contact's zkill button.

**Comment by warlof** [comment]
@Philekunf you can use intel feature to do so.
Just design a standing pattern and apply it in intel section of the character.

**Comment by Philekunf** [comment]
Im testing the intel tool for standings right now, and it doesnt fit our needs.

The standings profile requires you to preset entities with bad standings, but what about entities that arent black or white...
We dont want to know what we are looking for, we want to know whats there and analyse it.

**Comment by herpaderpaldent** [comment]
Would it be useful to extend this table with a view as we are using it in kill mails? 

![image](https://user-images.githubusercontent.com/6583519/49879054-6a940580-fe29-11e8-9be3-5608e55bebba.png)

With me recent contribution to name resolver, seat will eventually resolve affiliations (whenever the public job runs).

**Comment by warlof** [comment]
Will be shipped together with SeAT 4 ;)
