### ISSUE TITLE
SeAT Roles not working

### ISSUE THREAD

**Issue by gbrann** [eveseat/seat#388]
* **Problem**:  Roles are not working after being setup in Access Management with List rights enabled
* **Expected**: Officers with all character and corp roles should be able see other members and corps and pull the data. 
* **Logs / Screenshots / Proof**: 
https://imgur.com/3zPEyUn - shows after impersonating a member of Officer, no access to other corps save thier own.

https://imgur.com/pu4Wi74 - shows after impersonating a member of Officer, no access to see other members, as they should.

https://imgur.com/Knb4xPZ - Officer is setup to have all roles, except API roles, QueueManager, and Superuser.

* **Version Info**:  Docker Install of Seat 3.02 - SDE Version sde-20180529-TRANQUILITY | Web Version 3.0.2 Copyright © 2018 | SeAT

**Comment by herpaderpaldent** [comment]
Right column on roles edit is empty. This is your issue. 
http://imgur.com/R1k40TX

**Comment by gbrann** [comment]
It says groups. When I clicked this earlier it was empty save admin. Now
it's soon toons not groups.

**Comment by gbrann** [comment]
Also. Btw. In your example in the docs. That side said Users and was blank.
Wasn't even mentioned in the doc.
