### ISSUE TITLE
Assume Control of API

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#39]
Also when doing a bulk api, the users can no longer assume control of the api unless the person who imported gives them control of the api. Is there a way to make it to where when someone adds the api to their account, they assume control of the api as what was occurring previously in SeAT beta versions?

**Comment by leonjza** [comment]
I am assuming you are talking about CSV imports. The admin that imported the APIs via CSV own the keys. There is no way to know which SeAT user owns said key by a keyID. There has also never been a version that supports mass importing keys either (except via the SeAT API). If you mass imported keys, you have to transfer the ownership via the keys details to a SeAT user.

When you add an API key using the normal API Key Management, then the person that added the key also owns it.

**Comment by drkthunder02** [comment]
I just remember putting in api's by hand on the old version, and then when a user logged on with the same api key by putting it onto his profile, the user being able to assume control of the api.  There was no transfer ability back on 0.x version of SeAT.

**Comment by leonjza** [comment]
Ah yes. We can add the automatic ownership change when adding a key.
