### ISSUE TITLE
[Feature Request] Helm chart for Kubernetes Deployment

### ISSUE THREAD

**Issue by tarioch** [eveseat/seat#390]
I'm currently working on creating a helm chart which should allow easy deployment of seat into an Kubernetes Cluster.

**Comment by leonjza** [comment]
Thanks for this! I am going to assign you to the ticket and mark this as wishlist :)

**Comment by tarioch** [comment]
A first version is available here:

https://github.com/tarioch/helm/tree/master/charts/eveseat

I'm still working on testing it and improving some things before I would consider it "stable"

**Comment by tarioch** [comment]
Chart is now used for more than a week and runs fine,
created PR for the documentation
https://github.com/eveseat/docs/pull/72
