### ISSUE TITLE
[Feature Request] aggregate to main character /corporation/view/mining-ledger/ 

### ISSUE THREAD

**Issue by brown-star** [eveseat/seat#391]
This view works and pulls all miner actors in, I was just hoping that we could aggregate to the owner of the group instead of character level only.

**Comment by herpaderpaldent** [comment]
Hey @brown-star,
Would it be helpful if you'd have an additional column with the characters group/main in it? With this you could sort by main-character and aggregate them together?

**Comment by brown-star** [comment]
That would be helpful
