### ISSUE TITLE
main_character_id stored with double quotes when user initially registers, but without quotes when updated via profile

### ISSUE THREAD

**Issue by cryocaustik** [eveseat/seat#395]
* **Problem**: when user initially registers, their `main_character_id` in seat.user_settings is stored with double quotes, but when changing the main character via user profile, the value is stored without any quotes
* **Expected**: should always be stored without quotes
* **Logs / Screenshots / Proof**: ![screenshot](https://i.imgur.com/Q49jh1m.png)
* **Version Info**: web 3.0.1

**Comment by leonjza** [comment]
I suspect this was only a thing during the beta phase. Could you double check that newer entries dont do this anymore?

**Comment by warlof** [comment]
I confirm that's working as expected with last build.

**Comment by cryocaustik** [comment]
I will register a new character tonight and see if the issue persists
