### ISSUE TITLE
Add timers in Industry tab

### ISSUE THREAD

**Issue by H4Z4RD-H42** [eveseat/seat#398]
PI tab have it, why Industry tab not have it? It can be added? It would be very useful.

Something like this:
![image](https://user-images.githubusercontent.com/6650832/42320680-74f90a44-8056-11e8-97bc-3f853cdcf608.png)

**Comment by warlof** [comment]
Hum... Perhaps because we never think about it or the screen is already full 😐

But that's something we can work on.

**Comment by benthompson0** [comment]
@warlof please assign to me and close. thanks :)

**Comment by warlof** [comment]
Seems I miss that one.
However, it's already merged :D
