### ISSUE TITLE
I can't log in anymore. 

### ISSUE THREAD

**Issue by charafim** [eveseat/seat#399]
I have two characters that relapsed to Alpha state.  I didn't pay attention to that but I think the problem started when it happened.  They were both linked. Other characters weren't affected. 

I logged in as admin and deleted both charters, still didn't work.
I delete the characters from table users and the login worked again. 

The errors on the logs showed this 

[2018-07-08 15:23:13] local.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /var/www/seat/vendor/eveseat/services/src/Settings/Settings.php:147)

**Comment by H4Z4RD-H42** [comment]
same here https://eve-seat.slack.com/archives/C0H2VM324/p1530536487000189

**Comment by warlof** [comment]
should be fixed with #eveseat/web#195

**Comment by leonjza** [comment]
Fixed in latest web package.
