### ISSUE TITLE
Character Industry Error

### ISSUE THREAD

**Issue by JackONeill12** [eveseat/seat#4]
When I try to open the Industry Tab on an Character it shows me the following error.

http://pastebin.com/GeRk4jNB

**Comment by leonjza** [comment]
Fixed with https://github.com/eveseat/resources/commit/505db04f56a40d20902a5c89deda4d806494f4db

**Comment by JackONeill12** [comment]
Would be cool if you can bump the version number of resources so this gets implemented.

**Comment by leonjza** [comment]
Resources don't need a version bump. Just re-run the sde updater and you should get the new table imported.

**Comment by JackONeill12** [comment]
With SDE updater do you mean the one line update script. If so that doesnt fix it.

**Comment by leonjza** [comment]
I mean `php artisan eve:update-sde`. Its should also be part of the scheduler to run monthly.

**Comment by JackONeill12** [comment]
Now it works. Thanks a lot for the help.
