### ISSUE TITLE
Modifying Standing Definitions by unprivileged user

### ISSUE THREAD

**Issue by MoucceuWildfire** [eveseat/seat#401]
* **Problem**: Unprivileged users can modify Standings definitions in Standing Builder
* **Expected**: Only superuser should be granted to modify standings
* **Logs / Screenshots / Proof**: 
![img-2018-07-14-12-53-31](https://user-images.githubusercontent.com/39436031/42723387-69c5fc84-8765-11e8-92a9-104c7fc69856.png)
![img-2018-07-14-12-52-16](https://user-images.githubusercontent.com/39436031/42723389-6fbab972-8765-11e8-8b7f-51f0d59402d3.png)

* **Version Info**: 
![img-2018-07-14-12-54-22](https://user-images.githubusercontent.com/39436031/42723395-7533103e-8765-11e8-9288-a108b3d29a5b.png)

**Comment by leonjza** [comment]
This is something we will address in 3.1 with the ACL revamp.
