### ISSUE TITLE
error count

### ISSUE THREAD

**Issue by rafaelfariasbsb** [eveseat/seat#402]
I don´t know it is was suppose to show the error, but it would be nice if could click and show the errors. Check it the attachment file
![error](https://user-images.githubusercontent.com/4338815/42732923-7445bd48-8800-11e8-8cf4-1261be240d37.png)

**Comment by warlof** [comment]
@rafaelfariasbsb you need to have either `superuser` or `queue manager` permission to be able to access the job board.

**Comment by rafaelfariasbsb** [comment]
I got it Thanks!!!
