### ISSUE TITLE
Issue Editing Notification Groups

### ISSUE THREAD

**Issue by colcrunch** [eveseat/seat#404]
* **Problem**: Error encountered when attempting to edit notification group.
* **Expected**: To get taken to an edit page.
* **Logs / Screenshots / Proof**:  https://pastebin.com/X1XCPp2m
* **Version Info**: PHP 7.1, Seat 3.0, Ubuntu 16.04

**Comment by warlof** [comment]
What was the group type ?

**Comment by colcrunch** [comment]
Eve

**Comment by warlof** [comment]
will be fixed during next iteration : https://github.com/eveseat/notifications/pull/13

**Comment by leonjza** [comment]
Will de available in the next notifications package version later today.
