### ISSUE TITLE
SeAT backup/restore issue

### ISSUE THREAD

**Issue by MoucceuWildfire** [eveseat/seat#406]
* **Problem**: When you try to back up a database by using the command described in the documentation, the problem occurs. The command hangs without response. A backup file is created that is about 3 megabytes in size and stops increasing. After you become explicit that the file is not incremented, you can press ENTER and the command will abort, but the backup file is defective. 
During the discussion with other users I was asked to increase the timings in the database settings, but that did not work for me as for the author of the method. The next suggestion was to back up the outside of the Docker. To do this was installed MariaDB outside Docker and the instruction to create a backup look like this.

```
wildstrawberry [10:05 PM]
1. docker network ls
2. get network id of "seat-docker_seat-network
3. docker network inspect [id from 2.]
4. check IP for seat-mariadb container 
5. mysqldump -u seat -p"password from .env" seat -h [ip from 4.]  > dumpfile.sql
```

This method works fine for me, but it requires additional steps that you would like to avoid. 

Finally i found the instruction on the www how to back up the outside Docker a simpler method, in the adapted to the SeAT option the command looks like this:
`
docker exec seat-mariadb /usr/bin/mysqldump -u seat -p"my_psswd_from_.env" seat > backup.sql
`
where my_psswd_from_.env to be different for each instance of SeAT ofc
there is a command to restore from backup
`cat backup.sql | docker exec -i seat-mariadb /usr/bin/mysql -u seat -p"my_psswd_from_.env" seat`

* **Expected**: I just want to have abilitiy to keep my DB safe :)
* **Logs / Screenshots / Proof**: 
* **Version Info**: SeAT is DOCKER version,  SeAT Version 3,0+(3.0.1 -> 3.0.4) , Operating System Ubuntu server x64, server specs AMD Phenom x2 3,2 GHz, 8 GB RAM, SSD. I encounter issue on fresh installation of OS and SeAT and it still persist.

**Comment by leonjza** [comment]
> Finally i found the instruction on the www how to back up the outside Docker a simpler method, in the adapted to the SeAT option the command looks like this:
> docker exec seat-mariadb /usr/bin/mysqldump -u seat -p"my_psswd_from_.env" seat > backup.sql

So the documentation at the moment does the backup invoked via `docker-compose` in basically the [same](https://eveseat.github.io/docs/admin_guides/docker_admin/#database-backups-and-restore) way, picking up creds from the ENV and piping it through `gzip` for compression.

```
docker-compose exec mariadb sh -c 'exec mysqldump "$MYSQL_DATABASE" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' | gzip > seat_backup.sql.gz
```

> there is a command to restore from backup
> cat backup.sql | docker exec -i seat-mariadb /usr/bin/mysql -u seat -p"my_psswd_from_.env" seat

Restores are also (similar)[https://eveseat.github.io/docs/admin_guides/docker_admin/#database-backups-and-restore] in that we `gzcat` the SQL file to decompress and pipe it back to MySQL/MariaDB:

```
zcat seat_backup.sql.gz | docker-compose exec -T mariadb sh -c 'exec mysql "$MYSQL_DATABASE" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"'
```

I am confused by what your commands are actually doing different to be honest. Regardless, there is [this](https://github.com/eveseat/scripts/pull/22) PR that may help with some of the future issues.
