### ISSUE TITLE
Proposal:  Roles and Affiliations

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#41]
A short wiki article on what the roles and affiliations mean might help more users understand what is going on.  I don't exactly know what affiliations mean in the Access Management page, and I may not be the only one who is scratching my head on what the affiliations actually do.

**Comment by leonjza** [comment]
The current [TODO list](https://github.com/eveseat/seat/wiki/Todo-List#the-list) has this an something that needs to be documented.

**Comment by l0ser140** [comment]
Just a question. Sry for bump closed issue, but i really not want create new one for this.
Is it okay, what users not affiliated to their corp automatically based on their characters?
Should I create separated group for directors/members of every corp with affiliation to that corp or my installation broken?

**Comment by leonjza** [comment]
@l0ser140 could you come on Slack to make this discussion easier?
