### ISSUE TITLE
SQLstate 42S22

### ISSUE THREAD

**Issue by Flugschreipbaer** [eveseat/seat#412]
![seat problem 2--3](https://user-images.githubusercontent.com/8029440/43356435-f4d93532-9270-11e8-922b-c066ba1d4da7.PNG)
Hey guys,

I wanted to migrate from seat 2 to seat 3.

While trying to migrate I ran into the following problem:

`...Please be patient - the process can take a long time depending on the records amount in your database.

  [Illuminate\Database\QueryException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'upgraded' in 'where clause' (SQL: select count(*) as aggregate from `kill_mail_details` where `upgraded` = 0)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'upgraded' in 'where clause'

  [PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'upgraded' in 'where clause'

`

Does anybody else have this problem?

MariaDB 10.3.8
PHP 7.2

I tried the Update on a clean install (secondary machine) or on the same machine.

On the same machine while running 
`composer create-project eveseat/seat --no-dev`
It would only install seat 2.0.0  don't know why, but I just installed on a different machine.

**Comment by warlof** [comment]
Hi,

you have to run migration scripts. Should be part of the doc.
https://eveseat.github.io/docs/upgrading/from_seat_2_0/
https://github.com/warlof/seat-migrator

**Comment by Flugschreipbaer** [comment]
Hi, 
I did run the scripts as seen in the docs.

Thats why I am posting this as an issue.

**Comment by warlof** [comment]
go on your SeAT 2.x installation directory and run the two following commands :

```
php artisan vendor:publish --force
php artisan migrate
```

and paste the output here

**Comment by Flugschreipbaer** [comment]
First

`Copied Directory [/vendor/warlof/eveseat-mining-ledger/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/warlof/seat-migrator/src/Database/migrations] To [/database/migrations]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Copied Directory [/vendor/eveseat/api/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/eveapi/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/notifications/src/database/migrations] To [/database/migrations]
Copied Directory [/vendor/eveseat/services/src/database/migrations] To [/database/migrations]
Copied File [/vendor/maatwebsite/excel/src/config/excel.php] To [/config/excel.php]
Copied File [/vendor/yajra/laravel-datatables-oracle/src/config/config.php] To [/config/datatables.php]
Copied File [/vendor/yajra/laravel-datatables-oracle/src/resources/assets/buttons.server-side.js] To [/public/vendor/datatables/buttons.server-side.js]
Copied Directory [/vendor/yajra/laravel-datatables-oracle/src/resources/views] To [/resources/views/vendor/datatables]
Copied Directory [/vendor/eveseat/web/src/resources/assets] To [/public/web]
Copied Directory [/vendor/eveseat/web/src/database/migrations] To [/database/migrations]
Copied File [/vendor/components/font-awesome/css/font-awesome.min.css] To [/public/web/css/font-awesome.min.css]
Copied Directory [/vendor/components/font-awesome/fonts] To [/public/web/fonts]
Publishing complete for tag []!
`
Second:
`Preparing CapBluePrint for upgrade...
Preparing CapBluePrintNames for upgrade...
Preparing CapConBlueNames for upgrade...
Preparing CapConBluePrint for upgrade...
Preparing CorpSteuer for upgrade...
Preparing Ice for upgrade...
Preparing MineralPreise for upgrade...
Preparing Mineral_Eingang for upgrade...
Preparing Mineral_Member_Isk_EinAus for upgrade...
Preparing Mineral_Pool for upgrade...
Preparing Minerals for upgrade...
Preparing Ore for upgrade...
Preparing P0 for upgrade...
Preparing P1 for upgrade...
Preparing P2 for upgrade...
Preparing P3 for upgrade...
Preparing P4 for upgrade...
Preparing P4_Pool for upgrade...
Preparing Projects for upgrade...
Preparing account_account_statuses for upgrade...
Preparing account_api_key_info_characters for upgrade...
Preparing account_api_key_infos for upgrade...
Preparing affiliation_role for upgrade...
Preparing affiliation_user for upgrade...
Preparing affiliations for upgrade...
Preparing api_token_logs for upgrade...
Preparing api_tokens for upgrade...
Preparing character_account_balances for upgrade...
Preparing character_affiliations for upgrade...
Preparing character_asset_list_contents for upgrade...
Preparing character_asset_lists for upgrade...
Preparing character_bookmarks for upgrade...
Preparing character_character_sheet_corporation_titles for upgrade...
Preparing character_character_sheet_implants for upgrade...
Preparing character_character_sheet_jump_clone_implants for upgrade...
Preparing character_character_sheet_jump_clones for upgrade...
Preparing character_character_sheet_skills for upgrade...
Preparing character_character_sheets for upgrade...
Preparing character_chat_channel_infos for upgrade...
Preparing character_chat_channel_members for upgrade...
Preparing character_chat_channels for upgrade...
Preparing character_contact_list_alliance_labels for upgrade...
Preparing character_contact_list_alliances for upgrade...
Preparing character_contact_list_corporate_labels for upgrade...
Preparing character_contact_list_corporates for upgrade...
Preparing character_contact_list_labels for upgrade...
Preparing character_contact_lists for upgrade...
Preparing character_contact_notifications for upgrade...
Preparing character_contract_items for upgrade...
Preparing character_contracts for upgrade...
Preparing character_industry_jobs for upgrade...
Preparing character_kill_mails for upgrade...
Preparing character_mail_message_bodies for upgrade...
Preparing character_mail_messages for upgrade...
Preparing character_mailing_list_infos for upgrade...
Preparing character_mailing_lists for upgrade...
Preparing character_market_orders for upgrade...
Preparing character_notifications for upgrade...
Preparing character_notifications_texts for upgrade...
Preparing character_planetary_colonies for upgrade...
Preparing character_planetary_links for upgrade...
Preparing character_planetary_pins for upgrade...
Preparing character_planetary_routes for upgrade...
Preparing character_researches for upgrade...
Preparing character_skill_in_trainings for upgrade...
Preparing character_skill_queues for upgrade...
Preparing character_standings for upgrade...
Preparing character_upcoming_calendar_events for upgrade...
Preparing character_wallet_journals for upgrade...
Preparing character_wallet_transactions for upgrade...
Preparing chrFactions for upgrade...
Preparing corporation_account_balances for upgrade...
Preparing corporation_asset_list_contents for upgrade...
Preparing corporation_asset_lists for upgrade...
Preparing corporation_bookmarks for upgrade...
Preparing corporation_contact_list_alliance_labels for upgrade...
Preparing corporation_contact_list_alliances for upgrade...
Preparing corporation_contact_list_labels for upgrade...
Preparing corporation_contact_lists for upgrade...
Preparing corporation_contract_items for upgrade...
Preparing corporation_contracts for upgrade...
Preparing corporation_customs_office_locations for upgrade...
Preparing corporation_customs_offices for upgrade...
Preparing corporation_industry_jobs for upgrade...
Preparing corporation_kill_mails for upgrade...
Preparing corporation_locations for upgrade...
Preparing corporation_market_orders for upgrade...
Preparing corporation_medals for upgrade...
Preparing corporation_member_medals for upgrade...
Preparing corporation_member_securities for upgrade...
Preparing corporation_member_security_logs for upgrade...
Preparing corporation_member_security_titles for upgrade...
Preparing corporation_member_trackings for upgrade...
Preparing corporation_shareholders for upgrade...
Preparing corporation_sheet_divisions for upgrade...
Preparing corporation_sheet_wallet_divisions for upgrade...
Preparing corporation_sheets for upgrade...
Preparing corporation_standings for upgrade...
Preparing corporation_starbase_details for upgrade...
Preparing corporation_starbases for upgrade...
Preparing corporation_titles for upgrade...
Preparing corporation_wallet_journals for upgrade...
Preparing corporation_wallet_transactions for upgrade...
Preparing dgmTypeAttributes for upgrade...
Preparing dgmTypeEffects for upgrade...
Preparing eve_alliance_list_member_corporations for upgrade...
Preparing eve_alliance_lists for upgrade...
Preparing eve_api_call_lists for upgrade...
Preparing eve_api_keys for upgrade...
Preparing eve_character_info_employment_histories for upgrade...
Preparing eve_character_infos for upgrade...
Preparing eve_conquerable_station_lists for upgrade...
Preparing eve_error_lists for upgrade...
Preparing eve_notification_types for upgrade...
Preparing eve_ref_types for upgrade...
Preparing failed_jobs for upgrade...
Preparing fat_links for upgrade...
Preparing global_settings for upgrade...
Preparing group_affiliations for upgrade...
Preparing group_alerts for upgrade...
Preparing integration_notification_group for upgrade...
Preparing integrations for upgrade...
Preparing invCategories for upgrade...
Preparing invContrabandTypes for upgrade...
Preparing invControlTowerResourcePurposes for upgrade...
Preparing invControlTowerResources for upgrade...
Preparing invFlags for upgrade...
Preparing invGroups for upgrade...
Preparing invItems for upgrade...
Preparing invMarketGroups for upgrade...
Preparing invMetaGroups for upgrade...
Preparing invMetaTypes for upgrade...
Preparing invNames for upgrade...
Preparing invPositions for upgrade...
Preparing invTypeMaterials for upgrade...
Preparing invTypeReactions for upgrade...
Preparing invTypes for upgrade...
Preparing invUniqueNames for upgrade...
Preparing job_logs for upgrade...
Preparing job_trackings for upgrade...
Preparing jobs for upgrade...
Preparing kill_mail_attackers for upgrade...
Preparing kill_mail_details for upgrade...
Preparing kill_mail_items for upgrade...
Preparing mapDenormalize for upgrade...
Preparing map_jumps for upgrade...
Preparing map_kills for upgrade...
Preparing map_sovereignties for upgrade...
Preparing migrations for upgrade...
Preparing notes for upgrade...
Preparing notification_groups for upgrade...
Preparing notification_histories for upgrade...
Preparing notifications for upgrade...
Preparing password_resets for upgrade...
Preparing people for upgrade...
Preparing permission_role for upgrade...
Preparing permissions for upgrade...
Preparing person_members for upgrade...
Preparing ramActivities for upgrade...
Preparing role_user for upgrade...
Preparing roles for upgrade...
Preparing schedules for upgrade...
Preparing security_logs for upgrade...
Preparing server_server_statuses for upgrade...
Preparing staStations for upgrade...
Preparing standings_profile_standings for upgrade...
Preparing standings_profiles for upgrade...
Preparing user_login_histories for upgrade...
Preparing user_settings for upgrade...
Preparing users for upgrade...
Preparing warlof_mining_ledger_character_mining_journal for upgrade...
Preparing warlof_mining_ledger_esi_tokens for upgrade...
Preparing warlof_mining_ledger_eve_prices for upgrade...
Migrated: 2018_04_16_164623_add_200_to_300_migration_flags
`

**Comment by warlof** [comment]
so second is prove you didn't run migration :)
now you can't migrate data from 2x to 3x using the package.

**Comment by leonjza** [comment]
Please can we move this to slack. Invites here: https://eveseat.github.io/docs/about/contact/

Thanks

**Comment by Flugschreipbaer** [comment]
Warlof that was the second time I've run it
