### ISSUE TITLE
Huge amount of assets breaks assets.view

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#417]
This is a report relayed me from a member of my corporation. 

* **Problem**: The member got two chars for which the asset view does not compute. One of the characters owns 400 million (10^6) items of assets and the other got 10 million (10^6) items of assets. He does have several other characters which have less items for which seat works perfectly fine.
* **Expected**: Seat should represent the characters assets. Maybe paginated but it should be shown.
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/43996229-781122d6-9dbe-11e8-8328-ce4304499ad5.png)
![image](https://user-images.githubusercontent.com/6583519/43996233-918c06e0-9dbe-11e8-9275-0e648eb18d4f.png)

* **Version Info**: SDE Version sde-20180713-TRANQUILITY | Web Version 3.0.5

**Comment by herpaderpaldent** [comment]
Yeah looks like #352 regards the corporation view and mine the character view. But Problem persists on both ends. 

Looks like we should make these tables loading asynchrounsly: http://wern-ancheta.com/blog/2015/03/01/how-to-implement-scroll-in-laravel/ . Basic idea is to load the page with a paginated  subset of items. 
@warlof : Do you think this is feasible with the nested objects (f.e. in fitted items)?

i post this here as a bookmark when we get to work at this ticket

**Comment by erikterr** [comment]
Confirmed also in my installation, same problem both for corporation/accounts. Sometimes happen also with minor amount of assets but in a lot of multiple stations

**Comment by herpaderpaldent** [comment]
this has been resolved https://github.com/eveseat/web/commit/86b8dd9aac293009ff9db2ad9460755ab2a47130
