### ISSUE TITLE
SEAT API: /users endpoint is not paged

### ISSUE THREAD

**Issue by Lorisu** [eveseat/seat#421]
* **Problem**: SEAT instances with large amount of characters seem to cause the endpoint to time out because it tries to retrieve all the users.
* **Expected**: /users endpoint to return paged amount of users at a time to reduce response times and data size
* **Logs / Screenshots / Proof**:
API returns: {"message": "Server Error"}
Response time (3 tests): 14824ms, 13759ms, 13838ms
* **Version Info**: SeAT Api: Installed: v3.0.1

Could probably be fixed by adding '->paginate()' [here](https://github.com/eveseat/api/blob/master/src/Http/Controllers/Api/v2/UserController.php#L99) but I'm no PHP and I have no clue as to what impact the change has on the rest of the application.

**Comment by warlof** [comment]
Woops, thank you, I completely forget this.
