### ISSUE TITLE
Updating From Beta 3.0x

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#425]
When performing the update from the beta installation, the following errors are present during database migration:

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists (SQL: alter table `mail_
  labels` drop index `mail_labels_label_id_index`)

In PDOStatement.php line 144:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists

In PDOStatement.php line 142:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists

Is there a way around this error?

**Comment by drkthunder02** [comment]
I am trying to get off the beta with no success.

1.)  backup database
2.)  php artisan migrate:fresh
3.)  php artisan migrate:status (Showed all migrations had been completed and successful.)
4.)  Import database. (After several minutes the database is reimported as it's pretty big.)
5.)  php artisan migrate:status (Shows the migrations now haven't been completed.
6.)  Can't get past this part since the migrations seem to rollback when I reload the database.

| N    | 2018_05_18_232712_fix_mail_labels_indexes                              |
 | N    | 2018_05_27_085107_create_esi_statuses_table                            |
| N    | 2018_06_09_131054_add_refresh_token_soft_delete |
| N    | 2018_07_12_220118_add_method_to_api_token_logs_table                   |
| N    | 2018_07_13_215714_drop_deprecated_eve_type                             |

**Comment by drkthunder02** [comment]
Where is database/migrations/* located at?

**Comment by drkthunder02** [comment]
still get the same error after doing what you suggested.  That didn't work.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists (SQL: alter table `mail_
  labels` drop index `mail_labels_label_id_index`)


In PDOStatement.php line 144:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists


In PDOStatement.php line 142:

  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'mail_la
  bels_label_id_index'; check that column/key exists

**Comment by drkthunder02** [comment]
Alright, I give up.  I will just do a fresh install.  What tables do I need to keep in order to save roles and affiliations, and the users from the database?

**Comment by warlof** [comment]
well, restoring a backup from beta version over the release install can't work.
You're overwriting all the `migrate:fresh` steps.

Beta are simply not compatible with release.

**Comment by drkthunder02** [comment]
Just as fyi, I commented out a few lines of the two files which were giving the installation tool trouble, and it worked finally.  Not the best route to go, but after double checking the tables and realizing the tables in the database were already there and didn't need to be modified, I went ahead with the surgery.  The application is now updated.

**Comment by warlof** [comment]
What were those files ?

**Comment by drkthunder02** [comment]
The migration files which were the ones giving errors.  I commented out the lines so the migration would run successfully.

**Comment by warlof** [comment]
Can you explicitly give name of them ?
So... maybe we can search and apply some fix ?!

**Comment by herpaderpaldent** [comment]
can we close this issue?

**Comment by warlof** [comment]
I think it has been done by qu1ckkkk.
No support is provided for beta stage and people have been warn about this.
