### ISSUE TITLE
Mail Timeline can`t display national charset symbols

### ISSUE THREAD

**Issue by MoucceuWildfire** [eveseat/seat#429]
* **Problem**: Mail Timeline can`t display national(russian at least) charset symbols. For example:
From:   Leitenant
To Characters:   Moucceu Wildfire   Boris Dodger
{"mail_id":372382941,"body":"\u0410\u0440\u0445\u0430\u0442 \u0432 \u041d\u041f\u0426 \u043a\u043e\u0440\u043f\u0435. \u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0439\u0442\u0435 =)

--------------------------------
Re: \u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440
From: Boris Dodger
Sent: 2018.08.18 19:00
To: Leitenant, Moucceu Wildfire, 

\u041f\u0440\u0438\u0432\u0435\u0442
\u0423 \u0410\u0440\u0445\u0430\u0442\u0430 \u0435\u0441\u0442\u044c \u0440\u043e\u043b\u0438 \u0442\u0430\u043a \u0447\u0442\u043e \u0441\u043d\u0438\u043c\u0430\u0439 \u0438 \u0441\u043a\u0430\u0436\u0435\u0448\u044c \u043a\u043e\u0433\u0434\u0430 \u043f\u0440\u043e\u0439\u0434\u0435\u0442 \u0442\u0430\u0439\u043c\u0435\u0440 - \u043f\u0440\u0438\u043c\u0435\u043c ) \u0414\u0440\u0443\u0433\u043e\u0433\u043e \u0430\u043b\u044c\u0442\u0430 \u043f\u0440\u0438\u043d\u044f\u043b.

\u0411\u043e\u0440\u0438\u0441

--------------------------------

* **Expected**: Original mail from SeAT | Character mail
From:   Leitenant
To Characters:   Moucceu Wildfire   Boris Dodger
Архат в НПЦ корпе. принимайте =)

--------------------------------
Re: Разговор
From: Boris Dodger
Sent: 2018.08.18 19:00
To: Leitenant, Moucceu Wildfire, 

Привет
У Архата есть роли так что снимай и скажешь когда пройдет таймер - примем ) Другого альта принял.

Борис

* **Logs / Screenshots / Proof**: 
![mailtimeline2018-08-20-11-05-23](https://user-images.githubusercontent.com/39436031/44329235-994a3280-a46c-11e8-8d6e-aa1d911792ca.png)
![original mail2018-08-20-11-06-11](https://user-images.githubusercontent.com/39436031/44329254-a404c780-a46c-11e8-9f41-a80bc2927a91.png)

* **Version Info**: 
![version-2018-08-20-11-32-06](https://user-images.githubusercontent.com/39436031/44329280-bd0d7880-a46c-11e8-98ef-3dd54781c922.png)

**Comment by MoucceuWildfire** [comment]
Hi. I got this issue not only with this character but all mail with russian charset.

**Comment by warlof** [comment]
I got it, but we need content to debug :)

**Comment by MoucceuWildfire** [comment]
ok, wait a minute pls

**Comment by MoucceuWildfire** [comment]
Looks like this issue apply to my instance only.

**Comment by MoucceuWildfire** [comment]
Problem solved since SeAT update 09.12.2018
