### ISSUE TITLE
Starbase Offline Time is inaccurate.

### ISSUE THREAD

**Issue by molten360** [eveseat/seat#43]
I have a small POS that is set to offline in 1 month and 3 days, however SeAT currently states it is going to offline two weeks earlier. Updated API's before submitting bug report. Fuel amount has been in the POS since it was onlined and has not been added to or subtracted from outside the 8 blocks per hour.

**Comment by leonjza** [comment]
It will always be an estimate due to API update rotation and CCP cache timers.
Are the fuel bock amounts accurate?

**Comment by molten360** [comment]
Yes. Fuel is accurate within 1 hour. I could see an estimate being a couple of days out. But the current estimate is 2 full weeks different.

**Comment by leonjza** [comment]
Can you attach some screenshots showing the times that are off?

**Comment by warlof** [comment]
What is the starbase ? Empire, faction ?
What is its size
Is it involve in a sov system ?

**Comment by leonjza** [comment]
Ping @molten360

**Comment by molten360** [comment]
Here are two screenshots. One is the offline notification for the tower within Eve. The other is the Starbase Page from SeAT
![capture](https://cloud.githubusercontent.com/assets/8443104/12146165/38f87c74-b460-11e5-873c-c7d057767e15.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8443104/12146238/9a7eba44-b460-11e5-99fe-2451c3edce33.JPG)

**Comment by leonjza** [comment]
How many fuel blocks does the tower have in game? Or is the amount in the SeAT view correct?

**Comment by molten360** [comment]
the amount in SeAT is only off by an hour, or 8 blocks.

**Comment by leonjza** [comment]
Should be fixed in `eveseat/seat` [1.0.19](https://github.com/eveseat/seat/wiki/Web-Changelogs#1019)
