### ISSUE TITLE
DataTables warning from corporation-industry from last update

### ISSUE THREAD

**Issue by brown-star** [eveseat/seat#432]
DataTables warning: table id=corporation-industry - Requested unknown parameter 'solarSystemName' for row 0, column 2. For more information about this error, please see http://datatables.net/tn/4

**Comment by warlof** [comment]
Hi,

Are you certain you are running all latest packages?
As this field is non longer referenced - it has been replaced by `facilityName`

**Comment by heresboris** [comment]
i got the same error just for all characters page now.. jut updated to the latest via docker-compose pulll etc..  https://i.imgur.com/fPeZQHp.png

**Comment by warlof** [comment]
@heresboris can you open your browser console and check the output ?

1) go on the page
2) right click on it
3) choose inspect element in the contextual menu
4) move to network tab using XHR filter
5) refresh the page using f5
6) select the line with a 500 status and return the response here

**Comment by heresboris** [comment]
{
    "message": "Server Error"
}

**Comment by warlof** [comment]
Ah yeah, you all have to turn on the debug : https://eveseat.github.io/docs/troubleshooting/

**Comment by heresboris** [comment]
https://pastebin.com/FPzR0uyb
