### ISSUE TITLE
Feature Request: Differentiate Between Blueprint Originals and Copies

### ISSUE THREAD

**Issue by MushroomMayhem** [eveseat/seat#434]
* **Problem**: Impossible to tell if a blueprint in assets is a copy or an original
* **Feature Request**: Clearly show originals separate from copies
* **Suggested Logic**:Use the character_blueprints table to generate a new page. Sort all blueprints with a runs < 0 into the originals section, and everything else into the copies section. Capture ME/TE data. Organize by location like assets. 

![image](https://user-images.githubusercontent.com/39438876/44634531-c319c280-a960-11e8-8ba4-bd8e7fc67f41.png)

**Comment by herpaderpaldent** [comment]
Just a mental note: the asset view is already heavily loaded with logic etc. A PR of mine is pending to make it load asynchronously. 
Regarding the differentiation between copies and originals. The SeAT Table is `character_blueprints` where the column `quantity` indicates BP's status. `A range of numbers with a minimum of -2 and no maximum value where -1 is an original and -2 is a copy. It can be a positive integer if it is a stack of blueprint originals fresh from the market (e.g. no activities performed on them yet).` from: https://esi.evetech.net/ui#/Character/get_characters_character_id_blueprints

**Comment by herpaderpaldent** [comment]
@warlof you can assign me this issue: seems smth i can take into my backlog about datatables

**Comment by warlof** [comment]
I can't unfortunately, but will do virtually ^^'
Tabs rather than nested view would be better at ergonomic point of view though.

**Comment by herpaderpaldent** [comment]
![image](https://user-images.githubusercontent.com/6583519/50641048-087d7a80-0f67-11e9-9fca-5f8f44cd3b8e.png)
 how does this look like?

**Comment by MushroomMayhem** [comment]
I like it. It's consistent with other views and easy to read.
