### ISSUE TITLE
User Settings not removed after linking a toon

### ISSUE THREAD

**Issue by dysath** [eveseat/seat#435]
If I register two toons seperately, Bob and Joe, and have logged in as both, I have entries in 'user_settings'.  

Now, when I manually link Joe to Bob under the Users table, the 'user_settings' for both characters are still present.  The correct method should be, if I link Joe under Bob, Joe's user_settings should be removed.

Without this, there's not a good way to pull the user's mains out of the user_settings table.

**Comment by herpaderpaldent** [comment]
You pull the main from the users group not user_setting.

**Comment by warlof** [comment]
Nah, it shouldn't persist if a group is empty and therefore deleted.
