### ISSUE TITLE
Errors on the index page in fresh install

### ISSUE THREAD

**Issue by ChrisKing517** [eveseat/seat#44]
This is a new install, and I'm getting a "Whoops" error when I login, with this error in the log:

```
* Checking Pheal EVE API Access
PHP Fatal error:  Class name must be a valid object or a string in /var/www/public.com/seat/vendor/eveseat/services/src/Settings/Settings.php on line 80


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class name must be a valid object or a string
```

**Comment by ChrisKing517** [comment]
I mean, I realize this isnt a super helpful log after looking at the code there, but I don't know what else to give you.  I basically installed it using the same instructions as

https://github.com/eveseat/scripts/blob/master/install/ubuntu-14-04-x.sh

(But I walked through it one by one)

**Comment by ChrisKing517** [comment]
Ah, nevermind.  I realized you used a different php repo which had php 5.6

For those of you who had the same issue, take note!

**Comment by leonjza** [comment]
Yeah so Ubuntu 14.04 LTS ships with a PHP version that has a late static binding bug. However, you should not have been able to `composer create-package` by default as it should have failed the PHP version requirement defined [here](https://github.com/eveseat/seat/blob/master/composer.json#L8). Did you `git clone` -> `composer install` it?

**Comment by ChrisKing517** [comment]
```
php composer.phar create-project eveseat/seat seat --keep-vcs --prefer-source --no-dev
```

That worked with no problems with the outdated version of PHP

**Comment by leonjza** [comment]
Can you compare the versions composer installed to the latest repos?
