### ISSUE TITLE
SeAT 3.0.x - Channels don't show in character sheet

### ISSUE THREAD

**Issue by sergiorochalopes** [eveseat/seat#441]
Hi!

I'm SuperUser and have all ESI scopes active. I noticed that the channels page doesn't show up anymore in the character sheet(s). I just did an upgrade to latest version just in case and still nothing.

Any ideas?

The below list are the options that I see in a characters sheets.

Assets
Bookmarks
Calendar
Contacts
Contracts
Fittings
Industry
Intel
Killmails
Mail
Market
Mining
Notifications
PI
Research
Sheet
Skills
Standings
Wallet

Thank you.

**Comment by herpaderpaldent** [comment]
What is a channel page?

**Comment by sergiorochalopes** [comment]
A list of in-game chat channels for that character

**Comment by herpaderpaldent** [comment]
There is no ESI-Endpoint providing this information. Therefore we can not show informations regarding this.

**Comment by sergiorochalopes** [comment]
It's the esi-characters.read_chat_channels.v1 and it exists in the SSO Scope also.
SeAT had it before as seen here on this img:   https://discourse-cdn-sjc1.com/eveonline/uploads/default/original/3X/0/e/0e01308bc7c8946b871131d209ec5e2ea958f59c.jpeg

**Comment by leonjza** [comment]
https://developers.eveonline.com/blog/article/esi-chat-channel-deprecation

**Comment by sergiorochalopes** [comment]
Ok.. that answers that! 
Thanks
