### ISSUE TITLE
SeAT API /roles/affiliation/character results in 200 but no change.

### ISSUE THREAD

**Issue by Crypta-Eve** [eveseat/seat#445]
* **Problem**:
The API is returning success codes but not acting upon the request.
I make a POST to /roles/affiliation/character in order to add a character affiliation to a specific role, I get a 200 response yet dont see the change reflected in seat... ie the affiliation is never made. I check both through the web UI, and through the api itself.

* **Expected**:
I expected either the roles to be assigned or the API to return a result other than 200 (Successful)

* **Logs / Screenshots / Proof**: 
Let me know what I can give here but for now I will just attach the code I have which demonstrates the problem.
https://gist.github.com/Crypta-Eve/80503a43db0498771c7eb1ef5c0dc040
I know its convoluted and could be improved, but the code functions as follows;
```
get all seat users
for each defined corp
    get the affiliations of the leadership role
    for each seat user
        if seat user corp == corp
            if seat user not in current affiliations
                send POST to add user to corp leadership role affiliations
```

If this is an error in my code I apologise.

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
SeAT API - v3.0.4
SeAT Console v3.0.2
SeAT Eveapi v3.0.6
SeAT Notifications v3.0.1
SeAT Web v3.0.8
SeAT Services v3.0.2
PHP 7.0.30-0+deb9u1
Debian 9

**Comment by warlof** [comment]
Hello @Crypta-Eve ,

Apologies for such late answer but we've been busy a bit recently.
What you did using this route is adding the character into affiliated character from the specified role.

If you want to assign a role to a character, you need to use this route instead : `[POST] /roles/groups`

**Comment by MickeyBrock** [comment]
Roger, I think this stems from not understanding the whole character/groups thing when I started down the path. Either way, should it still return 200? I'll amend my code for the right endpoint.

**Comment by Crypta-Eve** [comment]
Roger, I think this stems from not understanding the whole character/groups thing when I started down the path. Either way, should it still return 200? I'll amend my code for the right endpoint.

**Comment by warlof** [comment]
Hey @Crypta-Eve,

It's hard to say without a sample of request. I would say yes, as long as the targeted group doesn't have already the provided character_id attached to its affiliation AND it exists :)

**Comment by Crypta-Eve** [comment]
I have confirmed that this issue is still present. I am trying to use the api to add a character as an affiliation to a role, the API returns 200 however no affiliation is made

```
| Vendor          | Package Name       | Installed Version |
| --------------- | ------------------ | ----------------- |
| eveseat         | api                | 3.0.6             |
| eveseat         | console            | 3.0.5             |
| eveseat         | eveapi             | 3.0.13            |
| eveseat         | notifications      | 3.0.3             |
| eveseat         | services           | 3.0.8             |
| eveseat         | web                | 3.0.20            |
| herpaderpaldent | seat-groups        | 1.7.1             |
| herpaderpaldent | seat-notifications | 2.0.0             |
```

**Comment by warlof** [comment]
I'm indead able to reproduce this if the body is sent malformed which seems to be the case as your body sample doesn't meet JSON specification :
- boolean must be lowercase and either `true` or `false`
- property must be surround using double quote `"` instead of simple quote `'`

Can you give it another try with `eveseat/api@3.0.7` which I just release ?
It is not yet including a query structure check (eveseat/api#34) - but you should be able to use Swagger UI for your tests now.

Also, if you're using a Swagger client, the definition has been altered a bit for POST and PUT endpoints. Maybe you could try to regenerate your code with the new definition (don't forget to update it with `php artisan `l5-swagger:generate`).

**Comment by warlof** [comment]
Did you regenerate the api definition?

**Comment by Crypta-Eve** [comment]
answering here as it was resolved on slack. `eveseat/api@3.0.7` works great. Swagger UI doesnt, even after regeneration but that is unrelated so going to close this issue.
