### ISSUE TITLE
Allow users to remove their own characters from SeAT

### ISSUE THREAD

**Issue by ghost** [eveseat/seat#448]
Requesting that people can remove their own characters from seat (maybe with a notification integration for slack) that way when someone sells an alt, it doesnt cause them to loose all roles, groups and discord permissions.

**Comment by herpaderpaldent** [comment]
i could imagine that user mark characters in their group as ‘traded’ and if someone with the correct permission approves the move of that character it will be assigned to another/fresh group.

**Comment by 0wnedadmin** [comment]
that or maybe a permission in ACL to grant others the role to delete from settings, saving me doing it all the time as i dont trust anyone else with super user.

**Comment by 0wnedadmin** [comment]
Thats a good point, then maybe an option then to mark it as sold and no longer part of the SeAT account group, where it doesnt impact permissions of its previously owned group.

**Comment by herpaderpaldent** [comment]
I created a PR for this issue:

https://github.com/eveseat/web/pull/231

it requires the admin to head to `configuration/users` and edit->deactivate the sold/biomassed character. 
It's not a super automatic process which is imho a good thing, as it requires the admin and user to communicate. Doing so noone is able to abuse the ability and a reason needs to be provisioned and is logged.

Do you think this PR would fullfil your feature request ghost? 

PS: he deleted his account, can we close this Issue with merging the mentioned PR?

**Comment by warlof** [comment]
> * **Problem**: _Whats wrong?_
> players dont listen and just willy nilly link all thier alts - this leads me to needing them to unlink characters so i can give htem and not thier alts roles / permissions
> 
> * **Expected**: _What did you expect to happen?_
> they can go to thier profile and "unlink character"
> 
> * **Logs / Screenshots / Proof**: _The more information you give the better!_
> this option does not exist to take a screenshot of 
> 
> * **Version Info**: _PHP Version, SeAT Version, Operating System etc._
> latest everything
> 
> ---
> 
> I have problem with this.
> one of my guy deleted own character from eve, and that removes all permission he's group have.
> so I have to reassin it to my trash group..
> 
> sorry for bad english but I think it better if user can unlink character from his main group

source from @GoemFunaila into eveseat/seat#506

**Comment by warlof** [comment]
Regarding this, I would make it optional and disable by default. Instance admin would be able to allow it from settings using a checkbox (allowed/denied).

Also, when a removal action occurs, it must be logged into security events.

**Comment by vladimmi** [comment]
Why does it require character to have (valid?) refresh token? I have user stuck with character in his list having no valid token anymore but there is no button to unlink it.

**Comment by warlof** [comment]
You must allow user to unlink character from their account in settings
Otherwise it can be done only by admin

**Comment by vladimmi** [comment]
It is allowed. As admin, I can see character in user's list but cannot unlink it. User does not see that characters in his list and cannot unlink it as well.

**Comment by warlof** [comment]
This has to be done from the user profile.
It doesn't need access to user list to get access to it's account

**Comment by vladimmi** [comment]
Again: if we go to the commit related to this issue and look at `src/resources/views/profile/view.blade.php`, line 330 means character can have invalid token and still linked to user. At the same time, line 344 means there will be no unlink button for character with no refresh token. Which goes to initial question: why does it require character to have (valid?) refresh token to unlink if character can be already be linked to user without that token?

**Comment by warlof** [comment]
A token being invalidated is by definition unlinked since soft deleted and non longer attached to an account

**Comment by vladimmi** [comment]
Hmm... But is character still associated to user somehow? Otherwise why would you check for token and display a marker of valid/invalid one? I'm starting to think I either have some DB/cache issues or understand "unlinking" wrong way.
