### ISSUE TITLE
[Feature Request] improve /configuration/users page usability

### ISSUE THREAD

**Issue by brown-star** [eveseat/seat#449]
The admin page listing all users has 3 functions that are listed per each character. This means you cannot bulk delete character information unless you have database access. When a user selects the delete function, they are given a modal acceptance and then the entire page must be re-rendered.

This is super painful if the player has over 2-3 characters. Imagine your HR manager needing to delete 102 characters from a profile...very painful.

I suggest a feature to add a select box to be able to delete multiple users in a single process.

**Comment by herpaderpaldent** [comment]
Hey @brown-star 
Maybe you can provide us with the use case you are facing? Deleting data should never be an option / or only in extreme use cases. So why do you think it was necessary?

**Comment by herpaderpaldent** [comment]
Regarding 1. You could try to launch more workers. Get in contact with us on slack. There are groups using SeAT with even more characters that could help you optimize the load. 

Regarding 2 and 3: A user can actually review its token status: https://github.com/eveseat/web/pull/205 

Regarding traded characters, there is a FR up for discussion for this to improve

**Comment by warlof** [comment]
The users list need a pagination à anyway.
Making deletion more smooth could be a good improvement too.

Also, we should add a delete all button on this list which will removing all account apart the admin and used one.
