### ISSUE TITLE
Request: Group general "People" with multiple API keys

### ISSUE THREAD

**Issue by ChrisKing517** [eveseat/seat#45]
Like in the old version of seat, it was a huge benefit to be able to track individuals by grouping their multiple character API keys under one user.  That doesn't seem implemented yet in this version

**Comment by warlof** [comment]
How did you find the seat 0.x feature ? Did he need improvements or can be taked like it was ?

**Comment by torlivar** [comment]
No original requester - but for us it works great in 0.x and this is one of the main functionalities we're waiting for before we really will consider moving up.

**Comment by leonjza** [comment]
Have received a large number of requests for this feature to be put back. Work has started on it. Expect it to return soon™

**Comment by dmeskel** [comment]
Glad to hear that Leonjza ! This feature is very usefull.
Would it be possible to go a step further and group people by status.
Exemple: corpmates/recruts/banned?

Thank you

**Comment by leonjza** [comment]
This was added to `eveseat/web` [1.0.19](https://github.com/eveseat/seat/wiki/Web-Changelogs#1019)

**Comment by ChrisKing517** [comment]
This was added, but I get a "TokenMismatchException" when adding an API to an existing people group

**Comment by leonjza** [comment]
I just tried this and cant seem to replicate the `TokenMismatch` under normal conditions. This typically happens when a session expired etc.

I can also confirm that the CSRF token is set in the form [here](https://github.com/eveseat/web/blob/master/src/resources/views/people/list.blade.php#L135)
