### ISSUE TITLE
[BUG][Datatables] Character Killmail

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#459]
`src/Http/Controllers/Character/KillmailController.php`

![image](https://user-images.githubusercontent.com/6583519/46568825-dea6be80-c94b-11e8-9751-547a64f41e90.png)

https://github.com/eveseat/web/pull/221#discussion_r221372195

**Comment by herpaderpaldent** [comment]
I am going to extend this Bug with some Feature-Request:

![image](https://user-images.githubusercontent.com/6583519/48825651-57c96c00-ed68-11e8-98a2-2a375ee446b3.png)

- Add: Region to location
- Add: Corporation and Alliance of Victim

**Comment by leg0las-devel** [comment]
in 3.0.10 i found this bug, i have window:
"DataTables warning: table id=character-killmails - Ajax error. For more information about this error, please see http://datatables.net/tn/7"
