### ISSUE TITLE
[BUG] [Datatables] Character Standing Compare

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#460]
`src/Http/Controllers/Character/IntelController.php`

![image](https://user-images.githubusercontent.com/6583519/46568836-00a04100-c94c-11e8-8c37-54541b65d572.png)

https://github.com/eveseat/web/pull/221#discussion_r221372738

**Comment by herpaderpaldent** [comment]
Have you tested this? I havent touched standings yet

**Comment by warlof** [comment]
My bad, I think it has been addressed with the intel block.
