### ISSUE TITLE
There is no sequence update.

### ISSUE THREAD

**Issue by fwfmiao** [eveseat/seat#461]
![image](https://user-images.githubusercontent.com/29328241/46568921-973a2580-c97f-11e8-9a2f-a0f441095f18.png)

I log in through SSO, there is no update, there is no error in the log, there is no content.

![image](https://user-images.githubusercontent.com/29328241/46568926-b9cc3e80-c97f-11e8-89c1-1a6993d2b185.png)

I remember there was a circle around here before.

![image](https://user-images.githubusercontent.com/29328241/46568938-d799a380-c97f-11e8-9239-294969755a71.png)

the status is Inactive

![image](https://user-images.githubusercontent.com/29328241/46568942-ec763700-c97f-11e8-9684-ef50f41514c3.png)

**Comment by warlof** [comment]
Related to the message you have in characters; there is a pending fix.

About sequence update, horizon dashboard will be slightly more useful to figure if or not you have an issue with job queuing.

Maybe we can move this to slack ;)

**Comment by fwfmiao** [comment]
I just want to wait for a while.Will it be normal?

**Comment by herpaderpaldent** [comment]
Usually this happens with my developer instance too, the reason lies in your worker not running. 

Try to restart `supervisor` if you have installed SeAT bare metal or restart `seat-worker` if you installed SeAT with Docker

**Comment by fwfmiao** [comment]
I use it

Systemctl restart supervisor.service

It's no use. I'm going to restart it. Try it.

**Comment by herpaderpaldent** [comment]
For Slack join here: https://eveseat-slack.herokuapp.com/ 
Might be easier for all of us to support you

**Comment by fwfmiao** [comment]
ok thx
