### ISSUE TITLE
[BUG] Database Issue

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#463]
https://prnt.sc/l3tpk1

SQLSTATE[[22003]: Numberic value of of range: 1264 Out of range value for column 'average_price' at row 1 (SQL: insert into `historical_prices` (`type_id`, `date`, `average_price`, `adjusted_price`, `updated_at`, `created_at`) 

Screen shot is linked at the top of the post.

**Comment by herpaderpaldent** [comment]
Duplication of: https://github.com/eveseat/seat/issues/451 

Fix is ready although not yet merged: https://github.com/eveseat/services/pull/64 

you can alter the column attributes accordingly.
