### ISSUE TITLE
error 500 pocos

### ISSUE THREAD

**Issue by groniu** [eveseat/seat#465]
[2018-10-10 07:22:20] local.ERROR: Undefined property: Seat\Eveapi\Models\Sde\MapDenormalize::$typeID (View: /var/www/seat/vendor/eveseat/web/src/resources/views/corporation/pocos.blade.php) {"userId":92719778,"exception":"[object] (ErrorException(co
de: 0): Undefined property: Seat\\Eveapi\\Models\\Sde\\MapDenormalize::$typeID (View: /var/www/seat/vendor/eveseat/web/src/resources/views/corporation/pocos.blade.php) at /var/www/seat/vendor/eveseat/eveapi/src/Models/Sde/MapDenormalize.php:193, Erro
rException(code: 0): Undefined property: Seat\\Eveapi\\Models\\Sde\\MapDenormalize::$typeID at /var/www/seat/vendor/eveseat/eveapi/src/Models/Sde/MapDenormalize.php:193)

**Comment by groniu** [comment]
I have a problem when i click  pocos link on corporation details page like https://host/corporation/view/pocos/[:id]
I get "Whoops, looks like something went wrong."

Log entry connected to this click

 `[2018-10-10 07:22:20] local.ERROR: Undefined property: Seat\Eveapi\Models\Sde\MapDenormalize::$typeID (View: /var/www/seat/vendor/eveseat/web/src/resources/views/corporation/pocos.blade.php) {"userId":92719778,"exception":"[object] (ErrorException(co
de: 0): Undefined property: Seat\Eveapi\Models\Sde\MapDenormalize::$typeID (View: /var/www/seat/vendor/eveseat/web/src/resources/views/corporation/pocos.blade.php) at /var/www/seat/vendor/eveseat/eveapi/src/Models/Sde/MapDenormalize.php:193, Erro
rException(code: 0): Undefined property: Seat\Eveapi\Models\Sde\MapDenormalize::$typeID at /var/www/seat/vendor/eveseat/eveapi/src/Models/Sde/MapDenormalize.php:193)`

**Comment by herpaderpaldent** [comment]
Can you assure that SDE is up2date?

**Comment by groniu** [comment]
SDE Version sde-20180827-TRANQUILITY

**Comment by ErickAsmock** [comment]
I get the same issue with the current version of SeAT and SDE.  It has been going on for a while.

**Comment by herpaderpaldent** [comment]
Please follow the steps provided here and provide us with the gained intel https://eveseat.github.io/docs/troubleshooting/
