### ISSUE TITLE
Cannot install using basic install

### ISSUE THREAD

**Issue by eivinda** [eveseat/seat#466]
* **Problem**: 
Installation using Basic install fails
* **Logs / Screenshots / Proof**: 
......snipped
Docker installed
docker-compose is not installed. Installing...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    998      0 --:--:-- --:--:-- --:--:--   998
100 10.3M  100 10.3M    0     0  3839k      0  0:00:02  0:00:02 --:--:-- 7685k
docker-compose installed
Ensuring /opt/seat-docker is available...
Grabbing docker-compose and .env file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2994  100  2994    0     0  10283      0 --:--:-- --:--:-- --:--:-- 10288
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1765  100  1765    0     0   6810      0 --:--:-- --:--:-- --:--:--  6814
Generating a random database password and writing it to the .env file.
Generating an application key and writing it to the .env file.
**Starting docker stack. This will download the images too. Please wait...
/dev/fd/63: line 62: docker-compose: command not found**
[root@eveseat ~]#
[root@eveseat ~]# cd /opt/seat-docker
[root@eveseat seat-docker]# /usr/local/bin/docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

* **Version Info**: 
CentOS-7

**Comment by herpaderpaldent** [comment]
Seems you distribution had Docker preinstalled. Check CentOS documentation on how to install and use docker. 

```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

This tells you that you can't execute docker properly.

**Comment by eivinda** [comment]
ok, thanks, a bit over my head, trying Ubuntu next

**Comment by herpaderpaldent** [comment]
if you use f.e. DigitalOcean there are 1-click installations with working docker ...
<img width="1268" alt="digitalocean_-_create_droplets" src="https://user-images.githubusercontent.com/6583519/46859412-fa0f3f00-ce0d-11e8-8c5b-02c36e338271.png">
