### ISSUE TITLE
[improvement] search and filter of Datatables

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#467]
* **Problem**: Searching by user-name does not work:
* **Expected**: return any contracts where the issuer or receiver got the name that was searched for
* **Logs / Screenshots / Proof**: 
![image](https://user-images.githubusercontent.com/6583519/46864051-75c2b900-ce19-11e8-9495-155ca037920a.png)
![image](https://user-images.githubusercontent.com/6583519/46864059-79564000-ce19-11e8-9583-7ab4d2181d2f.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by herpaderpaldent** [comment]
Contacts, wallet transactions and wallet journal same

**Comment by jediefe** [comment]
The problem here seems to be, that the searching algorithm is internally working with the user_id instead of the resolved name.
If I try to enter a random number that looks like a user_id, I get results in the search table.

**Comment by herpaderpaldent** [comment]
Add receipient and number of items 
![image](https://user-images.githubusercontent.com/6583519/47815252-24d71e00-dd50-11e8-9814-b1113a4a66a5.png)

**Comment by herpaderpaldent** [comment]
wallet journal: https://github.com/eveseat/web/pull/237

**Comment by herpaderpaldent** [comment]
Wallet Transactions is related to this issue: https://github.com/eveseat/seat/issues/476
