### ISSUE TITLE
Beeing able to export information in a CSV file

### ISSUE THREAD

**Issue by paintballlaws** [eveseat/seat#469]
Ability to have separate wallet divisions for the corporation and have the ability to export that information to a CSV format

**Comment by warlof** [comment]
@paintballlaws you already have separate wallet divisions with balance of each of them.
What want you exactly ?

Same question apply for the CSV export, where want you them ?

**Comment by paintballlaws** [comment]
@warlof is this still something that could possibly happen and just maybe got forgotten lol? Or should I just abandon my hopes and dreams now?

**Comment by warlof** [comment]
Hi @paintballlaws that can land with v4
I just need to add the option on new tables 😉

Good thing to bump to ticket
