### ISSUE TITLE
Horizon Dashboard

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#474]
The horizon dashboard shows jobs increasing on the Jobs Past Hour counter, but shows no active jobs, no failed jobs, no total process number, and doesn't show any queue on the seat pages.  Any idea why horizon would suddenly stop reporting statistics showing jobs being updated.  On a side note SeAT hasn't updated in a few days now anyone's information.

**Comment by warlof** [comment]
Hi @drkthunter02,

If you go on the jobs horizon board, do you have an area in the bottom - bellow `current workload`.

If the answer is no, you have to start supervisor using `sudo service supervisor restart`

**Comment by drkthunder02** [comment]
Ran the command anyways even though supervisor is running without any problems on another application.

http://prntscr.com/lfqucm

That is the screen shot of my horizon dashboard.  I put the configs below.  

Seat Versions:
SeAT Api:  3.0.4
SeAT Console: 3.0.2
SeAT Eveapi: 3.0.7
SeAT Notifications: 3.0.1
SeAT Web: 3.0.9
SeAT Services: 3.0.3
Eve Online SDE:  sde-20180827-TRANQUILITY

Supervisor Config:
[program:seat]
command=/usr/bin/php /var/www/seat/artisan horizon
process_name = %(program_name)s-80%(process_num)02d
stdout_logfile = /var/log/seat-80%(process_num)02d.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
numprocs=2
directory=/var/www/seat
stopwaitsecs=600
user=www-data

Crontab Configuration:
* * * * * /usr/bin/php /var/www/seat/artisan schedule:run

PHP Version:
PHP 7.2.11-4+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov  4 2018 05:10:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11-4+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by leonjza** [comment]
What is the value for your `.env` files `APP_ENV` key?

**Comment by herpaderpaldent** [comment]
i take Epoch18 is you?
![image](https://user-images.githubusercontent.com/6583519/48182815-f13a5c00-e32c-11e8-93ad-c6b0d0300868.png)

Please ensure that you only use one version of PHP. Maybe use virtualenv .... or use Docker!

**Comment by drkthunder02** [comment]
No.  Epoch18 is not me.

APP_ENV=production

**Comment by leonjza** [comment]
Restore it to the default value of [`local`](https://github.com/eveseat/seat/blob/master/.env.example#L1) and restart.

**Comment by herpaderpaldent** [comment]
This seems to be a support case. As these issues and responses are flooding the development channel we ask people to join our slack: https://eveseat-slack.herokuapp.com/ 
We might be more of help in the support-channel
