### ISSUE TITLE
Characters in mail are numbers instead of names

### ISSUE THREAD

**Issue by Pete1burn** [eveseat/seat#481]
Title says it.  In the mail timeline, all characters show up as their character ID instead of their name.  It was working for a while, now it's not.

**Comment by herpaderpaldent** [comment]
a simple search in closed issues would have lead you to: https://github.com/eveseat/seat/issues/296

**Comment by herpaderpaldent** [comment]
or this back from 2015: https://github.com/eveseat/seat/issues/9

**Comment by Pete1burn** [comment]
After a simple search, (and before I posted) I did find the first one, but the chown command in there did not resolve the issue, even after restarting artisan, and also the server.  As I said, it was working before, so this is something that happened maybe after a reboot of the server, which I do occasionally after doing updates.

**Comment by herpaderpaldent** [comment]
see here: https://github.com/eveseat/seat/issues/411

**Comment by herpaderpaldent** [comment]
should be closed with web 3.0.10
