### ISSUE TITLE
Be able to search in assets content

### ISSUE THREAD

**Issue by MushroomMayhem** [eveseat/seat#485]
* **Problem**:  Unable to easily search through large asset lists that have items inside containers or ships
In order to search for an item through a character, the user must expand all of the containers inside the asset window, then use browser search (CTRL-F) to find the item.

* **Desired**: Typing into search area of assets window locates items inside ships/containers

* **Logs / Screenshots / Proof**: 
![fr-1](https://user-images.githubusercontent.com/39438876/49749954-3ffe4d00-fc6f-11e8-8997-25f8b5f512d9.jpg)

![fr-2](https://user-images.githubusercontent.com/39438876/49749959-42f93d80-fc6f-11e8-8508-463a860355ea.jpg)

![fr-3](https://user-images.githubusercontent.com/39438876/49749965-45f42e00-fc6f-11e8-9d4a-7fa66501bd0b.jpg)

* **Version Info**: 
SeAT Api
 Installed: v3.0.5
 SeAT Console
 Installed: v3.0.2
 SeAT Eveapi
 Installed: v3.0.9
 SeAT Notifications
 Installed: v3.0.2
 SeAT Web
 Installed: v3.0.10
 SeAT Services
 Installed: v3.0.4

**Comment by warlof** [comment]
It's been implemented for SeAT 4.0 together with new table layout
