### ISSUE TITLE
Corp Assets Location invalid id

### ISSUE THREAD

**Issue by Fundaris** [eveseat/seat#486]
* **Problem**: 
Can't resolve the location of an item

The Structure is resolved where it is located in.

* **Expected**: 
No fail

* **Logs / Screenshots / Proof**:

```
Seat\Eseye\Exceptions\RequestFailedException: Invalid IDs in the request in /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:242
Stack trace:
#0 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(102): Seat\Eseye\Fetchers\GuzzleFetcher->httpRequest('post', 'https://esi.eve...', Array, '[1028616658326]')
```

`MariaDB [seat]> SELECT * FROM corporation_assets WHERE item_id = 1028616658326;`

```
| item_id       | type_id | quantity | location_id   | location_type | location_flag | is_singleton | x    | y    | z    | map_id | map_name | name | created_at          | updated_at          |

| 1028616658326 |   3962 |        8 | 1028813794282 | other         | CorpSAG5      |            0 | NULL | NULL | NULL |   NULL | NULL     | NULL | 2018-10-01 12:13:26 | 2018-12-11 10:15:55 |
```

*Corp Id was removed!*

* **Version Info**: 
Latest Docker

**Comment by herpaderpaldent** [comment]
it will eventually be resolved as soon as you got a character with ACL rights on the strucutre
see issue from esi: https://github.com/esi/esi-issues/issues/918

**Comment by Fundaris** [comment]
As said the structure is resolved so there is no sense in this lookup

![grafik](https://user-images.githubusercontent.com/3646843/49826181-93af8a00-fd86-11e8-8ec3-592cd3506a0e.png)

**Comment by warlof** [comment]
Closing as suspicion of ESI issue.

Fill free to reopen the ticket if it's still valid though.
