### ISSUE TITLE
Implement "deactivate all" feature in user account overview

### ISSUE THREAD

**Issue by mparadies** [eveseat/seat#489]
As a super user, I want to be able to deactivate all characters associated with an account.

![image](https://user-images.githubusercontent.com/9323165/49923864-0a4aa580-feb5-11e8-822f-6bfe4cb58840.png)

**Comment by benthompson0** [comment]
@warlof I would suggest closing this issue as it seems no longer relevant given the move from the one-user-per-character in SeAT 3.x to one-container-user in SeAT 4.x. Deactivating the user effectively deactivates any character belonging to that user from login.

**Comment by warlof** [comment]
You're right, this is non longer relevant.
