### ISSUE TITLE
Cronjob / API's not Pulling at intervals

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#49]
I followed the instructions for editing the cron job from the installation wiki for Ubuntu 14.04, but it seems with just the cron job alone as * * * * * /usr/bin/php /var/www/seat/artisan schedule:run 1>> /dev/null 2>&1 the scheduler doesn't seem to run the appropriate tasks as listed out in the Schedule when logged into the administration panel in SeAT.  If I do not manually request a job to pull all of the api keys, then the queue sits there doing nothing.

Redis says its running fine, and there are no jobs in the queue.  It's basically as if SeAT is not putting the api keys in the queue every hour as scheduled in the scheduler.

**Comment by leonjza** [comment]
Could you check out some of the logs to see of any exceptions pop up? Also, please send the output of `sudo -u apache php artisan seat:admin:diagnose` where _apache_ is the user the workers is running as.

**Comment by Xaroth** [comment]
I had a similar issue, but instead the corp API key threw an error which caused it to become disabled.. I nipped into a sql shell and re-enabled the account (setting the error value to NULL).

The error wasn't related to an API response, it was a http error response that (i think) upset the system.

Perhaps worth checking, and as a RFC: a button to re-enable a key in the api key listing page (either on the listing or on the details page for a key)

**Comment by leonjza** [comment]
@Xaroth I am adding the buttons for these in the next web package release. Don't know how I missed that xD

**Comment by drkthunder02** [comment]
warped@warpedintentions:/var/www/seat$ sudo -u www-data php artisan
seat:admin:d
iagnose
[sudo] password for warped:
SeAT Diagnostics
If you are not already doing so, it is recommended that you run this as the
user
the workers are running as.
Eg:
    sudo -u apache php artisan seat:admin:diagnose
This helps to check whether the permissions are correct.

 * Getting environment information
Current User: www-data
PHP Version: 5.6.16-4+deb.sury.org~trusty+1
Host OS: Linux warpedintentions 3.19.0-25-generic #26~14.04.1-Ubuntu SMP
Fri
Jul
24 21:16:20 UTC 2015 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/app/pheal/ is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is writable

 * Checking Database
+------------+-----------+
| Setting    | Value     |
+------------+-----------+
| Connection |           |
| Host       | localhost |
| Database   | seat      |
| Username   | seat      |
| Password   | ********* |
+------------+-----------+
Connection OK to database: seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of:
8HVUb1DTT6NYqiyfrsYQ3I9xpqgRcZ8IycYGW7T86V4iD1yQX7M2f1k9Eqz0m
SsT
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 29747

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 1.0.8         | 1.0.8         |
| Console       | 1.0.9         | 1.0.9         |
| Eveapi        | 1.0.8         | 1.0.8         |
| Notifications | 1.0.3         | 1.0.3         |
| Web           | 1.0.18        | 1.0.18        |
| Services      | 1.0.13        | 1.0.13        |
+---------------+---------------+---------------+
SeAT Diagnostics complete

I looked at the alarms, after deleting the line from my cronjob, and then
reinstalling the line, and it needs further study before I can determine if
it is pulling keys reliably.  Let me watch what is going on for the next
day, and I will have an update tomorrow for you.

On Mon, Jan 11, 2016 at 9:30 AM, Leon Jacobs <notifications@github.com>
wrote:

> Could you check out some of the logs to see of any exceptions pop up?
> Also, please send the output of sudo -u apache php artisan
> seat:admin:diagnose where *apache* is the user the workers is running as.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eveseat/seat/issues/49#issuecomment-170587922>.
>



-- 
Chris Mancuso

When you eliminate the impossible, whatever remains, however improbable,
must be the truth.  -- Spock

**Comment by warlof** [comment]
which is the owner of the posted crontab ? is it www-data ? else, you should remove this task and create a new one for www-data

**Comment by drkthunder02** [comment]
The owner of the posted crontab is www-data.  There are other jobs for
www-data as well, but the cron job for seat is the first in the list.

On Mon, Jan 11, 2016 at 1:48 PM, Loïc LEUILLIOT <notifications@github.com>
wrote:

> which is the owner of the posted crontab ? is it www-data ? else, you
> should remove this task and create a new one for www-data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eveseat/seat/issues/49#issuecomment-170668889>.
>



-- 
Chris Mancuso

When you eliminate the impossible, whatever remains, however improbable,
must be the truth.  -- Spock

**Comment by warlof** [comment]
Well, If it's still up to date, maybe will be able to find more answer with log files :
Apache vhost log
Php error log
seat_path/app/storage/logs log

**Comment by drkthunder02** [comment]
Well the scheduler built into the programming into SeAT is not running the job correctly.  I removed the cron job for doing the queue of the eve keys through cronjob, and no jobs for updating queue keys ran over the last 12 hours.  When I run it through the cronjob of the system, the queue keys does work correctly.

**Comment by leonjza** [comment]
Not sure I follow this last comment, but this definitely sounds like a configuration issue rather than a software bug so far.

**Comment by drkthunder02** [comment]
If I run the scheduler coded into SeAT 1.x, the api keys are not updated.

If I run a custom cronjob and delete the scheduler code for SeAT, the api
keys are updated at regular intervals according to the cronjob written in
the OS.

On Tue, Jan 12, 2016 at 7:22 AM, Leon Jacobs <notifications@github.com>
wrote:

> Not sure I follow this last comment, but this definitely sounds like a
> configuration issue rather than a software bug so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eveseat/seat/issues/49#issuecomment-170910053>.
>



-- 
Chris Mancuso

When you eliminate the impossible, whatever remains, however improbable,
must be the truth.  -- Spock

**Comment by leonjza** [comment]
I suggest you come onto slack sometime and come explain in detail what your setup/etc is. I still feel this is a config / install problem and not a software bug. Will update this ticket once a resolution is reached.
