### ISSUE TITLE
Show activation status of user/character in user list

### ISSUE THREAD

**Issue by mparadies** [eveseat/seat#490]
As super user, I want to be able to ascertain on first look whether a character is activated/deactivated in the user account overview.

Suggestion: Grey shading on inactivate characters

**Comment by warlof** [comment]
Hello @mparadies,

You already got a green tick on user with active token and a red cross for the other. 

Isn't good enough?

**Comment by herpaderpaldent** [comment]
it's about active or deactive users ...

**Comment by warlof** [comment]
Hum, assume it's a WIP topic so as except if I'm saying shit, the disable state of an user is non longer doing anything for now.
