### ISSUE TITLE
Total Mined Isk showing 0

### ISSUE THREAD

**Issue by lor1113** [eveseat/seat#492]
* **Problem**: _Whats wrong?_
* **Expected**: _What did you expect to happen?_
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

Problem: Total Mined Isk showing as 0

Expected: Total Mined Isk to show the total amount of isk i've mined, which I know is not 0

![minedstuff](https://user-images.githubusercontent.com/15572735/50045814-84378600-0091-11e9-8b7b-a2c812284a0f.PNG)
![0isk](https://user-images.githubusercontent.com/15572735/50045816-8994d080-0091-11e9-9e20-3914c2e80ffa.PNG)

OS: win10, SeaT running on Firefox latest with several cookie blocker and other privacy plugins

**Comment by warlof** [comment]
Hi @lor1113,

Thank you for the bug report.
It is a known bug which will be fixed on next release between the 21st and 23rd.
