### ISSUE TITLE
Updating emailaddress gives error

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#493]
Adding an emailaddress of a user via https://seat.tgrad.space/configuration/users/edit/<######> as a Superuser gives a 'Whoops, looks like something went wrong' error

Looking at the log files it is caused by 
[2018-12-16 11:18:20] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'where clause' (SQL: select count(*) as aggregate from `users` where `email` =

**Comment by kwazulueve** [comment]
Any chance of seperating this fix from the larger related change its now part of?

**Comment by herpaderpaldent** [comment]
I expect eveseat/web#231 to be in the next update. @warlof can you confirm this?

**Comment by kwazulueve** [comment]
Just tried to update a bunch of users and noticed this bug is still a thing. Would be great to have it solved if that fix is still existing from the larger #231 change

**Comment by kwazulueve** [comment]
Thanks, works now!
Small donation sent ;)
