### ISSUE TITLE
Seat Char Linking not working properly

### ISSUE THREAD

**Issue by Fundaris** [eveseat/seat#494]
* **Problem**: 
User lost all his permissions

Steps:
```
Main: Char1 Linked: (Char 1, Char2, Char3)
Login with Char4 (Not with Link Character!)
then click `link character` log into Char1
Seat then assignes all characters to Char 4
Resulted in Main: Char 4 Linked (Char 4, Char 1, Char2, Char3)
```

* **Expected**: 
User should keep his permissions
and Char4 should be assigned to Char1 as it is the older user

* **Logs / Screenshots / Proof**: 

41 minutes ago | Char4  | authentication | Updating Char1 to be part of Char4 
42 minutes ago |   | authentication | Creating new account for Char4 
42 minutes ago | Char4 | authentication | User logged in from ...

* **Version Info**: 
Docker

**Comment by herpaderpaldent** [comment]
I can add to this ticket as OP has contacted me prior to creating this ticket that this is related with seat-groups. 

I truly believe this is not an error:

usually superuser-rights are escaped here: 
https://github.com/herpaderpaldent/seat-groups/blob/master/src/Jobs/GroupSync.php#L81-L89

by switching `Seat\Web\Models\Group` this persistance of seat-groups/superuser right was not possible anymore, as the Group does not have superuser prior to the jobs execution
