### ISSUE TITLE
PHPExcel_Shared_Font not found. While upgrading seat

### ISSUE THREAD

**Issue by ItzMeJesse** [eveseat/seat#495]
https://imgur.com/a/tZQaqpq

Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In excel.php line 182:

  Class 'PHPExcel_Shared_Font' not found

Script @php artisan package:discover handling the post-autoload-dump event retur                                                                     ned with error code 1

I'm not used to linux and stuff and after following the manual upgrading guide (like always) I got this error message.

My last upgrade was done at the 10th of November.
The error occured when upgrading today.

I'm sure you guys know what needs to be done to fix it.

**Comment by warlof** [comment]
Hi,

From SeAT directory, you should have a folder `config` containing a file called `excel.php`. 

Simply drop it using `rm /var/www/seat/config/excel.php`.

Once done, restart the update process and be sure to runs both migration and publish vendors, especially SeAT web package.

**Comment by ItzMeJesse** [comment]
Yep that fixed it.
Thanks for helping me out there!

This ticket is now open for closing :D

Cheers!
