### ISSUE TITLE
Opening an individual contract in "linked characters contracts" shows an empty contract, if the active character is not part of the contract

### ISSUE THREAD

**Issue by mparadies** [eveseat/seat#499]
Repro Steps:
Let there be characters A, B, C, D all of which are linked to A.
Let there be an item exchange contract between B and C.

If I am on A, and I open contracts -> linked characters contracts, the contract shows as empty.
If I am on B, no matter whether I am on the main contracts page or the linked characters contract page, I can see the contents of the contract.

**Comment by mparadies** [comment]
@herpaderpaldent

**Comment by herpaderpaldent** [comment]
Confirming this finding.

this is the cause of the error: 
https://github.com/eveseat/web/blob/accd83e609c0d4469a4eb89c5274c91f45fa6a24/src/resources/views/character/contracts.blade.php#L124 

`character_id` should not be of the request but the linked character
