### ISSUE TITLE
Contacts Label

### ISSUE THREAD

**Issue by JackONeill12** [eveseat/seat#5]
The Labels on the contacts seems bugged because it shows for all aviable labels for all positive standings and none for the rest. Also it shows all lables not only the ones which are actually assinged to the caracter or Corp.

**Comment by leonjza** [comment]
Please elaborate a little on this. Can you show me some data from the db vs UI or something?

**Comment by JackONeill12** [comment]
http://i.imgur.com/tV53vmr.png

So it shows me all Labels that would be theroreticly aviable to asign ingame althrough most of this Caracters have only 1 Label assigned. And this only happens for positive standing. Neutral and negative shows no labels at all. Hope that helps.

**Comment by warlof** [comment]
I think I've found the issue which is based on the contact label integration.
CCP return the list of all label using binary style (the first label is 2, the second 4, etc...)

The relation between a contact and its labels is based on the sum of all label id which the contact has.

It's something like the accessMask control with API Key.

I'm working on a fix with qu1ckkkk support.

**Comment by warlof** [comment]
Fixed with https://github.com/eveseat/eveapi/pull/3

**Comment by leonjza** [comment]
Will have this with the next tagged version of the web package.

**Comment by JackONeill12** [comment]
Now the positive standings are labled correctly. But Neutral and Negative are still completely without lables.

**Comment by warlof** [comment]
I find why, working on the fix.

**Comment by warlof** [comment]
if you can confirmed that the issue has been fixed with the today's released verison ?! :)

**Comment by JackONeill12** [comment]
Issue has been fixed :)
Thx ;)
