### ISSUE TITLE
Api update

### ISSUE THREAD

**Issue by JackONeill12** [eveseat/seat#50]
At the Moment all of my Api updates produce the following error:

http://pastebin.com/09Ue1Wz3

**Comment by leonjza** [comment]
Please send the output of `describe account_api_key_info_characters` from your MySQL console. The table `account_api_key_info_characters` should have an ID column `https://github.com/eveseat/eveapi/blob/master/src/database/migrations/2015_09_04_193632_create_account_api_key_info_characters_table.php#L19`. If you installed this before the official release, you may be missing the column.

**Comment by JackONeill12** [comment]
mysql> describe account_api_key_info_characters;
+-----------------+--------------+------+-----+---------------------+-------+
| Field           | Type         | Null | Key | Default             | Extra |
+-----------------+--------------+------+-----+---------------------+-------+
| keyID           | int(11)      | NO   | MUL | NULL                |       |
| characterID     | int(11)      | NO   | MUL | NULL                |       |
| characterName   | varchar(255) | NO   | MUL | NULL                |       |
| corporationID   | int(11)      | NO   |     | NULL                |       |
| corporationName | varchar(255) | NO   |     | NULL                |       |
| created_at      | timestamp    | NO   |     | 0000-00-00 00:00:00 |       |
| updated_at      | timestamp    | NO   |     | 0000-00-00 00:00:00 |       |
+-----------------+--------------+------+-----+---------------------+-------+
7 rows in set (0.00 sec)

**Comment by warlof** [comment]
Fix the table according to qu1ckkkk says :
Alter table account_api_key_info_characters
ADD column id int auto_increment;

**Comment by JackONeill12** [comment]
Thx. Now loogs like the following and is working. ;)

mysql> describe account_api_key_info_characters;
+-----------------+------------------+------+-----+---------------------+----------------+
| Field           | Type             | Null | Key | Default             | Extra          |
+-----------------+------------------+------+-----+---------------------+----------------+
| keyID           | int(11)          | NO   | MUL | NULL                |                |
| id              | int(10) unsigned | NO   | PRI | NULL                | auto_increment |
| characterID     | int(11)          | NO   | MUL | NULL                |                |
| characterName   | varchar(255)     | NO   | MUL | NULL                |                |
| corporationID   | int(11)          | NO   |     | NULL                |                |
| corporationName | varchar(255)     | NO   |     | NULL                |                |
| created_at      | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
| updated_at      | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
+-----------------+------------------+------+-----+---------------------+----------------+
8 rows in set (0.00 sec)
