### ISSUE TITLE
10% Of jobs per hour are failing due to RequestFailedException(code: 401)

### ISSUE THREAD

**Issue by Gavalore** [eveseat/seat#502]
Hello, I recently did a fresh install of SeAT on a VPS instance using the basic install. I've noticed that every hour when CRON jobs are running to update information on the SeAT, that I aproximately 10% of jobs are failing due to error messages such as below;

`[2019-01-01 00:00:02] local.ERROR:  {"exception":"[object] (Seat\\Eseye\\Exceptions\\RequestFailedException(code: 401):  at /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:242)
[stacktrace]
#0 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(168): Seat\\Eseye\\Fetchers\\GuzzleFetcher->httpRequest('post', 'https://login.e...', Array)
#1 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(148): Seat\\Eseye\\Fetchers\\GuzzleFetcher->refreshToken()
#2 /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php(99): Seat\\Eseye\\Fetchers\\GuzzleFetcher->getToken()
#3 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(448): Seat\\Eseye\\Fetchers\\GuzzleFetcher->call('get', 'https://esi.eve...', Array)
#4 /var/www/seat/vendor/eveseat/eseye/src/Eseye.php(256): Seat\\Eseye\\Eseye->rawFetch('get', 'https://esi.eve...', Array)
#5 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/EsiBase.php(218): Seat\\Eseye\\Eseye->invoke('get', Object(GuzzleHttp\\Psr7\\Uri), Array)
#6 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Character/Assets.php(97): Seat\\Eveapi\\Jobs\\EsiBase->retrieve(Array)
#7 [internal function]: Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets->handle()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), false)
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\\Queue\\WorkerOptions))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'high,medium,low...')
#23 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#24 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#30 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#32 /var/www/seat/vendor/symfony/console/Application.php(953): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/seat/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 {main}
"}`

The code 401, is pretty consistent through ought the entirety of the logs which leaves me to believe that root cause of these errors must all be the same. Is it possible that this could be happening due to a bad installation?

**Comment by warlof** [comment]
Hi, can you provide information regarding your installation ?

Since eveseat/web@3.0.14 you got a quick assist button into settings which is putting you the complete SeAT package and upgraded plugins list into your clipboard.

Then, what is the token states of your users ?
Finally, which scopes are you requesting into SeAT and your Eve Application ?

**Comment by warlof** [comment]
Closing due to no feedback since near to be one year :/
