### ISSUE TITLE
[BUG] Security Logs order by date broken

### ISSUE THREAD

**Issue by GoemFunaila** [eveseat/seat#503]
* **Problem**: date is not perfectly orderd
* **Expected**: odered by date
* **Logs / Screenshots / Proof**: 
<img width="129" alt="20190102_164014" src="https://user-images.githubusercontent.com/44015503/50583536-24244a80-0ead-11e9-8135-9d90ff8f40e2.png">
this image show everything

* **Version Info**: SeAT latest release

**Comment by warlof** [comment]
I don't see issue in your screen?
In 9 hours is indead 9hours more than in 15 min. 
Which is 15min more than now
Which is also 5 hours later than the early oldest one 🤔

I also don't figure the issue with browser since date human diff are applied on server side here 😉

**Comment by GoemFunaila** [comment]
sorry for misunderstanding, It must be my language issue about 'in'
