### ISSUE TITLE
Be able to unlink its own character

### ISSUE THREAD

**Issue by GoemFunaila** [eveseat/seat#506]
* **Problem**: _Whats wrong?_
players dont listen and just willy nilly link all thier alts - this leads me to needing them to unlink characters so i can give htem and not thier alts roles / permissions

* **Expected**: _What did you expect to happen?_
they can go to thier profile and "unlink character"

* **Logs / Screenshots / Proof**: _The more information you give the better!_
this option does not exist to take a screenshot of 

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
latest everything

---

I have problem with this.
one of my guy deleted own character from eve, and that removes all permission he's group have.
so I have to reassin it to my trash group..

sorry for bad english but I think it better if user can unlink character from his main group

**Comment by warlof** [comment]
merging with eveseat/seat#448 due to duplication
