### ISSUE TITLE
Extractions only showing 3 lines instead of 4

### ISSUE THREAD

**Issue by Fundaris** [eveseat/seat#507]
* **Problem**: 
Seat ist only showing in extractions 3 ore lines instead of 4

* **Expected**: 
All 4 should be shown
* **Steps**:
When you enter data like:
Ore
Ore
Ore
Ore

instead of
Moon
Ore
Ore
Ore
Ore

![grafik](https://user-images.githubusercontent.com/3646843/51086968-71c27200-174d-11e9-9aad-7b49d00889ba.png)

* **Version Info**: Web 3.0.14

**Comment by warlof** [comment]
The parser will have to be improved a bit in order to trigger error if the format is altered.

You should have a header line which is skip by the process - as it's not in the report, you're only got 3 over 4 rows ;)

**Comment by warlof** [comment]
Has been address with https://github.com/eveseat/web/commit/0500d11747acafcc462cb349cb5617f5f71144d8
