### ISSUE TITLE
[FR] Unable to unlink characters?

### ISSUE THREAD

**Issue by dstevens79** [eveseat/seat#513]
* **Problem**: _Whats wrong?_
players dont listen and just willy nilly link all thier alts - this leads me to needing them to unlink characters so i can give htem and not thier alts roles / permissions

* **Expected**: _What did you expect to happen?_
they can go to thier profile and "unlink character"

* **Logs / Screenshots / Proof**: _The more information you give the better!_
this option does not exist to take a screenshot of 

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
latest everything

**Comment by herpaderpaldent** [comment]
Don't misunderstand this but you are using seat different as it is designed. 

Our Vision is that a human user is represented by 1 main character. This human has one group and you assing roles and permissions to that group and towards that human beeing. 
What you descripe varies fundamentally from our vision. 

I would object to building UIs to enable users to do what you wish for. 
However, as of today: an Admin can do so freely.

**Comment by warlof** [comment]
I'm sorry, but according to the issue itself, I don't really see what could avoid an user X to unlink one of its toon - ie: if he biomassed it.

It can be restrict with a permission and tracked easily for a security point of view.

It also can be put in an approval workflow.

**Comment by herpaderpaldent** [comment]
Same reasoning as in https://github.com/eveseat/web/pull/231#issuecomment-447972885
Its a security concern and he is not talking about biomassing. 

He wants 1 human to have n groups for roles and that has nothing to do with biomassing. Such manipulations of representation of rl users needs to be a superuser action. Just like recently decided why the mentioned PR must be in sec.log

**Comment by warlof** [comment]
closing as duplicated of eveseat/seat#506
