### ISSUE TITLE
When Deleting Corps an ESI Update Refreshes Them in the Corp Listing

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#514]
Can delete corporations I don't want to view anymore in the corporation listing.  Once the API's are updated again, the corporation re-appears.  What's the purpose of a delete button if it doesn't do anything?

**Comment by warlof** [comment]
If the Corp is turning back, that's mean you still have at least one character attached to it with a valid token.

**Comment by drkthunder02** [comment]
Is there a way other than manually sifting through 3000 keys to delete the
Corp keys?

**Comment by warlof** [comment]
Not magically no.

Go on your characters list
Search for the annoying corporation
Take a note of the character returned
Go into settings > users and drop them

Once done, you'll be able to drop the corporation which is annoying you and it will non longer come back.
