### ISSUE TITLE
Corporation Mining Ledger View: Can not sort by Main Character

### ISSUE THREAD

**Issue by jediefe** [eveseat/seat#515]
* **Problem**: In the mining ledger corporation view it is not possible to sort by main character
* **Expected**: Sort by main character in the corporation mining ledger view
* **Logs / Screenshots / Proof**: In `ledger.blade.php` line 53, the respective `<td>` is missing a `data-order` specifier.
* **Version Info**: eveseat/web 3.0.14

**Comment by warlof** [comment]
will depends on https://github.com/yajra/laravel-datatables/pull/2368 before being implemented.

**Comment by Crypta-Eve** [comment]
@warlof Is there anything left for this to work other than changing the composer.json to require `yajra/laravel-datatables-oracle:^9.10.0` ?

**Comment by warlof** [comment]
Confirmed the issue is now closed - I bump the minimum required version from DT factory.
