### ISSUE TITLE
Improvements - structure timers

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#516]
* **Problem**:  Structures with offline modules show Offline Est.
* **Expected**: Maybe show low-power mode? 
* **Logs / Screenshots / Proof**: _
![image](https://user-images.githubusercontent.com/6583519/51436673-dfacf300-1c91-11e9-8edb-e50beaf758c5.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by Crypta-Eve** [comment]
Working on it. CCP Soon(TM)
