### ISSUE TITLE
RefTypes updater triying to insert a duplicated entry

### ISSUE THREAD

**Issue by Hopobcn** [eveseat/seat#52]
Hi

Today I noticed about a new error/bug. Apparently seat is trying to insert an entry with refTypeID=58 into eve_ref_types table, but eve_ref_types already contains that entry, so the primary key is violated and the sql fails.

```
Last Updater: Processing: RefTypes

Exception: Illuminate\Database\QueryException
Error Code: 23000
Error Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '58' for key 'PRIMARY' (SQL: insert into `eve_ref_types` (`refTypeID`, `refTypeName`, `updated_at`, `created_at`) values (58, Researching Time Productivity, 2016-01-14 01:00:14, 2016-01-14 01:00:14))
File: /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php - Line: 651
...
```
Full stacktrace here: http://pastebin.com/AAXv67ni 

```
mysql> select * from eve_ref_types where refTypeID=58;
+-----------+-----------------------------+---------------------+---------------------+
| refTypeID | refTypeName                 | created_at          | updated_at          |
+-----------+-----------------------------+---------------------+---------------------+
|        58 | Researching Time Efficiency | 2015-12-25 01:01:26 | 2015-12-25 01:01:26 |
+-----------+-----------------------------+---------------------+---------------------+
```

**Comment by nizzan** [comment]
I'm having the same issue also, every night for the past 3 days.

**Comment by Cynabal** [comment]
you could add 

`WHERE NOT EXISTS (
    SELECT refTypeID FROM eve_ref_types WHERE refTypeID = '58'
)`

to the SQL Statement

**Comment by leonjza** [comment]
Got a feeling the XML response has a dupe entry in it. Will investigate.

**Comment by leonjza** [comment]
Just realized this job does a [insert, else update](https://github.com/eveseat/eveapi/blob/master/src/Api/Eve/RefTypes.php#L46). Strange that my installation is not doing this though. Lets investigate some more.

**Comment by warlof** [comment]
Should check différence on Reftypename with same reftypeid

**Comment by Nuramori** [comment]
I get this same error, clean install done a week ago.
