### ISSUE TITLE
[BUG/Improvement] - Seat Module Versions

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#522]
* **Problem**: Module Version view separates core and plugins, although the count of up2date and outdated outdated packages include both plugins and core.  
* **Expected**: 
1. Either count only the ones visible or (and that is what i would prefer) show both core and plugins on same page
2. rename `Updated packages` to  `up-to-date packages`
* **Logs / Screenshots / Proof**: 
* **Version Info**: 
```
| Vendor          | Package Name       | Installed Version |
| --------------- | ------------------ | ----------------- |
| eveseat         | api                | 3.0.6             |
| eveseat         | console            | 3.0.3             |
| eveseat         | eveapi             | 3.0.10            |
| eveseat         | notifications      | 3.0.3             |
| eveseat         | services           | 3.0.5             |
| eveseat         | web                | 3.0.14            |
| herpaderpaldent | seat-groups        | 1.6.4             |
| herpaderpaldent | seat-notifications | 1.0.9             |
```

**Comment by warlof** [comment]
Counters are here for global visiblity whereas core/plugins tab are displaying details.
It's something I want to keep as it.
