### ISSUE TITLE
Limits/Filters to Roles in SeAT

### ISSUE THREAD

**Issue by rupertd** [eveseat/seat#532]
One of the fundamental use-case scenarios with SeAT is the screening of potential applicants to join a Corp.  For this, we typically assign recruiters. To those same recruiters it would be great if we could assign a ROLE to them in SeAT that limits their ability to see only the characters submitted to the instance that were submitted within the last 7 days (as an example).  This would give them plenty of time to do their research and dig through the data; interview the prospective member. At the same time it would deny them the ability to crawl unceremoniously through the data for all other characters held in the system that are no longer of interest to them.

So, that's it; in simple terms. >> Set additional filter capabilities in the ROLE so that it can be limited in some form by an Admin to a defined or restricted span of configurable time.  It would also give recruiters a simpler view of SeAT as they'll only see the stuff which has been newly submitted.

**Comment by rupertd** [comment]
I have also been meddling with the GROUPS plugin. That has raised another idea; which is to limit the recruiters roll to see all characters that are NOT affiliated to a selection of Corporations selected by the Admin.  This would allow Corps that have ALT CORPS (as we have lots) to enable visibility of all characters in the SeAT instance that are NOT affiliated to the Corp or ALT CORPS in question.

Given recruiting is such a fundamental requirement of any Eve Corp going through the process of using SeAT it would be wonderful to cater to those specific needs in some form.  The Groups add-on makes it wonderfully easy to provide access to things like fittings if certain affiliations or even corp role TITLES are true; and somewhat frustrating that recruiters are not catered to in any form yet!  The rest of the tooling is brilliant and wonderful; no complaints at all; this is pure WISHLIST stuff! :-)  Thanks for the hard work you guys put into the package; we'd be lost without it!

**Comment by herpaderpaldent** [comment]
with latest comment regarding recuitment role: That's a dublicated of https://github.com/eveseat/seat/issues/365 

and: 
![image](https://user-images.githubusercontent.com/6583519/52709336-c1829c00-2f8c-11e9-931c-6a54d3554cde.png)
 
Regarding my plugin: It does group assignments on roles and is not meant to manage affiliations. You still need to setup a role and manage the affiliations

**Comment by rupertd** [comment]
Many thanks, understood; the current issue is that I can easily limit the viewability of CORP data by an inverse affiliation in the SeAT role; but I need to manually add the inverse affiliation of every single member that I don't want the Recruiters to see over the longer term.  In a Corp with 10's of 100's of members; or even thousands a small drop down list of 10 at a time (scrolling or not) that doesn't highlight those already selected means that this workaround is dead in the water; for us at least; because we are too big for that type of manual intervention.  We'll await the 3.1 release and see if those additional 'filters' will help achieve the aims!  Many thanks again.

**Comment by Eingang** [comment]
I was going to experiment with configuring a separate SeAT instance specifically for recruiting. Everyone in the `recruiter group` would see all the character details for anyone not currently in the alliance. Data would be wiped every seven to fourteen days using an external script for anyone not in a specified group, like recruiters, admin, etc.

**Comment by Crypta-Eve** [comment]
I am closing this issue as resolved.  Recruiter roles are possible since SeAT v4 through squads and seat-squad-sync. The only  use case not addressed is the time based restriction. If this is truly needed please open another issue.
