### ISSUE TITLE
[Feature Request] Item Replacement form (not srp :))

### ISSUE THREAD

**Issue by jim1471** [eveseat/seat#533]
Similar to SRP but a form to request replacement Items. IE Fuel Replacement for corps/alliances.

Reason for the request, i'm sure many corps/aliances have similar programmes, but personally my corp replaces Jump fuel and for example Fighter losses during fleets.

Select your Character (only those listed within your linked characters)
Item requested ( pre-fills when start to type to ensure no spelling mistakes.)
Amount (IE if asking for fuel replacement)
Comments:(Free text Box)
Pre-filled/Calculated field on esitmated Isk value

When user submits - it goes to a state of awaiting approval.
What does the admin/approver see.

- Outstanding requests - when opening outstanding requests there is a new field for approver comments
- Approved Requests - Highlighted Green
- Declined Requests - Highlighted Red

Back end / roles. my thoughts...

Member - can submit/view own submissions
Replcament_team - can view/approve/decline/comment

**Comment by warlof** [comment]
This is something which will not be handled by core.
I'm keeping it open for anyone interested to build a plugin.

**Comment by herpaderpaldent** [comment]
maybe targeted wrong github repo? https://github.com/dysath/seat-srp
