### ISSUE TITLE
[Feature]Navigation structures added to Corp Structure view

### ISSUE THREAD

**Issue by jim1471** [eveseat/seat#537]
The following structures to be added to the Corp Structures view.

The Pharolux Cyno Beacon
The Tenebrex Cyno Jammer
The Ansiblex Jump Gate

With Fuel indications

**Comment by warlof** [comment]
Hi @jim1471, normally since march 23 update and seat/eveapi@3.0.11 you should get them together with citadels, engineering and refinery structures.

As I'm not owning any navigation structures, could you confirm me this ?
