### ISSUE TITLE
HTTPS breaks the layout

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#54]
The site still runs and you can connect but the layout is all busted.

http://i.imgur.com/nfMndFs.png

**Comment by leonjza** [comment]
Check your web server configs. Plenty of HTTPs installs out there (incl. my own) and they run just fine.

**Comment by dysath** [comment]
Looks like your CSS didn't load for some reason.  Hit 'F12' to look at the Network traffic, load the page, and you'll likely find the issue

**Comment by leonjza** [comment]
@shibdib have you double checked your configs? I have just setup another instance with HTTPS and everything is ok.

**Comment by clonerworks** [comment]
@shibdib can you dump the source of the rended page? It looks like css or javascript might be getting 404 errors on render.

**Comment by shibdib** [comment]
https://gyazo.com/75c7664bc327a1aa62e7ff616be186ca

**Comment by leonjza** [comment]
Looks like the assets are being served over HTTP where the site is running HTTPs. Considering the definition for the `asset()` method used [here](https://laravel.com/docs/5.1/helpers#method-asset):
> Generate a URL for an asset using the current scheme of the request (HTTP or HTTPS)

Im still going to go with a configuration problem. I don't recall the actual fix, but when I previously saw this, it was an nginx configuration problem.

**Comment by shibdib** [comment]
Using apache, if there's a "head" file that has all the includes it can be fixed by removing the http from the url so it's just //url.here

But ill poke around on google about an apache fix

**Comment by leonjza** [comment]
Just realized. No content (css/js) in SeAT 1.x is being pulled off domain... Your screenshot obviously suggests otherwise.

As for the schema-less URLs, they are [dynamically generated](https://github.com/eveseat/web/blob/master/src/resources/views/layouts/app.blade.php#L13)

**Comment by shibdib** [comment]
https://gyazo.com/13bf9f71bb143dfff037426ae1856473 etc.. etc..

so it's being pulled off domain but not as https for some reason.

**Comment by leonjza** [comment]
I am using the following vhost config. Maybe this helps? Nothing fancy, but heh.

```
<VirtualHost *:443>
    ServerAdmin webmaster@xxx
    DocumentRoot "/var/www/html/seat"
    ServerName xxx
    ServerAlias www.xxx
    ErrorLog "logs/xxx-error_log"
    CustomLog "logs/xxx-access_log" common

    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/xxx/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/xxx/fullchain.pem

    <Directory "/var/www/html/seat">
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

**Comment by shibdib** [comment]
Basically the same as what I have

**Comment by leonjza** [comment]
Cool. Keep us posted if you manage to nail the problem.

**Comment by dysath** [comment]
The Apache config is fine.  It's more likely in the Seat config where
you've defined the URL as 'http://www.whatever.com' vs. '
https://www.whatever.com', and you have no HTTP listener set up.

Again, I recommend pulling up firebug, loading the page, and see which
files are failing to load and the reason.

On Thu, Jan 28, 2016 at 12:42 AM, Leon Jacobs <notifications@github.com>
wrote:

> Cool. Keep us posted if you manage to nail the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eveseat/seat/issues/54#issuecomment-176012942>.
>



-- 
Ed Stafford

**Comment by leonjza** [comment]
@dysath the SeAT config only applies to the CLI / Artisan. We have also already seen its mixed content issues from the previous screenshots.

**Comment by warlof** [comment]
Need the apache setting (both enabled vhost and security) and the seat path aswell if you want help. You can go on slack if you don't want to send such informations here. But without, we can't help you.

**Comment by warlof** [comment]
And like dysath says, firebug dump (or any other network tool result like chrome and IE)

**Comment by leonjza** [comment]
@warlof This screenshot given by OP already shows that its serving up the content via http and not https
https://gyazo.com/13bf9f71bb143dfff037426ae1856473

**Comment by warlof** [comment]
Ah, my Bad, didn't get it. What about apache settings ?

**Comment by leonjza** [comment]
Ping @shibdib
