### ISSUE TITLE
Language does not work as expected when using community package.

### ISSUE THREAD

**Issue by JHXSMatthew** [eveseat/seat#544]
* **Problem**:  Language seems does not load when on third-party application view. 

* **Expected**:  Native seat language should be loaded when on third-party application view.

* **Logs / Screenshots / Proof**: 
It works fine when on SEAT native views (i.e. home/corp/charsracters etc)

![image](https://user-images.githubusercontent.com/11565658/54101604-a8003300-4418-11e9-8af1-2aea55b2591b.png)

but seat does not load language when on the third-party application view

![image](https://user-images.githubusercontent.com/11565658/54101673-f01f5580-4418-11e9-994d-3111bd7fdf99.png)

* **Version Info**: don't think it is relevant but I will check if you need.

**Comment by leonjza** [comment]
Do your packages have the necessary translations? Are you sure the packages you are using are not hardcoding english strings? When changing locale, assuming the package correctly implements translations, these should load fine as the locale change is application wide.

**Comment by JHXSMatthew** [comment]
Thank you for your reply.
I am using discord connector.
It has essential translations for that package. (I added by myself)


proof:

![image](https://user-images.githubusercontent.com/11565658/54102500-d849d080-441c-11e9-92ee-e5381994eb6e.png)

![image](https://user-images.githubusercontent.com/11565658/54102509-dda71b00-441c-11e9-8780-c4b1c21d0cd5.png)



however, on that view, it still shows default language 

![image](https://user-images.githubusercontent.com/11565658/54102534-f7e0f900-441c-11e9-9504-a2493c29040b.png)

but if I switch to native views,
![image](https://user-images.githubusercontent.com/11565658/54102561-1515c780-441d-11e9-8e7c-c7f498a6ea94.png)


The locale is loaded application wide, except it does not load for third-party package view.

**Comment by warlof** [comment]
I can confirm the assert.

That's super weird, and seems to only be valid on the plugin Controllers.

**Comment by warlof** [comment]
This is related to the plugin and not the core.

@leonjza can you transfer this to my repo warlof/seat-discord-connector ?

**Comment by JHXSMatthew** [comment]
Ironically, other plugins' views do have the same issue.

I have changed the default locale to cn in app.php and it gets fixed.

I have no ideas what's going on but I don't think it is a plugin specific issue. tho I could be wrong bc I did not read every component.

Thanks all for your help.

**Comment by warlof** [comment]
It's related to a missing `locale` Middleware in plugins routes.
