### ISSUE TITLE
Permissions roundtable

### ISSUE THREAD

**Issue by warlof** [eveseat/seat#546]
Hello fellow, 

The purpose of this topic will be to got some talking place related to our ACL system. 

Those of you who are tracking the project for a while know that we want to completely refactor our security system using standard framework Gate in order to improve flexibility and most importantly, readability. 

Actual questions are :
 - Are you using the actual granularity of permissions? (granting wallet access for a character, assets for corporation, etc...)
- In case of a blank paper (SeAT without any ACL - everyone got a super access), what would you restrict and how ?

**Comment by herpaderpaldent** [comment]
kinda relates to this feedback thread: https://github.com/eveseat/seat/issues/410

**Comment by herpaderpaldent** [comment]
> In case of a blank paper (SeAT without any ACL - everyone got a super access), what would you restrict and how ? 

i would not do this. Without ACL setup you got access to your very resources and that is a good behaviour.

**Comment by warlof** [comment]
> > In case of a blank paper (SeAT without any ACL - everyone got a super access), what would you restrict and how ?
> 
> i would not do this. Without ACL setup you got access to your very resources and that is a good behaviour.

I didn't say we will remove it. It's just a way to say : starting from fresh, how will you and what will you need to manage your instance in a secure way.

**Comment by warlof** [comment]
The following things has been retain for 4th generation :

 - a complete revamp of the Access Control Layer interface in order to make it more user friendly
 - scopes are now publicly available on the UI and used to sort attached permissions
 - a generic way for third party developer to add permissions as been implemented from the `AbstractSeatPlugin` class
 - previously known `affiliation` has been turned into `filters` and stored as `json` object which should be a little bit more flexible for the future
 - you'll get a way to store logo for each role - which can be used later by third party plugins
 - those logo are stored inside the database - so you don't have to worry about the way to backup your instance, especially when using Docker installation
 
Please find details of the original pull request bellow.

---

It introduce some new role information fields dedicated to third party integration like the description and logo.
Roles can now be renamed which was a lack of feature since the beginning.

The affiliation mechanisms has been renamed into "filters" to be more expressible about what it's doing (restricting access to the entities in the filters).

Filters can now target alliance in addition of the two others (character and corporation).

Permissions has been split in scope and include description in order to assist admin while he's building its role.

The interface is also providing a quick "check all" button near each scope which will allow admin to quickly design its roles.

Filters are now stored into a JSON object instead of plain SQL relationship which should be more flexible than prior. The current pattern is designed as bellow but not restricted to :
```
{
   $type: [$entities],
   "character": [{"id": $character_id, "text": $character_name}, ...],
   "corporation": [{"id": $corporation_id, "text": $corporation_name}, ...],
   "alliance": [{"id": $alliance_id, "text": $alliance_name}, ...]
}
```

Regarding roles member management, removal is dynamic and you can remove multiple members without having to refresh the page (using ajax).

Member addition, role meta modification and permission modification are only applied once the complete role is saved.

![image](https://user-images.githubusercontent.com/648753/58547089-09a98f80-8207-11e9-8ca5-ec2d6f7e6ad2.png)

**Comment by autophob** [comment]
As your standard averagely (non-)intelligent user I took a look at your screenshot here and I am actually not sure if the names and descriptions are that user friendly.

In my understanding, you are manipulating a group there.

So does, for example, "_Grant Access to Character Assets_" mean that with this ticked, characters can look at their own assets (shouldn't they be able to do so anyways?) or at other character's assets (corp/alliance/whatever)?

So whilst I am a fan of keeping it simple, it also should always be clear what exactly will happen.

Sorry if I'm getting it all wrong. In that case, just disregard this.

**Comment by warlof** [comment]
User always got access to content their own. (you'll get access to assets related to your character). That's a nonsense to deny them access to things they know.

If you check the box, you'll grant roles members the permission near the check. So, including data user own, member of the role can access data of everyone.

In case you're adding "limits", the permission will be only applied to data inside provided filters.

If that's non clear, how can it be improve?

**Comment by Cwittofur** [comment]
I think the granularity would be beneficial for some use cases. For me, where I'm hosting SeAT for my alliance, I want each Corporation CEO to have the ability to see all of their members but not see members from other Corporations. I want to avoid the 'snooping' nature that lends itself to having that kind of access. I also want to create an ability for people to be 'recruiters' and see anyone who is not in the Alliance the ability to audit them for recruiting purposes. I had touched upon this idea in a previous post I had made [https://github.com/eveseat/seat/issues/365](Inverse Permissions). 

All in all, Permissions or ACL's can be highly granular, and the users will end up deciding how to implement it, I think documentation with various scenarios would be highly beneficial as sometimes the wording may not be entirely intuitive as to what is happening and what kind of behaviour would be expected.

**Comment by autophob** [comment]
Yup, that's what I meant. The wording still seems a bit unclear. Of course any given user should have access to their very own data since they know it anyways.

It's just the wording. So e.g. instead of "Grant access to Character Assets" maybe "Grant access to view assets of all users within this Access List"? Something along the line. It's just words, yet I think they can make quite a difference.

**Comment by warlof** [comment]
@autophob I got the wording may be an issue. I'm open to any suggestions. With the new system, permissions are defined by a few things
 - a technical name : as an end user and except if you're developing on SeAT, you probably don't care about it
 - a label : it must be as short as possible and highlight the final purpose of the permission itself
 - a description : no limitation here, it can be as verbose as you want (well, avoid to write a book anyway 😉) - it most be a first help and describe the permission purpose. What it does.

**Comment by autophob** [comment]
@warlof Thanks for linking this to me. If you're ok with it i will have a go through it and give you my ideas amd thoughts.

**Comment by warlof** [comment]
of course you can, you should even be able to edit the file directly under github - which will automatically spawn a pull request on the repository.

We never deny anybody to contribute to SeAT :)

**Comment by flyingferret** [comment]
With the V4 revamp, is there going to be the possibility to inverse the filter?  For example, I want to have a recruiter only see recruits information and not his fellow alliance members information (dirty spies).   Or even better have the ability to affiliate a role against  members in a squad.  For example have the recruiter permissions affiliated with all members in the recruit squad?
