### ISSUE TITLE
Add a "My Corporation" affiliation

### ISSUE THREAD

**Issue by Thornsnake** [eveseat/seat#549]
**Problem:** Affiliations can be either set to "All Corporations" or manually selected for each corporation individually. If I want to give each CEO of a corporation access to only the information of the members in his corporation, I would have to make a group for each corporation and set the affiliation manually.

![Current](https://user-images.githubusercontent.com/43046258/55290113-178d9080-53cf-11e9-9ca7-d1e3753b8f9c.png)

**Expected:** Have one group with an affiliation option called "My Corporation", where the CEO will be affiliated with the corporation he is currently in.

![Expected](https://user-images.githubusercontent.com/43046258/55290146-91be1500-53cf-11e9-9cbb-71284ef10d1e.png)

That would be a huge help to automize stuff. People would be automatically affiliated with the corporation they are members of.

**Comment by warlof** [comment]
Hi @Thornsnake 

As I'm actually working on 4th generation, could you check quickly things from those two links and tell me if it could suit your need instead introducing a new "special case" in the ACL system ?

 - new ACL engine : https://github.com/eveseat/web/pull/318
 - Permissions roundtable : https://github.com/eveseat/seat/issues/546

**Comment by Thornsnake** [comment]
Looked over it, but if I'm honest I'm not entirely sure if this would work for my usecase. Could be wrong though and missing something.

We have a managed group called **"Director"** people can sign up for. When they do, they should get access to the member list and member infos of their corporation, but not of the other corporations. Currently it was only possible to give them either access to all corporations or I would have to create a separate role for each one of them.

It would be great if giving CEOs access to their members could be automized. That way we can have them do their own background checks and see what their members are up to.

**Comment by warlof** [comment]
With SeAT 4.0.x, there is a self-built permission which grant all access to characters in a corporation, to the CEO
