### ISSUE TITLE
Are there permissions to see all Pilots / Corps without having affiliations

### ISSUE THREAD

**Issue by Xeltor** [eveseat/seat#55]
I was wondering if there is some way to give someone the rights to see all Pilots / Corps without having to be a super user or granting every affiliation in the world.

**Comment by leonjza** [comment]
Not yet. There is a TODO for this though `RBAC roles additions for; all characters; all corporations`.
See [this](https://github.com/eveseat/seat/wiki/Todo-List).

**Comment by Xeltor** [comment]
Ah, i missed that somehow, that is great to know!

**Comment by leonjza** [comment]
This feature _finally_ landed in [this](https://github.com/eveseat/web/commit/e38c7bad8aa97bc721f6db5159c77a31b59fd452) commit and will be available in SeAT 2.0 🎉

**Comment by leonjza** [comment]
This has landed in SeAT 2.0. From the access manager, select the option "All Pilots" or "All Corporations" as needed.
