### ISSUE TITLE
[Feature Request] Make ESI address configurable to support Serenity

### ISSUE THREAD

**Issue by XiLingHost** [eveseat/seat#550]
EVE's Serenity server is already undergoing a second test. NetEase took over the game operations in China, and they promised that the version of the Serenity will be synchronized with the Tranquility version and open the ESI.
However, until now, they have not yet opened the full SSO interface like [Applications](https://developers.eveonline.com/applications), but ESI can already use the "authorization" on [ESI](https://esi.evepc.163.com/ui/) to get the token.

**Comment by XiLingHost** [comment]
Please make `datasource`, `esi_host` on eseye project can configure on .env file.

**Comment by warlof** [comment]
@XiLingHost will sso be the same address?

**Comment by XiLingHost** [comment]
@warlof 
Authorization URL: https://login.evepc.163.com/v2/oauth/authorize

Flow: implicit

**Comment by warlof** [comment]
@XiLingHost we already support alternative ESI source, but we have to adapt a few for the SSO flow. I've write a quick patch which should take care of this issue https://github.com/eveseat/eseye/pull/47.

If you could confirm it's working ? as I don't have any valid account on Serenity and Tranquility isn't callable from China alternative ^^
