### ISSUE TITLE
Per user timezone settings in profile to show local times

### ISSUE THREAD

**Issue by fugue2005** [eveseat/seat#554]
In order to display date and time to user according to its own timezone, it would be useful to add a "timezone" drilldown inside user profile.

**Comment by warlof** [comment]
Hi @fugue2005,

If it's targetting the SeAT-calendar plugin, it must be open on its own repository https://github.com/BenHUET/eveseat-calendar

**Comment by fugue2005** [comment]
are profile settings added by plugins?

i think it would be better if timezone selection was in the base, besides the calendar there may be future plugins that could make use of it.

**Comment by warlof** [comment]
I got it :)

**Comment by warlof** [comment]
Closing since it appears to be a duplication of #230
