### ISSUE TITLE
sql error when trying to edit a user

### ISSUE THREAD

**Issue by odboEVEtech** [eveseat/seat#555]
Hi all, I'm receiving an error when trying to edit a user: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'where clause' (SQL: select count(*) as aggregate from `users` where `email` = `***@***.***` and `id` <> 2113509384)

I'm trying to edit the user to force seat to see a character as its main character because my user isn't reading a main character. I'm using herpaderpaldent/seat-groups. Any help would be greatly appreciated. Thank you.

Screenshot: https://imgur.com/a/FubLXIR

**Comment by warlof** [comment]
Hi odboEVEtech,

Can you provide your packages versions please?

**Comment by warlof** [comment]
Closing due to duplication of eveseat/seat#493
