### ISSUE TITLE
Incorrect corp mining data

### ISSUE THREAD

**Issue by leg0las-devel** [eveseat/seat#559]
What i mined:

https://i.ibb.co/WGNj3sr/Screenshot-20190422-172059.png

What say me "corporation_industry_mining_observer_data" table

https://i.ibb.co/X47vrvM/Screenshot-20190422-172259.png

(two rows has identical quantity value)
Personal mining data (from "character_minings" table) correct:

https://i.ibb.co/mHdxqKJ/Screenshot-20190422-173051.png

**Comment by warlof** [comment]
Hi,

The content of `corporation_industry_mining_observer_data` is only related to mined stuff around refinery owned by your own corporation. So, the fact that its content and your own ledger doesn't match make sense as I assume you didn't mine all your ore on one of your moon ?

What's exactly your problem ?

**Comment by leg0las-devel** [comment]
As you can see, ore type id is R64. Loparite. It mined on one moon at 2019/01/23-24. Corp CEO, which owned structure is in SeAT. My corp/corp CEO in SeAT too.

**Comment by leg0las-devel** [comment]
I see a problem, maybe last (upper) row need be correct, but there old value

**Comment by warlof** [comment]
@leg0las-devel did you check if your jobs were running properly?

Can you give me the output of the following query? 
```
SELECT type_id, solar_system_id, character_id, SUM(quantity) 
FROM character_minings
WHERE date BETWEEN '2019-01-22' AND '2019-01-25'
GROUP BY type_id, solar_system_id, character_id, date
```

**Comment by leg0las-devel** [comment]
So, i run code:

`SELECT date, type_id, solar_system_id, character_id, SUM(quantity) 
FROM character_minings
WHERE date BETWEEN '2019-01-22' AND '2019-01-25' AND character_id=2*******76
GROUP BY type_id, solar_system_id, character_id, date`

Result:

https://i.ibb.co/G7zzcz1/Screenshot-20190423-112133.png

**Comment by warlof** [comment]
Can you add the `time` column and tell me what's your server timezone configuration?

**Comment by leg0las-devel** [comment]
timezone on server is GMT / ET

**Comment by warlof** [comment]
Well, apparently for CCP you mined a part of stuff from your screen on the 24th instead the 23rd which is I suppose the expected mining date you would have?

I can ask them for some investigation, but I will need your SeAT domain and Character ID. You can send me them in PM on our Slack.
