### ISSUE TITLE
The Character.walletJournal and Corporation.walletJournal permissions don't seem to work.

### ISSUE THREAD

**Issue by Xeltor** [eveseat/seat#56]
i added a group with a few users and gave them affiliations on corps and pilots, for some reason however they are unable to view the Wallet Journals (the tab isn't there) for any of them even though they have the walletJournal permissions.

**Comment by leonjza** [comment]
I have tried to replicate this locally but can't seem to be able to. I have a blank user. Granted the `CharacterWalletJournal` and `CharacterWalletTransactions ` and gave the affiliation for the role. I then assigned the role to the SeAT user and it seemed to work ok.

Could you maybe provide more detail on how you managed to hit this snag?

**Comment by warlof** [comment]
Up

**Comment by leonjza** [comment]
@Xeltor any more info on this?

**Comment by leonjza** [comment]
Closing due to lack of response.
