### ISSUE TITLE
Notifications and or Alerts ... again

### ISSUE THREAD

**Issue by Metzgermeister81** [eveseat/seat#563]
could not find a corresponding open issue so I open a new one.

I made the changes of https://github.com/eveseat/notifications/commit/8c5f154104f6a20c20ae378a40e7fbc22d7fe5ee to my file and then it looked like it is working but now it stopped again.
I then cleared the caches and I got another two messages posted which have been really really old ...
now the Killmail notification stopped working again.
I have up to date version of seat
```
php artisan seat:version
Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.6         | 3.0.6         |
| Console       | 3.0.5         | 3.0.5         |
| Eveapi        | 3.0.13        | 3.0.13        |
| Notifications | 3.0.3         | 3.0.3         |
| Web           | 3.0.20        | 3.0.20        |
| Services      | 3.0.8         | 3.0.8         |
+---------------+---------------+---------------+
```

Error I receive on ...
```
php artisan alerts:run
Processing Category: seat
Handling: New SeAT Account@Seat\Notifications\Alerts\Seat\NewAccount
Processing Category: char
Handling: New Mail Message@Seat\Notifications\Alerts\Char\NewMailMessage
Processing Category: corp
Handling: Inactive Corp Members@Seat\Notifications\Alerts\Corp\MemberInactivity
Handling: Killmails@Seat\Notifications\Alerts\Corp\Killmails

In Killmail.php line 118:

  Trying to get property of non-object
```

I know you are currently focussing work on 3.1 and switching to the new notification system but maybe someone hast an idea.

**Comment by warlof** [comment]
fixed into `eveseat/notifications@3.0.4` - for some reason, it hasn't been published early.
