### ISSUE TITLE
so seat just pushed 5 months worth of killmails to my discord server for over an hour

### ISSUE THREAD

**Issue by dstevens79** [eveseat/seat#565]
seriously?

**Comment by Metzgermeister81** [comment]
possibly this may have been mails that have been not parsed due to the error in the alerts runner
I had the same issue... I redirected it to a private channel until it stopped then directed it back

**Comment by dstevens79** [comment]
Yea I recently added more task threads due to a six month to 2 year queue
and I'm sure this was it catching up...
