### ISSUE TITLE
seat-worker Processing GroupSync error

### ISSUE THREAD

**Issue by xenon007** [eveseat/seat#567]
o7
* **Problem**: I have a error twice every sync iteration:
* **Expected**: Fix
* **Logs / Screenshots / Proof**:
seat-worker    | [2019-06-26 18:15:05] Processing: Herpaderpaldent\Seat\SeatGroups\Jobs\GroupSync
seat-worker    |
seat-worker    | In CallQueuedHandler.php line 148:
seat-worker    |
seat-worker    |   method_exists(): The script tried to execute a method or access a property
seat-worker    |   of an incomplete object. Please ensure that the class definition "Herpaderp
seat-worker    |   aldent\Seat\SeatGroups\Jobs\GroupSync" of the object you are trying to oper
seat-worker    |   ate on was loaded _before_ unserialize() gets called or provide an autoload
seat-worker    |   er to load the class definition
* **Version Info**: _PHP 7.3.6, Dockerized SeAT Version 3.0.21, Debian._

**Comment by warlof** [comment]
Hi @xenon007 

This is a third party application. 
You have to open your issue on this repository https://github.com/herpaderpaldent/seat-groups
