### ISSUE TITLE
GDPR question

### ISSUE THREAD

**Issue by kozzito** [eveseat/seat#569]
Hi.
I just registered on a corp page BEFORE i left my current corp, what means, all corp an alliance mails went to the "new corp". Ok, it's from the mechanic, i agree. But, since GDPR is a big point of view, i generally MISS the option to delete all my data from the server. 
Furthermore, the registration process does not inform me about data handling, who will be responsible in person for my data, who can view it, store it, alter it, or delete is.

Its a MAJOR issue.

I don't know if development is still ongoing or not, but the software in use, so this could be a responsibility question.

Thx for your attention and answer.

**Comment by warlof** [comment]
Hi @kozzito 

The responsible is the instance owner (tldr: the guy who install SeAT).
For details, it's all depend on the way SeAT is installed.

I don't see way to provide a magic answer which can be valid for all of them.
As an example, you can host SeAT on your own Raspberry - located inside your own home and in a country not covered by GDPR (it's not applied worldwide).

Alternatively, it can be hosted by a third party (OVH, Microsoft with Azure or whatever) inside a datacenter which can be or not covered by GDPR itself.

Finally, GDPR is applying to personal information - everything except mail address which is stored inside SeAT are game/virtual world related.

The only exception to this are mail and password which are account data related.

I'm curious to see your option regarding this though.

**Comment by kozzito** [comment]
Hi!

Wow, thx for the fast answer. So, can we say, my concern about alliance and corp eve mails is pointless, regardless their contents, because those contents are basically "ingame" contents?
The data storage method is understandable, but reveal another question for me.
-Do i have to be informed if the data storage is out of GDPR borders?
- Still don't have to provide a safe data delete option to erase ALL data if i want to?
Thx. :)

**Comment by Crypta-Eve** [comment]
You do also realise that GPDR does not apply here in 99% of all cases.

Your data contains nothing that can identify you personally. The only data that is personally identifiable is held by CCP.... Eve the IP addresses in the log, in most cases are deemed not personal as they can and do change so often. 

Therefore you do not have to be informed about anything to do with GPDR as there is no personal information here. 

Allowing a user to delete data is in general a bad idea IMHO (personal opinion) as this defeats the purpose of seat. If you forgot to invalidate your old api auths before changing corps then too bad for you and free intel to the old corp. GPDR claims cannot be abused here as a scare tactic to cover user forgetfulness/carelessness.

For reference here is the link to the site where you can review your third party applications:
[Third Party Apps](https://community.eveonline.com/support/third-party-applications/)

**Comment by leonjza** [comment]
This is not in scope for us for the reasons already mentioned.
