### ISSUE TITLE
Extractions: Moon composition wrong

### ISSUE THREAD

**Issue by autophob** [eveseat/seat#575]
SeAT shows wrong composition for Moons, Only the percentage of the last ore in analysis is taken into account and put unto all ores, which leads to weird numbers.

![opera_tyUGLkmuCU](https://user-images.githubusercontent.com/47808472/62106634-00d84700-b2a6-11e9-9cd9-b05fde4419de.png)

**Comment by warlof** [comment]
Hi,

Can you PM me the used report on Slack please?

**Comment by warlof** [comment]
https://github.com/eveseat/web/blob/ebb8a6394424acdcfb1c3576d27be633a4a5b617/src/Http/Controllers/Corporation/ExtractionController.php#L79

Need to compute a list of moon ID before running an update flow and delete all existing entries before starting with the creation flow
