### ISSUE TITLE
Execute vendor:publish for community packages installed with Docker

### ISSUE THREAD

**Issue by porowns** [eveseat/seat#576]
When installing community packages, it'd be a cleaner user experience to have the Dockerfile `php artisan vendor:publish --force` when installing a community package. Some packages like `eveseat-calendar` will not work properly without it. 

Migrate is no big issue since it'll persist with the database, but for people running many SEAT containers for other groups it's a major pain.

**Comment by warlof** [comment]
Hi,

is that still a thing with SeAT 4 Docker image ?

**Comment by Nfinished** [comment]
Hasn't been in my experience.
