### ISSUE TITLE
Undefined index: allianceName

### ISSUE THREAD

**Issue by Xtrah** [eveseat/seat#577]
* **Problem**: Running alerts:run gives error message.
* **Expected**: Getting notified with Slack integration about Structure Under Attack.
* **Logs / Screenshots / Proof**:
COMMAND: ~# php /var/www/seat/artisan alerts:run
Processing Category: seat
Handling: New SeAT Account@Seat\Notifications\Alerts\Seat\NewAccount
Processing Category: char
Handling: New Mail Message@Seat\Notifications\Alerts\Char\NewMailMessage
Handling: Character Left Corporation@Seat\Notifications\Alerts\Char\CharLeftCorpMsg
Handling: Structure Services Offline@Seat\Notifications\Alerts\Char\StructureServicesOffline
Handling: Moon Extraction Finished@Seat\Notifications\Alerts\Char\MoonMiningExtractionFinished
Handling: Structure Fuel Alert@Seat\Notifications\Alerts\Char\StructureFuelAlert
Handling: Corporation Bill@Seat\Notifications\Alerts\Char\CorpAllBillMsg
Handling: Sovereignty Structure Reinforced@Seat\Notifications\Alerts\Char\SovStructureReinforced
Handling: Sovereignty Structure Destroyed@Seat\Notifications\Alerts\Char\SovStructureDestroyed
Handling: Structure Under Attack@Seat\Notifications\Alerts\Char\StructureUnderAttack
In StructureUnderAttack.php line 122:

  Undefined index: allianceName

* **Version Info**:
Everything is up to date as of this post with a clean install.

**Comment by warlof** [comment]
Hi @Xtrah 

Can you send me in PM on Slack the output of that query please ?
```
select *
from character_notifications
where `timestamp` > '2019-08-01'
and type = 'StructureUnderAttack';
```
