### ISSUE TITLE
[Notifications] Disable unrelated affiliation

### ISSUE THREAD

**Issue by Xtrah** [eveseat/seat#578]
* **Problem**: 
Slack Notifications with  `Corporation Affiliation` as filter doesn't send any notifications
* **Expected**: 
Set up Slack bot for one certain corporation. Send all notifications related to this corporation to Slack channel. Only works without any `affiliation` set right now.

* **Logs / Screenshots / Proof**: 
![Filter-bug](https://user-images.githubusercontent.com/12988459/63100042-86324b80-bf76-11e9-9884-fc6beaa325fb.PNG)
This doesn't send any notifications through to Slack. However if the `affiliations` are removed they go through,

* **Version Info**:
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.8         | 3.0.8         |
| Console       | 3.0.5         | 3.0.5         |
| Eveapi        | 3.0.17        | 3.0.17        |
| Notifications | 3.0.6         | 3.0.6         |
| Web           | 3.0.23        | 3.0.23        |
| Services      | 3.0.9         | 3.0.9         |
+---------------+---------------+---------------+

**Comment by warlof** [comment]
@Xtrah all your listed notifications are `characters` scoped - so, it make sense
however, corp drilldown should be disabled

**Comment by warlof** [comment]
Closing since the affiliation thing has been simplified and notifications system changed with 4.0.x
