### ISSUE TITLE
Improve character left corporation notification

### ISSUE THREAD

**Issue by Xtrah** [eveseat/seat#579]
* **Problem**: Lacking information. 
* **Expected**: Which character left which corporation? Suggestion: Include character, corporation, time, main character
* **Logs / Screenshots / Proof**: Current notification:
![improve_leftcorp](https://user-images.githubusercontent.com/12988459/63381708-862cb400-c399-11e9-8897-b4c65a217af2.PNG)
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
```
| Vendor          | Package Name   | Installed Version |
| --------------- | -------------- | ----------------- |
| eveseat         | api            | 3.0.8             |
| eveseat         | console        | 3.0.5             |
| eveseat         | eveapi         | 3.0.17            |
| eveseat         | notifications  | 3.0.6             |
| eveseat         | services       | 3.0.9             |
| eveseat         | web            | 3.0.23            |
| herpaderpaldent | seat-groups    | 1.7.2             |
| warlof          | seat-connector | 1.2.4             |
| warlof          | seat-teamspeak | 4.0.3             |
```

**Comment by Xtrah** [comment]
The notification `Inactive Corp Members` could also be improved with a character name, as it's also useless in its current state as you don't know which character it applies to. The link it provides is just to the related corporation.
![improve_inactivemember](https://i.imgur.com/bABYenI.png)

**Comment by warlof** [comment]
This is standard since SeAT 4
