### ISSUE TITLE
Add Permissions to A Corp not Individual

### ISSUE THREAD

**Issue by blakdragan7** [eveseat/seat#581]
I am trying to figure out how to add permissions to an entire corp instead of one character. 
I recently installed the seat-teamspeak package and want specific corps to be able to see it without having to assign every person as they log in. 
I can't seem to find a way to do this though.
I would have asked on slack except it wouldn't let me join the slack channel for some reason. Any help would be greatly appreciated.

**Comment by Xtrah** [comment]
Read SeAT docs
https://eveseat.github.io/docs/admin_guides/role_based_access_control/

>Automatically assigning users to a role based on ingame role, title or corporation/alliance membership is not part of the core SeAT packages and to do this you would need a SeAT plugin like herpaderpaldent/seat-groups. Affiliation does not give permissions to users, but restricts access to use given permissions only on specified entities.

**Comment by blakdragan7** [comment]
yup i just found that. Thank you for the quick response though !
