### ISSUE TITLE
Predis/Redis is going to be depreciated

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#583]
https://github.com/eveseat/seat/blob/851745cf6c510c6ae526fd672f6454464133735d/composer.json#L20

Consider switching to Phpredis (it's lighter on RAM anyways). Predis is going to be depreciated with laravel6: see https://github.com/laravel/ideas/issues/1779 

already merged in L6 https://github.com/laravel/framework/pull/29688

**Comment by warlof** [comment]
We will bump to L6 any time soon anyway, so definitely the switch will be made.

Horizon is still using prédis for now which is the first consumer though, so, have to wait a bit.

**Comment by herpaderpaldent** [comment]
Horizon works with both: https://github.com/laravel/framework/pull/29688#issuecomment-523927841 

It's just a heads up if you run into the topic.
