### ISSUE TITLE
User admin: Setting email to one used by another character gives a blank 500 page

### ISSUE THREAD

**Issue by torlivar** [eveseat/seat#59]
### To reproduce:
1. Go into user admin page (as a superuser)
2. Edit an existing user
3. Enter a new email for the user - pick one that is used by another user
4. Press Edit

Expected: Change of the email (or if the constraint is hard, an error message explaining what is wrong)
Actual: Server returned status 500

**Comment by leonjza** [comment]
Thanks for a really nice bug report. Ill check it out soon™
