### ISSUE TITLE
Weird stuff with corporation title(s) shown/used

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#598]
For this ticket, with corp title I mean the corporation role title with the ingame matrix that gives rights, not the 'title' text that can be entered manually for any corp character.

* **Problem**: 
A few recruiters noticed they couldn't view people in our Seat database anymore. These people have an ingame corporation title 'Recruiter' that gets applied in two ways in Seat: They get automatically added to a 'Recruiter' Discord channel and with SeAT Groups get tied to a Seat role 'Recruiter' that gives permissions to view other characters.

On the page of a recruiter character themselves (/character/view/sheet/xxx) the title isn't visible anymore but other, seemingly random, corporation titles are shown (those titles do not exist in our corp)

This is not just recruiters but goes wrong with anyone that has corp titles

The Discord channel hasn't been affected so the discord connector is still aware of the correct corporation titles somehow.

* **Logs / Screenshots / Proof**: 

Ingame
![image](https://user-images.githubusercontent.com/25641678/68063984-09fa0980-fd16-11e9-8128-c14fc27555c8.png)

Seat
![image](https://user-images.githubusercontent.com/25641678/68063988-18e0bc00-fd16-11e9-8e7d-eed9ecfa36db.png)

Correct corp titles are in database
![image](https://user-images.githubusercontent.com/25641678/68064014-6b21dd00-fd16-11e9-9720-a91e7f5a244a.png)

But one of these weird corp titles comes from a different corp it seems
![image](https://user-images.githubusercontent.com/25641678/68064010-580f0d00-fd16-11e9-8e5e-ee5f7c0f4301.png)

* **Version Info**: 
Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.8         | 3.0.8         |
| Console       | 3.0.5         | 3.0.5         |
| Eveapi        | 3.0.17        | 3.0.17        |
| Notifications | 3.0.6         | 3.0.6         |
| Web           | 3.0.25        | 3.0.25        |
| Services      | 3.0.11        | 3.0.11        |
+---------------+---------------+---------------+

Cache removed, view cache removed

**Comment by warlof** [comment]
@kwazulueve 

try to clear cache first - then wait for jobs to run once :
`php artisan seat:cache:clear` will do that for you

**Comment by kwazulueve** [comment]
Thanks, has cleared cache already at the time of filing this issue but yeah the jobs that ran overnight apparently fixed itself :)
