### ISSUE TITLE
Clean Ubuntu SeAT install API issue

### ISSUE THREAD

**Issue by phattpks** [eveseat/seat#60]
New to SeAT and super excited to see it in action!!
Sorry if this is not the place to post this but I have a error after clean install.
(Ubuntu 14.04 install.)

I am getting a Invalid Key pair Exception when adding API keys manually.
If I import the keys using the import tool they work just fine.

Attached Error:
[InvalidKeyPairException.txt](https://github.com/eveseat/seat/files/113158/InvalidKeyPairException.txt)

One Click install went with zero error's by the way!!! Thanks for the great script.

**Comment by leonjza** [comment]
Thanks. I can definitely replicate this now. Working on a fix.
