### ISSUE TITLE
[Feature Request] pilots can generate expirable link to share it with recruit officers, before they join corp

### ISSUE THREAD

**Issue by nsdonner** [eveseat/seat#603]
Hi, we trying to use seat centralized, for all our coalition, so at now recruit officers forced to ask permissions from admins to check new pilots, that wants to join alliance. How about to make pilots be able to generate expirable link to their account with read rights to share it with recruit officers, before they join any of corp.

**Comment by warlof** [comment]
Hi @nsdonner 

I don't think we will implement such system.
However, SeAT 4.x will get a kind of groups system built-in where people would be able to apply on their own.

Some of them could be moderated, others will be open.

Those groups will be directly coupled to roles.

**Comment by Xtrah** [comment]
Will the group system include all features of [seat-groups](https://github.com/herpaderpaldent/seat-groups)? Most importantly automatically adding users to a group based on in-game corp membership, in-game roles/titles, etc.?

**Comment by leonjza** [comment]
To be honest, implementing a temp character view link won't be very hard. If we keep it simple in that one could see everything, we can add a middleware over the character routes and some simple crud for temp links tied to an account. This would be a good PR :)

**Comment by benthompson0** [comment]
@warlof you can assign this one to me.
