### ISSUE TITLE
Being able to add custom links in sidebar

### ISSUE THREAD

**Issue by autophob** [eveseat/seat#605]
Our alliance uses a variety of different services (Buyback, Pathfinder, Skylizer, Structure Timers, ThunderED...).

Having the ability to add links in an easy way (e.g. Settings -> Custom Links) which then appear on the menu would be a nice addition.

**Comment by benthompson0** [comment]
@warlof please assign to me.

**Comment by warlof** [comment]
Closing as it's been addressed by eveseat/web#414.

This will be available in SeAT 4 ;)
