### ISSUE TITLE
ESI errors block login process

### ISSUE THREAD

**Issue by wfjsw** [eveseat/seat#609]
This issue is to continue discussion happened earlier to address the user experience failure on user login routine when error `500 Internal Server Error` is returned solely because of `handleProviderCallback` calling ESI methods synchoronously which subjects to additional limits and temporary external exceptions.

This issue assumes that SSO endpoints are accessible at any time.

* **Problem**: User authentication process interrupted for non-authentication related ESI exceptions. E.g. https://github.com/eveseat/web/blob/4.0.x/src/Http/Controllers/Auth/SsoController.php#L81
* **Expected**: 
    1. User are not present with bare 500 page on this error. At least a user-friendly error page explaining what is happening should be displayed instead.
    2. The authentication process is not interrupted. Refresh tokens should be held in database with the failed request retrying at the background (in job queue) so users don't have to be instructed to retry that many time for non-authentication issues.
        * It is okay to block the application main UI until said requests are finished in the background.
* **Proposed Solutions**:
    1. Shortcut (proposed by Slack#Crossfire): 
         Do proper error handling, display the error and reject the authentication request gracefully.
    2. The long path:
         1. Try to do these requests in login process in case they succeed, but catching non-404 errors they throw and continue the process.
         2. If above requests failed, schedule background jobs to retry them later.
              * Add a new command that list users missing these fields and schedule retries.
         3. In `auth` middleware, check if these fields are present. If not, render a page indicating *we are still fetching critical informations* and render a logout button instead of normal pages. The render process of this page should not access any incomplete records.

**Comment by warlof** [comment]
The flow has been reviewed with last changes
