### ISSUE TITLE
character.sheet permission needed when given.

### ISSUE THREAD

**Issue by op6sie** [eveseat/seat#61]
Great tool but.

I have more then 1 corp apikey in seat.
I have recruiters that i want to see only 1 corp.
so in the Access Managerment role (recruitment) i have this as access

Apikey.delete
Apikey.detail
Apikey.toggleStatus
Apikey.list
Apikey.update
People.view
Character.sheet

Corporation Affiliations : The Dutch East India Company.

then i do with an test account that has the role recruitment :  
Api management > list eve apikeys > pick a char in there
then i get : Unauthorized Request

with my supervisior i check the log : 
2016-02-04 08:59:16	tonny_test	authorization	Request to character/view/sheet/1093497501 was denied by the characterbouncer. The permission required is character.sheet.

but is has the permission Character.sheet.....

now when i add this char affiliation to the role recruitment all works well

Cheers.

[diagnose.txt](https://github.com/eveseat/seat/files/117124/diagnose.txt)
[laravel.txt](https://github.com/eveseat/seat/files/117128/laravel.txt)

there is no error to screenshot when putting debug on.

**Comment by leonjza** [comment]
Thanks for the report. Will test and feedback asap.

**Comment by op6sie** [comment]
extra information, if i give all priviledges (except supervisor) then it still does not work.
only with supervisor it works correct.

**Comment by OlllieB** [comment]
I am having a similar issue, I could give all the privileges apart from superuser to a newly created role and it gives this error: Request to character/view/sheet/1504350962 was denied by the characterbouncer. The permission required is character.sheet.

**Comment by leonjza** [comment]
Ok. Please could everyone recheck the permission config (`configuration/access/roles`). If a user does not own a character, they need to be granted the permission *and* an affiliation (character / corp). Granting someone just the permissions does not give them the permission to all characters / corporations. Adding an option for all chars/corps is something that is on the [todo](https://github.com/eveseat/seat/wiki/Todo-List)

**Comment by op6sie** [comment]
when granted corp/character affiliation it works.
but i be needing the all chars option as the super option is not the best
option for a corp recruiter.

Cheers still the error does not meet the message....
the needed affiliation is not i the error text

Cheers.


2016-02-17 19:47 GMT+01:00 Leon Jacobs <notifications@github.com>:

**Comment by leonjza** [comment]
The errors is technically correct. All that is missing is hints as to what is wrong.

**Comment by op6sie** [comment]
Well we could debate on that.
But any eta on the item in the todo list?

Cheers

2016-02-18 13:37 GMT+01:00 Leon Jacobs <notifications@github.com>:

**Comment by leonjza** [comment]
As soon as I have time™ or a PR comes in ;)

**Comment by leonjza** [comment]
Closing this as there is an outstanding PR in eveseat/web#22 for this capability to be added.
