### ISSUE TITLE
drop_character_id_from_mail_headers_table runs too slowly

### ISSUE THREAD

**Issue by wfjsw** [eveseat/seat#610]
This issue is an attempt to gather solution for speeding up migration `2019_10_30_131410_drop_character_id_from_mail_headers_table` on a huge dataset.

https://github.com/eveseat/eveapi/blob/01f03ab404b16a3dcc6689f602ba146d90793a2d/src/database/migrations/2019_10_30_131410_drop_character_id_from_mail_headers_table.php#L110-L128

Solution tried:
1. Create index for `mig_mail_recipients` => it speeds up first 200000 records, but not the rest([Related](https://stackoverflow.com/questions/4481388/why-does-mysql-higher-limit-offset-slow-the-query-down))
2. Switch to `cursor()` => Out of memory ([Related](https://github.com/laravel/framework/issues/14919))

Summary of current situation:
1. each == chunk(1000, foreach), chunk requires at least one ORDER BY
2. Without index, MySQL create a temporary index for sorting upon each query (filesort)
3. MySQL stops using existed indexes on OFFSET > 200000 and will always do an expensive filesort
4. cursor(), although designed for this specific use case, does not work because it tries to cache all results into memory, causing an out of memory error. Note that it does not seem to work even if `PDO::MYSQL_ATTR_USE_BUFFERED_QUERY` is set.

**Comment by warlof** [comment]
Closing it for now as it appears we would not be able to reduce the duration of really large mail tables migrations. If anyone is stuck with this, fill free to reopen it.
