### ISSUE TITLE
Workers/Processes disappearing in horizon dashboard

### ISSUE THREAD

**Issue by WiscoSailor91** [eveseat/seat#616]
* **Problem**:  laravel/horizon screen shows workers disappearing & reconnecting. The jobs per hour figure and expected wait time displayed fluctuates accordingly as well. 8 workers are on the main seat instance, 16 workers each on 2 separate servers (40 total workers).

* **Logs / Screenshots / Proof**: Looking through the logs we have not found an obvious cause for this.
![SeATExample1](https://user-images.githubusercontent.com/63900367/82130009-78278a80-9795-11ea-89ed-ad7d08d497ee.JPG)
![SeATExample2](https://user-images.githubusercontent.com/63900367/82130010-78c02100-9795-11ea-83c2-e505b3bdca3b.JPG)
![SeATExample3](https://user-images.githubusercontent.com/63900367/82130011-78c02100-9795-11ea-976d-73d0e14e28a9.JPG)

**Comment by warlof** [comment]
Hi,

SeAT 3 isn't supporting splitted instances - at least, not without changes.
Supervisor and queue are handled by the web package.

You will have to tweak your installation to beeing able to run such configurations.
https://github.com/eveseat/web/blob/3.0.x/src/WebServiceProvider.php#L284-L318
