### ISSUE TITLE
Issue with SkillsController.php - getCharacterSkillsCoverageChartData($character_id)

### ISSUE THREAD

**Issue by lk77** [eveseat/seat#618]
Hello

* **Problem**:

Issue with SkillsController.php, line 111 there is an exception :: property 'name' of undefined

* **Expected**: 

Character skills coverage are recovered correclty, or a page is displayed saying that character skill coverage can"t be recovered.

* **Logs / Screenshots / Proof**:

[2020-06-05 19:45:01] production.ERROR: Trying to get property 'name' of non-object {"userId":****,"email":"***","exception":"[object] (ErrorException(code: 0): Trying to get property 'name' of non-object at /var/www/seat/vendor/eveseat/web/src/Http/Controllers/Character/SkillsController.php:111)

* **Version Info**: 

+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 3.0.8         | 3.0.8         |
| Console       | 3.0.5         | 3.0.5         |
| Eveapi        | 3.0.20        | 3.0.20        |
| Notifications | 3.0.6         | 3.0.6         |
| Web           | 3.0.28        | 3.0.28        |
| Services      | 3.0.11        | 3.0.11        |
+---------------+---------------+---------------+

i've added an ``` optional($character)->name ``` as a temporary fix, it would be better to add an if statement to check if character is defined or return a 404 if not found. It would be necessary to handle 404's in the front aswell

thanks

**Comment by warlof** [comment]
hi,

why not submiting a pull request if you know where and how making change ? :)

**Comment by lk77** [comment]
Well,

i know how i would do it, but i don't know this package enough to make a PR.

**Comment by benthompson0** [comment]
This appears to be an issue in your DB @lk77 - it seems to indicate you are missing a corresponding character entry in the CharacterInfo model (character_infos DB table) for the character who's skills you are trying to get the data of. 

The API jobs should be updating the character info models for you regularly, although if that particular character is missing a refresh token, you should check you have the esi:update:publicinfo command scheduled to run as well so it can find and fill in this missing information. 

Something I would like you to check as well is do you have "Cleanup Stale Data" enabled in settings, and also have the seat:admin:maintenance job scheduled to run? Wondering if it is possible the cleanup job removed the CharacterInfo entry for some reason and left behind orphaned skills (and possible others as well) models.

**Comment by warlof** [comment]
It might be caused if you deleted the character which was defined as user main character. 
https://github.com/eveseat/web/blob/fab9f574b039040437e5fa7f3d938a97bbce7b8e/src/Http/Controllers/Character/SkillsController.php#L103

**Comment by lk77** [comment]
Hello,

yes cleanup is on.

it was on a brand new character, first login.

**Comment by warlof** [comment]
This is is normally non longer valid with new version.

Fill free to reopen the issue if you fall in it again.
