### ISSUE TITLE
Items to select when getting a full apikey.

### ISSUE THREAD

**Issue by op6sie** [eveseat/seat#62]
Hi,
is it possible to create a list of items we wish from the apikey?
now it just downloads all from the apikey, but what if i do not want the bookmarks?
no way to skip it.

Cheers.

**Comment by leonjza** [comment]
It is possible to disable workers globally. See [this](https://github.com/eveseat/seat/wiki/Eveapi-Configuration) wiki article. In your case, you will create a config file with something like:

```php
<?php
return [

    'disabled_workers' => [
        'api'         => [],
        'character'   => [
            Seat\Eveapi\Api\Character\Bookmarks::class,
        ],
        'corporation' => [],
        'eve'         => [],
        'map'         => [],
        'server'      => []
    ]
];
```

**Comment by op6sie** [comment]
sorry for the late reply but more then 1 item like bookmarks and standings
perhaps


2016-02-05 9:28 GMT+01:00 Leon Jacobs <notifications@github.com>:

**Comment by leonjza** [comment]
Just add all the classes of the workers you want to disable then. They can be comma separated as this is just a PHP `array`.
