### ISSUE TITLE
Missing items in killmail

### ISSUE THREAD

**Issue by akturis** [eveseat/seat#620]
* **Problem**: There are few items with same typeid exist in killmail, but job overwrites them in one entry
* **Expected**: Each killmail items must be stored different entries
* **Logs / Screenshots / Proof**: https://esi.evetech.net/latest/killmails/84807471/269c9c8ecf8afd0490f5bd1de9c081bd42a6d594/
item_type_id - 31932
https://bit.ly/2A1zD9b
* **Version Info**:  SeAT v3.0.0

Maybe there need to add field "flag" for searching
```
                    KillmailVictimItem::firstOrNew([
                        'killmail_id'  => $killmail_id,
                        'item_type_id' => $item->item_type_id,
                    ])->fill([
                        'quantity_destroyed' => property_exists($item, 'quantity_destroyed') ?
                            $item->quantity_destroyed : null,
                        'quantity_dropped'   => property_exists($item, 'quantity_dropped') ?
                            $item->quantity_dropped : null,
                        'singleton'          => $item->singleton,
                        'flag'               => $item->flag,
                    ])->save();
```

**Comment by warlof** [comment]
it makes sense
would be fixed on SeAT 4.0.x though - since this table isn't used by core actually and SeAT 4.0 is on final line.
