### ISSUE TITLE
Loyalty point data

### ISSUE THREAD

**Issue by leonjza** [eveseat/seat#623]
* **Problem**: It does not look like SeAT grabs loyalty point data, even though the [scope](https://github.com/eveseat/eveapi/blob/59ed7416c0f5c16b771f63cc6fac5355015d0cc6/src/Config/eveapi.scopes.php#L39) for it is requested by default.

* **Expected**: Loyalty point data to be pulled from ESI and displayed in the UI where appropriate.

This would be a great feature to PR for someone that is keen to dive into the full lifecycle of a feature that requires the ESI -> persistence -> UI cycle.

**Comment by warlof** [comment]
Talking about at least this endpoint https://esi.evetech.net/ui/#/operations/Loyalty/get_characters_character_id_loyalty_points

**Comment by recursivetree** [comment]
Loyalty points have been added. I think this can be closed
