### ISSUE TITLE
DB Backup & Restore

### ISSUE THREAD

**Issue by rock5917** [eveseat/seat#628]
_Please don't log issues for general discussions or non code problems. Instead, join us on Slack for a chat.
I have tried that, but I got no reply._

* **Problem**: _Whats wrong?_
I can backup my seat DB(mariadb) with mysqldump and restore but it doesn't work. So I guess something is missing before and/or after that.
* **Expected**: _What did you expect to happen?_
I expected for this to work.
* **Logs / Screenshots / Proof**: _The more information you give the better!_
From /domain/horizon/failed/
Error
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.invTypes' doesn't exist in /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
Current User: www-data
PHP Version: 7.1.33-16+ubuntu18.04.1+deb.sury.org+1
Host OS: Linux servername-a 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64
SeAT Basepath: /var/www/seat

**Comment by warlof** [comment]
`invTypes` is part of sde. Run `php artisan eve:update:sde --force` to get the table. 

How did you dump your database exactly?

**Comment by rock5917** [comment]
> `invTypes` is part of sde. Run `php artisan eve:update:sde --force` to get the table.
> 
> How did you dump your database exactly?

mysqldump -u root -p database_name > database_name.sql

*I did this without "php artisan down"

**Comment by warlof** [comment]
can you try to dump your database again using `mysqldump -uDB_USER -pPASSWORD seat --verbose | gzip > database_name.sql.gz` once you pull SDE back and try to restore it ?

Also, always cut jobs and turn SeAT in maintenance when you dump database in order to avoid database inconsistency and locks

`service supervisor stop` will cut jobs
`php artisan down` will set SeAT in maintenance

**Comment by rock5917** [comment]
> can you try to dump your database again using `mysqldump -uDB_USER -pDB_PASSWORD seat --verbose | gzip > database_name.sql.gz` once you pull SDE back and try to restore it ?

1. When you say pull SDE back your are talking about this "sudo -H -u www-data bash -c 'php /var/www/seat/artisan eve:update:sde'"? 
2. Should I pull SDE back before or after dumping the DB?

**Comment by warlof** [comment]
1) I'm indead refering to this command
2) pull SDE back before, as the purpose is to figure if yes or no you had an issue with your original dump

**Comment by rock5917** [comment]
It works with a new backup. Thanks.

**Comment by eotero13** [comment]
> [SeAT Diagnostics.txt](https://github.com/eveseat/seat/files/4950179/SeAT.Diagnostics.txt)
> When I try to go to domain/character/view/sheet/number I get this error:
> [error.txt](https://github.com/eveseat/seat/files/4948893/error.txt)

This is the error people are having here, due to something wrong in the eveapi.
https://github.com/eveseat/seat/issues/629
