### ISSUE TITLE
Undefined property: Illuminate\Database\Eloquent\Relations\HasOne::$start_date

### ISSUE THREAD

**Issue by jim1471** [eveseat/seat#629]
Hi,

When trying to select any character sheet the following error occurs;

`

(4/4) ErrorExceptionUndefined property: Illuminate\Database\Eloquent\Relations\HasOne::$start_date (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/includes/summary.blade.php) (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/includes/summary.blade.php) (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/includes/summary.blade.php)
--
in d75db327921c748b6fa3610768f9dadad521ece9.php line 59
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 45
at PhpEngine->evaluatePath('/var/www/seat/storage/framework/views/e32ee9b2216d33fd78cabe5d170538a4a3517751.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'attributes' => object(CharacterAttribute), 'fatigue' => object(CharacterFatigue), 'character_info' => object(CharacterInfo), 'employment' => object(Collection), 'implants' => object(Collection), 'last_jump' => object(CharacterClone), 'jump_clones' => object(Collection), 'skill_queue' => object(Collection), 'titles' => object(Collection)))in CompilerEngine.php line 59
at CompilerEngine->get('/var/www/seat/vendor/eveseat/web/src/resources/views/character/sheet.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'attributes' => object(CharacterAttribute), 'fatigue' => object(CharacterFatigue), 'character_info' => object(CharacterInfo), 'employment' => object(Collection), 'implants' => object(Collection), 'last_jump' => object(CharacterClone), 'jump_clones' => object(Collection), 'skill_queue' => object(Collection), 'titles' => object(Collection)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 42
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 724
at Router::toResponse(object(Request), object(View))in Router.php line 698
at Router->prepareResponse(object(Request), object(View))in Router.php line 658
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CharacterBouncer.php line 53
at CharacterBouncer->handle(object(Request), object(Closure), 'sheet')in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Locale.php line 44
at Locale->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 67
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 68
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 660
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 635
at Router->runRoute(object(Request), object(Route))in Router.php line 601
at Router->dispatchToRoute(object(Request))in Router.php line 590
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 54

`

**Comment by ssgtmccrae** [comment]
This is happening with one of our players as well. Please let me know if you want additional logs.

**Comment by ssgtmccrae** [comment]
Actually, after further investigation this is all of our characters when opened via the "All Characters" screen at the moment.

**Comment by leonjza** [comment]
I think this is related to some bad commits that made it into the 3.x branch when fixing up the unannounced stats endpoint removal from CCP.

**Comment by warlof** [comment]
yeah, there is a mixing of 4.0.x stuff which land into latest release - I have to find how to recover from all ran migrations :(

https://github.com/eveseat/eveapi/commit/d53f6a4a557e506ab599ae66b10d572e099d2c18
https://github.com/eveseat/eveapi/commit/7cb821f104e2aca99eb4ceb5fd13bac7b99d7f17

The easier is actually to rollback to eveapi 3.0.20 and restore a database backup older than July 19th - 9:27pm

**Comment by eotero13** [comment]
I am having the same issue after updating today. Let me know if there is anything you need me to provide such as logs.

**Comment by rock5917** [comment]
> yeah, there is a mixing of 4.0.x stuff which land into latest release - I have to find how to recover from all ran migrations :(
> 
> [eveseat/eveapi@d53f6a4](https://github.com/eveseat/eveapi/commit/d53f6a4a557e506ab599ae66b10d572e099d2c18)
> [eveseat/eveapi@7cb821f](https://github.com/eveseat/eveapi/commit/7cb821f104e2aca99eb4ceb5fd13bac7b99d7f17)
> 
> The easier is actually to rollback to eveapi 3.0.20 and restore a database backup older than July 19th - 9:27pm

Should we expect the same issue with the docker installation?
I don't know how big is this issue but, can we estimate that it could be fixed in like 3/6 months or a year?

**Comment by leonjza** [comment]
Join slack for an active conversation on this.

**Comment by eotero13** [comment]
> > yeah, there is a mixing of 4.0.x stuff which land into latest release - I have to find how to recover from all ran migrations :(
> > [eveseat/eveapi@d53f6a4](https://github.com/eveseat/eveapi/commit/d53f6a4a557e506ab599ae66b10d572e099d2c18)
> > [eveseat/eveapi@7cb821f](https://github.com/eveseat/eveapi/commit/7cb821f104e2aca99eb4ceb5fd13bac7b99d7f17)
> > The easier is actually to rollback to eveapi 3.0.20 and restore a database backup older than July 19th - 9:27pm
> 
> Should we expect the same issue with the docker installation?
> I don't know how big is this issue but, can we estimate that it could be fixed in like 3/6 months or a year?

I would say yes. I am running the docker installation and am now experiencing this issue after updating.

**Comment by leonjza** [comment]
Docker images are re-built when packages are tagged, so yes.

**Comment by warlof** [comment]
Waiting a better way to fix the current state - here is the workaround

# Docker instances

0. **MAKE A BACKUP FROM YOUR DATABASE** (and be sure it's recoverable)
1. cut your worker container (`docker stop seat-worker`)
2. open a shell into the app container (`docker exec -it seat-app sh`)
3. from then, you'll need to change 6 files

## 2019_08_17_212222_remove_character_contacts_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_212222_remove_character_contacts_surrogate_key.php
```

replace line 53 from

```
$table->dropPrimary();
```
to
```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_17_212459_remove_character_contact_labels_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_212459_remove_character_contact_labels_surrogate_key.php
```

replace line 56 from

```
$table->dropPrimary();
```
to
```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_17_212554_remove_corporation_contacts_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_212554_remove_corporation_contacts_surrogate_key.php
```

replace line 53 from

```
$table->dropPrimary();
```

to

```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_17_213047_remove_corporation_contact_labels_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_213047_remove_corporation_contact_labels_surrogate_key.php
```

replace line 56 from

```
$table->dropPrimary();
```

to

```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_24_192640_remove_character_bookmarks_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_24_192640_remove_character_bookmarks_surrogate_key.php
```

replace line 52 from

```
$table->dropIndex('character_id');
```

to

```
$table->dropIndex(['character_id']);
```

then, save and leave (escape, :wq)

## 2019_08_25_090128_remove_corporation_standings_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_25_090128_remove_corporation_standings_surrogate_key.php
```

replace line 53 from

```
$table->dropPrimary();
```

to

```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)
4. rollback last 12 migrations using `docker-compose exec seat-app php artisan migrate:rollback --step=12`
5. follow usual update flow (pull image, up -d, ...)

# Blade instances

0. **MAKE A BACKUP FROM YOUR DATABASE** (and be sure it's recoverable)
1. cut your worker container (`sudo servcice supervisor stop`)
2. from then, you'll need to change 6 files

## 2019_08_17_212222_remove_character_contacts_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_212222_remove_character_contacts_surrogate_key.php
```

replace line 53 from

```
$table->dropPrimary();
```
to
```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_17_212459_remove_character_contact_labels_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_212459_remove_character_contact_labels_surrogate_key.php
```

replace line 56 from

```
$table->dropPrimary();
```
to
```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_17_212554_remove_corporation_contacts_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_212554_remove_corporation_contacts_surrogate_key.php
```

replace line 53 from

```
$table->dropPrimary();
```

to

```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_17_213047_remove_corporation_contact_labels_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_17_213047_remove_corporation_contact_labels_surrogate_key.php
```

replace line 56 from

```
$table->dropPrimary();
```

to

```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)

## 2019_08_24_192640_remove_character_bookmarks_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_24_192640_remove_character_bookmarks_surrogate_key.php
```

replace line 52 from

```
$table->dropIndex('character_id');
```

to

```
$table->dropIndex(['character_id']);
```

then, save and leave (escape, :wq)

## 2019_08_25_090128_remove_corporation_standings_surrogate_key

```
vi /var/www/seat/vendor/eveseat/eveapi/src/database/migrations/2019_08_25_090128_remove_corporation_standings_surrogate_key.php
```

replace line 53 from

```
$table->dropPrimary();
```

to

```
$table->dropColumn('id');
```

then, save and leave (escape, :wq)
3. rollback last 12 migrations using `php artisan migrate:rollback --step=12`
4. drop eveapi vendor directory using `sudo rm -R /var/www/seat/vendor/eveseat/eveapi`
5. update using `composer update --no-dev`
6. start supervisor back with `sudo service supervisor start`

**Comment by jamiew0w** [comment]
confirmed fix is good, great work @warlof  and impressive turnaround 👍

**Comment by warlof** [comment]
Hotfix flow has been provided with eveapi 3.0.22 update which just been released.
Update like you used to do using `composer update --no-dev` and apply migrations with `php artisan migrate`

Docker version is landing soon.
