### ISSUE TITLE
Location of assets not updating

### ISSUE THREAD

**Issue by jim1471** [eveseat/seat#630]
Hi,

Mentioned this a couple of times on Slack but can't seem to find a solution.  See error text file and screenshot of asset list with Item location not updating. This error is across all characters and in differing locations, Specifically Citadels. 

Any help would be appreciated 👍 
<img width="633" alt="Capture" src="https://user-images.githubusercontent.com/43807998/88481385-1896e980-cf53-11ea-80aa-7767acc721dd.PNG">
[error.txt](https://github.com/eveseat/seat/files/4977756/error.txt)

**Comment by warlof** [comment]
Hi @jim1471 

As already estate, assets management is a nightmare. There are numerous rules which influx in the ability to resolve or not an asset location.

 - Does the asset owner have access to the structure where item is located ?
 Yes : show him structure information, including name
 No : deny him structure information - no showable name

 - Is the asset inside a container ?
 Yes: move to parent item to determine the asset location
 No: use current location

 - Is the asset related to a corporation ?
 Yes: determine if the asset is inside an Office, Delivery Hangar, etc...
 No: proceed to location resolving

However, things has been improved with SeAT 4 which should be released anytime soon (I really hope/trust it :( )

I keep the issue up - so people can come back if they still experienced issues with new version.

**Comment by jim1471** [comment]
Hi, 

V4 still having same/similar issue.
![image](https://user-images.githubusercontent.com/43807998/90385313-db69d700-e07a-11ea-96ab-5bbbfc8748b9.png)

Also not sure if related but `php artisan esi:update:public` currently shows error;
`[2020-08-17 10:11:15] local.ERROR: Argument 1 passed to Seat\Eveapi\Jobs\Universe\Stations::__construct() must be of the type array, object given, called in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 16 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Seat\\Eveapi\\Jobs\\Universe\\Stations::__construct() must be of the type array, object given, called in /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 16 at /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Universe/Stations.php:66)
[stacktrace]
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(16): Seat\\Eveapi\\Jobs\\Universe\\Stations->__construct(Object(Illuminate\\Support\\Collection))
#1 /var/www/seat/vendor/eveseat/console/src/Commands/Esi/Update/PublicInfo.php(72): Seat\\Eveapi\\Jobs\\AbstractJob::dispatch(Object(Illuminate\\Support\\Collection))
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Seat\\Console\\Commands\\Esi\\Update\\PublicInfo->Seat\\Console\\Commands\\Esi\\Update\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#3 /var/www/seat/vendor/eveseat/console/src/Commands/Esi/Update/PublicInfo.php(73): Illuminate\\Database\\Eloquent\\Builder->chunk(100, Object(Closure))
#4 [internal function]: Seat\\Console\\Commands\\Esi\\Update\\PublicInfo->handle()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#11 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /var/www/seat/vendor/symfony/console/Application.php(1000): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/seat/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Seat\\Console\\Commands\\Esi\\Update\\PublicInfo), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/seat/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
"} 
`

**Comment by warlof** [comment]
Jobs queue error has been fixed by eveseat/console#73
Asset location has been partially fixed by eveseat/web#469 (render)
