### ISSUE TITLE
2 data leak issues with Squads

### ISSUE THREAD

**Issue by Sjolus** [eveseat/seat#637]
1) When using squads, anyone that has logged in can see all the squads and who is moderating them, regardless of filter criteria.
   - My suggestion would be to introduce a permission to control view permission of Squad page.

----

2) When using squads, anyone that is a member of a squad can see the names of all the characters that is also a member of the squad. This means a line member can potentially see the names of all the alts of a director or FC, just because they are in the same Squad. This issue lead to us shutting down SeAT immediately due to the available data leaks to line members there.
   - My first suggestion would be to only list the members if the viewer of the page is a moderator of the Squad.
   - My second suggestion would be to only list the main character for each member instead of all the alts.

**Comment by veteranmina** [comment]
https://github.com/eveseat/web/pull/473

Initial pr to allow menu permission control.

**Comment by warlof** [comment]
Showing moderators is intended. That's a good spot for user which need backup : go and check with one of squads moderator.

Regarding members, we can switch to main instead character list except for moderator.

**Comment by warlof** [comment]
Closed since it has been covered in web package 4.2.0 and docker build 4.0.13
