### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Kaaloks** [eveseat/seat#638]
In the nginx log i found

rewrite or internal redirection cycle while internally redirecting to "/index.php",

in the Settings under /etc/nginx/sites-available/seat

server {

    listen 80;
    listen [::]:80;

    # If you are hosting this instance on a domain, set that
    # name here.
    server_name mywebside.com;

    # SeAT public directory. This is the only directory that
    # should be exposed by the webserver. If one has to expose
    # the parent directory then things like the .env file will
    # be available for anyone to download.
    root /var/www/seat/public;

    index index.php;

    location / {
       try_files \$uri \$uri/ /index.php?\$query_string;
    }

    # PHP-FPM configuration.
    location ~ \.php\$ {
       try_files \$uri /index.php =404;
       fastcgi_pass unix:/run/php/php7.3-fpm.sock;
       fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
       include fastcgi_params;
    }

    # Even though .htaccess rules mean nothing in the nginx
    # world, prevent those from being downloaded anyways.
    location ~ /\.ht {
       deny all;
    }

    # In case someone messes up, prevent .env files from
    # being downloaded as well.
    location ~ /\.env {
       deny all;
    }
}

**Comment by warlof** [comment]
@Kaaloks your configuration file is actually wrong.

Is it a new installation ?
Please find documentation here https://eveseat.github.io/docs/installation/manual_installation/#nginx-configuration

**Comment by Kaaloks** [comment]
It was my fail

works now
