### ISSUE TITLE
Opening Squad causes 100% CPU load with MariaDB

### ISSUE THREAD

**Issue by bubis7** [eveseat/seat#639]
* **Problem**: Opening a Squad causes 100% CPU load with MariaDB as culprit and 504 Gateway error as result
* **Expected**: The squad to open.
* **Logs / Screenshots / Proof**: 
![image](https://user-images.githubusercontent.com/13527057/90766494-4a059980-e2f4-11ea-84ee-8eeb3b4c825e.png)
![image](https://user-images.githubusercontent.com/13527057/90766533-5db10000-e2f4-11ea-890b-e9c39eea6af5.png)

After MariaDB service restart everything is normal until i try to open the squad (Squad has 6 groups with 2 rules in each group. Corp rule and Tittle rule)
There should be about only 10 users who should be affected by this squad.

* **Version Info**: _PHP Version - PHP 7.3.21, SeAT Version - 4.0.0, Operating System Ubuntu 20.04.1 for Raspberry PI 4 
Did a Manual install and before doing  migration, I restored SeAT3 DB.

**Comment by warlof** [comment]
Can you add a dump from running queries when this appens?

**Comment by bubis7** [comment]
This is the only querry that is running (atleast trying to run) when running "show full processlist;"

|  41 | seat | localhost:42936 | seat | Execute | 1212 | Statistics | select exists(select * from `users` where `id` = ? and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null) and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null)) and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null)) and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null)) and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null)) and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null)) and (exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `character_affiliations` where `character_infos`.`character_id` = `character_affiliations`.`character_id` and `corporation_id` = ?) and `refresh_tokens`.`deleted_at` is null) and exists (select * from `character_infos` inner join `refresh_tokens` on `refresh_tokens`.`character_id` = `character_infos`.`character_id` where `refresh_tokens`.`deleted_at` is null and `users`.`id` = `refresh_tokens`.`user_id` and exists (select * from `corporation_titles` inner join `character_info_corporation_title` on `corporation_titles`.`id` = `character_info_corporation_title`.`corporation_title_id` where `character_infos`.`character_id` = `character_info_corporation_title`.`character_info_character_id` and `title_id` = ?) and `refresh_tokens`.`deleted_at` is null)))) as `exists` |    0.000 |
| 688 | root | localhost       | NULL | Query   |    0 | starting   | SHOW FULL PROCESSLIST

**Comment by warlof** [comment]
Thank you
Can you also provide squad setup? (both type and filters)

**Comment by bubis7** [comment]
Might have found the problem, but as It gives me 503 when opening that squad, can't try this fix.
Here's the idea behind my filters.

![image](https://user-images.githubusercontent.com/13527057/90778549-6fe76a00-e305-11ea-98c8-8f25564f55df.png)

But there are another 4 groups that are the same, with different titles.

Making this example I noticed that the first group is parent group and the next ones are sub-groups. That might be the reason. as at first I thought that all of them are equal groups and made them the same. Should have made subgroups with copr and title filter. Example is made that way also.

Second possible problem could be a tittle that isn't part of that corp, as in title filters it seems to offer all titles that are available form all the corps that are in db.

**Comment by warlof** [comment]
Yes, so actually based on your screen, your filters is the following

- All users

- which have a character inside corporation A
- AND
- which have a character with title B
- AND
-  which has both a character inside corporation C and with title D

filters are independent, so if what you want to do is 

- All users
- which have either
- a character with title B
- OR
- a character with title D

this is how you should setup them

![image](https://user-images.githubusercontent.com/648753/90824325-8c9c9580-e337-11ea-815e-1505a84a07ae.png)


UI can be improve by appending the corporation to title drilldown criteria. However, start by updating your squad filters and tell us how it's going.

**Comment by bubis7** [comment]
Yeah, as i was making the example i noticed that mistake. And yeah, didnt think about making one corp rules and then a group with tittle filters set to "Any" :)

As right now the problem is that i cant edit that squad. As soon as i open it, it goes to 100%CPU usage and gives me 503 error.
I`m deleting that squad trough sql and will try to remake another one. 👍 
Made a new squad with correct filters and its working. Thanks! I guess this one is closed unless You want to make some checks on that querry or make failsafes in case anyone else does something like this :D

**Comment by warlof** [comment]
I'll keep it open to figure if nothing can be done to avoid the case.

Also, we're you a member of that squad?

**Comment by bubis7** [comment]
No, There where zero members, but i set myself as Moderator.

**Comment by warlof** [comment]
should be fixed with https://github.com/eveseat/web/commit/1142875468267dc41b573eb2627cc25c8e438b65.

Fill free to reopen the issue if you're landing on it again.
