### ISSUE TITLE
Connection refused [tcp://127.0.0.1:6379]

### ISSUE THREAD

**Issue by binarygod** [eveseat/seat#64]
Hello!  Performed a brand new install of Ubuntu 14 Server, ran the super awesome one line install script (nice work!), everything loads up fine.  I add an API key to the system and it's been sitting for an hour now.

Checked seat log in /var/log and found the following:

[Predis\Connection\ConnectionException]
  Connection refused [tcp://127.0.0.1:6379]

  [Predis\Connection\ConnectionException]
  Connection refused [tcp://127.0.0.1:6379]

  [Predis\Connection\ConnectionException]
  Connection refused [tcp://127.0.0.1:6379]

Processed: Illuminate\Queue\CallQueuedHandler@call
Processed: Illuminate\Queue\CallQueuedHandler@call
Processed: Illuminate\Queue\CallQueuedHandler@call
Processed: Illuminate\Queue\CallQueuedHandler@call

Any advice?

**Comment by warlof** [comment]
that's a firewall issue.
You should open the port 6379

iptables -A INPUT -s 127.0.0.1 -p tcp --dport 6379 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -d 127.0.0.1 -p tcp --sport 6379 -m state --state RELASTED,ESTABLISHED -j ACCEPT

**Comment by binarygod** [comment]
That's what I thought, I didn't even think it was on by default in a fresh Ubuntu install as I've never had to modify it before!  Thank you for the information and quick response.  Great work on everything!

**Comment by jsmb768ypl** [comment]
i am getting this same error, i ran the above code and still getting the error.

**Comment by warlof** [comment]
Hello, better should open à new issue, but anyway:

What's your distribution name and version ?

- Ensure that the redis service is running and listenning on `127.0.0.1:6379`
- Ensure that your seat user (generally `www-data`) have right to read and write to redis
- Post the output of `iptables -L` if your either on debian or ubuntu

**Comment by warlof** [comment]
And be sure that redis is installed first ^^
`sudo dpkg --get-selections | grep redis`

Solved on slack, issue remain closed.

**Comment by chilipepper987** [comment]
When this happened to me, the fix was just to restart reddis

**Comment by chilipepper987** [comment]
`systemctl restart reddis` fixed it for me.
