### ISSUE TITLE
ESI Error Rate Limit has been exceeded. All ESI jobs are locked until release

### ISSUE THREAD

**Issue by Kaaloks** [eveseat/seat#641]
I got over 10k Failed Jobs "ESI Error Rate Limit has been exceeded. All ESI jobs are locked until release"

in

Seat\Eveapi\Jobs\Industry\Corporation\Mining\Observers
Seat\Eveapi\Jobs\Market\History
Seat\Eveapi\Jobs\Corporation\Members

and other

**Comment by warlof** [comment]
things are currently in test to reduce this exception.

can you share your eseye log file from the day when those jobs fails ?

**Comment by warlof** [comment]
Throttler related to ESI and TQ status are now logging warning instead reporting exception and mark job as completed (eveseat/eveapi#250).
