### ISSUE TITLE
Jobs are not running

### ISSUE THREAD

**Issue by erikterr** [eveseat/seat#643]
After update to 4.0, all jobs are in paused state, tried to restart jobs or check on laravel but nothing. 
Of course all things (like wallet, corporations, mining ect..) are not updating.

**Comment by erikterr** [comment]
No :(
I still have all jobs in "pending" state, no revelant jobs in failed state (only some older jobs)

**Comment by Kaaloks** [comment]
Same Problem here. No Charakter and Corporation updates since yesterday

**Comment by warlof** [comment]
@erikterr can you try the following?

1) be sure you're running all latest package
2) clear your cache using `php artisan seat:cache:clear`
3) change value of `LOG_LEVEL` from error to debug into your `.env` file
4) wait for job to be queued and send me both your eseye and laravel logs on Slack

**Comment by erikterr** [comment]
Sure, here the results:
1. Updated to last versions (missing SeAT Eve API and Seat Web, now all green)
2. Cleared
3. Changed
4. Sent to you via PM on slack

Just for info, this morning all yesterday jobs went into failed state because of timeout (around 900 jobs). 
After the modification you asked, I found new error on lavarel log:
[2020-08-24 06:51:19] local.ERROR: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `users` where `id` = 12 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connectio$
[stacktrace]
But db seem ok as I can use history data..

**Comment by warlof** [comment]
issue was related to a half upgraded SeAT 3 instance (SeAT 2 moved to SeAT 3 - but running the old supervisor configuration)

simple fix :

```
sudo su
rm /etc/supervisor/conf.d/seat.conf

cat > /etc/supervisor/conf.d/seat.conf << EOL
[program:seat]
command=/usr/bin/php /var/www/seat/artisan horizon
process_name = %(program_name)s-80%(process_num)02d
stdout_logfile = /var/log/seat-80%(process_num)02d.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
numprocs=1
directory=/var/www/seat
stopwaitsecs=600
user=www-data
EOL

exit
```
