### ISSUE TITLE
Adding API Key does not schedule update as promised

### ISSUE THREAD

**Issue by binarygod** [eveseat/seat#65]
API Key Mangement -> Add a EVE API Key, enter details, click 'Check Key'.  Preliminary character info and access check comes up with button to 'Add Account API Key' with a Note: " Note: Adding an Api Key will automatically queue a new update job for it".

Click Add Account API Key.  If no jobs are in que then count changes to 1, if a "Started APIKeyInfo Update" que item already exists then the count neither increases or decreases.

API information is never updated.  Going to API Management -> List all API Keys results in a list showing the added API, but with entries like 'Type => Never', 'Expirey => Unknown' and Character column completely blank.

To resolve the issue I click on 'Details' for the line item in question and click on the big green 'Que an update job' button and data immediately starts to populate.

Thanks!

**Comment by warlof** [comment]
Hey, can you display the output of this command: `php artisan seat:admin:diagnose`

The installed Web package should appears as 1.0.21.
If it's not the case, install php-gd on your server

**Comment by vivace-io** [comment]
Same issue. Web package version 1.0.22 (also all other packages at the latest as of time of writing)

First time running `php artisan seat:admin:diagnose` yielded errors with Pheal read/writing to it's storage. Once I fixed that I re-ran and got all green. Problem still persisted.

**Comment by johnnysplunk** [comment]
I can report similar results with version 1.0.23. Adding a key for the first time queues for an update and logs it but never updates the APIKeyInfo. There are two options to get a new key updated:

* "Queue an Update Job" from the API Key detail view
* Waiting for the scheduled hourly key updates.

**Comment by jesterlol** [comment]
same issue

**Comment by warlof** [comment]
Still up with 1.0.24
