### ISSUE TITLE
SeAT 4 Access list management

### ISSUE THREAD

**Issue by meloncafe** [eveseat/seat#652]
In SeAT 3, it was possible to create rights to view only certain corporations.
However, in SeAT 4, when setting the authority, you can only place a limit on a specific character
There is an issue with hiring and certain Corporation representatives being able to see all characters.
That feature was a very useful feature.
If we created permission to view only certain corporations, we could manage the data of that corporation by adding only the person in charge.
In SeAT 4, don't you intend to add that feature again?

**Comment by warlof** [comment]
Hi,

I don't understand what you want.
With SeAT 4, you can grant a permission without limitation (default behavior), limit to selected characters, corporations or even alliances.

https://eveseat.github.io/docs/admin_guides/authorizations/

🤔

**Comment by warlof** [comment]
Members of the role bellow get access to all extractions information from `Daerie Inc.` corporation

![image](https://user-images.githubusercontent.com/648753/91291461-62166680-e795-11ea-8afa-28ebfa182a1c.png)

Members of the role bellow get access to skills from all characters in either `Daerie Inc.` corporation or `Get off my Lawn` alliance

![image](https://user-images.githubusercontent.com/648753/91291654-ab66b600-e795-11ea-8a7a-9f9c0e8967c1.png)

**Comment by meloncafe** [comment]
> Members of the role bellow get access to all extractions information from `Daerie Inc.` corporation

This was the information I really wanted.
Thank you very much.
