### ISSUE TITLE
queued jobs don't change to working jobs

### ISSUE THREAD

**Issue by run2death** [eveseat/seat#66]
how long it will take, please?
And ONLINE PLAYERS is unknown all the time.

**Comment by leonjza** [comment]
Server status updates [every 5 minutes](https://github.com/eveseat/services/blob/master/src/database/seeds/ScheduleSeeder.php#L34). I'd check that the workers are up and running to start.

**Comment by warlof** [comment]
What about log ? In your seat path /storage/log/laravel.log
What about firewall ? Iptables -L

**Comment by run2death** [comment]
last day log
it looks like not the same problrm[2016-02-10 08:44:19] local.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php:2927
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#2 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(12961): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#5 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(11555): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#8 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(12698): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#11 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(12635): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#14 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(2254): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /opt/lampp/htdocs/seat/bootstrap/cache/compiled.php(2237): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /opt/lampp/htdocs/seat/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#22 {main}

**Comment by run2death** [comment]
@leonjza 
how to check wokers are up?and running to start?
thx.

**Comment by run2death** [comment]
I install seat step by step with https://github.com/eveseat/seat/wiki/Quick-Installation

**Comment by run2death** [comment]
problem solved.
Thanks for you help.
@leonjza @warlof 
Workers are up now. :P

**Comment by leonjza** [comment]
Try `supervisorctl status`

**Comment by run2death** [comment]
@leonjza yes, I've done that. It worked after some steps. Thank you very much
