### ISSUE TITLE
100K Failed jobs per day

### ISSUE THREAD

**Issue by zino73** [eveseat/seat#663]
I Migrated my version from V3 docker to V4 Docker.
my server is 2 vCPU + 8 Go Ram + 150 Gb 

everything seems work but i noticed a lot of Failed jobs, first i thought its beacause of my migration but after 4 days i sax that was not related to my migration , so i started to investigate (the server was very unstable so i had to)
so this is the situation : now i h ave Around 700 MB of laravel logs per day, around 1.2 GB Failed_jobs.idb table  database size  and growing everyday (i had to truncate it manually because she was at 4.7 GB after 4 days)
this is my quick analyze of the laravel log file : 

62 errors like ; 
`local.ERROR:  {"exception":"[object] (Seat\\Eseye\\Exceptions\\RequestFailedException(code: 502):  at /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:289)`

985 errors like this : 
` local.ERROR: Unhandled internal error encountered! {"exception":"[object] (Seat\\Eseye\\Exceptions\\RequestFailedException(code: 500): Unhandled internal error encountered! at /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:289)`

4467 errors like this : 
`local.ERROR: Unable to retrieve structure information. {"structure ID":1027847404345,"token owner ID":XXXXXXXX} `

133 errors like this : 
`local.ERROR: The datasource tranquility is temporarily unavailable {"exception":"[object] (Seat\\Eseye\\Exceptions\\RequestFailedException(code: 503): The datasource tranquility is temporarily unavailable at /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:289)
`

298 errors like this : 
`local.ERROR: Timeout contacting tranquility {"exception":"[object] (Seat\\Eseye\\Exceptions\\RequestFailedException(code: 504): Timeout contacting tranquility at /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:289)`

15 errors like this : 
`local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry `

1 error like this : 
`local.ERROR: Allowed memory size of 134217728 bytes exhausted`

131604  errors like this :
105 : 
`local.ERROR: Seat\Eveapi\Jobs\Contracts\Corporation\Contracts has been attempted too many times or run too long. The job may have previously timed out. {"exception"
`
685 :  
` local.ERROR: Seat\Eveapi\Jobs\Contacts\Corporation\Labels has been attempted too many times or run too long. The job may have previously timed out. {"exception"`

and for information my server graphs activity :
![image](https://user-images.githubusercontent.com/15671678/92111753-0d09ce80-eded-11ea-8da1-004b982ac1d1.png)

**Comment by warlof** [comment]
Hi,

which jobs caused this :  `local.ERROR: Allowed memory size of 134217728 bytes exhausted`
which jobs caused this : ` local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry`

would it be possible to get the character ID for `local.ERROR: Unable to retrieve structure information.` ?

**Comment by zino73** [comment]
sent privacely

**Comment by warlof** [comment]
Hi,

with last changes applied on eveapi package, is it still a valid issue ?

**Comment by zino73** [comment]
hey i just updated my seat to last versions, sadly i got close to 500K errors in a days.

 all the failed job have this error :

Seat\Eveapi\Exception\TokenVersionException: Token Version Mismatch. Run command `php artisan seat:token:upgrade` in order to fix. in /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenVersion.php:63
--

**Comment by leonjza** [comment]
@zino73 did you run the command as stated in the error message?

**Comment by zino73** [comment]
oups, thanks for the info I didn't really read the error message, ok im doing it right now

**Comment by zino73** [comment]
done 
![image](https://user-images.githubusercontent.com/15671678/101239228-3b49c380-36e6-11eb-9a9c-6693e38e769a.png)

**Comment by vlvavan** [comment]
Hi!
in which directory should this command be run? if docker install
I have a similar error

**Comment by zino73** [comment]
still have a lot of same errors  :  
`Seat\Eveapi\Exception\TokenVersionException: Token Version Mismatch. Run command `php artisan seat:token:upgrade` in order to fix. in /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenVersion.php:63`

**Comment by warlof** [comment]
hotfix is in pipe - until then, you have to run the command this amount of time :
1) number of token
2) divide by 100
3) add one

**Comment by zino73** [comment]
ok then ill run it 4  times more (421/100 +1 = 5)

**Comment by zino73** [comment]
no errors since 1h30 since i ran 4 times more the token upgrade command. seems good

**Comment by zino73** [comment]
0 failed job since 16 hours now.

**Comment by zino73** [comment]
`Seat\Eveapi\Exception\TokenVersionException: Token Version Mismatch. Run command `php artisan seat:token:upgrade` in order to fix. in /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenVersion.php:63

tokenupgrade errors are back , i updated to the last version of Seat yesterday

**Comment by warlof** [comment]
@zino73 for which job man ?

that's actually not make any sense except if you're playing with tokens yourself.
will need more inputs for that dude, we can't investigate anything just with that.

**Comment by zino73** [comment]
ok, so i investigated, and i noted that the errors are related to a new member added his 3 char tockens, and all these errors since the 07-12-2020 are related to these 3 ESI, and when i checked i have this message : 
![image](https://user-images.githubusercontent.com/15671678/101983109-f7703480-3c78-11eb-9dd5-35830afb58b7.png)

perhaps because he added his tokens before the seat patch was out. im going to run token upgrader manually again and we will  see

**Comment by zino73** [comment]
done ! 
![image](https://user-images.githubusercontent.com/15671678/101983191-8a10d380-3c79-11eb-9e97-63fdc85fff09.png)

so lets see for the next new Tokens

**Comment by warlof** [comment]
that's probably the case indead.

**Comment by zino73** [comment]
it seems we are fine now :
![image](https://user-images.githubusercontent.com/15671678/103100986-9ef44c00-4615-11eb-94fa-5a124a2ff190.png)
