### ISSUE TITLE
Mail issues

### ISSUE THREAD

**Issue by d3vfreak** [eveseat/seat#664]
Trying to open up some specific mails results in "loading...."
[**Error.log**](https://paste.ubuntu.com/p/fpRVwfFsWm/)

**Comment by warlof** [comment]
is it still valid ?

**Comment by warlof** [comment]
Closing for now, assuming it has been addressed with changes from https://github.com/eveseat/web/commit/41ed7fe8a4655febd217786cd2b451981a2377d5
