### ISSUE TITLE
Maintenance + Clean Stale Data is not working

### ISSUE THREAD

**Issue by NeniAscee** [eveseat/seat#668]
as i understand is that characters/corporations without a valid user will get removed when maintenance mode and the "clean up stale data" is activated, this currently is not working.

if there is somewhere that we can access the logs for this event, we will supply you them (no idea where they are)

Our maintenance job is running now daily for the past week and the clean up stale data is on and characters without a valid user are still on seat

**Comment by warlof** [comment]
Clean stale data is actually not available.
Some database upgrade are required before it can be used again at an efficient way.
