### ISSUE TITLE
Asset Safety Items at location "Unknown"

### ISSUE THREAD

**Issue by SpectralFremen** [eveseat/seat#670]
Isn't happening to all my asset safety packages, but approximately 1/4 of them. Have checked in game and there doesn't seem to be anything special about these ones. They are going to NPC stations (not forced to other citadels).
https://i.imgur.com/P6j5AmG.png

Happy to provide any logs that may be helpful to troubleshoot this issue.
[admin.diagnose.seat-web.txt](https://github.com/eveseat/seat/files/5193053/admin.diagnose.seat-web.txt)
[admin.diagnose.seat-worker.txt](https://github.com/eveseat/seat/files/5193054/admin.diagnose.seat-worker.txt)

[laravel-2020-09-09.log](https://github.com/eveseat/seat/files/5193077/laravel-2020-09-09.log)

**Comment by warlof** [comment]
Hi,

can you update your initial post with provided template please ?
we need at least package versions, especially since two major versions are running at time.

**Comment by SpectralFremen** [comment]
My apologies, have added the diagnose results for web and worker, am getting the laravel log now.

**Comment by SpectralFremen** [comment]
I am quite certain that a number of these "unknown" assets are in ship hangers.

**Comment by SpectralFremen** [comment]
Also quite certain that some of them are asset safety wraps that are still "in transiction"

**Comment by warlof** [comment]
Hello there,

is it still an actual issue ?
Numerous changes have been applied related to the asset location case.
