### ISSUE TITLE
Permission Error Seat V4

### ISSUE THREAD

**Issue by olanguedoc** [eveseat/seat#671]
* **Problem**: Installation of SEAT with Auto-Install script  creates Read/Write Errors on some files/directories. This error prevents the access to logs. 

* **Expected**: Be able to access logs files and pass the docker **install diagnose** with all system green. `docker-compose exec seat-web su -c 'php artisan seat:admin:diagnose' -s /bin/sh www-data`

* **Logs / Screenshots / Proof**: 
![image (4)](https://user-images.githubusercontent.com/12350553/92593448-225c7e00-f26f-11ea-979a-05007274e4ed.png)
![image (5)](https://user-images.githubusercontent.com/12350553/92593449-22f51480-f26f-11ea-8141-bc5892f56edf.png)

* **Version Info**: PHP Version 7.3.21, SEAT 4.0.0, Ubuntu

**Comment by Nfinished** [comment]
Also encountering this issue when I try to clear clear the cache via `docker-compose exec seat-web php artisan seat:cache:clear`, the response is `Eseye Cache directory at /var/www/seat/storage/eseye is not writable`.

**Comment by Crypta-Eve** [comment]
Can you both comment back here filling out the following (placeholder values in my example)
Item | Data
------------ | -------------
Docker Version | 19.03.12 
Docker Compose Version | 1.26.2
Underlying OS | Debian
Underlying OS Version | 10 / buster
Used auto install script? | Yes/No (if no please provide details of your install process)
Upgraded from SeAT 3? | Yes/No

Also @Nfinished can you provide the output of `docker-compose exec seat-web su -c 'php artisan seat:admin:diagnose' -s /bin/sh www-data` too please.

**Comment by olanguedoc** [comment]
Docker Version : 19.03.12
Docker Compose version : 1.26.2, build eefe0d31
Docker-Py version : 4.2.2
Underlying OS :  Ubuntu 20.04
Underlying OS version : 20.04 / Focal
Used Auto install script : Yes
Upgraded from seat 3 : No

**Comment by Nfinished** [comment]
Docker Version : 19.03.12, build 48a66213fe
Docker Compose version : 1.26.2, build eefe0d31
Underlying OS : Ubuntu
Underlying OS version : Ubuntu 18.04.4 LTS
Used Auto install script : No, followed guides during 3 install and 4 upgrade.
Upgraded from seat 3 : Yes

```
SeAT Diagnostics
If you are not already doing so, it is recommended that you run this as the user the workers are running as.
Eg:
    sudo -u apache php artisan seat:admin:diagnose
    su -c "php artisan seat:admin:diagnose" -s /bin/sh www-data
This helps to check whether the permissions are correct.

 * Getting environment information
Current User: www-data
PHP Version: 7.3.21
Host OS: Linux 165ae5d21f48 5.3.0-1033-aws #35-Ubuntu SMP Wed Aug 5 15:47:17 UTC 2020 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/logs is writable
/var/www/seat/storage/eseye is not writable
/var/www/seat/storage/sde/ is not writable
/var/www/seat/storage/logs/laravel-2020-09-10.log  is not writable

 * Checking Database
+------------+---------------------+
| Setting    | Value               |
+------------+---------------------+
| Connection | mysql               |
| Host       | mariadb             |
| Database   | seat                |
| Username   | seat                |
| Password   | ******************* |
+------------+---------------------+
Connection OK to database: seat

 * Checking Redis
+----------+-------+
| Setting  | Value |
+----------+-------+
| Host     | redis |
| Port     | 6379  |
| Database | 0     |
+----------+-------+
Connected to Redis
Set random key of: nSPvt9w3Ll5CZ3ulTxw04YrzpczjkMUfVdIughmuIHeU01GarUKhYqPSH9jklFuW
Set key to expire in 10 sec
Read key OK

 * Checking ESI Access
Server Online Since: 2020-09-10T11:08:59Z
Online Players: 23317
ESI appears to be OK

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 4.1.0         | 4.1.0         |
| Console       | 4.0.4         | 4.0.4         |
| Eveapi        | 4.1.1         | 4.1.2         |
| Notifications | 4.0.2         | 4.0.3         |
| Web           | 4.2.1         | 4.2.2         |
| Services      | 4.0.0         | 4.0.0         |
+---------------+---------------+---------------+
SeAT Diagnostics complete
```

**Comment by olanguedoc** [comment]
Could this bug be a reason why my EVE Contacts arent showing in the Contacts page?

**Comment by Chaney08** [comment]
Same issue as mentioned above
Docker Version : 19.03.12 48a66213fe
Docker Compose Version : 1.27.3, build 4092ae5d
Underlying OS :  Ubuntu 
Underlying OS Version : 18.04
Used auto install script? : Yes
Upgraded from SeAT 3? : Yes - But I had only installed it so the SeAT 3 version had no data.

![image](https://user-images.githubusercontent.com/4929460/93785471-6ae04800-fc2e-11ea-8a1b-4c4a3a1e3f47.png)

**Comment by warlof** [comment]
Is the directory `/var/www/seat/storage/logs` empty ?

I suspect the reason of your failure is only because you attempt to extract data from a non-existing log file (by default, a log file exists at D day only if error have been logged).
