### ISSUE TITLE
All characters with Invalid Token

### ISSUE THREAD

**Issue by erikterr** [eveseat/seat#674]
o7, seem to be 2 weeks ago all of my chars registered inside seat (around 50 members) are broken with invalid token.
I tried to update to last modules, but nothing changed. We changed 2 weeks ago the address of seat for fix another problem (previus was www.oursite.org/seat now is seat.oursite.org) I don't know if that caused the problem (but worked for some days).

* **Problem**: _Whats wrong? -> All characters with invalid token
* **Expected**: _What did you expect to happen?_ -> Fix in some ways :)
* **Logs / Screenshots / Proof**: _The more information you give the better! -> Could post logs if required, actually nothing special, seem to be all are in the same state. 
* **Version Info**: _PHP Version, SeAT Version, Operating System etc. -> 
 SeAT API
Installed: v4.1.0
SeAT Console
Installed: v4.0.4
SeAT Eve API
Installed: v4.1.2
SeAT Notifications
Installed: v4.0.3
SeAT Services
Installed: v4.0.0
SeAT Web 
Installed: v4.2.2
Ubuntu VM version 18 on mariadb.

**Comment by warlof** [comment]
Hello,

a token which have been invalidated can't be recover.
here are common things :
- callback update on your EVE APP
- scopes update on your EVE APP
- manual revoke
- not upgradable token from v1 format to v2 one (it's a thing which may append, and it's only on CCP side, probably occures on verry old tokens)
- password reset on the account from which token have been granted
- CCP security rule (especially on botting monitoring, and other EULA violation stuff)
- EVE App client secret reset
