### ISSUE TITLE
Malformed discord notifications

### ISSUE THREAD

**Issue by Nfinished** [eveseat/seat#678]
As seen below, discord structure notifications using the slack integration (with /slack appended to webhook URL) are malformed on desktop and mobile.

![image](https://user-images.githubusercontent.com/1719791/94343449-53b2a900-ffe6-11ea-8b97-bb277cba388c.png)
![Screenshot_20200926-104858](https://user-images.githubusercontent.com/1719791/94343466-6331f200-ffe6-11ea-9780-53c8cd122130.png)

SeAT modules are all latest.

![image](https://user-images.githubusercontent.com/1719791/94343480-747afe80-ffe6-11ea-8535-29ff842a3d31.png)

**Comment by Nfinished** [comment]
Ditto for fuel notifications

![image](https://user-images.githubusercontent.com/1719791/94580307-bfe01780-0247-11eb-8db9-0ce25eb5a8a0.png)

**Comment by Rakdos8** [comment]
I added notification as well on our server but everything looks fine still we have duplicated messages
![image](https://user-images.githubusercontent.com/22244611/101284335-d2df0d00-37df-11eb-8c7f-346bf8eb1184.png)

I've anomysed data but it's always the same value every time

```
| Vendor  | Package Name   | Installed Version        |
| ------- | -------------- | ------------------------ |
| eveseat | api            | 4.2.1                    |
| eveseat | console        | 4.3.0                    |
| eveseat | eveapi         | 4.6.0                    |
| eveseat | notifications  | 4.2.0                    |
| eveseat | services       | 4.1.0                    |
| eveseat | web            | 4.4.0                    |
| ccp     | eve_online_sde | sde-20201110-TRANQUILITY |
```

**Comment by Crypta-Eve** [comment]
Closing as there are native discord notifications in v5
