### ISSUE TITLE
Contracts list: Show collateral for courier contracts instead of price

### ISSUE THREAD

**Issue by Xaroth** [eveseat/seat#68]
Seeing the price item is not used for courier contracts, the most sane would be to add the collateral amount instead.

**Comment by warlof** [comment]
why not both ? :)

**Comment by warlof** [comment]
It's available in last release (Web 1.0.31)

@qu1ckkkk issue can be closed.

**Comment by leonjza** [comment]
Fixed in https://github.com/eveseat/web/commit/584c9e68b5377bc8370dab4bd0ba5b7263512552
