### ISSUE TITLE
Squad Auto Multi rules

### ISSUE THREAD

**Issue by AlfLife-eve** [eveseat/seat#686]
hello,

i have a problem with multi rules in auto squad, they can't find anyone in the squads with this rule for example

![image](https://user-images.githubusercontent.com/65184046/95672592-4bd83480-0ba2-11eb-9e26-7563a1c35dab.png)

**Comment by Crypta-Eve** [comment]
Just for clarification, you are not expecting the bottom set of rules to match Revelation, Pheonix or Moros right. As the items you have in there are the skill books.

**Comment by warlof** [comment]
What's the main filter match kind ?

**Comment by warlof** [comment]
Furthermore, this is what your rules is actually describing, assuming the main match kind is `All`

All users
Who have at least one character in `alliance Toilet Paper.`
**AND** who have the `skill Jump Drive Calibration`
**AND** (
  who have the `skillbook Amarr Dreadnought in his assets`
  **OR** who have the `skillbook Caldari Dreadnought in his assets`
  **OR** who have the `skillbook Gallente Dreadnought in his assets`
)
