### ISSUE TITLE
Fatal error: Out of memory

### ISSUE THREAD

**Issue by jakesales** [eveseat/seat#688]
**Hello, I've not got particularly far unfortunately. 
Ubuntu 18.04
Manual Installation
Donwloading SeAT I get this error:**

Loading composer repositories with package information
Updating dependencies

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 1518874624) (tried to allocate 134217736 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 83

Fatal error: Out of memory (allocated 1518874624) (tried to allocate 134217736 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 83
-bash: -r: command not found

**Comment by Crypta-Eve** [comment]
Correct, composer uses a lot of memory. Until composer 2 is implemented you are stuck with this. Add a swap file to help with this: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

**Comment by jakesales** [comment]
Thanks- I’ve setup a 5GB swap file but still getting the same error unfortunately- surely it can’t need a larger swap file?

**Comment by Crypta-Eve** [comment]
To be honest yes it can (Im assuming seat 4 here) as the web, cron and worker containers can all be running composer at the same time. One way to mitigate this is to do a staggered startup. ie run `docker-compose up -d seat-web` wait till it is done then do cron/worker etc.

**Comment by jakesales** [comment]
Would you consider setting it up for me if I gave you SSH details? I’d pay for your time of course.

**Comment by jakesales** [comment]
I've got past the out of memory error now on the manual installation method. I had to upgrade to a server with 4GB RAM and set a page file to 8GB. Also, Ubuntu 20.04. Thanks for pointing me in the right direction.
