### ISSUE TITLE
Errored jobs with strange SQL error

### ISSUE THREAD

**Issue by torlivar** [eveseat/seat#69]
I'm getting a number of errors with error messages similar to this pastebin:
http://pastebin.com/J6MBddgF

(data fields Xed out)

 Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `account_api_key_info_characters` set `corporationID` = XXXXXX, `corporationName` = XXX XXXXXXX XXXXXXX, `updated_at` = 2016-02-13 16:00:56 where `id` is null)

**Comment by leonjza** [comment]
Hey, is it possible that you have been running your install before the official release of SeAT1x? 

As you can see [here](https://github.com/eveseat/eveapi/blob/master/src/database/migrations/2015_09_04_193632_create_account_api_key_info_characters_table.php#L19), the field `id` is in fact available, but from the commit history you will see it was added at a later stage. The official launch of SeAT was done with this migration already altered.

In your case, you can do the following:
- Check your table schema by running `describe account_api_key_info_characters`.
- If the `id` column is missing, add it with something like: `ALTER TABLE account_api_key_info_characters ADD id INT AUTOINCREMENT;` (_just double check the syntax_)

Report back you findings. If you need more help, I'll suggest you hop onto Slack. Details [here](https://github.com/eveseat/seat/wiki/Contact-Information).

**Comment by torlivar** [comment]
Yes, that is probably the correct explanation. I've added the ID column.

Thanks!
