### ISSUE TITLE
eveseat/services missing

### ISSUE THREAD

**Issue by jakesales** [eveseat/seat#690]
I'm still attempting the manual installation but am getting this error on the SeAT download step:

  Problem 1
    - eveseat/eveapi 4.1.3 requires ext-redis * -> the requested PHP extension redis is missing from your system.
    - eveseat/eveapi 4.1.2 requires ext-redis * -> the requested PHP extension redis is missing from your system.
    - eveseat/eveapi 4.1.1 requires ext-redis * -> the requested PHP extension redis is missing from your system.
    - eveseat/eveapi 4.1.0 requires ext-redis * -> the requested PHP extension redis is missing from your system.
    - eveseat/eveapi 4.0.2 requires ext-redis * -> the requested PHP extension redis is missing from your system.
    - eveseat/eveapi 4.0.1 requires ext-redis * -> the requested PHP extension redis is missing from your system.
    - eveseat/eveapi 4.0.0-rc7 requires eveseat/services 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0-rc6 requires eveseat/services 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0-rc5 requires eveseat/services 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0-rc4 requires eveseat/services 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0-rc3 requires eveseat/eseye 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0-rc2 requires eveseat/services 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0-rc1 requires eveseat/services 4.0.x-dev -> no matching package found.
    - eveseat/eveapi 4.0.0 requires ext-redis * -> the requested PHP extension redis is missing from your system.

please can anyone help?

**Comment by warlof** [comment]
Hi, 

Check your default php cli version and ensure you have required extensions deployed (all of them).

Steps are described into the official documentation https://eveseat.github.io/docs/installation/manual_installation/#php

**Comment by jakesales** [comment]
Hi thanks and yes, absolutely followed all the instructions and they just didn't work unfortunately. What I've done is rebuilt the server and am trying to install using the docker now.
