### ISSUE TITLE
User admin: Editing a user fails with "The email has already been taken."

### ISSUE THREAD

**Issue by torlivar** [eveseat/seat#70]
## Problem Statement
When editing a user (I tried changing password for a user who forgot his), the operation failed with the error message "The email has already been taken.". 

Suspect this could be a regression caused by the fix of #59

## Expected Behaviour
The changes should have gone in without error.

## Output of `php artisan seat:admin:diagnose`
    SeAT Diagnostics
    If you are not already doing so, it is recommended that you run this as the user the workers are running as.
    Eg:
        sudo -u apache php artisan seat:admin:diagnose
    This helps to check whether the permissions are correct.
    
     * Getting environment information
    Current User: www-data
    PHP Version: 5.5.30-1~dotdeb+7.1
    Host OS: Linux aura 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64
    SeAT Basepath: /srv/www/seat
    
     * Checking DEBUG mode
    Debug mode disabled
    
     * Checking storage
    /srv/www/seat/storage is writable
    /srv/www/seat/storage/app/pheal/ is writable
    /srv/www/seat/storage/sde/ is writable
    /srv/www/seat/storage/logs/laravel.log is writable
    
     * Checking Database
    +------------+--------------+
    | Setting    | Value        |
    +------------+--------------+
    | Connection |              |
    | Host       | localhost    |
    | Database   | seat         |
    | Username   | seat         |
    | Password   | ************ |
    +------------+--------------+
    Connection OK to database: seat
    
     * Checking Redis
    +----------+-----------+
    | Setting  | Value     |
    +----------+-----------+
    | Host     | 127.0.0.1 |
    | Port     | 6379      |
    | Database | 0         |
    +----------+-----------+
    Connected to Redis
    Set random key of:         mCMZMjlhY378qtyg6RJA3UMbyK6Sc1fw9Lnvqs4uCPcgY8KaS7c0zVli7lYZAHwK
    Set key to expire in 10 sec
    Read key OK
    
     * Checking Pheal EVE API Access
    Server Online: True
    Online Players: 31322
    
    Checking Local and Github Versions. Please wait...
    +---------------+---------------+---------------+
    | Package Name  | Local Version | Latest Github |
    +---------------+---------------+---------------+
    | Api           | 1.0.9         | 1.0.9         |
    | Console       | 1.0.10        | 1.0.10        |
    | Eveapi        | 1.0.11        | 1.0.11        |
    | Notifications | 1.0.4         | 1.0.4         |
    | Web           | 1.0.22        | 1.0.22        |
    | Services      | 1.0.14        | 1.0.14        |
    +---------------+---------------+---------------+
    SeAT Diagnostics complete
## Any Other Supporting Bits of Info
PHP 5.5.30-1~dotdeb+7.1 (cli) (built: Oct  1 2015 17:38:39)

**Comment by Bingmano** [comment]
I can confirm that i cannot edit my own username (admin) to something else.  I get the error of "The email has already been taken".

Workaround: change the email and username at the same time then change email back to original.  Confirmed that it works for me.
