### ISSUE TITLE
Auto Squads Not Gaining Correct Users

### ISSUE THREAD

**Issue by tohuw** [eveseat/seat#702]
* **Problem**: When I create auto squads with various kinds of filters (e.g. member of corporation, has title within corporation), it gains some users but not others who match the exact same criteria.

* **Expected**: Any user matching the criteria should be added to the group.

* **Logs / Screenshots / Proof**: The users I expect to see in the groups have the right titles and attributes, and all jobs for updating characters and corporations are succeeding. But if I create a group, it may be hours before it has any members at all, or it may gain members right away, but not represent the complete list of members. I see nothing in logs at debug level that pertain to squads, and I see no errors that seem related in any way. This is a completely fresh install and has no plugins.

* **Version Info**: 
```
```
| Vendor  | Package Name   | Installed Version        |
| ------- | -------------- | ------------------------ |
| eveseat | api            | 4.1.0                    |
| eveseat | console        | 4.0.5                    |
| eveseat | eveapi         | 4.2.0                    |
| eveseat | notifications  | 4.0.3                    |
| eveseat | services       | 4.0.0                    |
| eveseat | web            | 4.2.3                    |
| ccp     | eve_online_sde | sde-20201008-TRANQUILITY |
```
```

**Comment by tohuw** [comment]
Ok, I've detected a critical pattern. If a given user links any new character, they are added to the correct squads.

Signing out and in, changing main character, and similar actions don't cause them to be added to the squad. ONLY linking works.

What does that mean?

**Comment by warlof** [comment]
can you provide a squad configuration including filter rules ?

**Comment by tohuw** [comment]
![image](https://user-images.githubusercontent.com/2437862/97483290-40686580-1925-11eb-92cb-2a93ea17ef75.png)
![image](https://user-images.githubusercontent.com/2437862/97483328-4b22fa80-1925-11eb-8a87-41229d0b4d7c.png)

**Comment by warlof** [comment]
Ok, regarding the main character update, it's normal that it don't apply change to a squad.
Squads only track for certain changes, more precisely, changes related to available filters.

An user which is changing his main do not result in a character change. The originate and target character are still in the same alliance and corporation. They also still have the same assets and skills. Last but not least, they're still the same.

Squads filters are not apply to a main thing, they're applied to users and data they're owning.

**Comment by lk77** [comment]
Hello,

i've created a auto squad and it's empty, what is the solution ?

there is no artisan command to trigger an update of the squads members.

thanks.

**Comment by warlof** [comment]
Hi,

To provide assistance, we need information. What your squad setup looks like?

**Comment by lk77** [comment]
It's just a corporation filter :

Corporation |  Is | {name of the corp}

in the filters

and in the type select, auto is selected.

**Comment by warlof** [comment]
No, squad do not relay on permissions. They only maintain roles attached to an user account

**Comment by Nfinished** [comment]
Anecdotally I've found that users who log in with only the `publicData` scope don't seem to get added to auto squads. After requiring them to log in with an additional `killmails` scope the problem seems to have gone away.

**Comment by lk77** [comment]
He had a job issue it seems, we had scheduled commands that were removed from seat v4, and scheduler failed to execute some commands, i think jobs were not created in the first place to update the squads. I've removed everything from the scheduler and added back the commands that still exists and it works.

**Comment by warlof** [comment]
@lk77 do you have the list of said commands? Normally all v3 command should be drop by the seeder. But I may forgot one or the other.

**Comment by lk77** [comment]
some commands were from packages like seat-groups that were removed, i don't think that it was seat own commands
