### ISSUE TITLE
Error 500 when attempting to 'Change Main Character'

### ISSUE THREAD

**Issue by LuciousLisa** [eveseat/seat#708]
* **Problem**: After linking characters, my alt became the main character that logging in would default to. Clicking 'Change Main Character' in the cogwheel menu (profile settings etc) results in an error 500 page.
* **Expected**: Clicking 'Change Main Character' in the cogwheel menu (profile settings etc) should results in page with all linked characters, of which I can select one as my main character.
* **Logs / Screenshots / Proof**:
Steps to reproduce:
1. Link several characters in the same EVE account
2. Click 'Change Main Character' in the cogwheel menu (profile settings etc)
3. Error 500 page
* **Version Info**: As I have now lost access to my main character, which had admin rights, I am unable to retrieve this info until another admin removes the SeAT accounts for my alts. The last known info that I had (based on a bug report 4 days ago) is:
```| Vendor  | Package Name   | Installed Version        |
| ------- | -------------- | ------------------------ |
| eveseat | api            | 4.1.0                    |
| eveseat | console        | 4.0.4                    |
| eveseat | eveapi         | 4.1.3                    |
| eveseat | notifications  | 4.0.3                    |
| eveseat | services       | 4.0.0                    |
| eveseat | web            | 4.2.2                    |
| ccp     | eve_online_sde | sde-20201008-TRANQUILITY |```

**Comment by JLCarveth** [comment]
+1 this has occurred on several installations for myself as well

**Comment by warlof** [comment]
Hi,

We'll need logs to be able to determine what's going on. Is it a migrated Gen 3?

**Comment by LuciousLisa** [comment]
I do not have access to the logs on this particular server. If @JLCarveth or anyone else can provide them, that would be great! I will ask my fellow admin to get in touch with the server admin to try and retrieve logs, but I'm not holding my breath.  
As for the second question, yes - it was migrated from v3.

**Comment by JLCarveth** [comment]
https://pastebin.com/sSywcK6H
