### ISSUE TITLE
Incorrect seat api response on POST successes

### ISSUE THREAD

**Issue by jgrancell** [eveseat/seat#710]
* **Problem**: `/api/v2/roles` endpoint returns undocumented `201` error code on success.
* **Expected**: `200`, per Swagger documentation
* **Logs / Screenshots / Proof**: https://imgur.com/wRwG9rr.png
* **Version Info**: Not really relevant. PHP 7.4, Alpine container on Kubernetes.

I believe this is a documentation issue with the Swagger documentation, as Laravel returns a `201` when a new Resource is created by default.

I can submit a PR to fix this if needed.

**Comment by warlof** [comment]
Hi,

Indead, seems to be a typo in the swagger documentation block. 

Pull requests are always welcome 😊

**Comment by jgrancell** [comment]
PR submitted with fix for this specific response code. I'm working on building a Terraform provider for Seat, so i'll be touching every endpoint and can validate all of them over the next week.

We can keep that PR open to catch-all any other Swagger documentation fixes, or merge to close this. Doesn't matter to me.
