### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Maexwell-nolen** [eveseat/seat#711]
Hello Everyone,
i have install php7.4

That comes when I run composer

Installing eveseat/seat (4.0.0)
  - Syncing eveseat/seat (4.0.0) into cache
  - Installing eveseat/seat (4.0.0): Cloning ce830d9be9 from cache
Created project in /var/www/seat
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - eveseat/eveapi[4.0.0-rc1, ..., 4.0.0-rc7] require eveseat/services 4.0.x-d                       ev -> found eveseat/services[dev-release, dev-master, 1.0.0, ..., 1.0.23, 2.0.0-                       alpha1, ..., 2.x-dev, 3.0.0-beta1, ..., 3.0.x-dev, 4.0.0-rc1, ..., 4.0.0] but it                        does not match the constraint.
    - eveseat/eveapi 4.0.0-rc3 requires eveseat/eseye 4.0.x-dev -> found eveseat                       /eseye[dev-master, 0.0.1, ..., 0.0.12, 1.0.0, ..., 1.1.8, 2.0.0, ..., 2.2.2] but                        it does not match the constraint.
    - eveseat/eveapi[4.0.0, ..., 4.2.0] require ext-redis * -> it is missing fro                       m your system. Install or enable PHP's redis extension.
    - Root composer.json requires eveseat/eveapi ^4.0 -> satisfiable by eveseat/                       eveapi[4.0.0-rc1, ..., 4.2.0].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-bz2.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-curl.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-intl.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/20-zip.ini
You can also run `php --ini` inside terminal to see which files are used by PHP                        in CLI mode.
Running update with --no-dev does not mean require-dev is ignored, it just means                        the packages will not be installed. If dev requirements are blocking the update                        you have to resolve those problems.

**Comment by warlof** [comment]
Hi,

It appears you miss dependencies. Fix php extensions and you should be good to go.
