### ISSUE TITLE
ESS bounties not showing in wallet journal

### ISSUE THREAD

**Issue by leg0las-devel** [eveseat/seat#712]
SeAT:

![Screenshot_20201119_143731](https://user-images.githubusercontent.com/7235356/99667959-c6378680-2a75-11eb-9cf6-05fe37d99f67.png)

In-game journal:

![Screenshot_20201119_144148](https://user-images.githubusercontent.com/7235356/99668068-ec5d2680-2a75-11eb-8e29-616753b2dace.png)

Sorry for RU client, i hope, it's enough. SeAT last version (all updated), SDE too.

**Comment by wfjsw** [comment]
AFAIK ESS payments are still missing from the ESI endpoints.

**Comment by warlof** [comment]
Thank you for the feedback,

That was the thing I was aware. So, this will be sorted as soon as the entry land in ESI (and we perhaps had make some change according to new type - but not a big thing here)

**Comment by wfjsw** [comment]
ESS Escrow Payments is now available in corporation wallet journals.

No serious problem so far.

**Comment by leg0las-devel** [comment]
probably new type records, not showed in wallet atm

**Comment by wfjsw** [comment]
In v3.x it is shown as `Ess Escrow Payment`
Seems still unavailable in character journals.

**Comment by warlof** [comment]
As per ESI specs, there is `ess_escrow_transfer`, but I don't know if it's the one you're looking for.
Anyone can provide an ESI body including those new ESS things ?

The issue is still open on ESI board, so I don't think it has been changed.
