### ISSUE TITLE
Need help with api

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#72]
Trying to setup a php page that handles an api submission form. Has some filler data in it right now to test but doesn't do anything

```php
<?php
// set post fields
$post = [
    'key_id' => '***opsec***',
	'v_code' => '***opsec***',
];

$ch = curl_init('http://sec.mambaonline.org:8000/api/v1/key');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'X-Token: ***opsec***';

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$response = curl_exec($ch);
curl_close($ch);
?>
```

script runs but key isn't added.. curl is installed and active.

**Comment by freedenizen** [comment]
Well the first thing that comes to mind is testing api calls on the command line and see if it works.

**Comment by shibdib** [comment]
Is that as simple as putting the examples with correct info into the commandline? Because I tried that and it just seemed to hang

**Comment by leonjza** [comment]
Is your web server running on port 8000? If not, just drop the port portion and try again.

**Comment by shibdib** [comment]
that got it to execute, now (after adding an echo for the response) it's telling me unauthorized

**Comment by shibdib** [comment]
Nope still shows the request coming from the user. So just need to know what to put there to make it accept ip's.

**Comment by shibdib** [comment]
resolved in slack :)
