### ISSUE TITLE
Feature Request: API filtering

### ISSUE THREAD

**Issue by Nfinished** [eveseat/seat#720]
It'd be nice to be able to filter list endpoints such as `/contracts` by enums like status, type or availability. Right now you have to make multiple calls to the paginated endpoint before filtering the concatenated responses.

**Comment by warlof** [comment]
I introduce OData filters to the API with this pull request : https://github.com/eveseat/api/pull/59
Would it suit the needs ?

**Comment by Nfinished** [comment]
Could you add a status filter to the contracts endpoint? Super important bit of information

**Comment by warlof** [comment]
`/v2/character/contracts/{character_id}/?$filter=status eq in_progress` isn't working ?

**Comment by Nfinished** [comment]
Doesn't seem to be, am I doing something silly?

`{{baseUrl}}/corporation/contracts/{{corpId}}?$filter=status eq 'in_progress'`

**Comment by warlof** [comment]
are you using previously linked pull request ?

**Comment by Nfinished** [comment]
![image](https://i.giphy.com/media/3oEjI67Egb8G9jqs3m/giphy.webp)

I thought this was live in the most recent minor version...
