### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by erikterr** [eveseat/seat#723]
O7,
upgraded to last version, after everything on the upgrade worked fine, I cleaned the cache also,
I received the error 500 on web page.
I tried with php artisan seat:admin:diagnose and I received the following error:

In EseyeSetup.php line 44:
Class 'Composer\InstalledVersios' not found

Problem**: Unable to use seat anymore, error 500 on login page
Expected**: To use seat normally..
Logs / Screenshots / Proof**: Check on description, error 500 on seat webpage, error "InstalledVersions" not found on diagnose command
* **Version Info**: PHP: 7.3.24, SeAT Version should be 4.4.3 but the update broke something Operating System Ubuntu 18.04

**Comment by warlof** [comment]
Hi,

Please upgrade your composer version. 
To do so : `composer self-update`
After update, ensure it's version 2 or greater.
To do so : `composer --version`
If it's still in v1, force update to v2 channel. 
To do so : `composer self-update --2`

**Comment by erikterr** [comment]
Solved, composer was version 1.10 didn't noticed that was update available. Sorry for that and tnx a lot!
