### ISSUE TITLE
notifications::alerts.disabled_token seems not working

### ISSUE THREAD

**Issue by zino73** [eveseat/seat#725]
* **Problem**: i have setup mail notification for 3 alerts  : 

![image](https://user-images.githubusercontent.com/15671678/101828465-e23cbe00-3b31-11eb-874b-e42eb1445c06.png)

"Corporation Leaving Character" : work fine (I do receive an email when a member leaves the corporation)
"notifications::alerts.enabled_token" :  didnt work , I never received email when some one enabled a token
"notifications::alerts.disabled_token" : didnt work , I never received email when some disable character token

* **Version Info**:  docker version
![image](https://user-images.githubusercontent.com/15671678/101828909-7d359800-3b32-11eb-8674-41a460d0fac7.png)

**Comment by warlof** [comment]
That's normal, those two notifications are not supported by mail channel as shown by the missing mail icon in the list.
