### ISSUE TITLE
Feature Request : Adding Token Status to Characters list 

### ISSUE THREAD

**Issue by zino73** [eveseat/seat#726]
like this : 
![image](https://user-images.githubusercontent.com/15671678/101832050-1ebee880-3b37-11eb-9e21-5cf7779a3303.png)

would be awesome

**Comment by ppfeufer** [comment]
So much this. I didn't know that I need it, until now :-)

**Comment by mike0891** [comment]
@zino73 @ppfeufer There is the tracking page, that is under your corporation. Though it obviously does not track out of corp alts.
![image](https://user-images.githubusercontent.com/31676627/101944319-749d9a00-3be4-11eb-8532-fee6cd68a85f.png)

**Comment by zino73** [comment]
i know it, but i want to be able to track no corporation members as well
