### ISSUE TITLE
Scheduled Jobs not Executing

### ISSUE THREAD

**Issue by markm1701** [eveseat/seat#73]
Hi all, wonder if anyone can assist me with a problem - Scheduled Jobs not working

## Expected Behaviour
My system was running the 0.14 beta previously, 
which i deleted and went through the instructions from scratch
i'm running Centos 7
I can run the jobs manually from queue management

## Log Extracts / Proof
here is my laravel.log file, this is the only error present  (error is repeated about once a minute)
```
[2016-03-07 02:07:01] local.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "scheduled" namespace.

Did you mean this?
    schedule' in /var/www/seat/vendor/symfony/console/Application.php:469
Stack trace:
#0 /var/www/seat/vendor/symfony/console/Application.php(501): Symfony\Component\Console\Application->findNamespace('scheduled')
#1 /var/www/seat/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->find('scheduled:run')
#2 /var/www/seat/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/seat/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
```

## Output of `php artisan seat:admin:diagnose`
I ran this as my apache user

```
[root@meridian seat]# sudo -u apache php artisan seat:admin:diagnose
SeAT Diagnostics

 * Getting environment information
Current User: apache
PHP Version: 5.5.33
Host OS: Linux meridian 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/app/pheal/ is writable
/var/www/seat/storage/sde/ is writable
/var/www/seat/storage/logs/laravel.log is writable


Connection OK to database: seatv1

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6379      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: hBBASAErizzjHY7RR06iktXMM9KZ4uGWsz3KjVBwb8hGoJFepwDu7vrCl5GFkz9h
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 22391

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 1.0.9         | 1.0.9         |
| Console       | 1.0.10        | 1.0.10        |
| Eveapi        | 1.0.12        | 1.0.12        |
| Notifications | 1.0.4         | 1.0.4         |
| Web           | 1.0.23        | 1.0.23        |
| Services      | 1.0.14        | 1.0.14        |
+---------------+---------------+---------------+

```

**Comment by GunfighterJ** [comment]
I'm also having this issue, SeAT lists no jobs have ever existing, nor am I able to manually run them.

`SeAT Diagnostics
If you are not already doing so, it is recommended that you run this as the user the workers are running as.
Eg:
    sudo -u apache php artisan seat:admin:diagnose
This helps to check whether the permissions are correct.

 * Getting environment information
Current User: gunfighterj
PHP Version: 5.6.19-1~dotdeb+7.1
Host OS: Linux wolverine.notoriousdev.com 4.2.5-grsec-ndev #3 SMP Fri Jan 8 20:23:44 GMT 2016 x86_64
SeAT Basepath: /home/gunfighterj/httpdocs/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/home/gunfighterj/httpdocs/www/seat/storage is writable
/home/gunfighterj/httpdocs/www/seat/storage/app/pheal/ is writable
/home/gunfighterj/httpdocs/www/seat/storage/sde/ is writable
/home/gunfighterj/httpdocs/www/seat/storage/logs/laravel.log is writable

 * Checking Database
+------------+----------------------------------+
| Setting    | Value                            |
+------------+----------------------------------+
| Connection |                                  |
| Host       | localhost                        |
| Database   | hogs_seat                        |
| Username   | hogs_seat                        |
| Password   | ******************************** |
+------------+----------------------------------+
Connection OK to database: hogs_seat

 * Checking Redis
+----------+-----------+
| Setting  | Value     |
+----------+-----------+
| Host     | 127.0.0.1 |
| Port     | 6380      |
| Database | 0         |
+----------+-----------+
Connected to Redis
Set random key of: fyFf6QYGIkSlZ1t0X4hrOQ38UZu68ycoLnPGsKf7pZ41b4JqFUPf3nXc55Hh4kzq
Set key to expire in 10 sec
Read key OK

 * Checking Pheal EVE API Access
Server Online: True
Online Players: 20701

Checking Local and Github Versions. Please wait...
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 1.0.9         | 1.0.9         |
| Console       | 1.0.10        | 1.0.10        |
| Eveapi        | 1.0.12        | 1.0.12        |
| Notifications | 1.0.4         | 1.0.4         |
| Web           | 1.0.23        | 1.0.23        |
| Services      | 1.0.14        | 1.0.14        |
+---------------+---------------+---------------+
SeAT Diagnostics complete`

**Comment by leonjza** [comment]
@markm1701 can you please paste the line from your cronjob? I suspect you have something like (note the word `scheduled` with the trailing d:

 `* * * * * /usr/bin/php /var/www/seat/artisan scheduled:run 1>> /dev/null 2>&1` 

instead of:

`* * * * * /usr/bin/php /var/www/seat/artisan schedule:run 1>> /dev/null 2>&1`

**Comment by GunfighterJ** [comment]
I see his issue is slightly different. I'll make my own issue.

**Comment by markm1701** [comment]
that was exactly the issue, i've changed it and now its working fine, thank you very much,  i missed the the d has been removed when i went through the instructions

Thanks leonjza
