### ISSUE TITLE
Optimize load time default page tools/moons

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#741]
* **Problem**: We have imported a few thousand moons in our moon tool. Problem is that just opening the tools/moons takes about 17 seconds to fully load. I would recommend to only show the list of moons once a Search with some sort of selection has been initiated. This also makes the submitting a moon Import less tedious

* **Version Info**: 

```
| Vendor   | Package Name           | Installed Version        |
| -------- | ---------------------- | ------------------------ |
| eveseat  | api                    | 4.4.0                    |
| eveseat  | console                | 4.7.0                    |
| eveseat  | eveapi                 | 4.8.0                    |
| eveseat  | notifications          | 4.2.0                    |
| eveseat  | services               | 4.1.2                    |
| eveseat  | web                    | 4.8.0                    |
| denngarr | seat-fitting           | v4.0.3                   |
| denngarr | seat-srp               | 4.0.6                    |
| warlof   | seat-connector         | 2.0.2                    |
| warlof   | seat-discord-connector | 5.0.0                    |
| ccp      | eve_online_sde         | sde-20201201-TRANQUILITY |
```

**Comment by warlof** [comment]
Hi,

I don't see the link between showing moon list and import complexity ?
As performance point of view, I suspect the footer stats to be the cause - but need some investigate.

I have 1 100 moons on my prod instances and it load in less than 2 seconds.

**Comment by kwazulueve** [comment]
Yeah importing is not complex, but everytime you submit a moon, it loads the front page again for 17 seconds while this is not showing anything useful (it doesn't remember settings at the moment, but that would be a seperate feature request)

I don't know what exactly is causing it, but the moon totals (the footer) is shown pretty much instantly while the actual moon list in the center is shown after 17 seconds. (7000+ moons)

**Comment by warlof** [comment]
For hint, you don't have to paste report moon per moon.
The system is capable of importing batch reports - as longer as the format is the same the one used in-game :p
