### ISSUE TITLE
Missing "clear logs" button in connector

### ISSUE THREAD

**Issue by Nfinished** [eveseat/seat#744]
Spoke with Warlof a bit ago about clearing connector logs, he suggested that there was a `clear` button on `/seat-connector/logs` but we both discovered it must have been removed at some point.

I'm nearing 2,000,000 entries from public users joining our TeamSpeak, would really appreciate a way to wipe them out.

**Comment by warlof** [comment]
Sorry, this is a third party thing - I duplicated your issue on proper repository
warlof/seat-connector#52
