### ISSUE TITLE
Tracking Upstream PR - Allow ts3server URLs as custom links.

### ISSUE THREAD

**Issue by maxtsero** [eveseat/seat#750]
* **Problem**: _It's currently not possible to add a link directly to a TeamSpeak3 server as the Laravel Validator doesn't support the `ts3server` URI scheme._
* **Expected**: _The URI scheme is valid and should, therefore work!_
* **Version Info**: _PHP 7.3, SeAT Current Stable, Ubuntu 20.04._
* **Other Info**: _An [Upstream PR](https://github.com/laravel/framework/pull/35933) has been opened already. Once this is merged we just need to bump the `laravel/framework` version appropriately._

**Comment by warlof** [comment]
Wrong repository. Please open it on third party seat-connector

**Comment by benthompson0** [comment]
@warlof I think this is tracking the customlink feature in the web package for the sidebar menu.

**Comment by warlof** [comment]
Oh, sorry - I miss understand the case.
However, SeAT is still targeting LTS version

**Comment by MikeyMJCO** [comment]
In that case @warlof you're probably right to close this and just keep it for "searchability" since it will be a while before this feature makes it to Laravel LTS :-)

**Comment by maxtsero** [comment]
Probably right to close this @warlof - it's logged now and will show up if someone has the issue. If Laravel accept the PR it will eventually trickle down and work in SeAT :-)

**Comment by warlof** [comment]
All right, closing it then.

**Comment by MikeyMJCO** [comment]
Thanks :-) Laravel merged the fix, so eventually it'll make it's way through to SeAT, until then you can either edit the Laravel Framework package (or patch it) or use https redirection to link to your TS server by linking as `https://invite.teamspeak.com/ts.yourserver.uk/?password=yourserverpassword`
