### ISSUE TITLE
Admin Master Token for obtaining metadata stats about corp for website??

### ISSUE THREAD

**Issue by fallenreaper** [eveseat/seat#752]
* **Problem**: I am trying to find a way to get metadata about a Corp to use in their website.
* **Expected**: Ease of use to get metadata for public display
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by Crypta-Eve** [comment]
Please define exactly what you want to be available. This issue as it stands is meaningless as it does not make sense. 

Admin Master Token? Do you mean like the seat api?
Metadata stats for corp website? What are you trying to show?

**Comment by fallenreaper** [comment]
Sorry, had to run out.

I was trying to find a mechanism to fetch corp related statistics to
display on our website, hosted likely on the same server.  I wasnt sure if
there was a dbms I could use to query against or if I could use the
existing seat API to pull things like online members, or other ceo related
metadata.

I didn't know if there was an static, resettable, admin token which could
act similar to that of a ceo or director which allowed me to pull metrics.

**Comment by Crypta-Eve** [comment]
I suggest you have a look into the SeAT Api. It is accessible on the left hand menu, or at https://seat.your.domain/api/documentation

**Comment by warlof** [comment]
Hey there, were you able to find what you were looking about ?
