### ISSUE TITLE
abandoned packages replacement?

### ISSUE THREAD

**Issue by mercyground** [eveseat/seat#753]
* **Problem**: _Abandoned packages warning.
* **Expected**:  Attempted to replace. Ran into circular dependances
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead. Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.

+--------------------+---------------+----------------+
| Package Name       | Local Version | Latest Version |
+--------------------+---------------+----------------+
| SeAT API           | 4.4.0         | 4.4.0          |
| SeAT Console       | 4.7.0         | 4.7.0          |
| SeAT Eve API       | 4.8.0         | 4.8.0          |
| SeAT Notifications | 4.2.0         | 4.2.0          |
| SeAT Services      | 4.1.2         | 4.1.2          |
| SeAT Web           | 4.8.1         | 4.8.1          |
+--------------------+---------------+----------------+

PHP 7.4.14 
Ubuntu 18.04

jakub-onderka/php-console-highlighter v0.4 Highlight PHP code in terminal
├──nunomaduro/collision v3.1.0 (requires jakub-onderka/php-console-highlighter 0.3.*|0.4.*)
│  └──eveseat/seat (requires (for development) nunomaduro/collision ^3.0)
└──psy/psysh v0.9.12 (requires jakub-onderka/php-console-highlighter 0.3.*|0.4.*)
   ├──eveseat/seat (requires psy/psysh @stable)
   └──laravel/tinker v1.0.10 (requires psy/psysh 0.7.*|0.8.*|0.9.*)
      ├──eveseat/seat (requires laravel/tinker ^1.0)
      ├──eveseat/notifications 4.2.0 (requires laravel/tinker ^1.0)
      │  └──eveseat/seat (requires eveseat/notifications ^4.0)
      └──eveseat/web 4.8.1 (requires laravel/tinker ~1.0)
         ├──eveseat/seat (requires eveseat/web ^4.0)
         └──eveseat/api 4.4.0 (requires eveseat/web ^4.0)
            └──eveseat/seat (requires eveseat/api ^4.0)

php-parallel-lint/php-console-color v1.0 Simple library for creating colored console ouput.
├──jakub-onderka/php-console-highlighter v0.4 (requires jakub-onderka/php-console-color ~0.2)
│  ├──nunomaduro/collision v3.1.0 (requires jakub-onderka/php-console-highlighter 0.3.*|0.4.*)
│  │  └──eveseat/seat (requires (for development) nunomaduro/collision ^3.0)
│  └──psy/psysh v0.9.12 (requires jakub-onderka/php-console-highlighter 0.3.*|0.4.*)
│     ├──eveseat/seat (requires psy/psysh @stable)
│     └──laravel/tinker v1.0.10 (requires psy/psysh 0.7.*|0.8.*|0.9.*)
│        ├──eveseat/seat (requires laravel/tinker ^1.0)
│        ├──eveseat/notifications 4.2.0 (requires laravel/tinker ^1.0)
│        │  └──eveseat/seat (requires eveseat/notifications ^4.0)
│        └──eveseat/web 4.8.1 (requires laravel/tinker ~1.0)
│           ├──eveseat/seat (requires eveseat/web ^4.0)
│           └──eveseat/api 4.4.0 (requires eveseat/web ^4.0)
│              └──eveseat/seat (requires eveseat/api ^4.0)
├──php-parallel-lint/php-console-color v1.0 (replaces jakub-onderka/php-console-color *)
│  ├──eveseat/seat (requires php-parallel-lint/php-console-color ^1.0)
│  └──php-parallel-lint/php-console-color v1.0 (replaces jakub-onderka/php-console-color *) (circular dependency aborted here)
└──php-parallel-lint/php-console-highlighter v0.4 (requires jakub-onderka/php-console-color ~0.2)
   └──eveseat/seat (requires (for development) php-parallel-lint/php-console-highlighter 0.*)

having done some digging apparently both laravel and collision have fixed their dependances on these abandoned packages and updated. However it appears Seat is fixed on older out of date dependancies and thus these error messages are unable to be fixed as they rely on out of date packages.

Is Seat going to bump the requirements or is it just a case of ignoring the warnings and living with it?

Attempting to replace with  php-parallel-lint/php-console-color  gets me this.

Warning: Ambiguous class resolution, "JakubOnderka\PhpConsoleHighlighter\Highlighter" was found 2x: in "/var/www/seat/vendor/jakub-onderka/php-console-highlighter/src/Highlighter.php" and "/var/www/seat/vendor/php-parallel-lint/php-console-highlighter/src/Highlighter.php", the first will be used.

and trying to replace  php-parallel-lint/php-console-highlighter gets me 

  Problem 1
    - Root composer.json requires php-parallel-lint/php-console-highlighter ^0.5.0 -> satisfiable by php-parallel-lint/php-console-highlighter[v0.5].
    - php-parallel-lint/php-console-highlighter v0.5 requires php-parallel-lint/php-console-color ~0.2 -> found php-parallel-lint/php-console-color[v0.2, v0.3] but it conflicts with your root composer.json require (^1.0).

**Comment by warlof** [comment]
Bump `laravel/tinker` to 2.5 should hide warnings.
https://github.com/laravel/laravel/blob/d85be8669880cce457eb5827afbedb6ad30bb629/composer.json#L14

**Comment by mercyground** [comment]
k. edited tinker to 

    "laravel/tinker": "^2.5",

tried composer update and got this back

 Problem 1
    - eveseat/web[4.0.0-rc1, ..., 4.8.1] require laravel/tinker ~1.0 -> found laravel/tinker[v1.0.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.5).
    - eveseat/web[4.0.0-rc5, ..., 4.0.0-rc7] require eveseat/eveapi 4.0.x-dev -> found eveseat/eveapi[dev-master, 1.0.0, ..., 1.0.18, 2.0.0-alpha1, ..., 2.x-dev, 3.0.0-beta1, ..., 3.0.x-dev, 4.0.0-rc1, ..., 4.8.0] but it does not match the constraint.
    - Root composer.json requires eveseat/web ^4.0 -> satisfiable by eveseat/web[4.0.0-rc1, ..., 4.8.1].

**Comment by warlof** [comment]
If you don't apply changes to dependencies, you'll be stuck. 

This need to be sorted at core level. That's nothing critical though, you can pass through.

**Comment by mercyground** [comment]
i thought that changing the dependancy in the json file and then pushing a  composer update -W
would force tinker to get upgraded? have i misunderstood something?

**Comment by warlof** [comment]
Seems you miss understand packages dependencies

This is what you probably change https://github.com/eveseat/seat/blob/f2aac98b1454e84954fd79f74fb162f0b61bcc5d/composer.json#L19

Which require also this https://github.com/eveseat/web/blob/9160b8e8ae4a7b6f21c79d3e6feeb599cf50ddb3/composer.json#L45
or that https://github.com/eveseat/notifications/blob/5418f03371cfbafd64da147307c6945c702a276c/composer.json#L23

That's almost what the overall message you posted is telling you.

**Comment by mercyground** [comment]
this is my current composer.json file

`{
  "name": "eveseat/seat",
  "description": "Simple Eve Api Tool",
  "keywords": [
    "eve",
    "online",
    "corporation",
    "management",
    "api"
  ],
  "license": "GPL-2.0",
  "type": "project",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": "^7.3",
    "ext-pdo": "*",
    "eveseat/api": "^4.0",
    "eveseat/console": "^4.0",
    "eveseat/eveapi": "^4.0",
    "eveseat/notifications": "^4.0",
    "eveseat/services": "^4.0",
    "eveseat/web": "^4.0",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "^6.2",
    "laravel/tinker": "^2.5",
    "php-parallel-lint/php-console-color": "^1.0",
    "psy/psysh": "@stable"
  },
  "require-dev": {
    "facade/ignition": "^1.4",
    "fzaninotto/faker": "^1.4",
    "mockery/mockery": "^1.0",
    "nunomaduro/collision": "^3.0",
    "php-parallel-lint/php-console-highlighter": "0.*",
    "phpunit/phpunit": "^8.0"
  },
  "autoload": {
    "classmap": [
      "database/seeds",
      "database/factories"
    ],
    "psr-4": {
      "App\\": "app/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "extra": {
    "laravel": {
      "dont-discover": [
      ]
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "@php artisan key:generate --ansi"
    ],
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover --ansi"
    ]
  },
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true
  }
}
`

**Comment by mercyground** [comment]
composer require laravel/tinker "^2.5" -W

./composer.json has been updated
Running composer update laravel/tinker --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading laravel/tinker (v1.0.10 => v2.5.0)
  - Upgrading psy/psysh (v0.9.12 => v0.10.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading psy/psysh (v0.10.6)
  - Downloading laravel/tinker (v2.5.0)
  - Upgrading psy/psysh (v0.9.12 => v0.10.6): Extracting archive
  - Upgrading laravel/tinker (v1.0.10 => v2.5.0): Extracting archive

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: darkaonline/l5-swagger
Discovered Package: eveseat/api
Discovered Package: eveseat/console
Discovered Package: eveseat/eveapi
Discovered Package: eveseat/notifications
Discovered Package: eveseat/services
Discovered Package: eveseat/web
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/horizon
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: socialiteproviders/manager
Discovered Package: yajra/laravel-datatables-buttons
Discovered Package: yajra/laravel-datatables-html
Discovered Package: yajra/laravel-datatables-oracle
Package manifest generated successfully.

**Comment by mercyground** [comment]
composer require php-parallel-lint/php-console-highlighter -W
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Using version ^0.5.0 for php-parallel-lint/php-console-highlighter
./composer.json has been updated
Running composer update php-parallel-lint/php-console-highlighter --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 2 removals
  - Removing jakub-onderka/php-console-color (v0.2)
  - Removing jakub-onderka/php-console-highlighter (v0.4)
  - Upgrading php-parallel-lint/php-console-highlighter (v0.4 => v0.5)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 2 removals
  - Downloading php-parallel-lint/php-console-highlighter (v0.5)
  - Removing jakub-onderka/php-console-highlighter (v0.4)
  - Removing jakub-onderka/php-console-color (v0.2)
  - Upgrading php-parallel-lint/php-console-highlighter (v0.4 => v0.5): Extracting archive


All fixed thanks!

**Comment by warlof** [comment]
Laravel Tinker will be bump to 2.5 or greater according to latest Laravel template which will fix this deprecated package issue.

Users with Docker instance will not have anything to do, however, those using blade installation will have to update their `composer.json` to match with updated file from seat main package.

Update is scheduled on Saturday 13th of February.

**Comment by warlof** [comment]
this has been fully addressed by eveseat/seat@4.0.3 release
