### ISSUE TITLE
Switching squads leads to not getting all roles assigned.

### ISSUE THREAD

**Issue by jediefe** [eveseat/seat#754]
* **Problem**: Users that are added to an auto squad based on alliance affiliation are not assigned all roles belonging to the squad.
* **Expected**: User should have all roles that are defined in squad settings
* **Logs / Screenshots / Proof**: See description below
* **Version Info**: 
```
| Vendor   | Package Name           | Installed Version        |
| -------- | ---------------------- | ------------------------ |
| eveseat  | api                    | 4.4.0                    |
| eveseat  | console                | 4.7.1                    |
| eveseat  | eveapi                 | 4.8.0                    |
| eveseat  | notifications          | 4.2.0                    |
| eveseat  | services               | 4.1.2                    |
| eveseat  | web                    | 4.8.1                    |
| denngarr | seat-fitting           | v4.0.3                   |
| denngarr | seat-srp               | 4.0.6                    |
| kassie   | calendar               | 4.0.3                    |
| warlof   | seat-connector         | 2.2.0                    |
| warlof   | seat-discord-connector | 5.0.0                    |
| warlof   | seat-teamspeak         | 5.1.0                    |
| ccp      | eve_online_sde         | sde-20201201-TRANQUILITY |
```

The problem occurs with the following setup: 

Squad A: Auto Squad, based on filter "Is Member of Alliance A". Attached are roles *A* and *B*.
Squad B: Auto Squad, based on filter "Is Member of Alliance B". Attached are roles *A* and *C*.

Circumstances: Users' character switches corp, leaving Alliance *A* and joining Alliance *B*. Thus he is kicked from Squad *A* and added to Squad *B*. This leads him to lose roles *A* and *B*, but gets role *C* assigned only, instead of role *A* and *C*.

I hope that description is precise enough for investigation.

Also possibly related to #702

**Comment by warlof** [comment]
Hum, swapping the two actions add/remove here would probably fix that https://github.com/eveseat/web/blob/7b26bd0da14461ff8701eb863f269dd20d22a94f/src/Observers/AbstractSquadObserver.php#L63

So instead adding first, then removing - we will remove first, then adding.

Just thinking about which case could prevent it to work as expected.
