### ISSUE TITLE
Add Token Summery in Corporation list view

### ISSUE THREAD

**Issue by JohnSheppard001** [eveseat/seat#755]
**Feature Request**

In the All Corporation windows add characters token summer, to show both number and percentage of how many members of said corporation have registered on services.

In addition, a way to filter a specific alliance in all Corporation view to help audit corps within an alliance.

**Comment by warlof** [comment]
For the filter, searching the alliance isn't working?

**Comment by JohnSheppard001** [comment]
> For the filter, searching the alliance isn't working?

just checked it is working actually so just the first feature request to display token summary like 14/20 members registered or something like that

**Comment by JohnSheppard001** [comment]
Thank you @Crypta-Eve for implementing this feature, however, I see that you added it to the corp summary page rather than the corporations page.

would it be possible to move it to the corporations page instead of the member count. member count will barely show accurate numbers unless u have a director or CEO signed up and I don't think its needed as much as the token summary.

This will allow you to search your alliance for example and quickly look at their token summary for auditing or copy and pasting to discord or google docs for postings. Instead of having to click and show info on every corp of your alliance to check the summary page.

Cheers
