### ISSUE TITLE
Starbase modules not showing

### ISSUE THREAD

**Issue by shibdib** [eveseat/seat#76]
starbase modules don't show for any besides the top most pos on the list.

http://i.imgur.com/Vt042le.png

**Comment by leonjza** [comment]
Have the keys finished updating everything?
Please check the database if there is actually data there.

**Comment by shibdib** [comment]
the 2 starbase tables are all populated and updated. Can't find the table that lists modules tho

**Comment by leonjza** [comment]
This still the case?

**Comment by shibdib** [comment]
seems to be specific to chrome, tried it on IE and it works fine. Chrome with all extensions off doesn't work.

**Comment by leonjza** [comment]
Please paste the output (if any) that you get in the Chrome console when clicking the modules buttons.

**Comment by mpgram** [comment]
I can see all modules hanging on the POSes with no issues (3 total POS)  I am using Chrome v48.0.2564.116 m

**Comment by leonjza** [comment]
Yeah also having a hard time replicating this.

**Comment by shibdib** [comment]
Hmm weird, I tried with no extensions and still no dice besides the top one. But it works fine in IE so Ill just toss it up as a fluke?
