### ISSUE TITLE
Error on kicking users from Squads

### ISSUE THREAD

**Issue by jediefe** [eveseat/seat#764]
* **Problem**: Server returns an Error 500 when users are kicked manually from a squad.
* **Expected**: Users should be kicked properly.
* **Logs / Screenshots / Proof**: From the logs: ```Call to a member function where() on null at /var /www/seat4/vendor/eveseat/web/src/Observers/SquadMemberObserver.php:61```
Users are kicked from the squad but keep the attached roles. This is problematic behaviour. 
Problem causing code snippet: https://github.com/eveseat/web/blob/6e910d0ddb763e85dc43205e42930c1469361a43/src/Observers/SquadMemberObserver.php#L61
* **Version Info**:  
```
| Vendor   | Package Name           | Installed Version        |
| -------- | ---------------------- | ------------------------ |
| eveseat  | api                    | 4.5.0                    |
| eveseat  | console                | 4.7.2                    |
| eveseat  | eveapi                 | 4.9.2                    |
| eveseat  | notifications          | 4.3.0                    |
| eveseat  | services               | 4.1.3                    |
| eveseat  | web                    | 4.9.0                    |
| denngarr | seat-fitting           | 4.0.4                    |
| denngarr | seat-srp               | 4.0.6                    |
| kassie   | calendar               | 4.0.3                    |
| warlof   | seat-connector         | 2.2.0                    |
| warlof   | seat-discord-connector | 5.0.0                    |
| warlof   | seat-teamspeak         | 5.1.0                    |
| ccp      | eve_online_sde         | sde-20210211-TRANQUILITY |
```

**Comment by jediefe** [comment]
I spent some time to try to help investigate the issue. From what I could find so far is that it seems to me that `$member->squads` is not implemented in the User model, thus returning `null`. I hope this is useful for you in any way.

**Comment by warlof** [comment]
exact, I spot it when you open the issue.
it will be address on march rollup.

**Comment by jediefe** [comment]
Coolio, merci beaucoup ;-)
