### ISSUE TITLE
Trying to get the moon report and extraction to work.

### ISSUE THREAD

**Issue by kevinouw** [eveseat/seat#767]
Trying to get the moon report and extraction to work.

the logs above are the thing that show when i try to get to the pages:

[Scrrenshot 1](https://i.imgur.com/Slt4PmK.png)
[scrrenshot 2](https://i.imgur.com/U0NBTRC.png
)
Version details:
https://i.imgur.com/U0NBTRC.png

Done yesterday the update as listed here :
https://eveseat.github.io/docs/upgrading/general/

OS is ubuntu
Baremetal install

71): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illumin                                                                                                                                                             ate\\Http\\Request), Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middle                                                                                                                                                             ware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeli                                                                                                                                                             ne\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(I                                                                                                                                                             lluminate\\Http\\Request), Object(Closure))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareE                                                                                                                                                             rrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\                                                                                                                                                             {closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illumi                                                                                                                                                             nate\\Http\\Request), Object(Closure))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/Sta                                                                                                                                                             rtSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closur                                                                                                                                                             e}(Object(Illuminate\\Http\\Request))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\H                                                                                                                                                             ttp\\Request), Object(Closure))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQ                                                                                                                                                             ueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipe                                                                                                                                                             line\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(                                                                                                                                                             Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/Encr                                                                                                                                                             yptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closu                                                                                                                                                             re}(Object(Illuminate\\Http\\Request))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\                                                                                                                                                             Http\\Request), Object(Closure))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Ill                                                                                                                                                             uminate\\Http\\Request))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683                                                                                                                                                             ): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658                                                                                                                                                             ): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\                                                                                                                                                             Route), Object(Illuminate\\Http\\Request))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624                                                                                                                                                             ): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Obje                                                                                                                                                             ct(Illuminate\\Routing\\Route))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613                                                                                                                                                             ): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request                                                                                                                                                             ))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel                                                                                                                                                             .php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Reques                                                                                                                                                             t))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closu                                                                                                                                                             re}(Object(Illuminate\\Http\\Request))
#35 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\P                                                                                                                                                             ipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Requ                                                                                                                                                             est))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request),                                                                                                                                                              Object(Closure))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middle                                                                                                                                                             ware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipe                                                                                                                                                             line\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object                                                                                                                                                             (Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middle                                                                                                                                                             ware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipe                                                                                                                                                             line\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object                                                                                                                                                             (Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middle                                                                                                                                                             ware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipel                                                                                                                                                             ine\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(                                                                                                                                                             Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middle                                                                                                                                                             ware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate                                                                                                                                                             \\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(                                                                                                                                                             Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(                                                                                                                                                             105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Ill                                                                                                                                                             uminate\\Http\\Request))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel                                                                                                                                                             .php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel                                                                                                                                                             .php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object                                                                                                                                                             (Illuminate\\Http\\Request))
#48 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->ha                                                                                                                                                             ndle(Object(Illuminate\\Http\\Request))
#49 {main}
"}
[2021-02-27 11:39:45] local.ERROR: Call to undefined method Seat\Eveapi\Models\Sde\Moon::ubiquitous() {"userId":2,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Seat\\Eveapi\\Models\\Sde\\Moon::ubiquitous() at /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
[stacktrace]
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('ubiquitous')
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1622): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'ubiquitous', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1634): Illuminate\\Database\\Eloquent\\Model->__call('ubiquitous', Array)
#3 /var/www/seat/vendor/eveseat/web/src/Http/Controllers/Tools/MoonsController.php(51): Illuminate\\Database\\Eloquent\\Model::__callStatic('ubiquitous', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Seat\\Web\\Http\\Controllers\\Tools\\MoonsController->index(Object(Seat\\Web\\Http\\DataTables\\Tools\\MoonsDataTable))
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Seat\\Web\\Http\\Controllers\\Tools\\MoonsController), 'index')
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'moon.view_moon_...')
#12 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"}

**Comment by kevinouw** [comment]
Prune job queue, this will prevent already queued jobs to use old codebase

php artisan cache:clear
Renew cached configuration and routes

php artisan config:cache
php artisan route:cache

was also done like other commannds as well it did not update 2 packages

**Comment by warlof** [comment]
To retrieve versions information, you can run `php artisan seat:version` which will provide you the detailed information of all SeAT core packages including installed and last available versions.

If you're still outdated with one of the following packages, refer to last patch-note which are containing specific instructions for bare-metal installations :
 - eveseat/notifications => https://github.com/eveseat/notifications/releases/tag/4.3.0
 - eveseat/web => https://github.com/eveseat/web/releases/tag/4.9.0

Be sure you're using composer 2
Be sure you're using any php version between 7.3 or 7.4 to execute SeAT

**Comment by kevinouw** [comment]
root@ubuntu:/var/www/seat# php artisan seat:version
Checking Local and Latest Versions. Please wait...
+--------------------+---------------+----------------+
| Package Name       | Local Version | Latest Version |
+--------------------+---------------+----------------+
| SeAT API           | 4.5.0         | 4.5.0          |
| SeAT Console       | 4.7.2         | 4.7.2          |
| SeAT Eve API       | 4.9.2         | 4.9.2          |
| SeAT Notifications | 4.2.0         | 4.3.0          |
| SeAT Services      | 4.1.3         | 4.1.3          |
| SeAT Web           | 4.8.1         | 4.9.0          |
+--------------------+---------------+----------------+

root@ubuntu:/var/www/seat# php -v
PHP 7.3.27-9+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:10:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-9+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by kevinouw** [comment]
root@ubuntu:/var/www/seat# composer self-update
You are already using the latest available Composer version 2.0.11 (stable channel).

**Comment by kevinouw** [comment]
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'php artisan down'
Application is now in maintenance mode.
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'composer update --no-dev'
Cannot create cache directory /var/www/.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.cache/composer/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Nothing to install, update or remove
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class Coduo\PHPHumanizer\Tests\NumberHumanizerTest located in ./vendor/coduo/php-humanizer/tests/Coduo/PHPHumanizer/Tests/NumberHumanizerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Coduo\PHPHumanizer\Tests\DateTimeHumanizerTest located in ./vendor/coduo/php-humanizer/tests/Coduo/PHPHumanizer/Tests/DateTimeHumanizerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Coduo\PHPHumanizer\Tests\StringHumanizerTest located in ./vendor/coduo/php-humanizer/tests/Coduo/PHPHumanizer/Tests/StringHumanizerTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Coduo\PHPHumanizer\Tests\CollectionHumanizerTest located in ./vendor/coduo/php-humanizer/tests/Coduo/PHPHumanizer/Tests/CollectionHumanizerTest.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: cryptaeve/seat-squad-sync
Discovered Package: cryptaeve/seat-text
Discovered Package: darkaonline/l5-swagger
Discovered Package: eveseat/api
Discovered Package: eveseat/console
Discovered Package: eveseat/eveapi
Discovered Package: eveseat/notifications
Discovered Package: eveseat/services
Discovered Package: eveseat/web
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/horizon
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: socialiteproviders/manager
Discovered Package: warlof/seat-connector
Discovered Package: warlof/seat-discord-connector
Discovered Package: warlof/seat-teamspeak
Discovered Package: yajra/laravel-datatables-buttons
Discovered Package: yajra/laravel-datatables-html
Discovered Package: yajra/laravel-datatables-oracle
Package manifest generated successfully.
67 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'php artisan vendor:publish --force --all'
Copied File [/vendor/yajra/laravel-datatables-oracle/src/config/datatables.php] To [/config/datatables.php]
Copied File [/vendor/laravel/horizon/stubs/HorizonServiceProvider.stub] To [/app/Providers/HorizonServiceProvider.php]
Copied File [/vendor/laravel/horizon/config/horizon.php] To [/config/horizon.php]
Copied Directory [/vendor/laravel/horizon/public] To [/public/vendor/horizon]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views] To [/resources/views/errors]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Copied File [/vendor/darkaonline/l5-swagger/config/l5-swagger.php] To [/config/l5-swagger.php]
Copied Directory [/vendor/darkaonline/l5-swagger/resources/views] To [/resources/views/vendor/l5-swagger]
Copied File [/vendor/eveseat/eveapi/src/Config/esi.php] To [/config/esi.php]
Copied File [/vendor/eveseat/notifications/src/Config/notifications.alerts.php] To [/config/notifications.alerts.php]
Copied Directory [/vendor/eveseat/web/src/resources/css] To [/public/web/css]
Copied Directory [/vendor/eveseat/web/src/resources/img] To [/public/web/img]
Copied Directory [/vendor/eveseat/web/src/resources/js] To [/public/web/js]
Copied File [/vendor/twbs/bootstrap/dist/css/bootstrap.min.css] To [/public/web/css/bootstrap.min.css]
Copied File [/vendor/almasaeed2010/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js] To [/public/web/js/bootstrap.bundle.min.js]
Copied File [/vendor/datatables/datatables/media/css/dataTables.bootstrap4.min.css] To [/public/web/css/dataTables.bootstrap4.min.css]
Copied File [/vendor/datatables/datatables/media/js/jquery.dataTables.min.js] To [/public/web/js/jquery.dataTables.min.js]
Copied File [/vendor/datatables/datatables/media/js/dataTables.dataTables.min.js] To [/public/web/js/dataTables.dataTables.min.js]
Copied File [/vendor/datatables/datatables/media/js/dataTables.bootstrap4.min.js] To [/public/web/js/dataTables.bootstrap4.min.js]
Copied File [/vendor/almasaeed2010/adminlte/dist/css/adminlte.min.css] To [/public/web/css/adminlte.min.css]
Copied File [/vendor/almasaeed2010/adminlte/dist/js/adminlte.min.js] To [/public/web/js/adminlte.min.js]
Copied File [/vendor/components/font-awesome/css/all.min.css] To [/public/web/css/all.min.css]
Copied Directory [/vendor/components/font-awesome/webfonts] To [/public/web/webfonts]
Copied File [/vendor/eveseat/web/src/Config/seat-queues.php] To [/config/seat-queues.php]
Copied File [/vendor/fideloper/proxy/config/trustedproxy.php] To [/config/trustedproxy.php]
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Copied File [/vendor/laravel/tinker/config/tinker.php] To [/config/tinker.php]
Copied File [/vendor/maatwebsite/excel/src/Console/stubs/export.model.stub] To [/stubs/export.model.stub]
Copied File [/vendor/maatwebsite/excel/src/Console/stubs/export.plain.stub] To [/stubs/export.plain.stub]
Copied File [/vendor/maatwebsite/excel/src/Console/stubs/export.query.stub] To [/stubs/export.query.stub]
Copied File [/vendor/maatwebsite/excel/src/Console/stubs/export.query-model.stub] To [/stubs/export.query-model.stub]
Copied File [/vendor/maatwebsite/excel/src/Console/stubs/import.collection.stub] To [/stubs/import.collection.stub]
Copied File [/vendor/maatwebsite/excel/src/Console/stubs/import.model.stub] To [/stubs/import.model.stub]
Copied File [/vendor/maatwebsite/excel/config/excel.php] To [/config/excel.php]
Copied Directory [/vendor/yajra/laravel-datatables-html/src/resources/views] To [/resources/views/vendor/datatables]
Copied File [/vendor/yajra/laravel-datatables-html/src/resources/config/config.php] To [/config/datatables-html.php]
Copied File [/vendor/yajra/laravel-datatables-buttons/src/config/config.php] To [/config/datatables-buttons.php]
Copied File [/vendor/yajra/laravel-datatables-buttons/src/resources/assets/buttons.server-side.js] To [/public/vendor/datatables/buttons.server-side.js]
Copied Directory [/vendor/yajra/laravel-datatables-buttons/src/resources/views] To [/resources/views/vendor/datatables]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Mail/resources/views] To [/resources/views/vendor/mail]
Publishing complete.
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'php artisan migrate'
Nothing to migrate.
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'php artisan up'
Application is now live.
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'php artisan cache:clear'
Application cache cleared!
root@ubuntu:/var/www/seat# sudo -H -u www-data bash -c 'php artisan route:cache'
Route cache cleared!

**Comment by warlof** [comment]
provided links are saying

for outdated notifications package, where latest is 4.3.0, which is your case
> **CAUTION**
If you're using a bare-metal installation of SeAT (non Docker), you will have to manually edit your composer.json file located at root SeAT installation directory (default is /var/www/seat/composer.json) and alter the line 19 from "laravel/tinker": "^1.0", to "laravel/tinker": "^2.5", in order to be able to deploy that new version.

for outdated web package, where latest is 4.9.0, which is your case
> **CAUTION**
If you're using a bare-metal installation of SeAT (non Docker), you will have to manually edit your composer.json file located at root SeAT installation directory (default is /var/www/seat/composer.json) and alter the line 19 from "laravel/tinker": "^1.0", to "laravel/tinker": "^2.5", in order to be able to deploy that new version.

just apply, and then update...

**Comment by kevinouw** [comment]
thanks seems that was the issue
