### ISSUE TITLE
Seat\Eveapi\Jobs\Calendar\Event timeout

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#768]
Hi, installed Seat, everything seems work except this one:

Seat\Eveapi\Jobs\Calendar\Events
Illuminate\Queue\MaxAttemptsExceededException: Seat\Eveapi\Jobs\Calendar\Events has been attempted too many times or run too long. The job may have previously timed out. in /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:632

Admin diagnostic ok, cache cleared. 

---
P.S. - is there any way for easy auth page customization? Just need alliance logo on start page.

Thanks

**Comment by warlof** [comment]
regarding customization, everything you need is here https://eveseat.github.io/docs/styling/

**Comment by muzixa** [comment]
> regarding customization, everything you need is here https://eveseat.github.io/docs/styling/

Thank you already done.

Now only Events timeout errors :(

**Comment by warlof** [comment]
it appears to be an ESI temporary outage.
there is nothing we can do here.

**Comment by muzixa** [comment]
This happens when opening character "calendar" tab
![image](https://user-images.githubusercontent.com/2127645/110433427-7a125f80-80c1-11eb-870c-da865adcf22f.png)

It's strage. Im deployed a copy of seat to VPS-server for testing, and there are no event errors like this.

**Comment by warlof** [comment]
Can you follow the docs and provide logs information please? 
https://eveseat.github.io/docs/troubleshooting/

**Comment by muzixa** [comment]
In debug mode have only this:
![image](https://user-images.githubusercontent.com/2127645/110437388-61587880-80c6-11eb-8cc4-5a9502157a6d.png)

Next Illuminate\View\ViewException: Trying to get property 'text' of non-object (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/calendar-detail.blade.php) in /var/www/seat/storage/framework/views/8448cad78e22640a928aceadb019abe63c5e5e8d.php:2
Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/seat/s...', Array)
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/View.php(143): Illuminate\View\Engines\CompilerEngine->get('/var/www/seat/v...', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/seat/vendor/eveseat/web/src/Http/DataTables/Character/Intel/CalendarDataTable.php(48): Illuminate\View\View->render()
#6 /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/Utilities/Helper.php(65): Seat\Web\Http\DataTables\Character\Intel\CalendarDataTable->Seat\Web\Http\DataTables\Character\Intel\{closure}(Object(Seat\Eveapi\Models\Calendar\CharacterCalendarEvent))
#7 /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/Processors/DataProcessor.php(156): Yajra\DataTables\Utilities\Helper::compileContent(Object(Closure), Array, Object(Seat\Eveapi\Models\Calendar\CharacterCalendarEvent))
#8 /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/Processors/DataProcessor.php(107): Yajra\DataTables\Processors\DataProcessor->editColumns(Array, Object(Seat\Eveapi\Models\Calendar\CharacterCalendarEvent))
#9 /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php(791): Yajra\DataTables\Processors\DataProcessor->process(true)
#10 /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(101): Yajra\DataTables\DataTableAbstract->processResults(Object(Illuminate\Database\Eloquent\Collection), true)
#11 /var/www/seat/vendor/eveseat/web/src/Http/DataTables/Character/Intel/CalendarDataTable.php(74): Yajra\DataTables\QueryDataTable->make(true)
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Seat\Web\Http\DataTables\Character\Intel\CalendarDataTable->ajax()
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /var/www/seat/vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php(158): Illuminate\Container\Container->call(Array)
#18 /var/www/seat/vendor/eveseat/web/src/Http/Controllers/Character/CalendarController.php(46): Yajra\DataTables\Services\DataTable->render('web::character....', Array)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Seat\Web\Http\Controllers\Character\CalendarController->index(Object(Seat\Eveapi\Models\Character\CharacterInfo), Object(Seat\Web\Http\DataTables\Character\Intel\CalendarDataTable))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Seat\Web\Http\Controllers\Character\CalendarController), 'index')
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authorize->handle(Object(Illuminate\Http\Request), Object(Closure), 'character.calen...', 'character')
#27 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Web\Http\Middleware\Locale->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\Web\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#49 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /var/www/seat/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 {main}

**Comment by muzixa** [comment]
[2021-03-09T08:03:23.539579+00:00] eseye.ERROR: [http 502, bad gateway] get -> https://esi.evetech.net/v1/characters/********/calendar/?datasource=tranquility&from_event=802326 [t/e: 0.24s/]
