### ISSUE TITLE
auto squad 500 error & no auto  populating 

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#769]
Hi
Auto squad based on filters (corporation based) not populating squad.
When attempting to edit it (filters) and save squad settings i have 500 error.
After reload the squad page only one random corporation member is added to squad.

EDIT:
It's happens when:
1. Create new squad with auto-filter (eg. Corporation)
2. Editing squad with change filter
3. Kicking somebody from auto-squad

It's seems like only one action (adding or kicking) allowed after creating or editing squad.

Can't find any errors log, only apache 500 error 
172.18.0.3 - - [05/Mar/2021:16:21:46 +0000] "POST /squads/13/members/5 HTTP/1.1" 500 2684 "https://my.domen/squads/13" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"

Checking Local and Latest Versions. Please wait...
+--------------------+---------------+----------------+
| Package Name       | Local Version | Latest Version |
+--------------------+---------------+----------------+
| SeAT API                 | 4.5.0         | 4.5.0          |
| SeAT Console          | 4.8.0         | 4.8.0          |
| SeAT Eve API          | 4.10.0        | 4.10.0         |
| SeAT Notifications | 4.3.0         | 4.3.0          |
| SeAT Services         | 4.2.0         | 4.2.0          |
| SeAT Web               | 4.10.0        | 4.10.0         |
+--------------------+---------------+----------------+

**Comment by warlof** [comment]
If there is a 500, then, you have a log
https://eveseat.github.io/docs/troubleshooting/

**Comment by muzixa** [comment]
So, im enabled debug mode.
After editing squad have an error:

(1/1) TypeErrorArgument 1 passed to Seat\Notifications\Notifications\Seat\Mail\SquadMemberRemovedNotification::__construct() must be an instance of Seat\Web\Models\Squads\Squad, instance of Seat\Web\Models\Squads\SquadMember given, called in /var/www/seat/vendor/eveseat/notifications/src/Observers/SquadMemberObserver.php on line 79
--
in SquadMemberRemovedNotification.php line 53
at SquadMemberRemovedNotification->__construct(object(SquadMember))in SquadMemberObserver.php line 79
at SquadMemberObserver->Seat\Notifications\Observers\{closure}(object(stdClass), 0)in EnumeratesValues.php line 176
at Collection->each(object(Closure))in SquadMemberObserver.php line 81
at SquadMemberObserver->dispatch(object(SquadMember), 'squad_member_removed')in SquadMemberObserver.php line 49
at SquadMemberObserver->deleted(object(SquadMember))in Dispatcher.php line 389
at Dispatcher->Illuminate\Events\{closure}('eloquent.deleted: Seat\\Web\\Models\\Squads\\SquadMember', array(object(SquadMember)))in Dispatcher.php line 218
at Dispatcher->dispatch('eloquent.deleted: Seat\\Web\\Models\\Squads\\SquadMember', array(object(SquadMember)))in HasEvents.php line 189
at Model->fireModelEvent('deleted', false)in AsPivot.php line 124
at Pivot->Illuminate\Database\Eloquent\Relations\Concerns\{closure}(1)in helpers.php line 422
at tap(1, object(Closure))in AsPivot.php line 125
at Pivot->delete()in InteractsWithPivotTable.php line 462
at BelongsToMany->detachUsingCustomClass(3)in InteractsWithPivotTable.php line 418
at BelongsToMany->detach(3)in Squad.php line 91
at Squad::Seat\Web\Models\Squads\{closure}(object(User), 0)in EnumeratesValues.php line 176
at Collection->each(object(Closure))in Squad.php line 92
at Squad::Seat\Web\Models\Squads\{closure}(object(Squad))in Dispatcher.php line 369
at Dispatcher->Illuminate\Events\{closure}('eloquent.updated: Seat\\Web\\Models\\Squads\\Squad', array(object(Squad)))in Dispatcher.php line 218
at Dispatcher->dispatch('eloquent.updated: Seat\\Web\\Models\\Squads\\Squad', array(object(Squad)))in HasEvents.php line 189
at Model->fireModelEvent('updated', false)in Model.php line 750
at Model->performUpdate(object(Builder))in Model.php line 661
at Model->save()in SquadsController.php line 147
at SquadsController->update(object(Squad), object(Squad))in Controller.php line 54
at Controller->callAction('update', array(object(Squad), 'squad' => object(Squad)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(SquadsController), 'update')in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 681
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authorize.php line 45
at Authorize->handle(object(Request), object(Closure), 'squads.edit', 'squad')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Locale.php line 44
at Locale->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authenticate.php line 67
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 78
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 67
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in Router.php line 613
at Router->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in index.php line 54

**Comment by warlof** [comment]
thanks for the report, it's been fixed in new version
