### ISSUE TITLE
[Bug] Auto squad doesn't auto-add public scope users

### ISSUE THREAD

**Issue by Nfinished** [eveseat/seat#770]
I've got an auto squad that I use to assign basic roles such as connector access. The only filter is that a user is _not_ a certain character, so I'd expect everyone should be added to the squad on signing in.

Users can sign in with one of two scopes. One scope is *everything*, and the other is public data and killmails. All users who log in with the *everything* scope are correctly added to the auto squad. Users who log in with the public scope are never added to the squad. This happens 100% of the time.

All packages latest.

**Comment by muzixa** [comment]
EDIT:
Now no errors on squad edit, but characters adding only after squad filter editing

**Comment by warlof** [comment]
Squads rules are processed only on rules update, if squads is altered. Otherwise, it's done dynamically based on applied filter and the data source to which it's attached.

**Comment by muzixa** [comment]
Sorry, my english not so good.
Maybe i do not understand it but i have auto squad +corporation based filter.
When i change some filters it's works and immediately and adding all characters who is in corporation.
Then i register new character (in same corp) but he is not adding to this squad automatically, if im editing squad filters again he is adding fine after submit changes.

**Comment by warlof** [comment]
the thing you're talking about is covered by https://github.com/eveseat/web/pull/559 which has not been released yet.

**Comment by muzixa** [comment]
> the thing you're talking about is covered by [eveseat/web#559](https://github.com/eveseat/web/pull/559) which has not been released yet.

Ok, thank you very much

**Comment by muzixa** [comment]
Checked one more time.
And im think this is not only public scope issue. What i done:

1.Authed  1st character with public scope+killmails -> character not added to squad, 
   Authed same character with full scope (without deletinon user) -> character added to squad.
2. Authed 2nd character with full-scope -> character not added to squad,
    Authed 2nd character with public+killmails (without deletinon user) -> character added to squad.

It seems auto-squads works for me after some change done with squad filter or character.

**Comment by muzixa** [comment]
Seems there are just some delay for auto-squads, all characters was added automatically in 1 hour.
So, all works
