### ISSUE TITLE
Structure Names

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#772]
A lot of structure names return "Unknow"
Authorized few characters (every character with ingame directors roles or ceo), for some of them i can see structure names, for some only system name  and structure name as "Unknown"

**Comment by warlof** [comment]
Are you talking about assets location?

**Comment by muzixa** [comment]
> Are you talking about assets location?

No, about structure tab on corporation page

**Comment by muzixa** [comment]
After today update structure names works fine
