### ISSUE TITLE
Token Status sorting 

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#779]
Sorting characters by token status seems incorrect:

![image](https://user-images.githubusercontent.com/2127645/110256014-a2a63680-7fa7-11eb-92c9-2f86fca34c56.png)

**Comment by PhtevenHackett** [comment]
In the picture, you are sorted by Security Status. Token Status doesn't have a sort option.

**Comment by muzixa** [comment]
So the token status sorting actually by security status? 
Black arrow misled me, ok thanks

**Comment by warlof** [comment]
Sorting indicator is always on the right.
