### ISSUE TITLE
500 error in character sheet

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#780]
Hi
Today have 500 errors on character sheets and my own sheet too (but not all chars)

![image](https://user-images.githubusercontent.com/2127645/110515242-3cd9bc00-8119-11eb-8818-e9ab5b0140ce.png)

(2/2) ViewExceptionTrying to get property 'typeName' of non-object (View: /var/www/seat/vendor/eveseat/web/src/resources/views/character/sheet.blade.php)
--
in e32ee9b2216d33fd78cabe5d170538a4a3517751.php line 33
at CompilerEngine->handleViewException(object(ErrorException), 0)in PhpEngine.php line 45
at PhpEngine->evaluatePath('/var/www/seat/storage/framework/views/e32ee9b2216d33fd78cabe5d170538a4a3517751.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'character' => object(CharacterInfo)))in CompilerEngine.php line 59
at CompilerEngine->get('/var/www/seat/vendor/eveseat/web/src/resources/views/character/sheet.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'character' => object(CharacterInfo)))in View.php line 143
at View->getContents()in View.php line 126
at View->renderContents()in View.php line 91
at View->render()in Response.php line 42
at Response->setContent(object(View))in Response.php line 205
at Response->__construct(object(View), 200, array('Content-Type' => 'text/html'))in Router.php line 749
at Router::toResponse(object(Request), object(View))in Router.php line 721
at Router->prepareResponse(object(Request), object(View))in Router.php line 681
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authorize.php line 45
at Authorize->handle(object(Request), object(Closure), 'character.sheet', 'character')in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Locale.php line 44
at Locale->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Authenticate.php line 67
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 78
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 67
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in Router.php line 613
at Router->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in index.php line 54

**Comment by warlof** [comment]
this should have been fixed by newly released sde (20210310)
