### ISSUE TITLE
API Key Status not updating

### ISSUE THREAD

**Issue by Quackers7011** [eveseat/seat#79]
The "API Key Status" field on the "API Key Detail " page shows Enabled even though the API key in question has been expired in the account manager

**Comment by leonjza** [comment]
This may have been fixed in a seemingly unrelated commit [here](https://github.com/eveseat/eveapi/commit/85b21b0cb7b2c4ac1a92956ef41cac5ad81b9759).

**Comment by leonjza** [comment]
Upgrade to the latest versions of the `eveseat/*` packages and monitor it. If it still occurs feel free to open another issue.
