### ISSUE TITLE
esi:update:affiliations does not run without an argument

### ISSUE THREAD

**Issue by yarmout** [eveseat/seat#790]
* **Problem**:  esi:update:affiliations only successfully runs if a character id is given as an argument
* **Expected**:  esi:update:affiliations should update all characters on the instance when no argument is given
* **Logs / Screenshots / Proof**: 
`#8 {main}
"}
[2021-03-17 04:00:49] local.ERROR: Not enough arguments (missing: "character_id"). {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Not enough arguments (missing: \"character_id\"). at /var/www/seat/vendor/symfony/console/Input/Input.php:76)
[stacktrace]`
* **Version Info**: 
Running on Debian 10
![image](https://user-images.githubusercontent.com/58712447/111740295-dfe9ae80-885a-11eb-8179-ad783bf73b92.png)

**Comment by warlof** [comment]
Hi,

Can you also provide the stack trace here?
It lacks of context 😛

**Comment by piotrekdomin** [comment]
I have similar problem:
`[2021-04-21 23:01:03] local.ERROR: Not enough arguments (missing: "character_id"). {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Not enough arguments (missing: \"character_id\"). at /srv/seat/vendor/symfony/console/Input/Input.php:76)
[stacktrace]
#0 /srv/seat/vendor/symfony/console/Command/Command.php(250): Symfony\\Component\\Console\\Input\\Input->validate()
#1 /srv/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#2 /srv/seat/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /srv/seat/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Seat\\Eveapi\\Commands\\Esi\\Update\\Characters), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /srv/seat/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /srv/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 /srv/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /srv/seat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"}`

**Comment by warlof** [comment]
Can you guys show your schedulers?
The error seems truncated, but I don't think it's tied to affiliation.

**Comment by piotrekdomin** [comment]
You mean this?
![obraz](https://user-images.githubusercontent.com/41890080/115759330-6cc6e100-a3a0-11eb-8f74-ebe1bb15addc.png)

**Comment by warlof** [comment]
Yes, please use `php artisan db:seed --class=Seat\\Console\\database\\seeds\\ScheduleSeeder` to update your scheduler - it is completely outdated.

**Comment by piotrekdomin** [comment]
Now it works, thanks a lot! ;)

**Comment by Crypta-Eve** [comment]
Closing this as it appears resolved. Please reopen if the issue recurs.
