### ISSUE TITLE
default users sorting is Z -> A

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#798]
As title said
default users sorting is always Z -> A
![image](https://user-images.githubusercontent.com/2127645/113699250-f9ee1280-96dd-11eb-95d5-f80372e38de1.png)

**Comment by himanshu007-creator** [comment]
so you want to be a ->z?

**Comment by veteranmina** [comment]
Sorting order correct with change https://github.com/eveseat/web/pull/576
