### ISSUE TITLE
Duplicate mail error

### ISSUE THREAD

**Issue by freedenizen** [eveseat/seat#8]
Job error when adding mail:
```
Last Updater: Processing: MailBodies

Exception: Illuminate\Database\QueryException
Error Code: 23000
Error Message: SQLSTATE[23000]: Integrity constraint violation: Duplicate entry '344688271' for key 'PRIMARY' (SQL: insert into `character_mail_message_bodies` (`messageID`, `body`, `updated_at`, `created_at`) values (344688271, REDACTED, 2015-12-15 05:31:39, 2015-12-15 05:31:39))
File: /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php - Line: 653
```

**Comment by warlof** [comment]
Did you run manually an update of this api key or all Keys ?

**Comment by leonjza** [comment]
Sample scenario where this can happen is when 2 chars with the same mail happen to be having their mail updated at very close to the same time. One will win the body insert, the other will fail.

**Comment by warlof** [comment]
should update the PK to charID and MessageID so ?

**Comment by leonjza** [comment]
Update to `eveseat/eveapi` v1.0.7 should hopefully fix it.
