### ISSUE TITLE
Server Could not use ESI

### ISSUE THREAD

**Issue by ArielHeleneto** [eveseat/seat#804]
* **Problem**: Server Could not use ESI by web, but checks in console are correct
* **Expected**: Everything work well.
* **Logs / Screenshots / Proof**:  
* Checks: https://paste.ubuntu.com/p/9m86pkNC5W/ 
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._ 
![图片](https://user-images.githubusercontent.com/32459390/115824621-ced42480-a43a-11eb-82bb-c440452e0bc9.png)

**Comment by warlof** [comment]
Hi,

Running diagnose as root is almost useless.
Can you check the header warning and try again with proper user? 

What do you mean by "server could not use esi"?

**Comment by ArielHeleneto** [comment]
restart the server fix this **fucking** Bug
