### ISSUE TITLE
Visual error with Jet Skin, on Skill coverage graph.

### ISSUE THREAD

**Issue by mike0891** [eveseat/seat#805]
* **Problem**: Skills Coverage (in percent), has a white background behind the key. This seems exclusive to the Jet skin.
* **Expected**: There not to be a white background behind the key when using the Jet Skin.
* **Logs / Screenshots / Proof**: ![image](https://user-images.githubusercontent.com/31676627/115834520-3a070200-a40d-11eb-903e-4fe423b119ed.png) This is on the latest Chrome, it is reproducible on other browsers. There does not seem to be any other discrepanciesies with the skin.
* **Version Info**:
| Vendor    | Package Name           | Installed Version        |
| --------- | ---------------------- | ------------------------ |
| eveseat   | api                    | 4.5.0                    |
| eveseat   | console                | 4.8.0                    |
| eveseat   | eveapi                 | 4.11.0                   |
| eveseat   | notifications          | 4.3.1                    |
| eveseat   | services               | 4.2.0                    |
| eveseat   | web                    | 4.12.1                   |
| cryptaeve | seat-squad-sync        | 4.0.2                    |
| denngarr  | seat-fitting           | 4.0.4                    |
| denngarr  | seat-srp               | 4.1.0                    |
| kassie    | calendar               | 4.0.3                    |
| warlof    | seat-connector         | 2.3.0                    |
| warlof    | seat-discord-connector | 5.0.0                    |
| ccp       | eve_online_sde         | sde-20210310-TRANQUILITY |

**Comment by veteranmina** [comment]
Changes made to drop background color for ticks https://github.com/eveseat/web/pull/575

**Comment by mike0891** [comment]
This is fixed as of V4.14.
