### ISSUE TITLE
seat-app does not exist

### ISSUE THREAD

**Issue by SimplyCorbett** [eveseat/seat#818]
I'm installing seat with a docker installation and I'm getting this error when I try to create an admin password:

root@icarus:/opt/seat-docker# docker-compose exec seat-app php artisan seat:admin:login
ERROR: No such service: seat-app

The rest of the platform works. How would I assign myself as an admin in this situation?

**Comment by Crypta-Eve** [comment]
In SeAT 4, the seat-app container was replaced. Try replacing seat-app with seat-web.

**Comment by SimplyCorbett** [comment]
That did the trick!
