### ISSUE TITLE
Add Starbase and Structure API endpoints for Corporations

### ISSUE THREAD

**Issue by Evolution0** [eveseat/seat#822]
Currently if one wants to pull structure and starbase information up for a corporation you have to use the EVE API, this requires that you be *in* the corp in question, which is no bueno when you run an alliance and are trying to pull multiple corps information. The other way I believe is to (like SeAT) request the correct scopes somehow from each corp?

This is quite a bit of unneeded finagling when the information is already present in SeAT, just inaccessible through the API.

My request is the endpoints be added that mirror the format of the EVE API.

If this is the wrong place for this, or I'm missing some obvious existing endpoint please let me know.

**Comment by tehraven** [comment]
@Evolution0 this should be pretty straight forward.
