### ISSUE TITLE
[Feature Request] Ability to delete characters

### ISSUE THREAD

**Issue by paintballlaws** [eveseat/seat#824]
I would like the ability to completely remove characters (as an admin) that have been biomassed. As there is no way for a person to unlink a character that has been biomassed and it shows up as an invalid token instead of just a keepsake for knowledge. Currently the only way is to completely delete the entire user and have them add all active toons back.

**Comment by veteranmina** [comment]
This is already available through Characters -> All Characters no?

**Comment by paintballlaws** [comment]
I didn't even realize this got added thank you, I don't ever use that screen since there is like a billon people in my seat.
