### ISSUE TITLE
User deleted "Superuser" role and admin:reset did not get us back in

### ISSUE THREAD

**Issue by phneak** [eveseat/seat#83]
* **Problem**: No users had access (including admin) to see api keys or make changes
* **Expected**: Happened after user was modifying roles
* **Logs / Screenshots / Proof**: Research showed user deleted "superuser" role that had power users and admin associated.  "permission_role" in the database was empty
* **Version Info**: SEAT was on current version

User deleted "Superuser" role and admin:reset did not get us back in.  I recreated the "permission_role" table / data and it resolved the issue, but I think that admin:reset should have fixed this OR user should not have been able to delete the superuser ability from admin

**Comment by vivace-io** [comment]
Adding on, removing Superuser role from ANY account causes this.

**Comment by leonjza** [comment]
`seat:admin:reset` should hopefully be able to recover the `admin` account and its permissions now correctly. Fix will be in the next `eveseat/console` package release.
