### ISSUE TITLE
Eve SSO update changed quth from JSON to form-data

### ISSUE THREAD

**Issue by Nocturrne** [eveseat/seat#830]
Eve SSO was broken in an update today.  

[https://forums.eveonline.com/t/eve-sso-pathfinder-issues/326696/2]

The auth has to be submitted as form-data instead of JSON.

**Comment by warlof** [comment]
Isn't that already the case ?
SeAT is JWT compliant and relay on Socialite which used to be a solid reference.

**Comment by Nocturrne** [comment]
It was just coincidence that the EVE dev portal is down and someone mentioned a problem with Seat authentication at the same time.  Seat compliance is confirmed.
