### ISSUE TITLE
Grant type refresh_token is not supported.

### ISSUE THREAD

**Issue by TimeSpeeding** [eveseat/seat#837]
Hello,

Thanks for your working. This is an excellent system.
When I was using the seat,  I found there are a lot of failed jobs, most in characters queue. And the exception is
`Seat\Eseye\Exceptions\RequestFailedException: invalid_grant: Grant type refresh_token is not supported. in /var/www/seat/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:208`

Please help me with fixing this problem.

Best Regards,
Zhu Yibin

**Comment by veteranmina** [comment]
Can you provide SeAT versions please?

**Comment by TimeSpeeding** [comment]
> Can you provide SeAT versions please?

All are the latest version.
![image](https://user-images.githubusercontent.com/47582010/140457278-dfa77efa-23f9-48b8-b755-4d8803eaa714.png)

**Comment by veteranmina** [comment]
Is your client ID/secret set or has it been changed recently?

**Comment by TimeSpeeding** [comment]
> Is your client ID/secret set or has it been changed recently?

I just set them yesterday since the developer register of EVE broken down before.

**Comment by warlof** [comment]
Ensure callback, client ID, client secret and app scopes are properly set. Seems Sso may return this error message for various unrelated issues.

**Comment by TimeSpeeding** [comment]
> Ensure callback, client ID, client secret and app scopes are properly set. Seems Sso may return this error message for various unrelated issues.

Hi, I just checked the ID, callback, secret and the scopes are right.
Is this a problem that my seat was using an IP address with http, but not https?
The jobs still cannot passed. And this will disappear in the character tab.
![image](https://user-images.githubusercontent.com/47582010/140472595-050ee6bc-d26f-4828-9aad-4473e585b0c7.png)

**Comment by warlof** [comment]
Does callback setup in `.env` roughly match with the one into eve dev app? (including scheme, server and path?)

As of remind
- http://example.com is not https://example.com
- http://0.0.0.0 is not the same as http://example.com

**Comment by TimeSpeeding** [comment]
> Does callback setup in `.env` roughly match with the one into eve dev app? (including scheme, server and path?)
> 
> As of remind
> 
> * http://example.com is not https://example.com
> * http://0.0.0.0 is not the same as http://example.com

The callback in `.env` is same as the eve dev app, both `http://*.*.*.*/auth/eve/callback`

And it is not all jobs failed. Only several jobs (like contracts, roles, recent killmails) in character queue failed.

**Comment by TimeSpeeding** [comment]
I am trying to changing the url to a https domain. And I am sure that I changed settings correct. But the problem above did not fixed.
I can get the data like the skill summary and employment history. But when I trying to query the contracts, the job failed.
More details from Horizon here:
![image](https://user-images.githubusercontent.com/47582010/140870500-09087d5f-19d2-4901-9818-add82f35e0a3.png)
![image](https://user-images.githubusercontent.com/47582010/140870584-996cc70c-c005-420e-bca5-b78392269928.png)
![image](https://user-images.githubusercontent.com/47582010/140870618-27b9bb3a-0293-4a21-99bc-9c133985ba51.png)
![image](https://user-images.githubusercontent.com/47582010/140870659-023b1eee-d5d4-442e-acd3-db39c132d3b2.png)
![image](https://user-images.githubusercontent.com/47582010/140870675-3a6ddb53-816b-493d-8de5-310658d132e5.png)
![image](https://user-images.githubusercontent.com/47582010/140870709-6dbc2cb0-4cff-4fc6-abfe-45d662c47dd4.png)
![image](https://user-images.githubusercontent.com/47582010/140870752-5ced44c6-4d1b-4aa2-8881-e4c47dd51de5.png)

Is anyone can help me with this problem or help me to identify where the problem is?

**Comment by warlof** [comment]
Is there anything else than contract?

**Comment by TimeSpeeding** [comment]
> Is there anything else than contract?

Roles, Recent(killmails), Notifications in character queue.

**Comment by warlof** [comment]
Was it v1 to v2 converted tokens? (SeAT prior to v4 was using v1, if you migrate to v4, they've been upgraded to v2)

**Comment by TimeSpeeding** [comment]
> Was it v1 to v2 converted tokens? (SeAT prior to v4 was using v1, if you migrate to v4, they've been upgraded to v2)

Might be. But I just built the SeAT follow the SeAT Documentation > Manual Installation. Where can I find how to upgrade tokens to v2?

**Comment by warlof** [comment]
No need with that error, I just try to find the origin of your issue with no idea since it appears you're the only one experimenting this. How is SeAT installed? Are you using any non standard thing (including ESI endpoints)?

**Comment by warlof** [comment]
Can you try those ?
- clear overall cache using `php artisan seat:cache:clear` and `php artisan cache:clear`
- renew cached config with `php artisan config:cache`
- renew cached routes with `php artisan route:cache`

**Comment by bpvital** [comment]
Just Fyi I had exactly same problem:

-installed latest SeAT (manual instalation)
-Lots of failed jobs due to expired character tokens

the problem in my case was incorrect APP_URL in .env
