### ISSUE TITLE
status on php8.0/php8.1 compatibility?

### ISSUE THREAD

**Issue by jamiew0w** [eveseat/seat#839]
my apologies, i'm unable to join slack. i had a look around issues etc for any indication on php8.0 - could anyone shed some light on it please?

thanks!

**Comment by Crypta-Eve** [comment]
Hi,

As far as I am aware little to no effort has yet been placed on the move to higher versions of php beyond 7.4. This will change in the next major version with a move to Laravel 9 when available.

Also we are now on discord instead of the slack.

Cheers!
