### ISSUE TITLE
php artisan vendor:publish --force

### ISSUE THREAD

**Issue by CokkocZateki** [eveseat/seat#84]
Hi

Im trying to install SeAT  and going according to the guide i get as far as

php artisan vendor:publish --force

i get this info. any idea 
```
php artisan vendor:publish --force
Could not open input file: artisan

**Comment by dysath** [comment]
My guess is either you don't have the php-snmp module installed or you don't have net-snmp installed.  As I've never seen that error, it's a guess.  Which distro are you using?

**Comment by leonjza** [comment]
I honestly have no idea why you are getting SNMP related output for SeAT. SeAT has _nothing_ to do with SNMP whatsoever.  
Did you copy the correct error logs/output? Can you give more information about your environment?

**Comment by warlof** [comment]
That's more looking a custom path setup.
What's your server setup ?!

**Comment by theviking69** [comment]
im running Ubuntu 14.04 if that helps?

**Comment by CokkocZateki** [comment]
Ummm. im running Ubuntu 14.04?

**Comment by CokkocZateki** [comment]
@leonjza its really weird because i follow the steps to the T and i get no file found.

**Comment by CokkocZateki** [comment]
sorry updated my issue. that was irrelevant info.

**Comment by warlof** [comment]
You should run this command inside you seat setup path (where there is the .env file)

**Comment by leonjza** [comment]
Alright with the updated issue, you need to be in the same directory as `artisan` to run it. i.e. `/var/www/seat` if that is where you installed it.

**Comment by CokkocZateki** [comment]
facepalm.thats for that :)
