### ISSUE TITLE
Update from v3 to v4 member summary page not updating

### ISSUE THREAD

**Issue by atertoc** [eveseat/seat#841]
This is manual install that did appear to update successfully, though I was rather behind on migrations it seems. I have reviewed the cron tasks with other installs and there does not appear to be any ting missing.

I'm running the old warloff discord connector now know as seat-connector and that too seems to be working fine.

The main issue is that the the yellow exclamation seems to highlight that the token is not updating within 24 hours. Though it does go green when I log out and back in again, though the member summary page continues to indicate no training but there is when I look in game. This appears to be consistent across all users.

Diagnosis seems OK..

`
 * Getting environment information
Current User: www-docker
PHP Version: 7.3.12
Host OS: Linux 56d447f7ee93 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
SeAT Basepath: /var/www/html/eveseat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/html/eveseat/storage is writable
/var/www/html/eveseat/storage/logs is writable
/var/www/html/eveseat/storage/eseye is writable
/var/www/html/eveseat/storage/sde is writable
/var/www/html/eveseat/storage/logs/laravel-2021-11-28.log is writable

 * Checking Database
+------------+---------------+
| Setting    | Value         |
+------------+---------------+
| Connection | mysql         |
| Host       | mariadb.local |
| Database   | [DB]    |
| Username   | [USER]   |
| Password   | ***********   |
+------------+---------------+
Connection OK to database: [DB]

 * Checking Redis
+----------+-------------+
| Setting  | Value       |
+----------+-------------+
| Host     | redis.local |
| Port     | 6379        |
| Database | 0           |
+----------+-------------+
Connected to Redis
Set random key of: vKMVzwXXzPQlaZDwXzQTTlgXbkFWVoIwK64lEI2G1SOIGcb0xZD7Upvz6Xlh2gxc
Set key to expire in 10 sec
Read key OK

 * Checking ESI Access
Server Online Since: 2021-11-28T11:01:49Z
Online Players: 28529
ESI appears to be OK

Checking Local and Latest Versions. Please wait...
+--------------------+---------------+----------------+
| Package Name       | Local Version | Latest Version |
+--------------------+---------------+----------------+
| SeAT API           | 4.7.0         | 4.7.0          |
| SeAT Console       | 4.8.0         | 4.8.0          |
| SeAT Eve API       | 4.14.0        | 4.14.0         |
| SeAT Notifications | 4.3.1         | 4.3.1          |
| SeAT Services      | 4.2.0         | 4.2.0          |
| SeAT Web           | 4.15.0        | 4.15.0         |
+--------------------+---------------+----------------+
SeAT Diagnostics complete
`

I do see a few errors in the log as follow...

`2021-11-28 00:00:01] local.ERROR: There are no commands defined in the "seat-groups:users" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"seat-groups:users\" na$
[stacktrace]
#0 /var/www/html/eveseat/vendor/symfony/console/Application.php(657): Symfony\\Component\\Console\\Application->findNamespace('seat-groups:use...')
#1 /var/www/html/eveseat/vendor/symfony/console/Application.php(237): Symfony\\Component\\Console\\Application->find('seat-groups:use...')
#2 /var/www/html/eveseat/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /var/www/html/eveseat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 {main}
"}
[2021-11-28 00:00:04] local.ERROR: [seat-connector][discord] Client error: `DELETE https://discord.com/api/guilds/210370667353210880/members/210401320203583489/roles/210401928855814144` resulted in a `403 Forbidden` response:
{"message": "Missing Permissions", "code": 50013}

[2021-11-28 00:00:06] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'corporation_id' in where clause is ambiguous (SQL: delete `corporation_infos` from `corporation_infos` inner join `alliance_members` on `alliance_members`.`corporation_$
[stacktrace]
#0 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('delete `corpora...', Array, Object(Closure))
#1 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(495): Illuminate\\Database\\Connection->run('delete `corpora...', Array, Object(Closure))
#2 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(440): Illuminate\\Database\\Connection->affectingStatement('delete `corpora...', Array)
#3 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2823): Illuminate\\Database\\Connection->delete('delete `corpora...', Array)
#4 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(874): Illuminate\\Database\\Query\\Builder->delete()
#5 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->delete()
#6 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(385): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'delete', Array)
#7 /var/www/html/eveseat/vendor/eveseat/eveapi/src/Jobs/Maintenance.php(114): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('delete', Array)
#8 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(62): Seat\\Eveapi\\Jobs\\Maintenance->Seat\\Eveapi\\Jobs\\{closure}(Object(Seat\\Eveapi\\Models\\Alliances\\Alliance), 0)
#9 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Concerns\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 1)
#10 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(66): Illuminate\\Database\\Eloquent\\Builder->chunk(1000, Object(Closure))
#11 /var/www/html/eveseat/vendor/eveseat/eveapi/src/Jobs/Maintenance.php(115): Illuminate\\Database\\Eloquent\\Builder->each(Object(Closure))
#12 /var/www/html/eveseat/vendor/eveseat/eveapi/src/Jobs/Maintenance.php(78): Seat\\Eveapi\\Jobs\\Maintenance->cleanup_corps()
#13 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Seat\\Eveapi\\Jobs\\Maintenance->handle()
#14 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#19 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Seat\\Eveapi\\Jobs\\Maintenance))
#20 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Maintenance))
#21 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Seat\\Eveapi\\Jobs\\Maintenance), false)
#23 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Seat\\Eveapi\\Jobs\\Maintenance))
#24 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Maintenance))
#25 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#26 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Seat\\Eveapi\\Jobs\\Maintenance))
#27 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#28 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\\Queue\\Jobs\\Job->fire()
#29 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#30 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#31 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#32 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#33 /var/www/html/eveseat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()
#34 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#35 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#36 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#37 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#38 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#39 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#40 /var/www/html/eveseat/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#41 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#42 /var/www/html/eveseat/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /var/www/html/eveseat/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\$
#44 /var/www/html/eveseat/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /var/www/html/eveseat/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 {main}

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'corporation_id' in where clause is ambiguous at /var/www/html/eveseat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO$
[stacktrace]
#0 /var/www/html/eveseat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(87): Doctrine\\DBAL\\Driver\\PDO\\Exception::new(Object(PDOException))
#1 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(484): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('delete `corpora...')
#2 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('delete `corpora...', Array)
#3 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('delete `corpora...', Array, Object(Closure))
#4 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(495): Illuminate\\Database\\Connection->run('delete `corpora...', Array, Object(Closure))
#5 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(440): Illuminate\\Database\\Connection->affectingStatement('delete `corpora...', Array)
#6 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2823): Illuminate\\Database\\Connection->delete('delete `corpora...', Array)
#7 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(874): Illuminate\\Database\\Query\\Builder->delete()
#8 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->delete()

`
Is there anything else I need to do/check? I'm confused as to why its working partially not updating this summary page.

Many thanks

**Comment by warlof** [comment]
As per your issue, did you check your job dashboard yet ?
Is there a green mark or a red cross on it ?
How many queues are listed ?
Did you update supervisor config and restart it afterwhile to reflect changes from SeAT 4 ?

Regarding erros in your logs

```
2021-11-28 00:00:01] local.ERROR: There are no commands defined in the "seat-groups:users"
```

SeAT Groups is not compatible with SeAT 4 - there is a built-in core alternative called squads : https://eveseat.github.io/docs/admin_guides/squads/
This error is coming because you probably still have the related entry in your scheduler - drop it

```
[2021-11-28 00:00:06] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'corporation_id'
```

Seems to be tied to maintenance job and is an unknown issue

**Comment by atertoc** [comment]
Hi, yes, the dashboard appears god with a green tick. 2 workers 10,283 success in the last hour with no failures. Though if I click on the failures button in the Horizon interface, it does list failures...


```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'corporation_id' in where clause is ambiguous in /var/www/html/eveseat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
--
Stack trace:
#0 /var/www/html/eveseat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(82): PDO->prepare('delete `corpora...', Array)
#1 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(484): Doctrine\DBAL\Driver\PDOConnection->prepare('delete `corpora...')
#2 /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}('delete `corpora...', Array)
```
Along with some timeouts on random tasks...

`
GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: esi.evetech.net (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/eveseat/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
--
`


12 processes listed...

QUEUE_WORKERS=10 in the .ini file.

Queue | Processes | Jobs | Wait
-- | -- | -- | --
default | 3 | 0 | A Few Seconds
high | 3 | 0 | A Few Seconds
low | 3 | 0 | A Few Seconds
medium | 3 | 0 | A Few Seconds

just 1 row below that. 

Supervisor | Processes | Queues | Balancing
seat-workers | 12 | high, medium, low, default | (Auto)

I have removed the call to seat-groups:update. Not sure I need the new seat squads as the connector settings appear fine for my purposes.

**Comment by warlof** [comment]
Well, renew your image then, those queues are V3 queues. Most jobs are push on queues you don't have (ie: character, corporations, notification, etc)

Also regarding your curl issue, it's tied to outdated SSL library.
