### ISSUE TITLE
Log errors... Ambiguous column delete 

### ISSUE THREAD

**Issue by atertoc** [eveseat/seat#843]
Error in horizon logs...

+--------------------+---------------+----------------+
| Package Name | Local Version | Latest Version |
+--------------------+---------------+----------------+
| SeAT API | 4.7.0 | 4.7.0 |
| SeAT Console | 4.8.0 | 4.8.0 |
| SeAT Eve API | 4.14.0 | 4.14.0 |
| SeAT Notifications | 4.3.1 | 4.3.1 |
| SeAT Services | 4.2.0 | 4.2.0 |
| SeAT Web | 4.15.0 | 4.15.0 |
+--------------------+---------------+----------------+

**Schedules in case something is running that should not or is missing**

3	seat:admin:maintenance	0 0 * * *
4	queue:restart	0 1 * * *
7	eve:update:sde	0 0 1 * *
8	esi:update:public	5 15 * * *
17	horizon:snapshot	*/5 * * * *
18	seat-connector:apply:policies	*/10 * * * *
19	seat-connector:sync:sets	0 0 * * *
20	esi:update:status	* * * * *
21	eve:update:status	* * * * *
22	seat:buckets:update	*/2 * * * *
23	esi:update:affiliations	38 */2 * * *
24	esi:update:notifications	*/20 * * * *
25	esi:update:killmails	*/15 * * * *
26	esi:update:contracts	*/15 * * * *
27	esi:update:prices	8 9 * * *
28	esi:update:alliances	25 0 * * *
29	esi:update:insurances	5 0 * * *
30	esi:update:sovereignty	23 19 * * *
31	esi:update:stations	57 19 * * *

....

Seat\Eveapi\Jobs\Maintenance

...

`Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'corporation_id' in where clause is ambiguous (SQL: 

delete `corporation_infos` from `corporation_infos` inner join `alliance_members` on `alliance_members`.`corporation_id` = `corporation_infos`.`corporation_id` where `alliance_members`.`alliance_id` = 99000006 and `corporation_id` not between 1000000 and 1999999

) in /var/www/html/eveseat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669`

**Comment by tehraven** [comment]
https://github.com/eveseat/eveapi/blob/d1545a40a6eddab74812f6e2a541e17af1975b15/src/Jobs/Maintenance.php#L114
