### ISSUE TITLE
Server Error 500 when opening character skills page

### ISSUE THREAD

**Issue by MrElliwood** [eveseat/seat#844]
* **Problem**: Server Error 500 when opening skills page for a character where the new mining crystals are trained
* **Expected**: The skills page should open correctly
* **Logs / Screenshots / Proof / Version Info**: I'm just a user, not the hoster, so I can't provide logs or version information. 

We've been able to recreate the problem with 2 different main logins. Characters who have trained the new mining skills can't open the character skills page. Characters who did not start to train the new skills can still access the page.

**Comment by Crypta-Eve** [comment]
You should update your sde.
