### ISSUE TITLE
Sorting by Token Status doesn't work

### ISSUE THREAD

**Issue by kuch3n** [eveseat/seat#848]
* **Problem**: _Whats wrong?_
Sorting by Token Status does something but Status is still mixed
* **Expected**: _What did you expect to happen?_
All non valid tokens should appear in a row
* **Logs / Screenshots / Proof**: _The more information you give the better!_
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
 SDE Version sde-20211207-TRANQUILITY | Docker Version 4.2.0

**Comment by warlof** [comment]
Hi,

There are no views where you can sort by token with core on last stable.
Neither you can search on it by the way.

**Comment by mike0891** [comment]
> 

/corporations/*Corp_ID*/tracking can be filtered by Token Status and is very buggy. It is the Green and red Valid / Invalid Token button that filter.

**Comment by warlof** [comment]
indead, you can use actions to limit displayed entries on corporationt racking.
However, that wazs not the related screen of this issue.

> can be filtered by Token Status and is very buggy

I don't know what does it mean, sorry ;)
