### ISSUE TITLE
Cannot create project using Laravel 5.1

### ISSUE THREAD

**Issue by donkeysharp** [eveseat/seat#85]
When trying to create a new Laravel 5.1 project with
`$ composer create-project laravel/laravel blog "5.1.*"`
I have the next error
```
> php -r "copy('.env.example', '.env');"
> php artisan clear-compiled
PHP Warning:  require(/home/donkeysharp/code/foo/vvvv/bootstrap/../vendor/autoload.php): failed to open stream: No such file or direct
ory in /home/donkeysharp/code/foo/vvvv/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/donkeysharp/code/foo/vvvv/bootstrap/../vendor/autoload.php' (include_path=
'.:/usr/share/php:/usr/share/pear') in /home/donkeysharp/code/foo/vvvv/bootstrap/autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error
```
I saw that there is no problem with Laravel 5.2 so I think the problem is on 5.1
As 5.1 is a LTS version and not being able to create a project seems to be bad publicity for the project

**Comment by freedenizen** [comment]
I think you wanted to look for support for https://github.com/laravel/laravel this is an application that uses laravel.

**Comment by donkeysharp** [comment]
Sorry I really confused urls
