### ISSUE TITLE
Discord connector not updating

### ISSUE THREAD

**Issue by vlvavan** [eveseat/seat#858]
good afternoon everyone! and thanks for your work!
SDE Version sde-20211207-TRANQUILITY | Docker Version 4.2.4

![image](https://user-images.githubusercontent.com/71975702/151799059-13edecfd-9df2-47bb-8ad0-08d5bcdaa100.png)
but the following is visible in the logs
![image](https://user-images.githubusercontent.com/71975702/151799107-27af5779-67d9-459e-9bb9-9197e747ccdf.png)

What could be the reason?

**Comment by zmsMarc** [comment]
Same issue here

**Comment by veteranmina** [comment]
Please open an issue over here please :-)
https://github.com/warlof/seat-discord-connector

**Comment by vlvavan** [comment]
> Please open an issue over here please :-) https://github.com/warlof/seat-discord-connector

in that section, you can only create pull requests, but this is still not a wish

**Comment by grimreap124** [comment]
I'm also getting the same issue. I think it has also broken the discord server signup. It returns a 500 error but I can't find anything in the error logs.

**Comment by warlof** [comment]
Hey all, that's not a place for that issue - seat-connector is a third party package.

The currently installed displayed version will be fixed in 5.1.1 release - this was an UI issue only and as longer as update workflow was properly done, people were running new version.

**Comment by zmsMarc** [comment]
Could you enable Issues on the discord connector package repo for the future then @warlof? 
There is currently no way for people to open issues over there. Thanks for all your work!

**Comment by warlof** [comment]
@zmsMarc here you have https://github.com/warlof/seat-connector :)
discord connector is only a driver from seat-connector.
