### ISSUE TITLE
People Groups?

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#87]
What do the people groups actually do?  I can't find the documentation as to what they do, nor do I have a clue of what they used to do in the old SeAT either.  Any help would be appreciated.

**Comment by warlof** [comment]
It's à feature which Enable you to "regroup" multiple account. IE: one of your corpmate got 3 eve account with 7 characters using différent name. You can use this feature to remember that all those account are refering to the same person.

**Comment by leonjza** [comment]
Please join us on Slack [here](http://seat-docs.readthedocs.org/en/latest/contact/#slack) if you still would like to talk about this feature.
