### ISSUE TITLE
Tree's SeAT Utility Library not update

### ISSUE THREAD

**Issue by vlvavan** [eveseat/seat#876]
its normal? :)
![image](https://user-images.githubusercontent.com/71975702/209127740-978cab55-4877-4b47-b470-dfda57550257.png)

**Comment by recursivetree** [comment]
I tagged(v1.0.10 instead of 1.0.10) it wrong when creating the release, this is not an issue for seat. You have the latest version

**Comment by vlvavan** [comment]
thx !
