### ISSUE TITLE
InvalidStateException when user try to authenticate

### ISSUE THREAD

**Issue by YanagidaFuki** [eveseat/seat#886]
Please don't log issues for general discussions or non code problems. Instead, join us on Discord for a chat.

https://eveseat.github.io/docs/about/contact/

For some help on where to find logs, put SeAT into DEBUG mode etc, please refer to the following link:

https://eveseat.github.io/docs/about/reporting_bugs/

Thanks for wanting to report an issue you've found in SeAT. Please delete
this text and fill in the template below. If you are unsure about something,
just do as best as you're able.

* **Problem**: _Whats wrong?_ Unable for the members to login on Seat after it's installed 
* **Expected**: _What did you expect to happen?_
* **Logs / Screenshots / Proof**: _The more information you give the better!_ Attached 
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._ Ubuntu 20.04 

[laravel-2023-04-10.log](https://github.com/eveseat/seat/files/11190806/laravel-2023-04-10.log)

PHP Version: 7.3.33-10+ubuntu20.04.1+deb.sury.org+1

| Package                | Installed | Latest |
| ------------------- | ---------- | ----------- |
| SeAT API           | 4.9.0         | 4.9.0          |
| SeAT Console       | 4.8.0         | 4.8.0          |
| SeAT Eve API       | 4.18.2        | 4.18.2         |
| SeAT Notifications | 4.3.3         | 4.3.3          |
| SeAT Services      | 4.2.1         | 4.2.1          |
| SeAT Web           | 4.19.3        | 4.19.3

**Comment by YanagidaFuki** [comment]
[laravel-2023-04-10.log](https://github.com/eveseat/seat/files/11190806/laravel-2023-04-10.log)
Attached logs

**Comment by YanagidaFuki** [comment]
PHP Version: 7.3.33-10+ubuntu20.04.1+deb.sury.org+1

| SeAT API           | 4.9.0         | 4.9.0          |
| SeAT Console       | 4.8.0         | 4.8.0          |
| SeAT Eve API       | 4.18.2        | 4.18.2         |
| SeAT Notifications | 4.3.3         | 4.3.3          |
| SeAT Services      | 4.2.1         | 4.2.1          |
| SeAT Web           | 4.19.3        | 4.19.3

**Comment by warlof** [comment]
Hi,

Remember to edit your last entry with new content if nobody answered until then.

As per my understanding, your users are experincing troubles while attempting to authenticate against your SeAT instance ?
The error `InvalidStateException` used to occured when you have multiple domains targeting an installation but inconsistency with either the scheme or primary domain.

> [2023-04-10 13:32:43] local.ERROR:  {"exception":"[object] (Laravel\\Socialite\\Two\\InvalidStateException(code: 0):  at /var/www/seat/vendor/socialiteproviders/manager/src/OAuth2/AbstractProvider.php:37)

As a result, ensure that both your public address (the one used by users to authenticated against your SeAT instance, while they're landing on the login page) is the same base as the one you're using in your Eve Application callback url.

Here are most common example :

- http://www.example.tld is not http**s**://www.example.tld
- http://example.tld is not http://**www.**example.tld
- http://example.tld is not http**s**://**www.**example.tld

Double check values at the following locations :

- https://github.com/eveseat/seat/blob/2f23a1308b591fe927a966fa8c9b1d228bd54bbf/.env.example#L6
- https://github.com/eveseat/seat/blob/2f23a1308b591fe927a966fa8c9b1d228bd54bbf/.env.example#L54
- https://developers.eveonline.com in the callback from your Eve Application

Also, in case you're using https, ensure all request targeting the domain is properly redirected to use TLS protocol (in case user ask for http://www.example.tld, redirect the user to https://www.example.tld)

**Comment by YanagidaFuki** [comment]
Thank you for your reply , 

EVE_CALLBACK_URL=https://seat.local/auth/eve/callback and  APP_URL=http://localhost  have the same link , example " https://exampledomain.com 

This issue seems to occur on Chrome

**Comment by warlof** [comment]
What's your SeAT instance url ?
