### ISSUE TITLE
Starbase reinforcement timer

### ISSUE THREAD

**Issue by nizzan** [eveseat/seat#89]
It appears that the Reinforcement Estimate in the Starbase view only shows an estimate on how long the tower will be reinforced for, not the actual reinforcement timer.
It would be a great addition to see the actual reinforment timer on the tower and not just how long the stront will last.
When a tower gets reinforced, all stront is consumed and the estimate in the starbase view goes down to whatever strontium levels are left.
This meaning that i can't see when a tower will exit reinforcement.

**Comment by warlof** [comment]
We should be able to do that with the following formula

> (remaining stront / stront consumption_per_hour) = remaining_hours_based_on_stront - last_update_time = current_time + real_remaining_time = rf_exit_date

Quick exemple :

A large contorl tower
Strontium consumed per hour : 400
Strontium available in bay on last update : 2 666

> 2 666 / 400 = 6.665 - 0.45 = 6.215 = 1 461 059 608 + 6.215 * 60 * 60 = 1 461 059 608 + 22 374 = 1 461 081 982 = april 19th at 06:06:22 pm

**Comment by l0ser140** [comment]
As I know it's  possible to get accurate RF out time directly from API.

**Comment by warlof** [comment]
@l0ser140 do you have the documentation ? according to what I'm able to get from https://eveonline-third-party-documentation.readthedocs.org/en/latest/xmlapi/corporation/corp_starbasedetail.html there is nothing about RF end timer

**Comment by l0ser140** [comment]
Look into state ands tateTimestamp.

**Comment by warlof** [comment]
Oh yes, simple as that :D

**Comment by nizzan** [comment]
I have no clue what i just read, but it looks good!

**Comment by leonjza** [comment]
Thanks @warlof the eveseat/web#24 PR has been merged. Will be available in next tagged release.
