### ISSUE TITLE
unknown item in mail timeline

### ISSUE THREAD

**Issue by freedenizen** [eveseat/seat#9]
Sent SS to qu1ckkkk as it contains mail details. There are multiple locations in the mail timeline that show "unknown item"

**Comment by shibdib** [comment]
Confirmed also having this issue

http://i.imgur.com/SVPGbxi.png

**Comment by leonjza** [comment]
Having a little trouble reproducing this. There is an ajax call that will try and resolve the IDs in the mail to names for any ids in the `<span rel="id-to-name"></span>` tags [here](https://github.com/eveseat/web/blob/master/src/resources/views/includes/javascript/id-to-name.blade.php). The logic for the ajax call is [here](https://github.com/eveseat/web/blob/master/src/Http/Controllers/Support/ResolveController.php#L48).

Could anyone try and debug it a little to see why the name resolution fails?

I remember the screenshot @freedenizen sent also had the dates as "Unknown", which I am yet to try and reproduce too.

**Comment by freedenizen** [comment]
I'm wondering if my issue might be related to HHVM, I'll try to diagnose further.

**Comment by freedenizen** [comment]
So this doesn't appear to be HHVM related, removed it from the system, installed a fresh copy of seat (minus the db which I didn't change) and the problem continues across browsers as well. Strangely the queue counts in the upper right also show unknown item briefly as well.

I only see this behavior on one system, others appear to be fine

**Comment by warlof** [comment]
What about browser tests. I mean, is it appear on a specific browser or not

**Comment by freedenizen** [comment]
I tried it in chrome and FF and other seat 1.x installs I have work fine, I'm going to do a total reinstall next and see what happens

**Comment by freedenizen** [comment]
Confirmed fixed by PR
