### ISSUE TITLE
Feature Request:  Add Ability to be able to Search Mail Text

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/seat#90]
Can you all look into what it would take to add the ability to search all mail text?

**Comment by leonjza** [comment]
This is something that will be done in the Search functionality coming soon™

**Comment by leonjza** [comment]
Added in the first phase of the search functionality. Still needs improvement but the idea is there. Will be available in the next version of the `eveseat/web` and `eveseat/services` package.
