### ISSUE TITLE
squad with type auto and filter by scope not working

### ISSUE THREAD

**Issue by nuclear4547** [eveseat/seat#909]
* **Problem**: squad with type auto and filter by scope not working
* **Expected**: With two possible sets of sso authorizations, split them into different squads by checking one scope that is in one set and not in the other
* **Logs / Screenshots / Proof**: 
error occurs when saving a squad
![image](https://github.com/eveseat/seat/assets/22198404/698ab775-48b5-4197-b9a1-b7c0e567324b)
![image](https://github.com/eveseat/seat/assets/22198404/d4dfe4de-0907-43bf-9fe4-8f6bc7cdef45)
![image](https://github.com/eveseat/seat/assets/22198404/1a826219-b099-4f14-b48a-b3e2378f6342)
`Call to undefined method Seat\Eveapi\Models\Character\CharacterInfo::refresh_tokens() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Seat\\Eveapi\\Models\\Character\\CharacterInfo::refresh_tokens() at /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:67)
[stacktrace]
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('refresh_tokens')
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'refresh_tokens', Array)
#2 /var/www/seat/vendor/eveseat/services/src/Models/ExtensibleModel.php(111): Illuminate\\Database\\Eloquent\\Model->__call('refresh_tokens', Array)
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(876): Seat\\Services\\Models\\ExtensibleModel->__call('refresh_tokens', Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(110): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\Concerns\\{closure}()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(875): Illuminate\\Database\\Eloquent\\Relations\\Relation::noConstraints(Object(Closure))
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(39): Illuminate\\Database\\Eloquent\\Builder->getRelationWithoutConstraints('refresh_tokens')
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php(183): Illuminate\\Database\\Eloquent\\Builder->has('refresh_tokens', '>=', 1, 'or', Object(Closure))
#8 /var/www/seat/vendor/eveseat/web/src/Models/QueryGroupBuilder.php(105): Illuminate\\Database\\Eloquent\\Builder->orWhereHas('refresh_tokens', Object(Closure))
#9 /var/www/seat/vendor/eveseat/web/src/Models/Filterable.php(149): Seat\\Web\\Models\\QueryGroupBuilder->whereHas('refresh_tokens', Object(Closure))
#10 /var/www/seat/vendor/eveseat/web/src/Models/Filterable.php(125): Seat\\Web\\Models\\Squads\\Squad->applyRule(Object(Seat\\Web\\Models\\QueryGroupBuilder), Object(stdClass))
#11 /var/www/seat/vendor/eveseat/web/src/Models/Filterable.php(68): Seat\\Web\\Models\\Squads\\Squad->applyGroup(Object(Illuminate\\Database\\Eloquent\\Builder), Object(stdClass))
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(299): Seat\\Web\\Models\\Squads\\Squad->Seat\\Web\\Models\\{closure}(Object(Illuminate\\Database\\Eloquent\\Builder))
#13 /var/www/seat/vendor/eveseat/web/src/Models/QueryGroupBuilder.php(78): Illuminate\\Database\\Eloquent\\Builder->where(Object(Closure))
#14 /var/www/seat/vendor/eveseat/web/src/Models/Filterable.php(67): Seat\\Web\\Models\\QueryGroupBuilder->where(Object(Closure))
#15 /var/www/seat/vendor/eveseat/web/src/Models/Squads/Squad.php(99): Seat\\Web\\Models\\Squads\\Squad->isEligible(Object(Seat\\Eveapi\\Models\\Character\\CharacterInfo))
#16 /var/www/seat/vendor/eveseat/web/src/Observers/AbstractSquadObserver.php(74): Seat\\Web\\Models\\Squads\\Squad->isUserEligible(Object(Seat\\Web\\Models\\User))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Seat\\Web\\Observers\\AbstractSquadObserver->Seat\\Web\\Observers\\{closure}(Object(Seat\\Web\\Models\\Squads\\Squad), 2)
#18 /var/www/seat/vendor/eveseat/web/src/Observers/AbstractSquadObserver.php(73): Illuminate\\Support\\Collection->each(Object(Closure))
#19 /var/www/seat/vendor/eveseat/web/src/Observers/CharacterAssetObserver.php(49): Seat\\Web\\Observers\\AbstractSquadObserver->updateUserSquads(Object(Seat\\Eveapi\\Models\\Assets\\CharacterAsset))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Seat\\Web\\Observers\\CharacterAssetObserver->updated(Object(Seat\\Eveapi\\Models\\Assets\\CharacterAsset))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.update...', Array)
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('eloquent.update...', Array, false)
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(215): Illuminate\\Events\\Dispatcher->dispatch('eloquent.update...', Array)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1217): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('updated', false)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder))
#26 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Character/Assets.php(119): Illuminate\\Database\\Eloquent\\Model->save()
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets->Seat\\Eveapi\\Jobs\\Assets\\Character\\{closure}(Object(stdClass), 0)
#28 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Character/Assets.php(101): Illuminate\\Support\\Collection->each(Object(Closure))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets->handle()
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), false)
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Middleware/WithoutOverlapping.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Queue\\Middleware\\WithoutOverlapping->handle(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), Object(Closure))
#42 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenVersion.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckTokenVersion->handle(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), Object(Closure))
#44 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenScope.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckTokenScope->handle(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), Object(Closure))
#46 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckEsiRouteStatus.php(80): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckEsiRouteStatus->handle(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), Object(Closure))
#48 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckServerStatus.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#49 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckServerStatus->handle(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), Object(Closure))
#50 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckEsiRateLimit.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#51 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckEsiRateLimit->handle(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets), Object(Closure))
#52 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#53 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets))
#55 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#56 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#57 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#58 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#59 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon('redis', 'characters', Object(Illuminate\\Queue\\WorkerOptions))
#60 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'characters')
#61 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#62 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#63 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#64 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#65 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#66 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#67 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#68 /var/www/seat/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#69 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#70 /var/www/seat/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#71 /var/www/seat/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#72 /var/www/seat/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#73 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#74 /var/www/seat/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#75 {main}
"}`
* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

` * Getting environment information
Current User: seat
PHP Version: 8.2.19
Host OS: Linux ef1b772fe61f 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64
SeAT Basepath: /var/www/seat

 * Checking DEBUG mode
Debug mode disabled

 * Checking storage
/var/www/seat/storage is writable
/var/www/seat/storage/sde is writable
/var/www/seat/storage/logs/laravel-2024-06-12.log is writable

 * Checking Database
+------------+----------------------------------+
| Setting    | Value                            |
+------------+----------------------------------+
| Connection | mysql                            |
| Host       | mariadb                          |
| Database   | seat                             |
| Username   | seat                             |
| Password   | ******************************** |
+------------+----------------------------------+
Connection OK to database: seat

 * Checking Redis
+----------+-------+
| Setting  | Value |
+----------+-------+
| Host     | cache |
| Port     | 6379  |
| Database | 0     |
+----------+-------+
Connected to Redis
Set random key of: rLVXb8dkDfMRa7XjJ2Yd3S6puLrlLCfxLhdFnWDz3zMa69g9EOKVfNpHNu005Ys5
Set key to expire in 10 sec
Read key OK

 * Checking ESI Access
Server Online Since: 2024-06-12T11:21:10Z
Online Players: 31417
ESI appears to be OK

Checking Local and Latest Versions. Please wait...
+--------------------+---------------+----------------+
| Package Name       | Local Version | Latest Version |
+--------------------+---------------+----------------+
| SeAT API           | 5.0.0         | 5.0.0          |
| SeAT Eseye         | 3.0.1         | 3.0.1          |
| SeAT Eve API       | 5.0.13        | 5.0.13         |
| SeAT Notifications | 5.0.8         | 5.0.8          |
| SeAT Services      | 5.0.7         | 5.0.7          |
| SeAT Web           | 5.0.12        | 5.0.12         |
+--------------------+---------------+----------------+
SeAT Diagnostics complete`

**Comment by recursivetree** [comment]
Thanks for the report. I've successfully reproduced it and we will try to fix it.

On another note, you can only use the contains operator with scopes, `is` doesn't work.
