### ISSUE TITLE
Displaying what was in a contract.

### ISSUE THREAD

**Issue by LGP-Chronos** [eveseat/seat#92]
- **Problem**: Does not display what was inside the contracts only the price
- **Expected**: Pull down to display items in the contract
- **Logs / Screenshots / Proof**: http://puu.sh/osJM7/89ac092a86.png
- **Version Info**:  1.0.24

**Comment by leonjza** [comment]
Yeah this is definitely something that should be implemented in 1.x. It is just going to take a little time as the previous implementation was not very performance aware, and actually made some installation unstable with tons of contracts.

Will probably go the modal && ajax route this time.

**Comment by warlof** [comment]
take it this week as soon as you merge https://github.com/eveseat/web/pull/33/commits/09709011cd1f8946bf5ca5a0f428fbdfc8bbefbe :)

**Comment by monasucks** [comment]
+1

**Comment by leonjza** [comment]
Added for characters and corporations in these commits: https://github.com/eveseat/web/commit/11e3cb0601d7330c54e35564a1a9cbd6c7c78c38 & https://github.com/eveseat/web/commit/5d1d8602126358a9b1e9689680032b29fa405fe5. Tagged and released.
