### ISSUE TITLE
Corporation Wallet Ledger shows all Corp-Wallets

### ISSUE THREAD

**Issue by Flugschreipbaer** [eveseat/seat#93]
I don't know why, but under corp - wallet ledger I can see every wallet from every corporation:

http://flugschreipbaer.de/pics/walletbug.PNG
(4 Corporations are entered - totally independent from any roles)

I don't believe that this is correct ^^. Anybody knowing how to fix that?

**Comment by dysath** [comment]
No, definitely not right.  I'll have to check it tonight

**Comment by dysath** [comment]
I don't see anything in the logic that would allow this currently, but I'll see if I can get a second corp API installed so I can test it.

**Comment by leonjza** [comment]
During testing I had multiple corp wallets `corporationID` value set to the same as part of feature testing, and had a similar issue for this. Once that was reset to valid values this was no longer the case for me. @Flugschreipbaer could you please check the data in your `corporation_sheet_divisions` and `corporation_sheet_wallet_divisions` tables and ensure the `corporationID` values are correct?

As a side note, you can see the service [here](https://github.com/eveseat/services/blob/master/src/Repositories/Corporation/CorporationRepository.php#L819) filters the summary by `corporation_sheet_wallet_divisions.corporationID`.

**Comment by dysath** [comment]
This is what's bothering me, if you had bad data pull up additional
wallets, I need to rebuild that query to be a little stronger.  I just need
to get a second corp API to test with.  I'll see if I can do up a corp mgmt
1 skill on one of my alts tonight and force it to fail.

On Tue, Apr 26, 2016 at 4:57 AM, Leon Jacobs <notifications@github.com>
wrote:

> During testing I had multiple corp wallets corporationID value set to the
> same as part of feature testing, and had a similar issue for this. Once
> that was reset to valid values this was no longer the case for me.
> @Flugschreipbaer <https://github.com/Flugschreipbaer> could you please
> check the data in your corporation_sheet_divisions and
> corporation_sheet_wallet_divisions tables and ensure the corporationID
> values are correct?
>
> As a side note, you can see the service here
> <https://github.com/eveseat/services/blob/master/src/Repositories/Corporation/CorporationRepository.php#L819>
> filters the summary by corporation_sheet_wallet_divisions.corporationID.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/eveseat/seat/issues/93#issuecomment-214689330>
>



-- 
Ed Stafford

**Comment by leonjza** [comment]
@dysath I dont see a problem with the qyery. I tested it with multiple corp keys before merge too.

**Comment by Flugschreipbaer** [comment]
Hey,

I just checked the `corporationID` in both tables. They are correct, as in: Every corp got its own distinct `corporationID`.

and i don't know, but this code:

` return CorporationSheetWalletDivision::join(
            'corporation_account_balances',
            'corporation_sheet_wallet_divisions.accountKey', '=',
            'corporation_account_balances.accountKey')
            ->select(
                'corporation_account_balances.accountID as accountid',
                'corporation_account_balances.balance as balance',
                'corporation_sheet_wallet_divisions.description as description')
            ->where('corporation_sheet_wallet_divisions.corporationID', $corporation_id)
            ->get();
    }`
reads to me like the `accountKey` is beeing read independent of the `corporationID`. The `corporationID` is just beeing used to get the different values for corp (`corporationID`).

So everytime the function is called, every `accountKey` is joined from the three tables.

correct me if i got that wrong ^^

**Comment by leonjza** [comment]
@Flugschreipbaer err, good point! Time to relook this : )

As for the wallet division, IIRC this was dust related.
