### ISSUE TITLE
bzopen() error php 7

### ISSUE THREAD

**Issue by orbitroom** [eveseat/seat#94]
when running the command `php artisan eve:update-sde -n` It then spits out     `[Symfony\Component\Debug\Exception\FatalThrowableError]`
`Fatal error: Call to undefined function Seat\Console\Commands\Eve\bzopen()`

OS: Ubuntu 14.04
PHP version 7.0
ive also made sure bzip2 was installed to no avail.

**Comment by warlof** [comment]
That for sûre à setup issue.
Try with php7.0-bz2 ;)

**Comment by orbitroom** [comment]
that was it thank you I should have thought about that. its been a long night :)

**Comment by CokkocZateki** [comment]
how was this error sorted out. i seem to be getting it

**Comment by leonjza** [comment]
You need to install the bz2 package for your php distribution.

**Comment by CokkocZateki** [comment]
I've got it installed already when I got this error

**Comment by warlof** [comment]
If you're using apache mod, you have to restart apache.
This error is defenitely related to a missing bz2 package.

`sudo apt-get install php7.0-bz2` will install you bz2 package for php7

If you're using apache without fastcgi, you have then to restart it `sudo service apache2 restart`
If you're using php fastcgi, you have to restart it `sudo service php7.0-fpm restart`

**Comment by leonjza** [comment]
Please use slack for further support on this instead of flooding mailboxes unnecessarily. Thanks!
