### ISSUE TITLE
Rest support for CharacterID

### ISSUE THREAD

**Issue by markus-lassfolk** [eveseat/seat#96]
I've begun using the Rest API for SEAT, which is a fantastic feature! 
Though I've been unable to find a way to get the characters associated with a specific key. 
And also all character id's in the Corp. 

Could you add rest support for; 
a) Showing all CharacterID for a specific KeyID
b) Showing all CharacterID in a Corp 
c) List all Corp ID's (as seen here https://seat.ip-org.net/corporation/list) 

Thanks you :)

**Comment by leonjza** [comment]
Great news!

> a) Showing all CharacterID for a specific KeyID

Definitely do-able. Just have to make sure we place the endpoint in the most logical place if we cant source the data from an existing one. Will investigate.

> b) Showing all CharacterID in a Corp 

Sounds good.

> c) List all Corp ID's (as seen here https://seat.ip-org.net/corporation/list)

Could you elaborate on this one? As in, list all corps SeAT knows of?

**Comment by markus-lassfolk** [comment]
Sweet. Thanks for quick reply! 

c) I'm writing some scripts with logic where I would like to parse information for all members per corp. 
We have 3 different Corp ApiKeys added to SEAT. So I would like to first grab the CorpID for one of the corps, find all characterid's for that corp, and parse them. 
Then do the same for the next corp. 
I could hardcode the CorpIDs into the script but it would look better if it was dynamic and possible to read them from SEAT.  

So no, in my case there is no need to get all Corp ID's that SEAT knows about (meaning, also NPC corps etc etc) but it would be enough to show the corps where there are CorpAPI keys.

**Comment by leonjza** [comment]
Makes sense. In case it was not clear, I actually meant Corps with keys in SeAT instead of all corps. : )

**Comment by leonjza** [comment]
> a) Showing all CharacterID for a specific KeyID

[This](http://seat-docs.readthedocs.io/en/latest/seat_api/#get-a-single-eve-api-key) endpoint will now include the character info. [ref](https://github.com/eveseat/api/commit/be8e6aa51bc8ccd4a309c00f590736b430954088)

> b) Showing all CharacterID in a Corp 

I just realized, the member tracking call has this. [Details](http://seat-docs.readthedocs.io/en/latest/seat_api/#corporation-member-tracking)

> c) List all Corp ID's (as seen here https://seat.ip-org.net/corporation/list)

Added a [new endpoint](http://seat-docs.readthedocs.io/en/latest/seat_api/#all-corporations) for this. [ref](https://github.com/eveseat/api/commit/131a3b88745284e72bd2be571b6973a6b400dd13)

All of this will be available in the next `eveseat/api` package release.
