### ISSUE TITLE
API Key status Unknown rather than Error and not visible via RestAPI

### ISSUE THREAD

**Issue by markus-lassfolk** [eveseat/seat#97]
* **Problem**: 
The Website shows some keys as "Never / Unknown". it usually happens to _new_ keys it's unable to query because they are invalid or expired. And as SEAT has been unable to get information for that key but it has tried, I would kind of expect it to be status "Error" rather than "Unknown". 

Also, there is no way to see that information from the RestAPI as they look the same as a working key. 

* **Expected**: Would expect the key status to be "Error" if it has been unable to query the key even first time. And RestAPI to show the same info (or even more) than on the Webpage. 

* **Logs / Screenshots / Proof**: 
![rest1](https://cloud.githubusercontent.com/assets/3661143/14909263/a3552dda-0de1-11e6-9856-89630af467d4.jpg)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
Seat API v1.0.9
SeAT Console        v1.0.10
SeAT Eveapi         v1.0.12
SeAT Notifications v1.0.4
SeAT Web            v1.0.23
SeAT Services      v1.0.14

**Comment by leonjza** [comment]
I think I might have resolved this fundamentally more complex problem yesterday.  

To understand this better, I can start off by saying that if the key is disabled/error state etc, the information will reflect in the front end & API. That being said, I realized yesterday that there is a case where expired/invalid keys will never get disabled when they should. So, I fixed it in [this](https://github.com/eveseat/eveapi/commit/85b21b0cb7b2c4ac1a92956ef41cac5ad81b9759) commit.

Lets keep this open till the next tagged version is out and more widespread testing can take place.

**Comment by leonjza** [comment]
Updated `eveseat/eveapi` package has been pushed which should contain a fix for broken keys not correctly reporting their status. Update your packages and let me know!

**Comment by leonjza** [comment]
How is this going with the latest packages @markus-lassfolk ?

**Comment by markus-lassfolk** [comment]
Server was updated earlier today, will try it out tonight  and get back to you :)



3 maj 2016 kl. 19:04 skrev Leon Jacobs <notifications@github.com<mailto:notifications@github.com>>:


How is this going with the latest packages @markus-lassfolk<https://github.com/markus-lassfolk> ?

-
