### ISSUE TITLE
Configuring Admin Contact

### ISSUE THREAD

**Issue by vivace-io** [eveseat/seat#98]
Per issue #77 and the referenced commits (eveseat/eveapi@e9db18e and eveseat/web@60727e4), new jobs are refused from the queue if `admin_contact` is default, which is what is expected.

However, working through a new installation, there is no (documented) way that I can find for configuring this value without modifying source. Can we either create a way of configuring this from `.env`, or create a way of doing so (and update documentation)?

**Comment by leonjza** [comment]
Good point! I sort of (and very incorrectly) assumed everyone uses the web interface ad will see the notification when an admin logs in.

Will add docs and a command line to set the value as required.

**Comment by vivace-io** [comment]
Yeah the only reason I noticed it was when I was migrating to a new server.
When I restored my database and everything, I was totally confused about
the warning I was getting. The Admin did not get any notification about
this either (presumably because I was working off a restored database).

Thanks!
